//mod supports BP-BGT Worldmap. This patch allows it to support EET worldmap natively too

APPEND_OUTER ~EET/tbl/map_eet_areas.tbl~ ~
//Stone of Askavar New Areas Table
SHORT_NAME CONTENT    LONG_NAME  FLAGS      BAM_ANIM   X_POS      Y_POS      NAME       TOOLTIP    LOAD_IM

ARS002     ARS002     ARS002     4          41         235        925        @ARS002    @ARS002    N        //Bluebell wood
ARS005     ARS005     ARS005     4          39         627        545        @ARS005    @ARS005    N        //Dystra old watch tower~
