//mod supports BP-BGT Worldmap. This patch allows it to support EET worldmap natively too

APPEND_OUTER ~EET/tbl/map_eet_areas.tbl~ ~
//Stone of Askavar New Areas Table; x + 373
SHORT_NAME  CONTENT  LONG_NAME  FLAGS  BAM_ANIM  X_POS  Y_POS  NAME         TOOLTIP      LOAD_IM

ARS002      ARS002   ARS002     4      41        235    925    @SOA_782001  @SOA_782001  N        //Bluebell wood
ARS005      ARS005   ARS005     4      39        609    545    @SOA_782002  @SOA_782002  N        //Dystra old watch tower~
