//mod supports BP-BGT Worldmap. This patch allows it to support EET worldmap natively too

APPEND_OUTER ~%MOD_FOLDER%/tbl/map_eet_areas.tbl~ ~
//Stone of Askavar New Areas Table
SHORT_NAME CONTENT    LONG_NAME  FLAGS      BAM_ANIM   X_POS      Y_POS      NAME       TOOLTIP    LOAD_IM

ARS002     ARS002     ARS002     4          59         590        2255       @ARS002    @ARS002    N        //Bluebell wood
ARS005     ARS005     ARS005     4          62         1265       1757       @ARS005    @ARS005    N        //Dystra old watch tower~ KEEP_CRLF
