-- -- -- -- --
-- BGEE.LUA --
-- -- -- -- --

styles['gamelog'] = {
	color = 'B',
	font = 'POSTANTI',
	point = 12,
	useFontZoom = 1,
	valign = 'top',
	halign = 'left',
}
styles['normal'] = {
	color = 'B',
	font = 'MODESTOM',
	point = 14,
	useFontZoom = 1,
	valign = 'top',
	halign = 'left',
}
styles['normal_parchment'] = {
	color = '5',
	font = 'POSTANTI',
	point = 12,
	useFontZoom = 1,
	valign = 'top',
	halign = 'left',
}
styles['title'] = {
	color = '1',
	font = 'SHERWOOD',
	point = 20,
	useFontZoom = 0,
	valign = 'center',
	halign = 'center',
}
styles['parchment'] = {
	color = '5',
	font = 'POSTANTI',
	point = 12,
	useFontZoom = 1,
	valign = 'top',
	halign = 'left',
}
styles['button'] = {
	color = 'B',
	font = 'MODESTOM',
	point = 18,
	useFontZoom = 0,
	valign = 'center',
	halign = 'center',
	upper = 1,
	pad = {8,8,8,8},
}
styles['label'] = {
	color = 'B',
	font = 'MODESTOM',
	point = 14,
	useFontZoom = 0,
	valign = 'center',
	halign = 'center',
}
styles['label_parchment'] = {
	color = '5',
	font = 'POSTANTI',
	point = 12,
	useFontZoom = 0,
	valign = 'center',
	halign = 'center',
}
styles['button_parchment'] = {
	color = '5',
	font = 'POSTANTI',
	point = 12,
	useFontZoom = 0,
	valign = 'center',
	halign = 'center',
	pad = {0,5,0,0},
}
styles['edit'] = {
	color = 'B',
	font = 'MODESTOM',
	point = 14,
	useFontZoom = 1,
	valign = 'top',
	halign = 'left',
}
styles['edit_parchment'] = {
	color = '5',
	font = 'POSTANTI',
	point = 12,
	useFontZoom = 1,
	valign = 'top',
	halign = 'left',
}
styles['list'] = {
	color = 'B',
	font = 'STONESML',
	point = 18,
	useFontZoom = 0,
	valign = 'center',
	halign = 'left',
}
styles['list_parchment'] = {
	color = '5',
	font = 'POSTANTI',
	point = 12,
	useFontZoom = 0,
	valign = 'center',
	halign = 'left',
}
styles['gold'] = {
	color = '$',
	font = 'MODESTOM',
	point = 12,
	useFontZoom = 0,
	valign = 'center',
	halign = 'center',
}
styles['label_loadname'] = {
	color = 'B',
	font = 'MODESTOM',
	point = 20,
	useFontZoom = 0,
	valign = 'center',
	halign = 'center',
}
