/////                                                  \\\\\
///// Leftover BG:EE code in BG2:EE                    \\\\\
/////                                                  \\\\\

//Leftover BG:EE ARE scripts code
ACTION_FOR_EACH file IN AR0100 AR0101 AR0103 AR0106 AR0108 AR0111 AR0112 AR0114 AR0115 AR0119 AR0121 AR0123 AR0125 AR0128 AR0130 AR0137 AR0138 AR0145 AR0146 AR0149 AR0153 AR0608 AR0612 AR1803 AR2301 AR2609 AR2611 AR2626 AR3300 AR3304 AR3352 AR5400 AR5405 BEGIN
	ACTION_IF NOT FILE_EXISTS_IN_GAME ~%file%.ARE~ BEGIN //just to be sure that other mod didn't add these areas
		COPY - ~.../blank.txt~ ~.../%file%.baf~
		COMPILE ~.../%file%.baf~
	END
END
//Leftover BG:EE ARE scripts code used in scripts that are also used in BG2:EE
<<<<<<<< .../AR0514.baf
IF
  Global("Durtomb","GLOBAL",1)
  Global("DurTombTele","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("DurTombTele","GLOBAL",1)
    ActionOverride(Player1,LeaveAreaLUAPanic("AR0515","",[327.201],E))
    ActionOverride(Player1,LeaveAreaLUA("AR0515","",[327.201],E))
    ActionOverride(Player1,SetMasterArea("AR0500"))
    ActionOverride(Player2,LeaveAreaLUA("AR0515","",[424.243],E))
    ActionOverride(Player3,LeaveAreaLUA("AR0515","",[472.321],E))
    ActionOverride(Player4,LeaveAreaLUA("AR0515","",[433.398],E))
    ActionOverride(Player5,LeaveAreaLUA("AR0515","",[228.409],E))
    ActionOverride(Player6,LeaveAreaLUA("AR0515","",[168.303],E))
END

IF
  Global("Viking","GLOBAL",1)
  Global("VikingTele","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("VikingTele","GLOBAL",1)
    ActionOverride(Player1,LeaveAreaLUAPanic("AR0515","",[327.201],E))
    ActionOverride(Player1,LeaveAreaLUA("AR0515","",[327.201],E))
    ActionOverride(Player1,SetMasterArea("AR0500"))
    ActionOverride(Player2,LeaveAreaLUA("AR0515","",[424.243],E))
    ActionOverride(Player3,LeaveAreaLUA("AR0515","",[472.321],E))
    ActionOverride(Player4,LeaveAreaLUA("AR0515","",[433.398],E))
    ActionOverride(Player5,LeaveAreaLUA("AR0515","",[228.409],E))
    ActionOverride(Player6,LeaveAreaLUA("AR0515","",[168.303],E))
END

IF
  Global("DurStatue","GLOBAL",1)
  Global("DurStatueTele","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("DurStatueTele","GLOBAL",1)
    ActionOverride(Player1,LeaveAreaLUAPanic("AR0515","",[327.201],E))
    ActionOverride(Player1,LeaveAreaLUA("AR0515","",[327.201],E))
    ActionOverride(Player1,SetMasterArea("AR0500"))
    ActionOverride(Player2,LeaveAreaLUA("AR0515","",[424.243],E))
    ActionOverride(Player3,LeaveAreaLUA("AR0515","",[472.321],E))
    ActionOverride(Player4,LeaveAreaLUA("AR0515","",[433.398],E))
    ActionOverride(Player5,LeaveAreaLUA("AR0515","",[228.409],E))
    ActionOverride(Player6,LeaveAreaLUA("AR0515","",[168.303],E))
END

IF
  Global("TeleRoom","GLOBAL",1)
  OpenState("FinalDoor",FALSE)
THEN
  RESPONSE #100
    OpenDoor("FinalDoor")
END
>>>>>>>>
<<<<<<<< .../AR2001.baf
IF
  Global("Door2012Disabled","GLOBAL",1)
  Global("Infected","GLOBAL",1)
THEN
  RESPONSE #100
    TriggerActivation("DOOR2012",TRUE)
    SetGlobal("Door2012Disabled","GLOBAL",0)
END

IF
  Global("Door2012Disabled","GLOBAL",0)
  Global("Infected","GLOBAL",0)
THEN
  RESPONSE #100
    TriggerActivation("DOOR2012",FALSE)
    SetGlobal("Door2012Disabled","GLOBAL",1)
END

IF
  OpenState("DOR2012",FALSE)
  Global("Infected","GLOBAL",1)
THEN
  RESPONSE #100
    OpenDoor("DOR2012")
END

IF
  OpenState("DOR2012",TRUE)
  Global("Infected","GLOBAL",0)
THEN
  RESPONSE #100
    CloseDoor("DOR2012")
END
>>>>>>>>
ACTION_FOR_EACH file IN AR0514 AR2001 BEGIN
	COPY_EXISTING ~%file%.BCS~ ~override~
		REPLACE_BCS_BLOCK ~.../%file%.baf~ ~.../blank.baf~ ON_MISMATCH PATCH_WARN ~WARNING: .../%file%.baf doesn't exist within %file%.BCS~ END
	BUT_ONLY
END

/////                                                  \\\\\
///// DAYNITE/NITEDAY movies                           \\\\\
/////                                                  \\\\\

<<<<<<<< .../DAYNITE_NITEDAY-eb.baf
IF
  Time(DUSK_END)
  !GlobalTimerNotExpired("K#TimerSunset","GLOBAL")
  OR(6)
    AreaCheckObject("%SOURCE_RES%",Player1)
    AreaCheckObject("%SOURCE_RES%",Player2)
    AreaCheckObject("%SOURCE_RES%",Player3)
    AreaCheckObject("%SOURCE_RES%",Player4)
    AreaCheckObject("%SOURCE_RES%",Player5)
    AreaCheckObject("%SOURCE_RES%",Player6)
THEN
  RESPONSE #100
    StartMovie("DAYNITE")
    SetGlobalTimer("K#TimerSunset","GLOBAL",ONE_HOUR)
END

IF
  Time(DAWN_END)
  !GlobalTimerNotExpired("K#TimerSunrise","GLOBAL")
  OR(6)
    AreaCheckObject("%SOURCE_RES%",Player1)
    AreaCheckObject("%SOURCE_RES%",Player2)
    AreaCheckObject("%SOURCE_RES%",Player3)
    AreaCheckObject("%SOURCE_RES%",Player4)
    AreaCheckObject("%SOURCE_RES%",Player5)
    AreaCheckObject("%SOURCE_RES%",Player6)
THEN
  RESPONSE #100
    StartMovie("NITEDAY")
    SetGlobalTimer("K#TimerSunrise","GLOBAL",ONE_HOUR)
END
>>>>>>>>

/*COPY_EXISTING ~AR2000.ARE~ ~override~ //Trademeet
	~AR2800.ARE~ ~override~ //Suldanesselar
	READ_BYTE 0x48 flags
	PATCH_IF (~%flags%~ BAND BIT3) BEGIN
		SET flags = flags - BIT3
		WRITE_BYTE 0x48 "flags"
	END
BUT_ONLY*/

COPY_EXISTING_REGEXP GLOB ~.*\.are~ ~override~
	READ_BYTE 0x48 flags
	PATCH_IF (flags BAND BIT0) AND (flags BAND BIT1) AND (flags BAND BIT3) AND (flags BAND BIT6) BEGIN
		INNER_ACTION BEGIN
			EXTEND_BOTTOM ~%SOURCE_RES%.BCS~ ~.../DAYNITE_NITEDAY-eb.baf~ EVALUATE_BUFFER
			PRINT ~DAYNITE/NITEDAY movies added to %SOURCE_RES%.BCS~
		END
	END
BUT_ONLY

/////                                                  \\\\\
///// BALDUR.BCS, BALDUR25.BCS                         \\\\\
/////                                                  \\\\\

<<<<<<<< .../oBALDUR.baf
IF
  StoryModeOn()
  InMyArea(Familiar)
  !CheckSpellState(Familiar,STORY_MODE)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    ApplySpellRES("OHSMODE4",Familiar)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !StoryModeOn()
  InMyArea(Familiar)
  CheckSpellState(Familiar,STORY_MODE)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    ApplySpellRES("OHSMODE3",Familiar)
    SetInterrupt(TRUE)
    Continue()
END
>>>>>>>> 

<<<<<<<< .../nBALDUR.baf
>>>>>>>>

COPY_EXISTING ~BALDUR.BCS~ ~override~
	~BALDUR25.BCS~ ~override~
R_B_B ~.../oBALDUR.baf~ ~.../nBALDUR.baf~ ON_MISMATCH PATCH_WARN ~WARNING: Could not find block matching .../oBALDUR.baf in %SOURCE_FILE%~ END

COPY_EXISTING ~BALDUR.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~\(^[%TAB% ]*Global("JosterLeave","GLOBAL",1)\)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~Global("JosterLeave","GLOBAL",1)
  !AreaType(BG1AREA)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

<<<<<<<< .../BALDUR-eb.baf
//code from BG:EE
IF
  Global("TanariXP","GLOBAL",1)
  Dead("DeathK") // Demon Knight
  Dead("loupgar") // Loup Garou
  Global("FinishedExpansion","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("FinishedExpansion","GLOBAL",1)
    AddJournalEntry(224117,INFO)
END

IF
  Global("HasTranzigScroll","GLOBAL",0)
  PartyHasItem("SCRL2X") // Letter
THEN
  RESPONSE #100
    SetGlobal("HasTranzigScroll","GLOBAL",1)
    AddJournalEntry(231449,QUEST)
END

IF
  InParty("Baeloth") // Baeloth
  Global("BaelothJoinedParty","GLOBAL",0)
THEN
  RESPONSE #100
    ReputationInc(-2)
    SetGlobal("BaelothJoinedParty","GLOBAL",1)
END

IF
  !InParty("Baeloth") // Baeloth
  !Dead("Baeloth") // Baeloth
  Global("BaelothJoinedParty","GLOBAL",1)
THEN
  RESPONSE #100
    ReputationInc(2)
    SetGlobal("BaelothJoinedParty","GLOBAL",0)
END

IF
  GlobalTimerExpired("EndGame","GLOBAL")
THEN
  RESPONSE #100
    Kill(Player1)
END

IF
  GlobalTimerExpired("PoisonParty","GLOBAL")
  GlobalLT("PoisonWarning","GLOBAL",9)
  Global("PartyCured","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobalTimer("PoisonParty","GLOBAL",ONE_DAY)
    IncrementGlobal("PoisonWarning","GLOBAL",1)
    DisplayString(Myself,211833)
    Continue()
END

IF
  Global("PartyCured","GLOBAL",0)
  GlobalTimerExpired("PoisonParty","GLOBAL")
  Global("PoisonPartyIcon","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("PoisonPartyIcon","GLOBAL",1)
    ApplySpellRES("bdmarek",Player1)
END

IF
  GlobalTimerExpired("PoisonParty2","GLOBAL")
  Global("PartyCured","GLOBAL",0)
THEN
  RESPONSE #100
    Kill(Player1)
END

IF
  Global("Infected","GLOBAL",1)
  GlobalTimerExpired("PlayerInfected","GLOBAL")
  !Dead("Mendas3")
  Exists(Player2)
THEN
  RESPONSE #100
    ActionOverride(Player2,ForceSpell(Myself,PLAYER_WEREWOLF_CHANGE))
    ActionOverride(Player3,ForceSpell(Myself,PLAYER_WEREWOLF_CHANGE))
    ActionOverride(Player4,ForceSpell(Myself,PLAYER_WEREWOLF_CHANGE))
    ActionOverride(Player5,ForceSpell(Myself,PLAYER_WEREWOLF_CHANGE))
    ActionOverride(Player6,ForceSpell(Myself,PLAYER_WEREWOLF_CHANGE))
END

IF
  GlobalTimerExpired("bd_taerom_vial","GLOBAL")
  Global("bd_taerom_newitems","GLOBAL",0)
THEN
  RESPONSE #100
    AddStoreItem("taerum","ax1h01q",9,1)
    AddStoreItem("taerum","blun02q",15,1)
    AddStoreItem("taerum","blun04q",5,1)
    AddStoreItem("taerum","blun06q",5,1)
    AddStoreItem("taerum","dagg01q",0,1)
    AddStoreItem("taerum","halb01q",5,1)
    AddStoreItem("taerum","hamm01q",5,1)
    AddStoreItem("taerum","sper01q",10,1)
    AddStoreItem("taerum","sw1h01q",3,1)
    AddStoreItem("taerum","sw1h04q",6,1)
    AddStoreItem("taerum","sw1h07q",8,1)
    RemoveStoreItem("taerum","ax1h01",0)
    RemoveStoreItem("taerum","blun02",0)
    RemoveStoreItem("taerum","blun04",0)
    RemoveStoreItem("taerum","blun06",0)
    RemoveStoreItem("taerum","dagg01",0)
    RemoveStoreItem("taerum","halb01",0)
    RemoveStoreItem("taerum","hamm01",0)
    RemoveStoreItem("taerum","sper01",0)
    RemoveStoreItem("taerum","sw1h01",0)
    RemoveStoreItem("taerum","sw1h04",0)
    RemoveStoreItem("taerum","sw1h07",0)
    SetGlobal("bd_taerom_newitems","GLOBAL",1)
END

IF
  Global("CDLetterCheckscrl2z","GLOBAL",1)
  !ActuallyInCombat()
  Global("CHAPTER","GLOBAL",3)
THEN
  RESPONSE #100
    Wait(2)
    RevealAreaOnMap("BG2200")
    IncrementChapter("CHPTXT4")
    AddJournalEntry(215838,INFO)
    EraseJournalEntry(231450)
    EraseJournalEntry(231448)
    EraseJournalEntry(227218)
    EraseJournalEntry(227217)
    EraseJournalEntry(227381)
    EraseJournalEntry(226856)
    EraseJournalEntry(226861)
    EraseJournalEntry(227378)
    EraseJournalEntry(227383)
    EraseJournalEntry(226850)
    EraseJournalEntry(227468)
    EraseJournalEntry(227473)
    EraseJournalEntry(226862)
    EraseJournalEntry(227379)
    EraseJournalEntry(227382)
    EraseJournalEntry(227469)
    EraseJournalEntry(227474)
    EraseJournalEntry(227492)
    EraseJournalEntry(226858)
    EraseJournalEntry(227380)
    EraseJournalEntry(226857)
    EraseJournalEntry(226859)
    EraseJournalEntry(227476)
    EraseJournalEntry(226860)
    AddJournalEntry(231451,QUEST)
END

IF
  Global("Chapter","GLOBAL",4)
  GlobalLT("BD_Chapter_Save","GLOBAL",4)
THEN
  RESPONSE #100
    SetGlobal("BD_Chapter_Save","GLOBAL",4)
    SaveGame(29)
END

IF
  Global("PartyCured","GLOBAL",0)
  TriggerOverride(Player1,Global("bdmarek","LOCALS",1))
  Dead("Marek")
THEN
  RESPONSE #100
    SetGlobal("PartyCured","GLOBAL",1)
    AddJournalEntry(227253,QUEST_DONE)
    EraseJournalEntry(226793)
    EraseJournalEntry(226982)
    EraseJournalEntry(227240)
    EraseJournalEntry(227241)
    EraseJournalEntry(227242)
    EraseJournalEntry(227243)
    EraseJournalEntry(227183)
    DisplayString(Player1,220675)
    AddexperienceParty(10000)
END

IF
  Global("PartyCured","GLOBAL",0)
  TriggerOverride(Player1,Global("bdmarek","LOCALS",1))
  !Dead("Marek")
THEN
  RESPONSE #100
    SetGlobal("PartyCured","GLOBAL",1)
    AddJournalEntry(231188,QUEST_DONE)
    EraseJournalEntry(226793)
    EraseJournalEntry(226982)
    EraseJournalEntry(227240)
    EraseJournalEntry(227241)
    EraseJournalEntry(227242)
    EraseJournalEntry(227243)
    EraseJournalEntry(227183)
    DisplayString(Player1,220675)
    AddexperienceParty(10000)
END

IF
  !InParty(Player1)
THEN
  RESPONSE #100
    GameOver(19377)
END

//code from SoD
IF
  Global("bd_spect","global",3)
  Global("bd_spect_journal","global",0)
THEN
  RESPONSE #100
    AddJournalEntry(261616,QUEST_DONE) // Zaviak's Vision Quest  The Spectacles of Spectacle are out of charges.   The creatures I did see were unusual, dangerous, and fascinating. Zaviak may be a strange character, but his glasses worked and they did open my mind to some degree.
    SetGlobal("bd_spect_journal","global",1)
END

IF
  Global("BD_XHOST_SWORD","GLOBAL",1)
  OR(6)
    HasItemEquipedReal("BDSW1HX5",Player1) // Gift of the Demon +1
    HasItemEquipedReal("BDSW1HX5",Player2) // Gift of the Demon +1
    HasItemEquipedReal("BDSW1HX5",Player3) // Gift of the Demon +1
    HasItemEquipedReal("BDSW1HX5",Player4) // Gift of the Demon +1
    HasItemEquipedReal("BDSW1HX5",Player5) // Gift of the Demon +1
    HasItemEquipedReal("BDSW1HX5",Player6) // Gift of the Demon +1
THEN
  RESPONSE #1000
    SetGlobal("BD_XHOST_SWORD","GLOBAL",2)
    DisplayStringHeadOwner("BDSW1HX5",267252) // Your sword blade snaps in half with a crack that almost sounds like a rasping laugh.
END

IF
  Global("BD_PARTY_HAS_BDCLCK05","GLOBAL",0)
  PartyHasItem("bdclck05")  // Cloak of the Gargoyle
THEN
  RESPONSE #100
    SetGlobal("BD_PARTY_HAS_BDCLCK05","GLOBAL",1)
END

IF
  AreaCheck("bd1000")
  Global("bd_remove_bdrep","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("bd_remove_bdrep","GLOBAL",1)
    SetGlobalTimer("bd_reputation_warning_timer","global",3)
    ApplySpellRES("BDREP1",Player2)  // No such index
    ApplySpellRES("BDREP1",Player3)  // No such index
    ApplySpellRES("BDREP1",Player4)  // No such index
    ApplySpellRES("BDREP1",Player5)  // No such index
    ApplySpellRES("BDREP1",Player6)  // No such index
END
>>>>>>>>

EXTEND_BOTTOM ~BALDUR.BCS~ ~.../BALDUR-eb.baf~
EXTEND_BOTTOM ~BALDUR25.BCS~ ~.../BALDUR-eb.baf~

<<<<<<<< .../BALDUR25-eb.baf
//code from SoA
IF
  InPartyAllowDead("Nalia")
  Dead("Nalia")
  Dead("Torgal")
  Global("NaliaTorgalDies","GLOBAL",0)
  Global("NaliaKeepPlot","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("NaliaTorgalDies","GLOBAL",1)
END

IF
  InPartyAllowDead("Nalia")
  Dead("Nalia")
  AreaCheck("AR1300")
  Global("EnteredAR1300","GLOBAL",0)
  Global("NaliaKeepPlot","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("EnteredAR1300","GLOBAL",1)
    SetGlobalTimer("ArrivedNaliaKeep","GLOBAL",ONE_DAY)
END

IF
  InPartyAllowDead("Nalia")
  Dead("Nalia")
  Global("DelciaLeave","GLOBAL",1)
  Global("NaliaKeepPlot","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("DelciaLeave","GLOBAL",2)
END

IF
  InPartyAllowDead("Nalia")
  Dead("Nalia")
  AreaCheck("AR1302")
  CombatCounter(0)
  Global("NaliaInAR1302","AR1302",0)
THEN
  RESPONSE #100
    SetGlobal("NaliaInAR1302","AR1302",1)
END

IF
  InPartyAllowDead("Nalia")
  Dead("Nalia")
  AreaCheck("AR1303")
  Global("NaliaInAR1303","AR1303",0)
THEN
  RESPONSE #100
    SetGlobal("NaliaInAR1303","AR1303",1)
END

IF
  Delay(10)
  Global("FoundMontaronBody","GLOBAL",0)
  PartyHasItem("MISC5U") // Montaron's Body
THEN
  RESPONSE #100
    SetGlobal("FoundMontaronBody","GLOBAL",1)
    AddexperienceParty(20000)
END

IF
  Delay(10)
  Global("HabibAppearance","GLOBAL",0)
  PartyHasItem("SW1H56") // Scimitar
THEN
  RESPONSE #100
    ActionOverride(Player1,DropItem("SW1H56",[-1.-1])) // Scimitar
    ActionOverride(Player2,DropItem("SW1H56",[-1.-1])) // Scimitar
    ActionOverride(Player3,DropItem("SW1H56",[-1.-1])) // Scimitar
    ActionOverride(Player4,DropItem("SW1H56",[-1.-1])) // Scimitar
    ActionOverride(Player5,DropItem("SW1H56",[-1.-1])) // Scimitar
    ActionOverride(Player6,DropItem("SW1H56",[-1.-1])) // Scimitar
    SetGlobal("HabibAppearance","GLOBAL",1)
END

IF
  Delay(10)
  Global("HabibAppearance","GLOBAL",1)
  AreaCheck("AR0408")
  PartyHasItem("MISC07") // Gold
THEN
  RESPONSE #100
    ActionOverride(Player1,DropItem("MISC07",[-1.-1])) // Gold
    ActionOverride(Player2,DropItem("MISC07",[-1.-1])) // Gold
    ActionOverride(Player3,DropItem("MISC07",[-1.-1])) // Gold
    ActionOverride(Player4,DropItem("MISC07",[-1.-1])) // Gold
    ActionOverride(Player5,DropItem("MISC07",[-1.-1])) // Gold
    ActionOverride(Player6,DropItem("MISC07",[-1.-1])) // Gold
    SetGlobal("HabibAppearance","GLOBAL",2)
END

IF
  OR(2)
    Global("PCSphere","GLOBAL",2)
    ReputationLT(Player1,4)
  GlobalLT("BribedCowled","GLOBAL",2)
THEN
  RESPONSE #100
    SetGlobal("BribedCowled","GLOBAL",2)
END

IF
  !Global("Chapter","GLOBAL",16)
  !Global("Chapter","GLOBAL",17)
  !Global("Chapter","GLOBAL",19)
  !Global("Chapter","GLOBAL",22)
  AreaType(OUTDOOR)
  !AreaCheck("AR2500")
  !AreaCheck("AR1901")
  !AreaCheck("OH5500")
  Dead("cefald01")
  Class(Player1,DRUID_ALL)
  !Class(Player1,SHAMAN)
  LevelGT(Player1,13)
  Global("DruidADSpawn","GLOBAL",0)
  Global("GreatDruid","GLOBAL",0)
THEN
  RESPONSE #100
    Wait(2)
    SetGlobal("DruidADSpawn","GLOBAL",1)
    CreateCreatureObject("bdoffscr",Player1,0,0,0)  // No such index
    ApplySpellRES("bdoffscr","bdoffscr")  // No such index
    SmallWait(1)
    CreateCreatureObject("DRUIDAD","bdoffscr",0,0,0)  // Druid
END

IF
  !Global("Chapter","GLOBAL",16)
  !Global("Chapter","GLOBAL",17)
  !Global("Chapter","GLOBAL",19)
  !Global("Chapter","GLOBAL",22)
  AreaType(OUTDOOR)
  !AreaCheck("AR2500")
  !AreaCheck("AR1901")
  !AreaCheck("OH5500")
  Class(Player1,DRUID_ALL)
  !Class(Player1,SHAMAN)
  LevelGT(Player1,13)
  Global("DruidADSpawn","GLOBAL",1)
  Global("GreatDruid","GLOBAL",0)
  GlobalTimerExpired("DruidADReturn","GLOBAL")
THEN
  RESPONSE #100
    SetGlobal("DruidADSpawn","GLOBAL",2)
    CreateCreatureObject("bdoffscr",Player1,0,0,0)  // No such index
    ApplySpellRES("bdoffscr","bdoffscr")  // No such index
    SmallWait(1)
    CreateCreatureObject("DRUIDAD","bdoffscr",0,0,0)  // Druid
END

IF
  Global("drowTalk","GLOBAL",0)
  Global("slayer1","GLOBAL",0)
  PartyRested()
  GlobalGT("AsylumPlot","GLOBAL",43)
THEN
  RESPONSE #100
    SetGlobal("drowTalk","GLOBAL",2)
    SetGlobal("slayer1","GLOBAL",1)
    SetGlobalTimer("SlayerTimer2","GLOBAL",FIVE_MINUTES)
    ActionOverride(Player1,StartDialog("player1",Player1))
END

IF
  GlobalTimerExpired("SlayerTimer2","GLOBAL")
  Global("goodagain","GLOBAL",0)
THEN
  RESPONSE #100
    ActionOverride(Player1,ReallyForceSpellRES("spin718a",Myself)) // End Slayer Change
    SetGlobal("goodagain","GLOBAL",1)
    SetGlobal("DrowTalk","GLOBAL",4)
    ActionOverride(Player1,StartDialog("player1",Player1))
END

IF
  Global("Slayer10","GLOBAL",1)
THEN
  RESPONSE #100
    ActionOverride(Player1,StartDialog("player1",Player1))
END

IF
  GlobalTimerExpired("PGThievesReturn","GLOBAL")
  Global("NotifyThiefHead","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("NotifyThiefHead","GLOBAL",1)
    DisplayStringHead(Player1,62083) // Your thieves have returned from their missions.
END

IF
  GlobalTimerExpired("JosterReturn","GLOBAL")
  Global("JosterLeave","GLOBAL",1)
  !AreaType(BG1AREA)
  !Global("Chapter","GLOBAL",16)
  !Global("Chapter","GLOBAL",17)
  !Global("Chapter","GLOBAL",19)
  !Global("Chapter","GLOBAL",22)
THEN
  RESPONSE #100
    SetGlobal("JosterLeave","GLOBAL",2)
    SetGlobalTimer("JosterReturn","GLOBAL",SIX_DAYS)
    SetGlobalTimer("JosterPaid","GLOBAL",FIVE_DAYS)
    DisplayStringHead(Player1,62081) // The quartermaster awaits you in the guild for Renal's due.
END

IF
  GlobalTimerExpired("JosterPaid","GLOBAL")
  !Global("JosterLeave","GLOBAL",1)
  Global("PGFailed","GLOBAL",0)
  !Global("Chapter","GLOBAL",16)
  !Global("Chapter","GLOBAL",17)
  !Global("Chapter","GLOBAL",19)
THEN
  RESPONSE #100
    SetGlobal("PGFailed","GLOBAL",1)
    DisplayStringHead(Player1,62082) // Renal will no longer wait for his due... You have lost your guild.
END

IF
  Global("MinscByeBye","GLOBAL",1)
THEN
  RESPONSE #100
    ActionOverride("Minsc",EscapeArea())
END

IF
  Global("MinscByeBye","GLOBAL",2)
THEN
  RESPONSE #100
    MoveGlobal("AR0400","Minsc",[519.529])
END

IF
  Global("SpawnTanadv","GLOBAL",0)
  Global("TurnCragmoon","GLOBAL",1)
  GlobalTimerExpired("CragmoonAttack","GLOBAL")
  !Global("Chapter","GLOBAL",16)
  !Global("Chapter","GLOBAL",17)
  !Global("Chapter","GLOBAL",19)
  !Global("Chapter","GLOBAL",22)
  AreaType(CITY)
  !AreaCheck("AR2500")
  !AreaCheck("AR1000")
  !AreaCheck("AR0700")
  !AreaCheck("AR0900")
  AreaType(OUTDOOR)
THEN
  RESPONSE #100
    SetGlobal("SpawnTanadv","GLOBAL",1)
    CreateCreatureObject("bdoffscr",Player1,0,0,0)  // No such index
    ApplySpellRES("bdoffscr","bdoffscr")  // No such index
    SmallWait(1)
    CreateCreatureObject("TANADV01","bdoffscr",0,0,0)  // Strachan Fireblade
    CreateCreatureObject("bdoffscr",Player1,0,0,0)  // No such index
    ApplySpellRES("bdoffscr","bdoffscr")  // No such index
    SmallWait(1)
    CreateCreatureObject("TANADV02","bdoffscr",0,0,0)  // Adventurer
    CreateCreatureObject("bdoffscr",Player1,0,0,0)  // No such index
    ApplySpellRES("bdoffscr","bdoffscr")  // No such index
    SmallWait(1)
    CreateCreatureObject("TANADV03","bdoffscr",0,0,0)  // Adventurer
    CreateCreatureObject("bdoffscr",Player1,0,0,0)  // No such index
    ApplySpellRES("bdoffscr","bdoffscr")  // No such index
    SmallWait(1)
    CreateCreatureObject("TANADV04","bdoffscr",0,0,0)  // Adventurer
    CreateCreatureObject("bdoffscr",Player1,0,0,0)  // No such index
    ApplySpellRES("bdoffscr","bdoffscr")  // No such index
    SmallWait(1)
    CreateCreatureObject("TANADV05","bdoffscr",0,0,0)  // Adventurer
    CreateCreatureObject("bdoffscr",Player1,0,0,0)  // No such index
    ApplySpellRES("bdoffscr","bdoffscr")  // No such index
    SmallWait(1)
    CreateCreatureObject("TANADV06","bdoffscr",0,0,0)  // Dunbar the Fifth
END

IF
  Dead("Jaheira")
  GlobalGT("JaheiraCursed","GLOBAL",0)
  GlobalLT("JaheiraCursed","GLOBAL",8)
  Global("JaheiraCursedDead","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("JaheiraCursedDead","GLOBAL",1)
END

IF
  GlobalGT("JaheiraCursed","GLOBAL",6)
  Global("JaheiraCursedDead","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("JaheiraCursedDead","GLOBAL",0)
    Continue()
END

IF
  GlobalGT("JaheiraCursed","GLOBAL",0)
  GlobalLT("JaheiraCursed","GLOBAL",8)
  Global("JaheiraCursedDead","GLOBAL",1)
  !Dead("Jaheira")
THEN
  RESPONSE #100
    ActionOverride("Jaheira",StartDialogueNoSet([PC]))
END

IF
  GlobalTimerExpired("OgronAssault","GLOBAL")
  !Global("Chapter","GLOBAL",16)
  !Global("Chapter","GLOBAL",17)
  !Global("Chapter","GLOBAL",19)
  AreaType(OUTDOOR)
  Global("DelonSpawn","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("DelonSpawn","GLOBAL",1)
    SetGlobal("OgronAttack","GLOBAL",1)
    CreateCreatureObject("bdoffscr",Player1,0,0,0)  // No such index
    ApplySpellRES("bdoffscr","bdoffscr")  // No such index
    SmallWait(1)
    CreateCreatureObject("DELON","bdoffscr",0,0,0)  // Delon
    ActionOverride("delon",StartDialogueNoSet(Player1))
END

IF
  GlobalTimerExpired("UmarAssault","GLOBAL")
  !Global("Chapter","GLOBAL",16)
  !Global("Chapter","GLOBAL",17)
  !Global("Chapter","GLOBAL",19)
  AreaType(OUTDOOR)
  Global("DelonSpawn","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("DelonSpawn","GLOBAL",2)
    SetGlobal("UmarPlot","GLOBAL",1)
    CreateCreatureObject("bdoffscr",Player1,0,0,0)  // No such index
    ApplySpellRES("bdoffscr","bdoffscr")  // No such index
    SmallWait(1)
    CreateCreatureObject("DELON","bdoffscr",0,0,0)  // Delon
    ActionOverride("delon",StartDialogueNoSet(Player1))
END

IF
  GlobalTimerExpired("MeetHiggin","GLOBAL")
  Global("MeckComesFirst","GLOBAL",0)
  !Global("Chapter","GLOBAL",16)
  !Global("Chapter","GLOBAL",17)
  !Global("Chapter","GLOBAL",19)
  !Global("Chapter","GLOBAL",22)
  !AreaCheck("AR2000")
  Global("BardPlot1","GLOBAL",0)
  AreaType(CITY)
  OR(3)
    AreaType(OUTDOOR)
    AreaCheck("AR0522")
    AreaCheck("AR0511")
THEN
  RESPONSE #100
    SetGlobal("MeckComesFirst","GLOBAL",1)
    CreateCreatureObject("bdoffscr",Player1,0,0,0)  // No such index
    ApplySpellRES("bdoffscr","bdoffscr")  // No such index
    SmallWait(1)
    CreateCreatureObject("bdgoph01","bdoffscr",0,0,0)  // Meck
END

IF
  GlobalTimerExpired("MeetHiggin","GLOBAL")
  !Global("Chapter","GLOBAL",16)
  !Global("Chapter","GLOBAL",17)
  !Global("Chapter","GLOBAL",19)
  !Global("Chapter","GLOBAL",22)
  AreaType(CITY)
  !AreaCheck("AR2000")
  Global("BardPlot1","GLOBAL",3)
  OR(3)
    AreaType(OUTDOOR)
    AreaCheck("AR0522")
    AreaCheck("AR0511")
THEN
  RESPONSE #100
    SetGlobal("BardPlot1","GLOBAL",4)
    SetGlobal("BardPlotOn","GLOBAL",1)
    CreateCreatureObject("bdoffscr",Player1,0,0,0)  // No such index
    ApplySpellRES("bdoffscr","bdoffscr")  // No such index
    SmallWait(1)
    CreateCreatureObject("bdgoph01","bdoffscr",0,0,0)  // Meck
END

IF
  GlobalTimerExpired("MeetHiggin2","GLOBAL")
  !Global("Chapter","GLOBAL",16)
  !Global("Chapter","GLOBAL",17)
  !Global("Chapter","GLOBAL",19)
  !Global("Chapter","GLOBAL",22)
  AreaType(CITY)
  !AreaCheck("AR2000")
  Global("BardPlot1","GLOBAL",6)
  OR(3)
    AreaType(OUTDOOR)
    AreaCheck("AR0522")
    AreaCheck("AR0511")
THEN
  RESPONSE #100
    SetGlobal("BardPlot1","GLOBAL",7)
    SetGlobal("BardPlotOn","GLOBAL",1)
    CreateCreatureObject("bdoffscr",Player1,0,0,0)  // No such index
    ApplySpellRES("bdoffscr","bdoffscr")  // No such index
    SmallWait(1)
    CreateCreatureObject("bdgoph01","bdoffscr",0,0,0)  // Meck
END

IF
  GlobalTimerExpired("MeetHiggin3","GLOBAL")
  !Global("Chapter","GLOBAL",16)
  !Global("Chapter","GLOBAL",17)
  !Global("Chapter","GLOBAL",19)
  !Global("Chapter","GLOBAL",22)
  AreaType(CITY)
  !AreaCheck("AR2000")
  Global("BardPlot1","GLOBAL",9)
  OR(3)
    AreaType(OUTDOOR)
    AreaCheck("AR0522")
    AreaCheck("AR0511")
THEN
  RESPONSE #100
    SetGlobal("BardPlot1","GLOBAL",10)
    SetGlobal("BardPlotOn","GLOBAL",1)
    CreateCreatureObject("bdoffscr",Player1,0,0,0)  // No such index
    ApplySpellRES("bdoffscr","bdoffscr")  // No such index
    SmallWait(1)
    CreateCreatureObject("bdgoph01","bdoffscr",0,0,0)  // Meck
END

IF
  GlobalTimerExpired("MeetHiggin4","GLOBAL")
  !Global("Chapter","GLOBAL",16)
  !Global("Chapter","GLOBAL",17)
  !Global("Chapter","GLOBAL",19)
  !Global("Chapter","GLOBAL",22)
  AreaType(CITY)
  !AreaCheck("AR2000")
  Global("BardPlot1","GLOBAL",12)
  OR(3)
    AreaType(OUTDOOR)
    AreaCheck("AR0522")
    AreaCheck("AR0511")
THEN
  RESPONSE #100
    SetGlobal("BardPlot1","GLOBAL",13)
    SetGlobal("BardPlotOn","GLOBAL",1)
    CreateCreatureObject("bdoffscr",Player1,0,0,0)  // No such index
    ApplySpellRES("bdoffscr","bdoffscr")  // No such index
    SmallWait(1)
    CreateCreatureObject("bdgoph01","bdoffscr",0,0,0)  // Meck
END

IF
  GlobalTimerExpired("MeetHiggin5","GLOBAL")
  !Global("Chapter","GLOBAL",16)
  !Global("Chapter","GLOBAL",17)
  !Global("Chapter","GLOBAL",19)
  !Global("Chapter","GLOBAL",22)
  AreaType(CITY)
  !AreaCheck("AR2000")
  Global("BardPlot1","GLOBAL",16)
  OR(3)
    AreaType(OUTDOOR)
    AreaCheck("AR0522")
    AreaCheck("AR0511")
THEN
  RESPONSE #100
    SetGlobal("BardPlot1","GLOBAL",17)
    SetGlobal("BardPlotOn","GLOBAL",1)
    CreateCreatureObject("bdoffscr",Player1,0,0,0)  // No such index
    ApplySpellRES("bdoffscr","bdoffscr")  // No such index
    SmallWait(1)
    CreateCreatureObject("bdgoph01","bdoffscr",0,0,0)  // Meck
END

IF
  GlobalTimerExpired("MeetHiggin6","GLOBAL")
  !Global("Chapter","GLOBAL",16)
  !Global("Chapter","GLOBAL",17)
  !Global("Chapter","GLOBAL",19)
  !Global("Chapter","GLOBAL",22)
  AreaType(CITY)
  !AreaCheck("AR2000")
  Global("BardPlot1","GLOBAL",19)
  OR(2)
    AreaType(OUTDOOR)
    AreaCheck("AR0511")
THEN
  RESPONSE #100
    SetGlobal("BardPlot1","GLOBAL",40)
    SetGlobal("BardPlotOn","GLOBAL",1)
    CreateCreatureObject("bdoffscr",Player1,0,0,0)  // No such index
    ApplySpellRES("bdoffscr","bdoffscr")  // No such index
    SmallWait(1)
    CreateCreatureObject("bdgoph01","bdoffscr",0,0,0)  // Meck
END

IF
  GlobalTimerExpired("MeetHiggin7","GLOBAL")
  Global("BardPlot1","GLOBAL",42)
  !Global("Chapter","GLOBAL",16)
  !Global("Chapter","GLOBAL",17)
  !Global("Chapter","GLOBAL",19)
  !Global("Chapter","GLOBAL",22)
  AreaType(CITY)
  !AreaCheck("AR2000")
  OR(3)
    AreaType(OUTDOOR)
    AreaCheck("AR0522")
    AreaCheck("AR0511")
THEN
  RESPONSE #100
    SetGlobal("BardPlot1","GLOBAL",45)
    SetGlobal("BardPlotOn","GLOBAL",1)
    CreateCreatureObject("bdoffscr",Player1,0,0,0)  // No such index
    ApplySpellRES("bdoffscr","bdoffscr")  // No such index
    SmallWait(1)
    CreateCreatureObject("bdgoph01","bdoffscr",0,0,0)  // Meck
END

IF
  GlobalTimerExpired("MeetHiggin8","GLOBAL")
  AreaType(CITY)
  !AreaCheck("AR2000")
  Global("BardPlot1","GLOBAL",50)
  !Global("Chapter","GLOBAL",16)
  !Global("Chapter","GLOBAL",17)
  !Global("Chapter","GLOBAL",19)
  !Global("Chapter","GLOBAL",22)
  OR(3)
    AreaType(OUTDOOR)
    AreaCheck("AR0522")
    AreaCheck("AR0511")
THEN
  RESPONSE #100
    SetGlobal("BardPlot1","GLOBAL",51)
    SetGlobal("BardPlotOn","GLOBAL",1)
    CreateCreatureObject("bdoffscr",Player1,0,0,0)  // No such index
    ApplySpellRES("bdoffscr","bdoffscr")  // No such index
    SmallWait(1)
    CreateCreatureObject("bdgoph01","bdoffscr",0,0,0)  // Meck
END

IF
  PartyRested()
  GlobalTimerExpired("JaheiraReturn","GLOBAL")
  Global("JaheiraReturns","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("JaheiraReturns","GLOBAL",1)
    MoveGlobalObject("Jaheira",Player1)
END

IF
  GlobalTimerExpired("BardMoneyTime","GLOBAL")
  GlobalGT("BardMoney","GLOBAL",500)
  Global("BardPlotOn","GLOBAL",5)
THEN
  RESPONSE #100
    SetGlobalTimer("BardMoneyTime","GLOBAL",SEVEN_DAYS)
    DisplayString(Player1,47142) // Gold has been placed in your keep.
    IncrementGlobal("BardMoney","GLOBAL",-100)
    AddGlobals("BardMoneyX","BardMoney")
END

IF
  GlobalTimerExpired("BardMoneyTime","GLOBAL")
  GlobalLT("BardMoney","GLOBAL",501)
  Global("BardPlotOn","GLOBAL",5)
THEN
  RESPONSE #100
    SetGlobalTimer("BardMoneyTime","GLOBAL",SEVEN_DAYS)
    DisplayString(Player1,47142) // Gold has been placed in your keep.
    AddGlobals("BardMoneyX","BardMoney")
END

IF
  GlobalTimerExpired("KPTaxTime","GLOBAL")
  Global("PCKeepOwner","GLOBAL",1)
THEN
  RESPONSE #100
    DisplayString(Player1,47142) // Gold has been placed in your keep.
    SetGlobalTimer("KPTaxTime","GLOBAL",SEVEN_DAYS)
    IncrementGlobal("KPTaxes","GLOBAL",500)
END

IF
  GlobalTimerExpired("KPPlotTime","GLOBAL")
  AreaType(OUTDOOR)
  !AreaCheck("AR2500")
  !AreaCheck("AR2600")
  !AreaCheck("AR2000")
  !AreaCheck("AR1900")
  !AreaCheck("OH5500")
  Global("KeepPlot","GLOBAL",4)
  InParty("Nalia")
  !Global("Chapter","GLOBAL",16)
  !Global("Chapter","GLOBAL",17)
  !Global("Chapter","GLOBAL",19)
  !Global("Chapter","GLOBAL",22)
  Global("NaliaIsaeaPlotDone","GLOBAL",1)
  Global("KPRunnerSpawn","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("KPRunnerSpawn","GLOBAL",1)
    CreateCreatureObject("bdoffscr",Player1,0,0,0)  // No such index
    ApplySpellRES("bdoffscr","bdoffscr")  // No such index
    SmallWait(1)
    CreateCreatureObject("KPRUNN01","bdoffscr",0,0,0)  // Keep Messenger
END

IF
  GlobalTimerExpired("KPPlotTime","GLOBAL")
  AreaType(OUTDOOR)
  !AreaCheck("AR2500")
  !AreaCheck("AR2600")
  !AreaCheck("AR2000")
  !AreaCheck("AR1900")
  !AreaCheck("OH5500")
  !Global("Chapter","GLOBAL",16)
  !Global("Chapter","GLOBAL",17)
  !Global("Chapter","GLOBAL",19)
  !Global("Chapter","GLOBAL",22)
  Global("KeepPlot","GLOBAL",4)
  !InParty("Nalia")
  Global("KPRunnerSpawn","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("KPRunnerSpawn","GLOBAL",1)
    CreateCreatureObject("bdoffscr",Player1,0,0,0)  // No such index
    ApplySpellRES("bdoffscr","bdoffscr")  // No such index
    SmallWait(1)
    CreateCreatureObject("KPRUNN01","bdoffscr",0,0,0)  // Keep Messenger
END

IF
  GlobalTimerExpired("KPPlotTime","GLOBAL")
  AreaType(OUTDOOR)
  !AreaCheck("AR2500")
  !AreaCheck("AR2600")
  !AreaCheck("AR2000")
  !AreaCheck("AR1900")
  !AreaCheck("OH5500")
  !Global("Chapter","GLOBAL",16)
  !Global("Chapter","GLOBAL",17)
  !Global("Chapter","GLOBAL",19)
  !Global("Chapter","GLOBAL",22)
  Global("KeepPlot","GLOBAL",7)
  Global("KPRunnerSpawn","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("KPRunnerSpawn","GLOBAL",2)
    CreateCreatureObject("bdoffscr",Player1,0,0,0)  // No such index
    ApplySpellRES("bdoffscr","bdoffscr")  // No such index
    SmallWait(1)
    CreateCreatureObject("KPRUNN01","bdoffscr",0,0,0)  // Keep Messenger
END

IF
  GlobalTimerExpired("KPPlotTime","GLOBAL")
  AreaType(OUTDOOR)
  !AreaCheck("AR2500")
  !AreaCheck("AR2600")
  !AreaCheck("AR2000")
  !AreaCheck("AR1900")
  !AreaCheck("OH5500")
  !Global("Chapter","GLOBAL",16)
  !Global("Chapter","GLOBAL",17)
  !Global("Chapter","GLOBAL",19)
  !Global("Chapter","GLOBAL",22)
  Global("KeepPlot","GLOBAL",8)
  Global("KPRunnerSpawn","GLOBAL",2)
THEN
  RESPONSE #100
    SetGlobal("KPRunnerSpawn","GLOBAL",3)
    CreateCreatureObject("bdoffscr",Player1,0,0,0)  // No such index
    ApplySpellRES("bdoffscr","bdoffscr")  // No such index
    SmallWait(1)
    CreateCreatureObject("KPRUNN01","bdoffscr",0,0,0)  // Keep Messenger
END

IF
  GlobalGT("KPRevolt","GLOBAL",9)
  Global("RoenalControl","GLOBAL",0)
  GlobalLT("KeepPlot","GLOBAL",12)
THEN
  RESPONSE #100
    ClearAllActions()
    StartCutSceneMode()
    StartCutScene("Cut32n")
END

IF
  GlobalTimerExpired("TeolMessenger","GLOBAL")
  !Global("Chapter","GLOBAL",16)
  !Global("Chapter","GLOBAL",17)
  !Global("Chapter","GLOBAL",19)
  !Global("Chapter","GLOBAL",22)
  AreaType(OUTDOOR)
  !AreaCheck("AR2500")
  !AreaCheck("AR2600")
  !AreaCheck("OH5500")
  Global("NatulaSpawn","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("NatulaSpawn","GLOBAL",1)
    CreateCreatureObject("MGASS01",Player1,0,0,0) // Sergeant Natula
    ActionOverride("MGASS01",StartDialogueNoSet(Player1))
END

IF
  Global("geniesgone","GLOBAL",0)
  Dead("trgeni01")
THEN
  RESPONSE #100
    SetGlobal("geniesgone","GLOBAL",1)
END

IF
  Global("K#DisableSPIN649","GLOBAL",1)
  OR(2)
    AreaCheck("AR4500")
    !AreaCheckObject("AR4500",Player1)
THEN
  RESPONSE #100
    ReallyForceSpellRES("K#PP_REM",Player1) // No such index
    SetGlobal("K#DisableSPIN649","GLOBAL",0)
    Continue()
END

//code from DPLAYER2.BCS (which doesn't work when AI is off)
IF
  GlobalTimerExpired("PoisonParty","GLOBAL")
  GlobalLT("PoisonWarning","GLOBAL",9)
  Global("PartyCured","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobalTimer("PoisonParty","GLOBAL",ONE_DAY)
    IncrementGlobal("PoisonWarning","GLOBAL",1)
    DisplayString(Player1,11833) // You feel very ill, and you have thrown up your previous meal. Your head is fuzzy, and you are confused as to why you are sick. Then you remember what Lothander had told you. You've been poisoned! Lothander wasn't lying after all, and only he has the cure.
END

IF
  GlobalTimerExpired("PoisonParty2","GLOBAL")
  Global("PartyCured","GLOBAL",0)
THEN
  RESPONSE #100
    Kill(Player6)
    Kill(Player5)
    Kill(Player4)
    Kill(Player3)
    Kill(Player2)
    Kill(Player1)
END

IF
  Global("Infected","GLOBAL",1)
  GlobalTimerExpired("PlayerInfected","GLOBAL")
  !Dead("Mendas3") // Mendas
  Exists(Player2)
THEN
  RESPONSE #100
    ActionOverride(Player2,ForceSpell(Myself,PLAYER_WEREWOLF_CHANGE))
    ActionOverride(Player3,ForceSpell(Myself,PLAYER_WEREWOLF_CHANGE))
    ActionOverride(Player4,ForceSpell(Myself,PLAYER_WEREWOLF_CHANGE))
    ActionOverride(Player5,ForceSpell(Myself,PLAYER_WEREWOLF_CHANGE))
    ActionOverride(Player6,ForceSpell(Myself,PLAYER_WEREWOLF_CHANGE))
END
>>>>>>>>

EXTEND_BOTTOM ~BALDUR25.BCS~ ~.../BALDUR25-eb.baf~

<<<<<<<< .../timers-et.baf
//counts how many REAL hours you have been playing
IF
  Global("K#TotalPlayTimeActive","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("K#TotalPlayTimeActive","GLOBAL",1)
    RealSetGlobalTimer("K#RealTimerOneHour","GLOBAL",3600)
    Continue()
END

IF
  RealGlobalTimerExpired("K#RealTimerOneHour","GLOBAL")
THEN
  RESPONSE #100
    IncrementGlobal("K#TotalPlayTime","GLOBAL",1)
    RealSetGlobalTimer("K#RealTimerOneHour","GLOBAL",3600)
    Continue()
END

//counts total in-game days passed
IF
  Global("K#SetTimerOneDay","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("K#SetTimerOneDay","GLOBAL",1)
    SetGlobalTimer("K#TimerOneDay","GLOBAL",ONE_DAY)
    Continue()
END

IF
  GlobalTimerExpired("K#TimerOneDay","GLOBAL")
  Global("K#CheckDays","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("K#CheckDays","GLOBAL",1)
    SetGlobalTimer("K#TimerCheckDay","GLOBAL",1)
    Continue()
END

IF
  GlobalsGT("K#TimerOneDay","K#TimerCheckDay")
  Global("K#CheckDays","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("K#CheckDays","GLOBAL",0)
    Continue()
END

IF
  GlobalsGT("K#TimerCheckDay","K#TimerOneDay")
  Global("K#CheckDays","GLOBAL",1)
THEN
  RESPONSE #100
    IncrementGlobal("K#TimerOneDay","GLOBAL",108000) //FIFTEEN_DAYS
    IncrementGlobal("K#DaysPassed","GLOBAL",1)
END
>>>>>>>>

EXTEND_TOP ~BALDUR.BCS~ ~.../timers-et.baf~
EXTEND_TOP ~BALDUR25.BCS~ ~.../timers-et.baf~
EXTEND_TOP ~BDBALDUR.BCS~ ~.../timers-et.baf~

/////                                                  \\\\\
///// DS3483.BCS (Town Crier)                          \\\\\
/////                                                  \\\\\

//workaround for CalanderDay trigger used in TOWNC01.DLG
<<<<<<<< .../DS3483-eb.baf
IF
  Global("K#DoOnce","LOCALS",0)
  Global("K#TOWNC01_cnt","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("K#DoOnce","LOCALS",1)
    SetGlobal("K#TOWNC01_cnt","GLOBAL",1) //modify this value if you want to change starting day
    SetGlobal("K#TOWNC01_day","GLOBAL",0) //just to be sure
    AddGlobals("K#TOWNC01_day","K#DaysPassed")
    Continue()
END

IF
  Global("K#DoOnce","LOCALS",1)
  GlobalsGT("K#DaysPassed","K#TOWNC01_day")
THEN
  RESPONSE #100
    IncrementGlobal("K#TOWNC01_cnt","GLOBAL",1)
    IncrementGlobal("K#TOWNC01_day","GLOBAL",1)
    Continue()
END
>>>>>>>>

EXTEND_BOTTOM ~DS3483.BCS~ ~.../DS3483-eb.baf~

/////                                                  \\\\\
///// DPLAYER2.BCS                                     \\\\\
/////                                                  \\\\\

COPY_EXISTING ~DPLAYER2.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~!InParty(Myself)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~Global("ENDOFBG1","GLOBAL",2)
  !InParty(Myself)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END

		SPRINT textToReplace ~BreakingPoint()~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~Global("ENDOFBG1","GLOBAL",2)
  BreakingPoint()~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END

		SPRINT textToReplace ~Global("IHATEYOUALL","LOCALS",1)[%newline%]*InParty(Myself)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~Global("ENDOFBG1","GLOBAL",2)
  Global("IHATEYOUALL","LOCALS",1)
  InParty(Myself)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END

<<<<<<<< .../DPLAYER2-eb.baf
IF
  GlobalLT("ENDOFBG1","GLOBAL",2)
  OR(2)
    !Specifics(Myself,NORMAL)
    !Global("bd_joined","locals",0)
  InPartyAllowDead(Myself)
  GlobalGT("bd_plot","global",0)
THEN
  RESPONSE #100
    ChangeSpecifics(Myself,NORMAL)
    SetGlobal("bd_joined","locals",0)
    SetGlobal("bd_npc_camp","locals",0)
END

IF
  GlobalLT("ENDOFBG1","GLOBAL",2)
  !InPartyAllowDead(Myself)
  GlobalGT("bd_plot","global",0)
THEN
  RESPONSE #100
    SetGlobal("KickedOut","LOCALS",0)
    SetGlobal("bd_joined","locals",1)
    SetGlobal("bd_npc_camp","locals",0)
    ChangeAIScript("bdparty",DEFAULT)
END

IF
  GlobalLT("ENDOFBG1","GLOBAL",2)
  !InParty(Myself)
  OR(5)
    Name("neera",Myself)
    Name("dorn",Myself)
    Name("rasaad",Myself)
    Name("baeloth",Myself)
    HappinessGT(Myself,-299)
THEN
  RESPONSE #100
    Dialog(Player1)
    ChangeAIScript("",DEFAULT)
END

IF
  GlobalLT("ENDOFBG1","GLOBAL",2)
  !InParty(Myself)
  !HappinessGT(Myself,-299)
  !Name("neera",Myself)
  !Name("dorn",Myself)
  !Name("rasaad",Myself)
  !Name("baeloth",Myself)
THEN
  RESPONSE #100
    VerbalConstant(Myself,UNHAPPY_BREAKING_POINT)
    Wait(5)
    EscapeArea()
END

IF
  GlobalLT("ENDOFBG1","GLOBAL",2)
  !Name("Imoen2",Myself)
  BreakingPoint()
THEN
  RESPONSE #100
    VerbalConstant(Myself,UNHAPPY_BREAKING_POINT)
    Wait(3)
    EscapeArea()
END

//IF
//  CheckStat(Myself,0,DEX)
//  See("Kiel") // Kiel the Legion Killer
//THEN
//  RESPONSE #100
//    ActionOverride("Kiel",DestroySelf())
//    LeaveParty()
//    SetDialogue("KielPC")
//    SetGlobal("KielPC","GLOBAL",1)
//    ChangeAIScript("",DEFAULT)
//END
>>>>>>>>

EXTEND_BOTTOM ~DPLAYER2.BCS~ ~.../DPLAYER2-eb.baf~

/////                                                  \\\\\
///// DPLAYER3.BCS                                     \\\\\
/////                                                  \\\\\

COPY_EXISTING ~DPLAYER3.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~Global("OHN_NEERA_RENC","GLOBAL",1)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~Global("ENDOFBG1","GLOBAL",2)
  Global("OHN_NEERA_RENC","GLOBAL",1)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END

<<<<<<<< .../oDPLAYER3.baf
IF
  GlobalTimerExpired("EndGame","GLOBAL")
THEN
  RESPONSE #100
    Kill(Player1)
END

IF
  GlobalTimerExpired("PoisonParty","GLOBAL")
  GlobalLT("PoisonWarning","GLOBAL",9)
  Global("PartyCured","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobalTimer("PoisonParty","GLOBAL",ONE_DAY)
    IncrementGlobal("PoisonWarning","GLOBAL",1)
    DisplayString(Myself,11833)
END

IF
  GlobalTimerExpired("PoisonParty2","GLOBAL")
  Global("PartyCured","GLOBAL",0)
THEN
  RESPONSE #100
    Kill(Player6)
    Kill(Player5)
    Kill(Player4)
    Kill(Player3)
    Kill(Player2)
    Kill(Player1)
END
>>>>>>>> 

<<<<<<<< .../nDPLAYER3.baf
>>>>>>>>

COPY_EXISTING ~DPLAYER3.bcs~ ~override~
R_B_B ~.../oDPLAYER3.baf~ ~.../nDPLAYER3.baf~ ON_MISMATCH PATCH_WARN ~WARNING: Could not find block matching .../oDPLAYER3.baf in %SOURCE_FILE%~ END

/////                                                  \\\\\
///// PLAYER1D.BCS                                     \\\\\
/////                                                  \\\\\

<<<<<<<< .../PLAYER1D-eb.baf
IF
  OR(2)
    Global("bd_cant_rest","myarea",1)
    Global("bd_no_camp_rest","myarea",1)
THEN
  RESPONSE #100
    DisplayStringNoName(Player1,269033) // ^RYou may not rest in this place.^-
END

IF
  GlobalGT("chapter","global",7)
  GlobalLT("chapter","global",13)
  !GlobalTimerNotExpired("bd_dream_timer","global")
  Global("bd_ddd","global",0)
THEN
  RESPONSE #100
    SetGlobal("bd_ddd","global",1)
    StartCutSceneMode()
    FadeToColor([30.0],0)
    SmallWait(20)
    AdvanceTime(EIGHT_HOURS)
    SetGlobalTimer("bd_dream_timer","global",TWELVE_HOURS)
    ApplySpellRES("bdrejuve",Player1) // No such index
    ApplySpellRES("bdrejuve",Player2) // No such index
    ApplySpellRES("bdrejuve",Player3) // No such index
    ApplySpellRES("bdrejuve",Player4) // No such index
    ApplySpellRES("bdrejuve",Player5) // No such index
    ApplySpellRES("bdrejuve",Player6) // No such index
    StartCutSceneEx("bdddd1a",TRUE)
END

IF
  GlobalGT("chapter","global",8)
  GlobalLT("chapter","global",13)
  !GlobalTimerNotExpired("bd_dream_timer","global")
  Global("bd_ddd","global",1)
THEN
  RESPONSE #100
    SetGlobal("bd_ddd","global",2)
    StartCutSceneMode()
    FadeToColor([30.0],0)
    SmallWait(20)
    AdvanceTime(EIGHT_HOURS)
    SetGlobalTimer("bd_dream_timer","global",TWELVE_HOURS)
    ApplySpellRES("bdrejuve",Player1) // No such index
    ApplySpellRES("bdrejuve",Player2) // No such index
    ApplySpellRES("bdrejuve",Player3) // No such index
    ApplySpellRES("bdrejuve",Player4) // No such index
    ApplySpellRES("bdrejuve",Player5) // No such index
    ApplySpellRES("bdrejuve",Player6) // No such index
    StartCutSceneEx("bdddd2a",TRUE)
END

IF
  GlobalGT("chapter","global",9)
  GlobalLT("chapter","global",13)
  !GlobalTimerNotExpired("bd_dream_timer","global")
  Global("bd_ddd","global",2)
THEN
  RESPONSE #100
    SetGlobal("bd_ddd","global",3)
    StartCutSceneMode()
    FadeToColor([30.0],0)
    SmallWait(20)
    AdvanceTime(EIGHT_HOURS)
    SetGlobalTimer("bd_dream_timer","global",TWELVE_HOURS)
    ApplySpellRES("bdrejuve",Player1) // No such index
    ApplySpellRES("bdrejuve",Player2) // No such index
    ApplySpellRES("bdrejuve",Player3) // No such index
    ApplySpellRES("bdrejuve",Player4) // No such index
    ApplySpellRES("bdrejuve",Player5) // No such index
    ApplySpellRES("bdrejuve",Player6) // No such index
    StartCutSceneEx("bdddd3a",TRUE)
END

IF
  GlobalGT("chapter","global",10)
  GlobalLT("chapter","global",13)
  !GlobalTimerNotExpired("bd_dream_timer","global")
  Global("bd_ddd","global",3)
THEN
  RESPONSE #100
    SetGlobal("bd_ddd","global",4)
    StartCutSceneMode()
    FadeToColor([30.0],0)
    SmallWait(20)
    AdvanceTime(EIGHT_HOURS)
    SetGlobalTimer("bd_dream_timer","global",TWELVE_HOURS)
    ApplySpellRES("bdrejuve",Player1) // No such index
    ApplySpellRES("bdrejuve",Player2) // No such index
    ApplySpellRES("bdrejuve",Player3) // No such index
    ApplySpellRES("bdrejuve",Player4) // No such index
    ApplySpellRES("bdrejuve",Player5) // No such index
    ApplySpellRES("bdrejuve",Player6) // No such index
    StartCutSceneEx("bdddd4a",TRUE)
END

IF
  AreaCheck("bd0104")
  GlobalGT("bd_jail_visitors","bd0104",11)
  GlobalLT("bd_plot","global",615)
THEN
  RESPONSE #100
    StartCutSceneMode()
    SetGlobal("bd_plot","global",615)
    ClearAllActions()
    StartCutSceneEx("bdcut64",TRUE)
END
>>>>>>>>

EXTEND_BOTTOM ~PLAYER1D.BCS~ ~.../PLAYER1D-eb.baf~

/////                                                  \\\\\
///// Imoen death variable changes                     \\\\\
/////                                                  \\\\\

COPY_EXISTING ~CLONROOM.BCS~ ~override~
	~CUT01.BCS~ ~override~
	~CUTD1.BCS~ ~override~
	~CUTSKIP2.BCS~ ~override~
	~ELLEROOM.BCS~ ~override~
	~LIBRARY.BCS~ ~override~
	~NEWGAME.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~"Imoen"~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~"Imoen2"~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

/////                                                  \\\\\
///// ToB transition                                   \\\\\
/////                                                  \\\\\

COPY_EXISTING ~CUT100A.BCS~ ~override~
	~CUT100B.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~MoveToExpansion()~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~MoveToCampaign("ToB")~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

/////                                                  \\\\\
///// Animation/color import for cutscene CRE files    \\\\\
/////                                                  \\\\\

ACTION_DEFINE_ASSOCIATIVE_ARRAY table_sourceBase BEGIN
	1 , ~CUT01~ , ~ CreateCreature("CSIMOEN",[^)]+)~ , ~CSIMOEN~ => ~Imoen2~ //Waukeen Promenade Imoen
	2 , ~MOVIE01A~ , ~ LeaveAreaLUA("AR0069","",\[0\.0\],S)~ , ~cuimoen~ => ~Imoen2~ //AR0069.ARE
	3 , ~MOVIE02A~ , ~ LeaveAreaLUA("AR0070","",\[0\.0\],S)~ , ~cuimoen2~ => ~Imoen2~ //AR0070.ARE
	4 , ~MOVIE03A~ , ~ LeaveAreaLUA("AR0071","",\[0\.0\],S)~ , ~cuimoen3~ => ~Imoen2~ //AR0071.ARE
	5 , ~MOVIE03B~ , ~ LeaveAreaLUA("AR0071","",\[0\.0\],S)~ , ~cuimoen3~ => ~Imoen2~ //AR0071.ARE
	6 , ~CUT67D~ , ~ CreateCreatureDoor("dpimo01",[^)]+)~ , ~dpimo01~ => ~Imoen2~
	7 , ~CUT69C~ , ~ CreateCreatureDoor("dpimo01",[^)]+)~ , ~dpimo01~ => ~Imoen2~
	8 , ~CUT28A~ , ~ LeaveAreaLUA("AR0011","",\[799\.1579\],N)~ , ~dream1~ => ~Imoen2~ //AR0011.ARE
	9 , ~CUT49A~ , ~ LeaveAreaLUA("AR0013","",\[1491\.1173\],W)~ , ~drim01~ => ~Imoen2~ //AR0013.ARE
	10 , ~CUT49C~ , ~ LeaveAreaLUA("AR0014","",\[721\.654\],N)~ , ~drim02~ => ~Imoen2~ //AR0014.ARE
	11 , ~CUT41H~ , ~ LeaveAreaLUA("AR0028","",\[2680\.2104\],NW)~ , ~ppdrimov~ => ~Imoen2~ //AR0028.ARE
	12 , ~AR1515~ , ~ CreateCreature("ppimoen",\[937\.1229\],E)~ , ~ppimoen~ => ~Imoen2~ //Spellhold Imoen
	13 , ~CUT41F~ , ~ CreateCreature("ppimoen",\[1098\.537\],S)~ , ~ppimoen~ => ~Imoen2~ //Spellhold Imoen
END

ACTION_PHP_EACH table_sourceBase AS source => base BEGIN
	COPY_EXISTING ~%source_1%.BCS~ ~override~
		DECOMPILE_AND_PATCH BEGIN
			SPRINT textToReplace ~\(%source_2%\)~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY ~%textToReplace%~ ~\1
		ActionOverride("%source_3%",PolymorphCopy("%base%"))~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
			END ELSE BEGIN
				PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
			END
		END
	BUT_ONLY
END

//AR0012.ARE Imoen
<<<<<<<< .../PPDRIMO-et.baf
IF
  Global("K#AnimationSwap","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("K#AnimationSwap","LOCALS",1)
    PolymorphCopy("Imoen2")
    Continue()
END
>>>>>>>>
EXTEND_TOP ~PPDRIMO.BCS~ ~.../PPDRIMO-et.baf~

/////                                                  \\\\\
///// AR0304 (Edwin spawn)                             \\\\\
/////                                                  \\\\\

<<<<<<<< .../AR0304-et.baf
IF
  Global("K#EdwinImport","AR0304",0)
  BeenInParty("Edwin")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Edwin",STATE_REALLY_DEAD)
THEN
  RESPONSE #100
    ActionOverride("Edwin",SetDialog("Edwin"))
    ActionOverride("Edwin",ChangeAIScript("",CLASS))
    ActionOverride("Edwin",ChangeAIScript("",RACE))
    ActionOverride("Edwin",ChangeAIScript("WTARSGT",GENERAL))
    ActionOverride("Edwin",ChangeAIScript("DPLAYER",DEFAULT))
    ActionOverride("Edwin",ChangeAIScript("Edwin",OVERRIDE))
    MoveGlobal("AR0304","Edwin",[852.340])
    ActionOverride("Edwin",Face(S))
    ActionOverride("Edwin",SetGlobal("BD_JOINXP","LOCALS",0))
    ActionOverride("Edwin",SetGlobal("KickedOut","LOCALS",0))
    ActionOverride("Edwin",SetNumTimesTalkedTo(0))
    ActionOverride("Edwin",DestroyAllEquipment())
    //DestroyItem("MISC89_") // Edwin's Amulet
    ActionOverride("Edwin",CreateItem("STAF01",1,0,0)) // Quarterstaff
    ActionOverride("Edwin",CreateItem("MISC89",1,0,0)) // Edwin's Amulet
    ActionOverride("Edwin",CreateItem("DAGG01",1,0,0)) // Dagger
    ActionOverride("Edwin",CreateItem("CLCK14",1,0,0)) // Adventurer's Robe
    ActionOverride("Edwin",CreateItem("EDWINKEY",1,0,0)) // Mae'Var's Strongbox Key
    ActionOverride("Edwin",FillSlot(SLOT_ARMOR))
    ActionOverride("Edwin",FillSlot(SLOT_WEAPON))
    ActionOverride("Edwin",FillSlot(SLOT_AMULET))
    ActionOverride("Edwin",EquipMostDamagingMelee())
    //ReallyForceSpellRES("K#POREDW","Edwin") // No such index
    SetPlayerSound("Edwin",-1,INITIAL_MEETING) // No such index
    SetPlayerSound("Edwin",3966,MORALE) // I'll not die to incompetence!
    SetPlayerSound("Edwin",3968,HAPPY) // I had not thought this group capable of pleasing me, but I am impressed.
    SetPlayerSound("Edwin",3969,UNHAPPY_ANNOYED) // Could my opinion of this group drop ANY lower? Evidently so.
    SetPlayerSound("Edwin",3970,UNHAPPY_SERIOUS) // I warn you, I cannot abide this charity. It is not to my tastes at all.
    SetPlayerSound("Edwin",3971,UNHAPPY_BREAKING_POINT) // No, I do not feel this is working out. You waste opportunity after opportunity. I will stand no more.
    SetPlayerSound("Edwin",3972,LEADER) // It is about time you monkeys realized who should be leader.
    SetPlayerSound("Edwin",3973,TIRED) // I require rest. I demand we stop.
    SetPlayerSound("Edwin",3974,BORED) // Inactive outward, inactive inward. Why do I suffer these fools?
    SetPlayerSound("Edwin",3967,BATTLE_CRY1) // Your worthless lives end here!
    SetPlayerSound("Edwin",30694,BATTLE_CRY2) // Cry for your lives; they are over!
    SetPlayerSound("Edwin",30706,BATTLE_CRY3) // You can do nothing but die!
    SetPlayerSound("Edwin",-1,BATTLE_CRY4) // No such index
    SetPlayerSound("Edwin",-1,BATTLE_CRY5) // No such index
    SetPlayerSound("Edwin",-1,ATTACK1) // No such index
    SetPlayerSound("Edwin",-1,ATTACK2) // No such index
    SetPlayerSound("Edwin",-1,ATTACK3) // No such index
    SetPlayerSound("Edwin",-1,ATTACK4) // No such index
    SetPlayerSound("Edwin",5350,DAMAGE) // 
    SetPlayerSound("Edwin",5351,DYING) // 
    SetPlayerSound("Edwin",3975,HURT) // I could use some help here, fools.
    SetPlayerSound("Edwin",5345,AREA_FOREST) // I find the "great outdoors" chaotic and dirty. It needs a shaping will to slap the beasts into proper order. 
    SetPlayerSound("Edwin",5346,AREA_CITY) // The city changes, but the fools within are always the same. 
    SetPlayerSound("Edwin",5347,AREA_DUNGEON) // Could we not have hired some poor fools to do this for us? This is no place for a man of my stature.
    SetPlayerSound("Edwin",5348,AREA_DAY) // Another day and more aimless stumbling about. 
    SetPlayerSound("Edwin",5349,AREA_NIGHT) // Intelligent peoples do not wander around looking for trouble in the evening hours.
    SetPlayerSound("Edwin",3976,SELECT_COMMON1) // Yes?
    SetPlayerSound("Edwin",3977,SELECT_COMMON2) // What is it now?!
    SetPlayerSound("Edwin",3978,SELECT_COMMON3) // Go bother someone else.
    SetPlayerSound("Edwin",30709,SELECT_COMMON4) // I'm busy, okay? I'm busy!
    SetPlayerSound("Edwin",30710,SELECT_COMMON5) // Have you nothing else to do but bother me?
    SetPlayerSound("Edwin",30711,SELECT_COMMON6) // Ye-es, master, what shall I fetch now?
    SetPlayerSound("Edwin",30712,SELECT_ACTION1) // Oh, all right!
    SetPlayerSound("Edwin",30713,SELECT_ACTION2) // Yes, yes, I see.
    SetPlayerSound("Edwin",30714,SELECT_ACTION3) // One day... one day...
    SetPlayerSound("Edwin",30715,SELECT_ACTION4) // If I must.
    SetPlayerSound("Edwin",3984,SELECT_ACTION5) // Tedious monkey-work.
    SetPlayerSound("Edwin",3985,SELECT_ACTION6) // A waste of my talents.
    SetPlayerSound("Edwin",3986,SELECT_ACTION7) // Fine, fine, just stop pestering me.
    SetPlayerSound("Edwin",-1,INTERACTION1) // No such index
    SetPlayerSound("Edwin",-1,INTERACTION1) // No such index
    SetPlayerSound("Edwin",-1,INTERACTION2) // No such index
    SetPlayerSound("Edwin",-1,INTERACTION3) // No such index
    SetPlayerSound("Edwin",-1,INTERACTION4) // No such index
    SetPlayerSound("Edwin",-1,INTERACTION5) // No such index
    SetPlayerSound("Edwin",-1,INSULT1) // No such index
    SetPlayerSound("Edwin",-1,INSULT2) // No such index
    SetPlayerSound("Edwin",-1,INSULT3) // No such index
    SetPlayerSound("Edwin",-1,COMPLIMENT1) // No such index
    SetPlayerSound("Edwin",-1,COMPLIMENT2) // No such index
    SetPlayerSound("Edwin",-1,COMPLIMENT3) // No such index
    SetPlayerSound("Edwin",-1,SPECIAL1) // No such index
    SetPlayerSound("Edwin",-1,SPECIAL2) // No such index
    SetPlayerSound("Edwin",-1,SPECIAL3) // No such index
    SetPlayerSound("Edwin",-1,REACT_TO_DIE_GENERAL) // No such index
    SetPlayerSound("Edwin",-1,REACT_TO_DIE_SPECIFIC) // No such index
    SetPlayerSound("Edwin",-1,MISCELLANEOUS) // No such index
    SetPlayerSound("Edwin",-1,RESPONSE_TO_COMPLIMENT2) // No such index
    SetPlayerSound("Edwin",-1,RESPONSE_TO_COMPLIMENT3) // No such index
    SetPlayerSound("Edwin",-1,RESPONSE_TO_INSULT1) // No such index
    SetPlayerSound("Edwin",-1,RESPONSE_TO_INSULT2) // No such index
    SetPlayerSound("Edwin",-1,RESPONSE_TO_INSULT3) // No such index
    SetPlayerSound("Edwin",-1,DIALOG_HOSTILE) // No such index
    SetPlayerSound("Edwin",-1,DIALOG_DEFAULT) // No such index
    SetPlayerSound("Edwin",30716,SELECT_RARE1) // Very well.
    SetPlayerSound("Edwin",30717,SELECT_RARE2) // "Edwin, do this." "Edwin, do that." Somebody get this jerk a banana.
    SetPlayerSound("Edwin",30718,CRITICAL_HIT) // Ha! Fear me!
    SetPlayerSound("Edwin",30719,CRITICAL_MISS) // Bah! Useless weapon!
    SetPlayerSound("Edwin",30720,TARGET_IMMUNE) // Pfeh. This weapon is worthless!
    SetPlayerSound("Edwin",30721,INVENTORY_FULL) // I will carry no more. Find your trinket upon the ground.
    SetPlayerSound("Edwin",30722,PICKED_POCKET) // The fool saw nothing. Such simple larceny.
    SetPlayerSound("Edwin",30723,EXISTANCE1) // I am concealed, though I see no need.
    SetPlayerSound("Edwin",30724,EXISTANCE2) // My spell disrupted?! Augh!
    SetPlayerSound("Edwin",30725,EXISTANCE3) // I prefer to attack more directly, but a trap will do for now.
    SetPlayerSound("Edwin",-1,EXISTANCE4) // No such index
    SetPlayerSound("Edwin",10216,EXISTANCE5) // When asked about how he came to be in the employ of the Shadow Thieves, EDWIN sneers that it is none of your business. In his opinion, you are lucky enough to have encountered him at all, and further inquiries beyond this initial boon will only serve to tempt the fates. Despite his obstinate nature, there is a hint that his present circumstance is not all that favorable, and his willingness to join with you contradicts his supposed distaste for the company of others. Edwin ignores speculation about his recent past, but he does appear to have placed less emphasis on the Red Wizard colors he has so brazenly displayed in the past. It is an understandable act for a wizard traveler in mage-fearing Amn.
    SetGlobal("K#EdwinImport","AR0304",1)
    Continue()
END

/*IF
  Global("K#EdwinImport","AR0304",0)
  BeenInParty("Edwin")
  CheckStatLT("Edwin",10,STR)
THEN
  RESPONSE #100
    ChangeStat("Edwin",STR,10,SET)
    Continue()
END

IF
  Global("K#EdwinImport","AR0304",0)
  BeenInParty("Edwin")
  CheckStatLT("Edwin",10,WIS)
THEN
  RESPONSE #100
    ChangeStat("Edwin",WIS,10,SET)
    Continue()
END*/

IF
  Global("K#EdwinImport","AR0304",0)
  !BeenInParty("Edwin")
  GlobalLT("chapter","GLOBAL",20)
  //!StateCheck("Edwin",STATE_REALLY_DEAD)
  //LevelLT(Player1,9)
THEN
  RESPONSE #100
    CreateCreature("Edwin7",[852.340],S)
    ActionOverride("Edwin",MakeGlobalOverride())
    SetGlobal("K#EdwinImport","AR0304",1)
    Continue()
END

/*IF
  Global("K#EdwinImport","AR0304",0)
  !BeenInParty("Edwin")
  GlobalLT("chapter","GLOBAL",20)
  //!StateCheck("Edwin",STATE_REALLY_DEAD)
  LevelGT(Player1,8)
  LevelLT(Player1,11)
THEN
  RESPONSE #100
    CreateCreature("Edwin9",[852.340],S)
    ActionOverride("Edwin",MakeGlobalOverride())
    SetGlobal("K#EdwinImport","AR0304",1)
    Continue()
END

IF
  Global("K#EdwinImport","AR0304",0)
  !BeenInParty("Edwin")
  GlobalLT("chapter","GLOBAL",20)
  //!StateCheck("Edwin",STATE_REALLY_DEAD)
  Level(Player1,11)
THEN
  RESPONSE #100
    CreateCreature("Edwin11",[852.340],S)
    ActionOverride("Edwin",MakeGlobalOverride())
    SetGlobal("K#EdwinImport","AR0304",1)
    Continue()
END

IF
  Global("K#EdwinImport","AR0304",0)
  !BeenInParty("Edwin")
  GlobalLT("chapter","GLOBAL",20)
  //!StateCheck("Edwin",STATE_REALLY_DEAD)
  Level(Player1,12)
THEN
  RESPONSE #100
    CreateCreature("Edwin12",[852.340],S)
    ActionOverride("Edwin",MakeGlobalOverride())
    SetGlobal("K#EdwinImport","AR0304",1)
    Continue()
END

IF
  Global("K#EdwinImport","AR0304",0)
  !BeenInParty("Edwin")
  GlobalLT("chapter","GLOBAL",20)
  //!StateCheck("Edwin",STATE_REALLY_DEAD)
  LevelGT(Player1,12)
THEN
  RESPONSE #100
    CreateCreature("Edwin13",[852.340],S)
    ActionOverride("Edwin",MakeGlobalOverride())
    SetGlobal("K#EdwinImport","AR0304",1)
    Continue()
END*/
>>>>>>>>

EXTEND_TOP ~AR0304.BCS~ ~.../AR0304-et.baf~

/////                                                  \\\\\
///// AR0602 (newgame, Minsc, Jaheira, Imoen spawn)    \\\\\
/////                                                  \\\\\

<<<<<<<< .../AR0602-et.baf
IF
  Global("K#ImoenImport","AR0602",0)
  BeenInParty("Imoen2")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Imoen2",STATE_REALLY_DEAD)
THEN
  RESPONSE #100
    ActionOverride("Imoen2",SetDialog("IMOEN10"))
    ActionOverride("Imoen2",ChangeAIScript("NPCMAGE1",CLASS))
    ActionOverride("Imoen2",ChangeAIScript("",RACE))
    ActionOverride("Imoen2",ChangeAIScript("",GENERAL))
    ActionOverride("Imoen2",ChangeAIScript("WTASIGHT",DEFAULT))
    ActionOverride("Imoen2",ChangeAIScript("IMOEN",OVERRIDE))
    MoveGlobal("AR0602","Imoen2",[3198.2837])
    ActionOverride("Imoen2",Face(S))
    ActionOverride("Imoen2",SetGlobal("BD_JOINXP","LOCALS",0))
    ActionOverride("Imoen2",SetGlobal("KickedOut","LOCALS",0))
    ActionOverride("Imoen2",SetNumTimesTalkedTo(0))
    //ActionOverride("Imoen2",DestroyAllEquipment())
    ActionOverride("Imoen2",CreateItem("IMOENHP1",1,0,0)) // Imoen's Belt
    ActionOverride("Imoen2",FillSlot(SLOT_BELT))
    //ReallyForceSpellRES("K#PORIMO","Imoen2") // No such index
    SetPlayerSound("Imoen2",-1,INITIAL_MEETING) // No such index
    SetPlayerSound("Imoen2",11037,MORALE) // No, no! No, I'm not gonna end up dead in this place! I have to get out! I have to get to the surface!
    SetPlayerSound("Imoen2",30726,HAPPY) // Now I remember why traveling with you was always so much fun.
    SetPlayerSound("Imoen2",4338,UNHAPPY_ANNOYED) // I'll stick with you no matter what, but we should still try and be decent to people.
    SetPlayerSound("Imoen2",30727,UNHAPPY_SERIOUS) // I think all this has really changed you. Come on, this isn't like us at all.
    SetPlayerSound("Imoen2",-1,UNHAPPY_BREAKING_POINT) // No such index
    SetPlayerSound("Imoen2",4337,LEADER) // Aww, come on. I'm not cut out for the leadership stuff.
    SetPlayerSound("Imoen2",4339,TIRED) // *yawn* I'm getting sleepy. Wish we could stop for a bit.
    SetPlayerSound("Imoen2",4333,BORED) // If we're going to do nothing, let's at least find a safer place to do it.
    SetPlayerSound("Imoen2",11035,BATTLE_CRY1) // My blade will cut you down to size!
    SetPlayerSound("Imoen2",30729,BATTLE_CRY2) // If I have to fight to get out of here, so be it!
    SetPlayerSound("Imoen2",30730,BATTLE_CRY3) // You're not gonna keep me here!
    SetPlayerSound("Imoen2",-1,BATTLE_CRY4) // No such index
    SetPlayerSound("Imoen2",-1,BATTLE_CRY5) // No such index
    SetPlayerSound("Imoen2",-1,ATTACK1) // No such index
    SetPlayerSound("Imoen2",-1,ATTACK2) // No such index
    SetPlayerSound("Imoen2",-1,ATTACK3) // No such index
    SetPlayerSound("Imoen2",-1,ATTACK4) // No such index
    SetPlayerSound("Imoen2",5395,DAMAGE) // 
    SetPlayerSound("Imoen2",5396,DYING) // 
    SetPlayerSound("Imoen2",4330,HURT) // Come on, now, don't let me suffer in this place. We've both had enough of that.
    SetPlayerSound("Imoen2",30731,AREA_FOREST) // I wish I could spend more time in the forest. Oh, it feels so alive.
    SetPlayerSound("Imoen2",30732,AREA_CITY) // I don't feel like I fit in with people in the city anymore.
    SetPlayerSound("Imoen2",11036,AREA_DUNGEON) // This place is just too darn creepy. I really want out of here.
    SetPlayerSound("Imoen2",30733,AREA_DAY) // Glad to see another day. I think the light hurts my eyes though.
    SetPlayerSound("Imoen2",30734,AREA_NIGHT) // Might as well be up and about. I don't think I'd sleep anyway.
    SetPlayerSound("Imoen2",30735,SELECT_COMMON1) // Yep?
    SetPlayerSound("Imoen2",30736,SELECT_COMMON2) // Whatchu want?
    SetPlayerSound("Imoen2",30737,SELECT_COMMON3) // Name it.
    SetPlayerSound("Imoen2",30738,SELECT_COMMON4) // Ready and willing.
    SetPlayerSound("Imoen2",30739,SELECT_COMMON5) // Somethin' up?
    SetPlayerSound("Imoen2",30740,SELECT_COMMON6) // Time to move?
    SetPlayerSound("Imoen2",11038,SELECT_ACTION1) // Gotcha.
    SetPlayerSound("Imoen2",11039,SELECT_ACTION2) // Good to go.
    SetPlayerSound("Imoen2",4335,SELECT_ACTION3) // Right you are.
    SetPlayerSound("Imoen2",4336,SELECT_ACTION4) // All right, all right.
    SetPlayerSound("Imoen2",11043,SELECT_ACTION5) // No problem at all.
    SetPlayerSound("Imoen2",11042,SELECT_ACTION6) // You can count on me!
    SetPlayerSound("Imoen2",11045,SELECT_ACTION7) // This way then?
    SetPlayerSound("Imoen2",-1,INTERACTION1) // No such index
    SetPlayerSound("Imoen2",-1,INTERACTION1) // No such index
    SetPlayerSound("Imoen2",-1,INTERACTION2) // No such index
    SetPlayerSound("Imoen2",-1,INTERACTION3) // No such index
    SetPlayerSound("Imoen2",-1,INTERACTION4) // No such index
    SetPlayerSound("Imoen2",-1,INTERACTION5) // No such index
    SetPlayerSound("Imoen2",-1,INSULT1) // No such index
    SetPlayerSound("Imoen2",-1,INSULT2) // No such index
    SetPlayerSound("Imoen2",-1,INSULT3) // No such index
    SetPlayerSound("Imoen2",-1,COMPLIMENT1) // No such index
    SetPlayerSound("Imoen2",-1,COMPLIMENT2) // No such index
    SetPlayerSound("Imoen2",-1,COMPLIMENT3) // No such index
    SetPlayerSound("Imoen2",-1,SPECIAL1) // No such index
    SetPlayerSound("Imoen2",-1,SPECIAL2) // No such index
    SetPlayerSound("Imoen2",-1,SPECIAL3) // No such index
    SetPlayerSound("Imoen2",-1,REACT_TO_DIE_GENERAL) // No such index
    SetPlayerSound("Imoen2",-1,REACT_TO_DIE_SPECIFIC) // No such index
    SetPlayerSound("Imoen2",-1,MISCELLANEOUS) // No such index
    SetPlayerSound("Imoen2",-1,RESPONSE_TO_COMPLIMENT2) // No such index
    SetPlayerSound("Imoen2",-1,RESPONSE_TO_COMPLIMENT3) // No such index
    SetPlayerSound("Imoen2",-1,RESPONSE_TO_INSULT1) // No such index
    SetPlayerSound("Imoen2",-1,RESPONSE_TO_INSULT2) // No such index
    SetPlayerSound("Imoen2",-1,RESPONSE_TO_INSULT3) // No such index
    SetPlayerSound("Imoen2",-1,DIALOG_HOSTILE) // No such index
    SetPlayerSound("Imoen2",-1,DIALOG_DEFAULT) // No such index
    SetPlayerSound("Imoen2",30741,SELECT_RARE1) // Right as rain.
    SetPlayerSound("Imoen2",30742,SELECT_RARE2) // Just like old times. Well, except for the torture and all.
    SetPlayerSound("Imoen2",30746,CRITICAL_HIT) // Gotcha good!
    SetPlayerSound("Imoen2",30747,CRITICAL_MISS) // Next time...
    SetPlayerSound("Imoen2",30748,TARGET_IMMUNE) // Gotta try something else.
    SetPlayerSound("Imoen2",30749,INVENTORY_FULL) // Sorry, but I couldn't hold that last item. It's on the ground.
    SetPlayerSound("Imoen2",30750,PICKED_POCKET) // Easy as pie.
    SetPlayerSound("Imoen2",30751,EXISTANCE1) // Now you see me, now you don't.
    SetPlayerSound("Imoen2",30752,EXISTANCE2) // Ugh! The magic fizzled. 
    SetPlayerSound("Imoen2",30753,EXISTANCE3) // Shh! It's set and ready to go.
    SetPlayerSound("Imoen2",-1,EXISTANCE4) // No such index
    SetPlayerSound("Imoen2",10233,EXISTANCE5) // IMOEN chuckles when you ask her about her past, assuming you are just trying to keep her mind on happier times and places. She indulges you, and certainly does cheer up when speaking of how you spent your youths together in Candlekeep. She arrived there the same as you, in the company of your foster father Gorion, but despite this similarity, she grew up much more carefree than you did. Indeed, her lighthearted outlook has long kept her immune to the hardships of the world, though the dark confines and horrors of your current location have definitely taken their toll.
    SetGlobal("K#ImoenImport","AR0602",1)
    Continue()
END

IF
  Global("K#ImoenImport","AR0602",0)
  !BeenInParty("Imoen2")
  GlobalLT("chapter","GLOBAL",20)
  //!StateCheck("Imoen2",STATE_REALLY_DEAD)
THEN
  RESPONSE #100
    CreateCreature("Imoen10",[3198.2837],S) // Imoen
    ActionOverride("Imoen2",MakeGlobalOverride())
    SetGlobal("K#ImoenImport","AR0602",1)
    Continue()
END

IF
  Global("K#JaheiraImport","AR0602",0)
  BeenInParty("Jaheira")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Jaheira",STATE_REALLY_DEAD)
THEN
  RESPONSE #100
    ActionOverride("Jaheira",SetDialog("Jaheira")
    ActionOverride("Jaheira",ChangeAIScript("SHOUT",CLASS))
    ActionOverride("Jaheira",ChangeAIScript("NPCDRU1",RACE))
    ActionOverride("Jaheira",ChangeAIScript("",GENERAL))
    ActionOverride("Jaheira",ChangeAIScript("WTARSGT",DEFAULT))
    ActionOverride("Jaheira",ChangeAIScript("JAHEIRA",OVERRIDE))
    MoveGlobal("AR0602","Jaheira",[3898.2676])
    ActionOverride("Jaheira",Face(S))
    ActionOverride("Jaheira",SetGlobal("BD_JOINXP","LOCALS",0))
    ActionOverride("Jaheira",SetGlobal("KickedOut","LOCALS",0))
    ActionOverride("Jaheira",SetNumTimesTalkedTo(0))
    //ActionOverride("Jaheira",DestroyAllEquipment())
    //ReallyForceSpellRES("K#PORJAH","Jaheira") // No such index
    SetPlayerSound("Jaheira",-1,INITIAL_MEETING) // No such index
    SetPlayerSound("Jaheira",4008,MORALE) // I will not fall here!
    SetPlayerSound("Jaheira",4010,HAPPY) // Our actions are good, and will serve the greater balance.
    SetPlayerSound("Jaheira",4011,UNHAPPY_ANNOYED) // I hope this is not a sign of things to come. We must strive to maintain balance.
    SetPlayerSound("Jaheira",4012,UNHAPPY_SERIOUS) // This is no longer a matter that can be brushed aside! Change your ways or we shall be at odds!
    SetPlayerSound("Jaheira",4013,UNHAPPY_BREAKING_POINT) // I... I cannot believe the change in this group! For the greater balance, I... I must oppose you!
    SetPlayerSound("Jaheira",4014,LEADER) // As I have said before, you could not have made a better choice.
    SetPlayerSound("Jaheira",4015,TIRED) // Rest would be welcome lest we endanger ourselves.
    SetPlayerSound("Jaheira",4016,BORED) // It is strange that we stand about when there is so much to do.
    SetPlayerSound("Jaheira",4009,BATTLE_CRY1) // For the fallen!
    SetPlayerSound("Jaheira",30765,BATTLE_CRY2) // Fall, creature! And feed the earth!
    SetPlayerSound("Jaheira",30766,BATTLE_CRY3) // Nature take the life she gave!
    SetPlayerSound("Jaheira",-1,BATTLE_CRY4) // No such index
    SetPlayerSound("Jaheira",-1,BATTLE_CRY5) // No such index
    SetPlayerSound("Jaheira",-1,ATTACK1) // No such index
    SetPlayerSound("Jaheira",-1,ATTACK2) // No such index
    SetPlayerSound("Jaheira",-1,ATTACK3) // No such index
    SetPlayerSound("Jaheira",-1,ATTACK4) // No such index
    SetPlayerSound("Jaheira",5353,DAMAGE) // 
    SetPlayerSound("Jaheira",5354,DYING) // 
    SetPlayerSound("Jaheira",4017,HURT) // I will require healing if I am to be of use to the group.
    SetPlayerSound("Jaheira",4018,AREA_FOREST) // I am at peace in the outdoor places, though it never seems to last.
    SetPlayerSound("Jaheira",4019,AREA_CITY) // I have no patience for cities. Our stay had best be a short one.
    SetPlayerSound("Jaheira",4020,AREA_DUNGEON) // Nature could find a home here if it were properly cleansed and balanced.
    SetPlayerSound("Jaheira",5352,AREA_DAY) // I welcome each day we see. Some are not so lucky. 
    SetPlayerSound("Jaheira",4021,AREA_NIGHT) // Nature has many children that call the darkness home. I am not one of them. 
    SetPlayerSound("Jaheira",4022,SELECT_COMMON1) // Nature's servant awaits.
    SetPlayerSound("Jaheira",4023,SELECT_COMMON2) // I await your need.
    SetPlayerSound("Jaheira",54350,SELECT_COMMON3) // Yes?
    SetPlayerSound("Jaheira",4024,SELECT_COMMON4) // I am ready.
    SetPlayerSound("Jaheira",30767,SELECT_COMMON5) // It is about time.
    SetPlayerSound("Jaheira",30768,SELECT_COMMON6) // Speak your mind.
    SetPlayerSound("Jaheira",4025,SELECT_ACTION1) // It is done.
    SetPlayerSound("Jaheira",30769,SELECT_ACTION2) // I am willing.
    SetPlayerSound("Jaheira",4027,SELECT_ACTION3) // I go.
    SetPlayerSound("Jaheira",4028,SELECT_ACTION4) // As I would have done.
    SetPlayerSound("Jaheira",4029,SELECT_ACTION5) // If it will help.
    SetPlayerSound("Jaheira",4030,SELECT_ACTION6) // I thought as much.
    SetPlayerSound("Jaheira",4031,SELECT_ACTION7) // As you would have it.
    SetPlayerSound("Jaheira",-1,INTERACTION1) // No such index
    SetPlayerSound("Jaheira",-1,INTERACTION1) // No such index
    SetPlayerSound("Jaheira",-1,INTERACTION2) // No such index
    SetPlayerSound("Jaheira",-1,INTERACTION3) // No such index
    SetPlayerSound("Jaheira",-1,INTERACTION4) // No such index
    SetPlayerSound("Jaheira",-1,INTERACTION5) // No such index
    SetPlayerSound("Jaheira",-1,INSULT1) // No such index
    SetPlayerSound("Jaheira",-1,INSULT2) // No such index
    SetPlayerSound("Jaheira",-1,INSULT3) // No such index
    SetPlayerSound("Jaheira",-1,COMPLIMENT1) // No such index
    SetPlayerSound("Jaheira",-1,COMPLIMENT2) // No such index
    SetPlayerSound("Jaheira",-1,COMPLIMENT3) // No such index
    SetPlayerSound("Jaheira",-1,SPECIAL1) // No such index
    SetPlayerSound("Jaheira",-1,SPECIAL2) // No such index
    SetPlayerSound("Jaheira",-1,SPECIAL3) // No such index
    SetPlayerSound("Jaheira",-1,REACT_TO_DIE_GENERAL) // No such index
    SetPlayerSound("Jaheira",-1,REACT_TO_DIE_SPECIFIC) // No such index
    SetPlayerSound("Jaheira",-1,MISCELLANEOUS) // No such index
    SetPlayerSound("Jaheira",-1,RESPONSE_TO_COMPLIMENT2) // No such index
    SetPlayerSound("Jaheira",-1,RESPONSE_TO_COMPLIMENT3) // No such index
    SetPlayerSound("Jaheira",-1,RESPONSE_TO_INSULT1) // No such index
    SetPlayerSound("Jaheira",-1,RESPONSE_TO_INSULT2) // No such index
    SetPlayerSound("Jaheira",-1,RESPONSE_TO_INSULT3) // No such index
    SetPlayerSound("Jaheira",-1,DIALOG_HOSTILE) // No such index
    SetPlayerSound("Jaheira",-1,DIALOG_DEFAULT) // No such index
    SetPlayerSound("Jaheira",30770,SELECT_RARE1) // You require nothing more?
    SetPlayerSound("Jaheira",30771,SELECT_RARE2) // If you think it is wise to do so. So much comes back to haunt us.
    SetPlayerSound("Jaheira",30772,CRITICAL_HIT) // With vengeance!
    SetPlayerSound("Jaheira",30775,CRITICAL_MISS) // Ugh!
    SetPlayerSound("Jaheira",30776,TARGET_IMMUNE) // Weapon has no effect!
    SetPlayerSound("Jaheira",30777,INVENTORY_FULL) // I have too much in my pack as it is. You'll have to pick that up off the ground.
    SetPlayerSound("Jaheira",30778,PICKED_POCKET) // 
    SetPlayerSound("Jaheira",30779,EXISTANCE1) // 
    SetPlayerSound("Jaheira",30780,EXISTANCE2) // My concentration is undone. My spell has failed!
    SetPlayerSound("Jaheira",30781,EXISTANCE3) // 
    SetPlayerSound("Jaheira",-1,EXISTANCE4) // No such index
    SetPlayerSound("Jaheira",10199,EXISTANCE5) // When asked about her past, JAHEIRA glares as she speaks. She says that she was born in the Tethyr region to a loyalist of the King Alemander regime, unfortunately during the Tethyrian civil war. Her family was among the nobles targeted by the angry mobs of peasants, and she was only spared because a servant girl took her from their castle before it fell. An enclave of druids in the Forest of Tethir was willing to grant shelter, and Jaheira grew up headstrong in their care. She believes the only way to protect nature is to have an active role in the world, but the cost of this dedication seems to weigh heavily on her mind these days.  She grows quiet when you ask about recent events, and while she gives the appearance of her normal, strong-willed self, there is a look of doubt in her eyes. It would seem that she has seen too many friends fall to remain unaffected. She does not like the subject, and lets it drop.
    SetGlobal("K#JaheiraImport","AR0602",1)
    Continue()
END

/*IF
  Global("K#JaheiraImport","AR0602",0)
  BeenInParty("Jaheira")
  CheckStatLT("Jaheira",17,DEX)
THEN
  RESPONSE #100
    ChangeStat("Jaheira",DEX,17,SET)
    Continue()
END*/

IF
  Global("K#JaheiraImport","AR0602",0)
  !BeenInParty("Jaheira")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Jaheira",STATE_REALLY_DEAD)
  //LevelLT(Player1,8)
THEN
  RESPONSE #100
    CreateCreature("Jaheir7",[3898.2676],S) // Jaheira
    ActionOverride("Jaheira",MakeGlobalOverride())
    SetGlobal("K#JaheiraImport","AR0602",1)
    Continue()
END

/*IF
  Global("K#JaheiraImport","AR0602",0)
  !BeenInParty("Jaheira")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Jaheira",STATE_REALLY_DEAD)
  LevelGT(Player1,7)
  LevelLT(Player1,11)
THEN
  RESPONSE #100
    CreateCreature("Jaheir8",[3898.2676],S) // Jaheira
    ActionOverride("Jaheira",MakeGlobalOverride())
    SetGlobal("K#JaheiraImport","AR0602",1)
    Continue()
END

IF
  Global("K#JaheiraImport","AR0602",0)
  !BeenInParty("Jaheira")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Jaheira",STATE_REALLY_DEAD)
  Level(Player1,11)
THEN
  RESPONSE #100
    CreateCreature("Jaheir11",[3898.2676],S) // Jaheira
    ActionOverride("Jaheira",MakeGlobalOverride())
    SetGlobal("K#JaheiraImport","AR0602",1)
    Continue()
END

IF
  Global("K#JaheiraImport","AR0602",0)
  !BeenInParty("Jaheira")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Jaheira",STATE_REALLY_DEAD)
  LevelGT(Player1,11)
THEN
  RESPONSE #100
    CreateCreature("Jaheir12",[3898.2676],S) // Jaheira
    ActionOverride("Jaheira",MakeGlobalOverride())
    SetGlobal("K#JaheiraImport","AR0602",1)
    Continue()
END*/

IF
  Global("K#MinscImport","AR0602",0)
  BeenInParty("Minsc")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Minsc",STATE_REALLY_DEAD)
THEN
  RESPONSE #100
    ActionOverride("Minsc",SetDialog("MINSCA"))
    ActionOverride("Minsc",ChangeAIScript("",CLASS))
    ActionOverride("Minsc",ChangeAIScript("",RACE))
    ActionOverride("Minsc",ChangeAIScript("MINSCX",GENERAL))
    ActionOverride("Minsc",ChangeAIScript("DPLAYER",DEFAULT))
    ActionOverride("Minsc",ChangeAIScript("MINSC",OVERRIDE))
    MoveGlobal("AR0602","Minsc",[4029.2759])
    ActionOverride("Minsc",Face(S))
    ActionOverride("Minsc",SetGlobal("BD_JOINXP","LOCALS",0))
    ActionOverride("Minsc",SetGlobal("KickedOut","LOCALS",0))
    ActionOverride("Minsc",SetNumTimesTalkedTo(0))
    //ActionOverride("Minsc",DestroyAllEquipment())
    ChangeStat("MINSC",HATEDRACE,125,SET)
    ChangeAlignment("Minsc",CHAOTIC_GOOD)
    //ReallyForceSpellRES("K#PORMIN","Minsc") // No such index
    SetPlayerSound("Minsc",-1,INITIAL_MEETING) // No such index
    SetPlayerSound("Minsc",30788,MORALE) // Despair not! I will inspire you by charging blindly on!
    SetPlayerSound("Minsc",4087,HAPPY) // We are all heroes, you and Boo and I! Hamsters and rangers everywhere, rejoice!
    SetPlayerSound("Minsc",4088,UNHAPPY_ANNOYED) // This behavior must not continue! Feel the burning stare of my hamster and change your ways!
    SetPlayerSound("Minsc",4089,UNHAPPY_SERIOUS) // This is not right. Change our course or I will have to apply a considerable wallop of virtue!
    SetPlayerSound("Minsc",4090,UNHAPPY_BREAKING_POINT) // Boo can stand only so much!
    SetPlayerSound("Minsc",30790,LEADER) // Minsc will lead with blade and boot! Boo will take care of the details.
    SetPlayerSound("Minsc",4092,TIRED) // We must rest soon. Boo is getting squirrely.
    SetPlayerSound("Minsc",4093,BORED) // Boo must have his exercise lest he bite us all in hard-to-reach places.
    SetPlayerSound("Minsc",4086,BATTLE_CRY1) // Go for the eyes, Boo, GO FOR THE EYES! RrraaaAAGHGHH!
    SetPlayerSound("Minsc",30793,BATTLE_CRY2) // Feel the backhand of justice!
    SetPlayerSound("Minsc",30794,BATTLE_CRY3) // Great fun! Hehe. Right, Boo?
    SetPlayerSound("Minsc",-1,BATTLE_CRY4) // No such index
    SetPlayerSound("Minsc",-1,BATTLE_CRY5) // No such index
    SetPlayerSound("Minsc",-1,ATTACK1) // No such index
    SetPlayerSound("Minsc",-1,ATTACK2) // No such index
    SetPlayerSound("Minsc",-1,ATTACK3) // No such index
    SetPlayerSound("Minsc",-1,ATTACK4) // No such index
    SetPlayerSound("Minsc",5359,DAMAGE) // 
    SetPlayerSound("Minsc",5360,DYING) // 
    SetPlayerSound("Minsc",4094,HURT) // I must get aid soon. Boo is too young to have to avenge me.
    SetPlayerSound("Minsc",4095,AREA_FOREST) // You know... I think the forest likes Boo.
    SetPlayerSound("Minsc",5357,AREA_CITY) // Cities always teem with evil and decay. Let's give it a good shake and see what falls out!
    SetPlayerSound("Minsc",4096,AREA_DUNGEON) // A den of stinking evil. Cover your nose, Boo. We will leave no crevice untouched!
    SetPlayerSound("Minsc",5358,AREA_DAY) // Ahh, I prefer the bright of day. Evil must be able to see the justice I dispense!
    SetPlayerSound("Minsc",4097,AREA_NIGHT) // Strange things go bump in the night, but none bump bigger than Minsc!
    SetPlayerSound("Minsc",4098,SELECT_COMMON1) // You point, I punch.
    SetPlayerSound("Minsc",4099,SELECT_COMMON2) // Swords, not words!
    SetPlayerSound("Minsc",4100,SELECT_COMMON3) // Minsc and Boo stand ready.
    SetPlayerSound("Minsc",30796,SELECT_COMMON4) // Every hamster has his day.
    SetPlayerSound("Minsc",30798,SELECT_COMMON5) // Armored, sharpened, and raring to go.
    SetPlayerSound("Minsc",30799,SELECT_COMMON6) // Boo says, "What?!"
    SetPlayerSound("Minsc",4101,SELECT_ACTION1) // Where Minsc goes, evil stands aside.
    SetPlayerSound("Minsc",30800,SELECT_ACTION2) // Jump on my sword while you can, evil. I won't be as gentle!
    SetPlayerSound("Minsc",30801,SELECT_ACTION3) // Live by the sword, live a good long time!
    SetPlayerSound("Minsc",4104,SELECT_ACTION4) // Stand back for justice!
    SetPlayerSound("Minsc",30806,SELECT_ACTION5) // See battle, Boo? Run, Boo, Run!
    SetPlayerSound("Minsc",30807,SELECT_ACTION6) // Make way, villainy! Hero coming through!
    SetPlayerSound("Minsc",4107,SELECT_ACTION7) // Butt-kicking for goodness!
    SetPlayerSound("Minsc",-1,INTERACTION1) // No such index
    SetPlayerSound("Minsc",-1,INTERACTION1) // No such index
    SetPlayerSound("Minsc",-1,INTERACTION2) // No such index
    SetPlayerSound("Minsc",-1,INTERACTION3) // No such index
    SetPlayerSound("Minsc",-1,INTERACTION4) // No such index
    SetPlayerSound("Minsc",-1,INTERACTION5) // No such index
    SetPlayerSound("Minsc",-1,INSULT1) // No such index
    SetPlayerSound("Minsc",-1,INSULT2) // No such index
    SetPlayerSound("Minsc",-1,INSULT3) // No such index
    SetPlayerSound("Minsc",-1,COMPLIMENT1) // No such index
    SetPlayerSound("Minsc",-1,COMPLIMENT2) // No such index
    SetPlayerSound("Minsc",-1,COMPLIMENT3) // No such index
    SetPlayerSound("Minsc",-1,SPECIAL1) // No such index
    SetPlayerSound("Minsc",-1,SPECIAL2) // No such index
    SetPlayerSound("Minsc",-1,SPECIAL3) // No such index
    SetPlayerSound("Minsc",-1,REACT_TO_DIE_GENERAL) // No such index
    SetPlayerSound("Minsc",-1,REACT_TO_DIE_SPECIFIC) // No such index
    SetPlayerSound("Minsc",-1,MISCELLANEOUS) // No such index
    SetPlayerSound("Minsc",-1,RESPONSE_TO_COMPLIMENT2) // No such index
    SetPlayerSound("Minsc",-1,RESPONSE_TO_COMPLIMENT3) // No such index
    SetPlayerSound("Minsc",-1,RESPONSE_TO_INSULT1) // No such index
    SetPlayerSound("Minsc",-1,RESPONSE_TO_INSULT2) // No such index
    SetPlayerSound("Minsc",-1,RESPONSE_TO_INSULT3) // No such index
    SetPlayerSound("Minsc",-1,DIALOG_HOSTILE) // No such index
    SetPlayerSound("Minsc",-1,DIALOG_DEFAULT) // No such index
    SetPlayerSound("Minsc",30808,SELECT_RARE1) // The bigger they are, the harder I hit!
    SetPlayerSound("Minsc",30809,SELECT_RARE2) // Don't teach my hamster to suck eggs!
    SetPlayerSound("Minsc",30937,CRITICAL_HIT) // Ah hay!
    SetPlayerSound("Minsc",31850,CRITICAL_MISS) // Gah, that's not right!
    SetPlayerSound("Minsc",31901,TARGET_IMMUNE) // No effect? I need bigger sword!
    SetPlayerSound("Minsc",33805,INVENTORY_FULL) // I have had to drop what you gave me. I have only two arms and no more space.
    SetPlayerSound("Minsc",34379,PICKED_POCKET) // 
    SetPlayerSound("Minsc",34380,EXISTANCE1) // None shall see me... though my battle cry may give me away.
    SetPlayerSound("Minsc",34381,EXISTANCE2) // I turned to shield Boo and have lost my spell. I am NOT sorry.
    SetPlayerSound("Minsc",34744,EXISTANCE3) // 
    SetPlayerSound("Minsc",-1,EXISTANCE4) // No such index
    SetPlayerSound("Minsc",10185,EXISTANCE5) // When asked about his past, MINSC proclaims that he is a berserker warrior from the nation of Rashemen in the Utter East, though his affinity for animals speaks to his skill as a ranger as well. He originally came to the Sword Coast on a dajemma, a ritual journey to manhood, as the bodyguard of a young Wychlaran of Rashemen named Dynaheir. To his shame, Dynaheir is now dead, and he fears that the doors of the honored Ice Dragon Berserker Lodge are forever closed to him. This personal tragedy has obviously not strengthened Minsc's hold on reality, as evidenced by his continued dependence on his animal companion "Boo," a creature that he claims is a miniature giant space hamster. Apparently such things do exist somewhere in the Realms, but Minsc has surely taken too many blows to the head.
    SetGlobal("K#MinscImport","AR0602",1)
    Continue()
END

/*IF
  Global("K#MinscImport","AR0602",0)
  BeenInParty("Minsc")
  CheckStatLT("Minsc",16,DEX)
THEN
  RESPONSE #100
    ChangeStat("Minsc",DEX,16,SET)
    Continue()
END*/

IF
  Global("K#MinscImport","AR0602",0)
  !BeenInParty("Minsc")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Minsc",STATE_REALLY_DEAD)
  //LevelLT(Player1,8)
THEN
  RESPONSE #100
    CreateCreature("Minsc7",[4029.2759],S) // Minsc
    ActionOverride("Minsc",MakeGlobalOverride())
    SetGlobal("K#MinscImport","AR0602",1)
    Continue()
END

/*IF
  Global("K#MinscImport","AR0602",0)
  !BeenInParty("Minsc")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Minsc",STATE_REALLY_DEAD)
  Level(Player1,8)
THEN
  RESPONSE #100
    CreateCreature("Minsc8",[4029.2759],S) // Minsc
    ActionOverride("Minsc",MakeGlobalOverride())
    SetGlobal("K#MinscImport","AR0602",1)
    Continue()
END

IF
  Global("K#MinscImport","AR0602",0)
  !BeenInParty("Minsc")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Minsc",STATE_REALLY_DEAD)
  Level(Player1,9)
THEN
  RESPONSE #100
    CreateCreature("Minsc9",[4029.2759],S) // Minsc
    ActionOverride("Minsc",MakeGlobalOverride())
    SetGlobal("K#MinscImport","AR0602",1)
    Continue()
END

IF
  Global("K#MinscImport","AR0602",0)
  !BeenInParty("Minsc")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Minsc",STATE_REALLY_DEAD)
  OR(2)
    Level(Player1,10)
    Level(Player1,11)
THEN
  RESPONSE #100
    CreateCreature("Minsc10",[4029.2759],S) // Minsc
    ActionOverride("Minsc",MakeGlobalOverride())
    SetGlobal("K#MinscImport","AR0602",1)
    Continue()
END

IF
  Global("K#MinscImport","AR0602",0)
  !BeenInParty("Minsc")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Minsc",STATE_REALLY_DEAD)
  LevelGT(Player1,11)
THEN
  RESPONSE #100
    CreateCreature("Minsc12",[4029.2759],S) // Minsc
    ActionOverride("Minsc",MakeGlobalOverride())
    SetGlobal("K#MinscImport","AR0602",1)
    Continue()
END*/

IF
  Global("ENDOFBG1","GLOBAL",0)
  Global("K#NewGame","AR0602",0)
THEN
  RESPONSE #100
    SetGlobal("K#NewGame","AR0602",1)
    SetGlobal("DREAM","GLOBAL",7)
    SetGlobal("ENDOFBG1","GLOBAL",2)
    SetGlobal("NEWGAME_SOA","GLOBAL",1)
    //AdvanceTime(ONE_YEAR)
    ActionOverride(Player1,LeaveAreaLUAPanic("AR0602","",[3744.2801],S))
    ActionOverride(Player1,LeaveAreaLUA("AR0602","",[3744.2801],S))
    ActionOverride(Player2,LeaveAreaLUA("AR0602","",[3585.2917],SWW))
    ActionOverride(Player3,LeaveAreaLUA("AR0602","",[3532.2956],NW))
    ActionOverride(Player4,LeaveAreaLUA("AR0602","",[3374.3068],NNE))
    ActionOverride(Player5,LeaveAreaLUA("AR0602","",[3824.2447],E))
    ActionOverride(Player6,LeaveAreaLUA("AR0602","",[3889.2479],SSE))
    MultiPlayerSync()
    SmallWait(2)
    RemoveWorldmapAreaFlag("BG4800",ENABLED) //Reveal from linked area
    ReallyForceSpellRES("K#REMBHA",Player1)
    TakeItemListPartyNum("K#PLOT",99)
    Continue()
END

IF
  !Global("ENDOFBG1","GLOBAL",0)
  Global("K#NewGame","AR0602",0)
THEN
  RESPONSE #100
    SetGlobal("K#NewGame","AR0602",2)
    SetGlobal("ENDOFBG1","GLOBAL",2)
    ActionOverride(Player1,MakeUnselectable(1))
    ActionOverride(Player2,MakeUnselectable(1))
    ActionOverride(Player3,MakeUnselectable(1))
    ActionOverride(Player4,MakeUnselectable(1))
    ActionOverride(Player5,MakeUnselectable(1))
    ActionOverride(Player6,MakeUnselectable(1))
    //ActionOverride(Player1,SetPlayerSound(Myself,15881,EXISTANCE5))
    RemoveWorldmapAreaFlag("BD0010",15) //Visible, Reveal from linked area, Can be visited, Has been visited
    AddWorldmapAreaFlag("AR0020",ENABLED) //Reveal from linked area
    ApplySpellRES("K#FATIGP",Player1)
    ReallyForceSpellRES("K#FAMREM",Player1)
    ReallyForceSpellRES("K#FAMREM",Player2)
    ReallyForceSpellRES("K#FAMREM",Player3)
    ReallyForceSpellRES("K#FAMREM",Player4)
    ReallyForceSpellRES("K#FAMREM",Player5)
    ReallyForceSpellRES("K#FAMREM",Player6)
    Continue()
END

IF
  Global("NEWGAME_SOA","GLOBAL",1)
  Global("K#NewGame","AR0602",1)
  Global("MoveScreen","AR0602",1)
  ReputationGT(Player1,9)
THEN
  RESPONSE #100
    SetGlobal("K#NewGame","AR0602",2)
    ActionOverride(Player1,AddSpecialAbility("SPIN101")) // Cure Light Wounds
    ActionOverride(Player1,AddSpecialAbility("SPIN102")) // Slow Poison
    ActionOverride(Player1,AddSpecialAbility("SPIN102")) // Slow Poison
    ActionOverride(Player1,AddSpecialAbility("SPIN103")) // Draw Upon Holy Might
    ActionOverride(Player1,AddSpecialAbility("SPIN103")) // Draw Upon Holy Might
    ActionOverride(Player1,AddSpecialAbility("SPIN101")) // Cure Light Wounds
    Continue()
END

IF
  Global("NEWGAME_SOA","GLOBAL",1)
  Global("K#NewGame","AR0602",1)
  Global("MoveScreen","AR0602",1)
  ReputationLT(Player1,10)
THEN
  RESPONSE #100
    SetGlobal("K#NewGame","AR0602",2)
    ActionOverride(Player1,AddSpecialAbility("SPIN104")) // Larloch's Minor Drain
    ActionOverride(Player1,AddSpecialAbility("SPIN105")) // Horror
    ActionOverride(Player1,AddSpecialAbility("SPIN105")) // Horror
    ActionOverride(Player1,AddSpecialAbility("SPIN106")) // Vampiric Touch
    ActionOverride(Player1,AddSpecialAbility("SPIN106")) // Vampiric Touch
    ActionOverride(Player1,AddSpecialAbility("SPIN104")) // Larloch's Minor Drain
    Continue()
END

IF
  Global("K#StoryMode","AR0602",0)
  StoryModeOn()
  Global("OHSMODE","GLOBAL",-1)
  Global("MoveScreen","AR0602",1)
THEN
  RESPONSE #100
    SetGlobal("K#StoryMode","AR0602",1)
    SetGlobal("OHSMODE","GLOBAL",1)
    ReallyForceSpellDeadRES("OHSMODE1",Player1)
    Continue()
END
>>>>>>>>

EXTEND_TOP ~AR0602.BCS~ ~.../AR0602-et.baf~

COPY_EXISTING ~AR0602.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~TakePartyGold(2147483647)[%newline%]*ActionOverride(Player1,DestroyAllEquipment())[%newline%]*ActionOverride(Player2,DestroyAllEquipment())[%newline%]*ActionOverride(Player3,DestroyAllEquipment())[%newline%]*ActionOverride(Player4,DestroyAllEquipment())[%newline%]*ActionOverride(Player5,DestroyAllEquipment())[%newline%]*ActionOverride(Player6,DestroyAllEquipment())~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~TakeObjectGoldGlobal("K#ImportGold","GLOBAL",Player1)
    ActionOverride("K#ImportContainer",TakeCreatureItems(Player1,ALL))
    ActionOverride("K#ImportContainer",TakeCreatureItems(Player2,ALL))
    ActionOverride("K#ImportContainer",TakeCreatureItems(Player3,ALL))
    ActionOverride("K#ImportContainer",TakeCreatureItems(Player4,ALL))
    ActionOverride("K#ImportContainer",TakeCreatureItems(Player5,ALL))
    ActionOverride("K#ImportContainer",TakeCreatureItems(Player6,ALL))
    MoveContainerContents("BD6100*K#ImportContainer","AR0602*K#ImportContainer")~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
		SPRINT textToReplace ~ActionOverride("Picture1",CreateItem("MISC47",0,0,0))~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~ActionOverride("Picture1",TakePartyItem("MISC47")~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

/////                                                  \\\\\
///// AR0607                                           \\\\\
/////                                                  \\\\\

COPY_EXISTING ~AR0607.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~ActionOverride("Aerie",SetBeenInPartyFlags())~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

/////                                                  \\\\\
///// AR1000 (Viconia spawn)                           \\\\\
/////                                                  \\\\\

<<<<<<<< .../AR1000-et.baf
IF
  Global("K#ViconiaImport","AR1000",0)
  BeenInParty("Viconia")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Viconia",STATE_REALLY_DEAD)
THEN
  RESPONSE #100
    ActionOverride("Viconia",SetDialog("VICONI"))
    ActionOverride("Viconia",ChangeAIScript("INITRG10",CLASS))
    ActionOverride("Viconia",ChangeAIScript("VICX",RACE))
    ActionOverride("Viconia",ChangeAIScript("WTASIGHT",GENERAL))
    ActionOverride("Viconia",ChangeAIScript("DPLAYER",DEFAULT))
    ActionOverride("Viconia",ChangeAIScript("VICONIA",OVERRIDE))
    MoveGlobal("AR1000","Viconia",[1821.1081])
    ActionOverride("Viconia",Face(S))
    ActionOverride("Viconia",SetGlobal("BD_JOINXP","LOCALS",0))
    ActionOverride("Viconia",SetGlobal("KickedOut","LOCALS",0))
    ActionOverride("Viconia",SetNumTimesTalkedTo(0))
    ActionOverride("Viconia",DestroyAllEquipment())
    //ReallyForceSpellRES("K#PORVIC","Viconia") // No such index
    SetPlayerSound("Viconia",-1,INITIAL_MEETING) // No such index
    SetPlayerSound("Viconia",3613,MORALE) // We must flee to fight another day!
    SetPlayerSound("Viconia",3615,HAPPY) // I find this a most satisfactory arrangement.
    SetPlayerSound("Viconia",3616,UNHAPPY_ANNOYED) // Surface-dwellers can be so stupid.
    SetPlayerSound("Viconia",3617,UNHAPPY_SERIOUS) // I am beginning to tire of spending my time with fools.
    SetPlayerSound("Viconia",3618,UNHAPPY_BREAKING_POINT) // I have no desire to remain in the company of the witless.
    SetPlayerSound("Viconia",3619,LEADER) // I see you have learned much in your short lifespan.
    SetPlayerSound("Viconia",3620,TIRED) // How long do you intend to crack your whip on my back?! I say we stop now.
    SetPlayerSound("Viconia",3621,BORED) // The drow are never this idle with their time.
    SetPlayerSound("Viconia",3614,BATTLE_CRY1) // Lil alurl! For Shar!
    SetPlayerSound("Viconia",29812,BATTLE_CRY2) // No mercy for those who oppose us!
    SetPlayerSound("Viconia",29813,BATTLE_CRY3) // Ultrinnan!
    SetPlayerSound("Viconia",-1,BATTLE_CRY4) // No such index
    SetPlayerSound("Viconia",-1,BATTLE_CRY5) // No such index
    SetPlayerSound("Viconia",-1,ATTACK1) // No such index
    SetPlayerSound("Viconia",-1,ATTACK2) // No such index
    SetPlayerSound("Viconia",-1,ATTACK3) // No such index
    SetPlayerSound("Viconia",-1,ATTACK4) // No such index
    SetPlayerSound("Viconia",29814,DAMAGE) // 
    SetPlayerSound("Viconia",5285,DYING) // 
    SetPlayerSound("Viconia",3622,HURT) // No... it cannot end like this... I shall not allow it!
    SetPlayerSound("Viconia",3623,AREA_FOREST) // I am still unused to all this green and fragrant brightness... part of me yet looks for the hidden spider's web amongst all this.
    SetPlayerSound("Viconia",5281,AREA_CITY) // The stink of the collected rivvin... how I despise them all. 
    SetPlayerSound("Viconia",5283,AREA_DUNGEON) // I swim in memories in such a place as this... most unpleasant memories.
    SetPlayerSound("Viconia",3624,AREA_DAY) // Ahhh, this light... still it burns me!
    SetPlayerSound("Viconia",3625,AREA_NIGHT) // There is no roof to this world. I feel as if I shall fall into this sky of yours sometimes.
    SetPlayerSound("Viconia",3626,SELECT_COMMON1) // Jal Khaless?
    SetPlayerSound("Viconia",3627,SELECT_COMMON2) // Yes, abbil?
    SetPlayerSound("Viconia",3628,SELECT_COMMON3) // Usstan zhah dosst.
    SetPlayerSound("Viconia",30517,SELECT_COMMON4) // I am yours to command.
    SetPlayerSound("Viconia",30520,SELECT_COMMON5) // Shar guides my hand.
    SetPlayerSound("Viconia",30524,SELECT_COMMON6) // Victory shall be ours! You know this.
    SetPlayerSound("Viconia",3630,SELECT_ACTION1) // Trust is for the foolish... and the dead.
    SetPlayerSound("Viconia",3631,SELECT_ACTION2) // I shall follow your strength.
    SetPlayerSound("Viconia",3632,SELECT_ACTION3) // Destiny awaits!
    SetPlayerSound("Viconia",3633,SELECT_ACTION4) // Nau natha.
    SetPlayerSound("Viconia",3634,SELECT_ACTION5) // A'dos quarth!
    SetPlayerSound("Viconia",3635,SELECT_ACTION6) // As you desire.
    SetPlayerSound("Viconia",3636,SELECT_ACTION7) // If that is your will.
    SetPlayerSound("Viconia",-1,INTERACTION1) // No such index
    SetPlayerSound("Viconia",-1,INTERACTION1) // No such index
    SetPlayerSound("Viconia",-1,INTERACTION2) // No such index
    SetPlayerSound("Viconia",-1,INTERACTION3) // No such index
    SetPlayerSound("Viconia",-1,INTERACTION4) // No such index
    SetPlayerSound("Viconia",-1,INTERACTION5) // No such index
    SetPlayerSound("Viconia",-1,INSULT1) // No such index
    SetPlayerSound("Viconia",-1,INSULT2) // No such index
    SetPlayerSound("Viconia",-1,INSULT3) // No such index
    SetPlayerSound("Viconia",-1,COMPLIMENT1) // No such index
    SetPlayerSound("Viconia",-1,COMPLIMENT2) // No such index
    SetPlayerSound("Viconia",-1,COMPLIMENT3) // No such index
    SetPlayerSound("Viconia",-1,SPECIAL1) // No such index
    SetPlayerSound("Viconia",-1,SPECIAL2) // No such index
    SetPlayerSound("Viconia",-1,SPECIAL3) // No such index
    SetPlayerSound("Viconia",-1,REACT_TO_DIE_GENERAL) // No such index
    SetPlayerSound("Viconia",-1,REACT_TO_DIE_SPECIFIC) // No such index
    SetPlayerSound("Viconia",-1,MISCELLANEOUS) // No such index
    SetPlayerSound("Viconia",-1,RESPONSE_TO_COMPLIMENT2) // No such index
    SetPlayerSound("Viconia",-1,RESPONSE_TO_COMPLIMENT3) // No such index
    SetPlayerSound("Viconia",-1,RESPONSE_TO_INSULT1) // No such index
    SetPlayerSound("Viconia",-1,RESPONSE_TO_INSULT2) // No such index
    SetPlayerSound("Viconia",-1,RESPONSE_TO_INSULT3) // No such index
    SetPlayerSound("Viconia",-1,DIALOG_HOSTILE) // No such index
    SetPlayerSound("Viconia",-1,DIALOG_DEFAULT) // No such index
    SetPlayerSound("Viconia",30526,SELECT_RARE1) // Folt xund!
    SetPlayerSound("Viconia",30527,SELECT_RARE2) // I serve Shar above all others, but I shall remain with you... for now.
    SetPlayerSound("Viconia",30528,CRITICAL_HIT) // Vith'os!
    SetPlayerSound("Viconia",30529,CRITICAL_MISS) // Vith'ir!
    SetPlayerSound("Viconia",30534,TARGET_IMMUNE) // My weapon is faulty!
    SetPlayerSound("Viconia",30535,INVENTORY_FULL) // I will carry no more. You may scrounge for what I have dropped upon the ground.
    SetPlayerSound("Viconia",30536,PICKED_POCKET) // 
    SetPlayerSound("Viconia",30537,EXISTANCE1) // 
    SetPlayerSound("Viconia",30538,EXISTANCE2) // My thoughts are disrupted. My magic is lost!
    SetPlayerSound("Viconia",30539,EXISTANCE3) // 
    SetPlayerSound("Viconia",-1,EXISTANCE4) // No such index
    SetPlayerSound("Viconia",10217,EXISTANCE5) // When you ask about her recent past, VICONIA snarls that it is not your place to know such things of her. There is still pride in her voice when she speaks about her Underdark home of Menzoberranzan, but you get the feeling that there is nothing left for her there, her family and House most likely victims of typically vicious drow "politics." She has continued in her worship of the night goddess Shar, but that appears to have been the only boon to her exile. She seems sullen and bitter, and has certainly learned much of the intolerance she must face while living amongst surface peoples. Her natural abilities as a drow have faded with time, also contributing to her lost sense of belonging. 
    SetGlobal("K#ViconiaImport","AR1000",1)
    Continue()
END

/*IF
  Global("K#ViconiaImport","AR1000",0)
  BeenInParty("Viconia")
  CheckStatLT("Viconia",18,WIS)
THEN
  RESPONSE #100
    ChangeStat("Viconia",WIS,18,SET)
    Continue()
END

IF
  Global("K#ViconiaImport","AR1000",0)
  BeenInParty("Viconia")
  CheckStatLT("Viconia",65,RESISTMAGIC)
THEN
  RESPONSE #100
    ChangeStat("Viconia",RESISTMAGIC,65,SET)
    Continue()
END*/

IF
  Global("K#ViconiaImport","AR1000",0)
  !BeenInParty("Viconia")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Viconia",STATE_REALLY_DEAD)
  //LevelLT(Player1,8)
THEN
  RESPONSE #100
    CreateCreatureImpassable("VICONI6",[1821.1081],S)
    ActionOverride("Viconia",MakeGlobalOverride())
    SetGlobal("K#ViconiaImport","AR1000",1)
    Continue()
END

/*IF
  Global("K#ViconiaImport","AR1000",0)
  !BeenInParty("Viconia")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Viconia",STATE_REALLY_DEAD)
  Level(Player1,8)
THEN
  RESPONSE #100
    CreateCreatureImpassable("VICONI8",[1821.1081],S)
    ActionOverride("Viconia",MakeGlobalOverride())
    SetGlobal("K#ViconiaImport","AR1000",1)
    Continue()
END

IF
  Global("K#ViconiaImport","AR1000",0)
  !BeenInParty("Viconia")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Viconia",STATE_REALLY_DEAD)
  OR(2)
    Level(Player1,9)
    Level(Player1,10)
THEN
  RESPONSE #100
    CreateCreatureImpassable("VICONI9",[1821.1081],S)
    ActionOverride("Viconia",MakeGlobalOverride())
    SetGlobal("K#ViconiaImport","AR1000",1)
    Continue()
END

IF
  Global("K#ViconiaImport","AR1000",0)
  !BeenInParty("Viconia")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Viconia",STATE_REALLY_DEAD)
  OR(2)
    Level(Player1,11)
    Level(Player1,12)
THEN
  RESPONSE #100
    CreateCreatureImpassable("VICONI11",[1821.1081],S)
    ActionOverride("Viconia",MakeGlobalOverride())
    SetGlobal("K#ViconiaImport","AR1000",1)
    Continue()
END

IF
  Global("K#ViconiaImport","AR1000",0)
  !BeenInParty("Viconia")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Viconia",STATE_REALLY_DEAD)
  LevelGT(Player1,12)
THEN
  RESPONSE #100
    CreateCreatureImpassable("VICONI13",[1821.1081],S)
    ActionOverride("Viconia",MakeGlobalOverride())
    SetGlobal("K#ViconiaImport","AR1000",1)
    Continue()
END*/

IF
  Global("K#ViconiaSpawn","AR1000",0)
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Viconia",STATE_REALLY_DEAD)
THEN
  RESPONSE #100
    SetGlobal("K#ViconiaSpawn","AR1000",1)
    CreateCreature("VICG1",[1885.1032],0)
    CreateCreature("VICG2",[1738.1154],10)
    CreateCreature("VICTOWN1",[1955.1148],6)
    CreateCreature("VICTOWN2",[1918.1172],6)
    CreateCreature("VICTOWN3",[1817.1197],8)
    CreateCreature("VICTOWN4",[1874.1187],6)
    CreateCreature("VICG3",[1526.1164],12)
    Continue()
END
>>>>>>>>

EXTEND_TOP ~AR1000.BCS~ ~.../AR1000-et.baf~

/////                                                  \\\\\
///// AR0900 (Dorn spawn)                              \\\\\
/////                                                  \\\\\

<<<<<<<< .../AR0900-rbOld.baf
IF
  HasDLC("dorn")
  GlobalLT("OHD_PLOT","GLOBAL",1)
  !Global("OHH_DORN_INIT","ar0900",1)
  XPLT(Player1,280501)
THEN
  RESPONSE #100
    ActionOverride("dorn",DestroySelf())
    CreateCreature("DORN8",[2550.3394],E) // Dorn
    SetGlobal("OHH_DORN_INIT","ar0900",1)
END

IF
  HasDLC("dorn")
  GlobalLT("OHD_PLOT","GLOBAL",1)
  !Global("OHH_DORN_INIT","ar0900",2)
  XPGT(Player1,280500)
  XPLT(Player1,600001)
THEN
  RESPONSE #100
    ActionOverride("dorn",DestroySelf())
    CreateCreature("DORN9",[2550.3394],E) // Dorn
    SetGlobal("OHH_DORN_INIT","ar0900",2)
END

IF
  HasDLC("dorn")
  GlobalLT("OHD_PLOT","GLOBAL",1)
  !Global("OHH_DORN_INIT","ar0900",3)
  XPGT(Player1,600000)
  XPLT(Player1,1000001)
THEN
  RESPONSE #100
    ActionOverride("dorn",DestroySelf())
    CreateCreature("DORN10",[2550.3394],E) // Dorn
    SetGlobal("OHH_DORN_INIT","ar0900",3)
END

IF
  HasDLC("dorn")
  GlobalLT("OHD_PLOT","GLOBAL",1)
  !Global("OHH_DORN_INIT","ar0900",4)
  XPGT(Player1,1000000)
THEN
  RESPONSE #100
    ActionOverride("dorn",DestroySelf())
    CreateCreature("DORN12",[2550.3394],E) // Dorn
    SetGlobal("OHH_DORN_INIT","ar0900",4)
END
>>>>>>>>

<<<<<<<< .../AR0900-rbNew.baf
IF
  HasDLC("dorn")
  GlobalLT("OHD_PLOT","GLOBAL",1)
  Global("K#DornImport","AR0900",0)
  BeenInParty("Dorn")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Dorn",STATE_REALLY_DEAD)
THEN
  RESPONSE #100
    ActionOverride("Dorn",SetDialog("DORN"))
    ActionOverride("Dorn",ChangeAIScript("",CLASS))
    ActionOverride("Dorn",ChangeAIScript("",RACE))
    ActionOverride("Dorn",ChangeAIScript("",GENERAL))
    ActionOverride("Dorn",ChangeAIScript("",DEFAULT))
    ActionOverride("Dorn",ChangeAIScript("DORN",OVERRIDE))
    MoveGlobal("AR0900","Dorn",[2550.3394])
    ActionOverride("Dorn",Face(E))
    ActionOverride("Dorn",SetGlobal("BD_JOINXP","LOCALS",0))
    ActionOverride("Dorn",SetGlobal("KickedOut","LOCALS",0))
    ActionOverride("Dorn",SetNumTimesTalkedTo(0))
    ActionOverride("Dorn",DestroyAllEquipment())
    ActionOverride("Dorn",CreateItem("HELM01",1,0,0)) // Helmet
    ActionOverride("Dorn",CreateItem("PLAT01",1,0,0)) // Plate Mail
    ActionOverride("Dorn",CreateItem("SW2HD1",1,0,0)) // Rancor +1
    ActionOverride("Dorn",FillSlot(SLOT_HELMET))
    ActionOverride("Dorn",FillSlot(SLOT_ARMOR))
    ActionOverride("Dorn",FillSlot(SLOT_WEAPON))
    ActionOverride("Dorn",EquipMostDamagingMelee())
    //ReallyForceSpellRES("K#PORDOR","Dorn")
    SetPlayerSound("Dorn",-1,INITIAL_MEETING) // No such index
    SetPlayerSound("Dorn",-1,MORALE) // No such index
    SetPlayerSound("Dorn",93367,HAPPY) // I am pleased.
    SetPlayerSound("Dorn",93368,UNHAPPY_ANNOYED) // Most disagreeable.
    SetPlayerSound("Dorn",93369,UNHAPPY_SERIOUS) // Do not push me further.
    SetPlayerSound("Dorn",93370,UNHAPPY_BREAKING_POINT) // NO MORE!
    SetPlayerSound("Dorn",93329,LEADER) // You have made a wise decision. We will reach new and greater heights under my command.
    SetPlayerSound("Dorn",93330,TIRED) // I grow weary.
    SetPlayerSound("Dorn",93331,BORED) // There are hundreds, thousands, hundreds of thousands of people we could be slaying right now, and we do nothing!
    SetPlayerSound("Dorn",93326,BATTLE_CRY1) // I'll send you to the Abyss!
    SetPlayerSound("Dorn",93327,BATTLE_CRY2) // Death to all who stand against me!
    SetPlayerSound("Dorn",93328,BATTLE_CRY3) // Taste darkness, fool!
    SetPlayerSound("Dorn",-1,BATTLE_CRY4) // No such index
    SetPlayerSound("Dorn",-1,BATTLE_CRY5) // No such index
    SetPlayerSound("Dorn",-1,ATTACK1) // No such index
    SetPlayerSound("Dorn",-1,ATTACK2) // No such index
    SetPlayerSound("Dorn",-1,ATTACK3) // No such index
    SetPlayerSound("Dorn",-1,ATTACK4) // No such index
    SetPlayerSound("Dorn",93347,DAMAGE) // Ah! Ah...
    SetPlayerSound("Dorn",93348,DYING) // Augh! Go ahead then, you gods of death! Take me!
    SetPlayerSound("Dorn",93332,HURT) // It'll take more than a scratch to stop Dorn Il-Khan!
    SetPlayerSound("Dorn",93349,AREA_FOREST) // So peaceful and serene it seems. It is a lie. The leaves and branches hide a savagery we sapients can only aspire to.
    SetPlayerSound("Dorn",93350,AREA_CITY) // The city is no different from the forest—men, dwarves, elves, orcs... we are all beasts. Some just have stronger leashes than others.
    SetPlayerSound("Dorn",93351,AREA_DUNGEON) // Anything that gets in our way will be buried in this place's rubble.
    SetPlayerSound("Dorn",93352,AREA_DAY) // Each day I live is another day I stole from the gods.
    SetPlayerSound("Dorn",93353,AREA_NIGHT) // Glory awaits in darkness.
    SetPlayerSound("Dorn",93357,SELECT_COMMON1) // What would you have me do?
    SetPlayerSound("Dorn",102634,SELECT_COMMON2) // I will listen... for now.
    SetPlayerSound("Dorn",93343,SELECT_COMMON3) // Mind your tone.
    SetPlayerSound("Dorn",93336,SELECT_COMMON4) // You have a problem?
    SetPlayerSound("Dorn",93355,SELECT_COMMON5) // You are going somewhere you do not want to be.
    SetPlayerSound("Dorn",93334,SELECT_COMMON6) // Hrm. Yes.
    SetPlayerSound("Dorn",93340,SELECT_ACTION1) // Very well.
    SetPlayerSound("Dorn",93341,SELECT_ACTION2) // I look forward to it.
    SetPlayerSound("Dorn",93342,SELECT_ACTION3) // I will enjoy this.
    SetPlayerSound("Dorn",93335,SELECT_ACTION4) // I will take care of this.
    SetPlayerSound("Dorn",93344,SELECT_ACTION5) // It will be done.
    SetPlayerSound("Dorn",93345,SELECT_ACTION6) // Easily.
    SetPlayerSound("Dorn",93346,SELECT_ACTION7) // A waste of my talents, but so be it.
    SetPlayerSound("Dorn",-1,INTERACTION1) // No such index
    SetPlayerSound("Dorn",-1,INTERACTION1) // No such index
    SetPlayerSound("Dorn",-1,INTERACTION2) // No such index
    SetPlayerSound("Dorn",-1,INTERACTION3) // No such index
    SetPlayerSound("Dorn",-1,INTERACTION4) // No such index
    SetPlayerSound("Dorn",-1,INTERACTION5) // No such index
    SetPlayerSound("Dorn",-1,INSULT1) // No such index
    SetPlayerSound("Dorn",-1,INSULT2) // No such index
    SetPlayerSound("Dorn",-1,INSULT3) // No such index
    SetPlayerSound("Dorn",-1,COMPLIMENT1) // No such index
    SetPlayerSound("Dorn",-1,COMPLIMENT2) // No such index
    SetPlayerSound("Dorn",-1,COMPLIMENT3) // No such index
    SetPlayerSound("Dorn",-1,SPECIAL1) // No such index
    SetPlayerSound("Dorn",-1,SPECIAL2) // No such index
    SetPlayerSound("Dorn",-1,SPECIAL3) // No such index
    SetPlayerSound("Dorn",93354,REACT_TO_DIE_GENERAL) // I've no use for the weak. We are better off.
    SetPlayerSound("Dorn",-1,REACT_TO_DIE_SPECIFIC) // No such index
    SetPlayerSound("Dorn",-1,MISCELLANEOUS) // No such index
    SetPlayerSound("Dorn",-1,RESPONSE_TO_COMPLIMENT2) // No such index
    SetPlayerSound("Dorn",-1,RESPONSE_TO_COMPLIMENT3) // No such index
    SetPlayerSound("Dorn",-1,RESPONSE_TO_INSULT1) // No such index
    SetPlayerSound("Dorn",-1,RESPONSE_TO_INSULT2) // No such index
    SetPlayerSound("Dorn",-1,RESPONSE_TO_INSULT3) // No such index
    SetPlayerSound("Dorn",-1,DIALOG_HOSTILE) // No such index
    SetPlayerSound("Dorn",-1,DIALOG_DEFAULT) // No such index
    SetPlayerSound("Dorn",93337,SELECT_RARE1) // Kill them all and have done with it.
    SetPlayerSound("Dorn",93356,SELECT_RARE2) // I am Dorn Il-Khan. I do as I will. You do not give me orders.
    SetPlayerSound("Dorn",93358,CRITICAL_HIT) // Hah! I'll rip you apart, you wheyfaced cur!
    SetPlayerSound("Dorn",93359,CRITICAL_MISS) // You were lucky then. But luck runs out.
    SetPlayerSound("Dorn",93360,TARGET_IMMUNE) // Curse it!
    SetPlayerSound("Dorn",93361,INVENTORY_FULL) // I am not some beast of burden. I'll carry no more of your trinkets.
    SetPlayerSound("Dorn",93362,PICKED_POCKET) // Who says Dorn Il-Khan is incapable of subtlety?
    SetPlayerSound("Dorn",93364,EXISTANCE1) // A blind enemy is a beaten one.
    SetPlayerSound("Dorn",93365,EXISTANCE2) // Curse the luck! My spell was fouled!
    SetPlayerSound("Dorn",93366,EXISTANCE3) // I will leave our enemies a gift.
    SetPlayerSound("Dorn",-1,EXISTANCE4) // No such index
    SetPlayerSound("Dorn",91841,EXISTANCE5) // The half-orc blackguard is a man more comfortable with action than words. When pressed, he gruffly alludes to an act of betrayal that set him upon a bloody path of vengeance with the assistance of his patron, Ur-Gothoz. Since eliminating those who betrayed him, he has continued to spread chaos, death, and destruction at his dark patron's behest. While Dorn seems to revel in carnage and bloodshed, when he speaks of his work for Ur-Gothoz, you believe you detect a note of dissatisfaction in his voice.
    SetGlobal("K#DornImport","AR0900",1)
    SetGlobal("OHH_DORN_INIT","ar0900",1)
    //Continue()
END

IF
  HasDLC("dorn")
  Global("K#DornImport","AR0900",0)
  !BeenInParty("Dorn")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Dorn",STATE_REALLY_DEAD)
  GlobalLT("OHD_PLOT","GLOBAL",1)
  !Global("OHH_DORN_INIT","ar0900",1)
  //XPLT(Player1,280501)
THEN
  RESPONSE #100
    CreateCreature("DORN8",[2550.3394],E) // Dorn
    ActionOverride("Dorn",MakeGlobalOverride())
    SetGlobal("OHH_DORN_INIT","ar0900",1)
END
>>>>>>>>

COPY_EXISTING ~AR0900.BCS~ ~override~
	REPLACE_BCS_BLOCK ~.../AR0900-rbOld.baf~ ~.../AR0900-rbNew.baf~ ON_MISMATCH PATCH_WARN ~WARNING: could not find REPLACE_BCS_BLOCK matching .../AR0900-rbOld.baf in %SOURCE_FILE%~ END
BUT_ONLY

/////                                                  \\\\\
///// AR1512 (Spellhold Imoen spawn)                   \\\\\
/////                                                  \\\\\

<<<<<<<< .../AR1512-et.baf
IF
  Global("K#ImoenImport","AR1512",0)
  GlobalLT("chapter","GLOBAL",20)
  //!StateCheck("Imoen2",STATE_REALLY_DEAD)
THEN
  RESPONSE #100
    ActionOverride("Imoen2",SetDialog("IMOEN2"))
    ActionOverride("Imoen2",ChangeAIScript("IMOEN2",OVERRIDE))
    MoveGlobal("AR1512","Imoen2",[1857.1520])
    ActionOverride("Imoen2",Face(SW))
    ActionOverride("Imoen2",SetGlobal("BD_JOINXP","LOCALS",0))
    ActionOverride("Imoen2",SetGlobal("KickedOut","LOCALS",0))
    ActionOverride("Imoen2",SetNumTimesTalkedTo(0))
    ActionOverride("Imoen2",DestroyItem("IMOENHP1")) // Imoen's Belt
    SetPlayerSound("Imoen2",30759,MORALE) // I got enough trouble without fightin' these odds!
    SetPlayerSound("Imoen2",30760,BORED) // I'm withering away just standing here. Let's get going.
    SetPlayerSound("Imoen2",30761,BATTLE_CRY2) // You asked for it!
    SetPlayerSound("Imoen2",30762,BATTLE_CRY3) // Oh, I'll show you a fight!
    SetPlayerSound("Imoen2",30764,HURT) // I'm weak enough without my wounds. Someone give me a hand over here, please?
    SetPlayerSound("Imoen2",74276,EXISTANCE5) // IMOEN chuckles when you ask her about her past, assuming you are just trying to keep her mind on happier times and places. She indulges you, and certainly does cheer up when speaking of how you spent your youths together in Candlekeep. She arrived there the same as you, in the company of your foster father Gorion, but despite this similarity, she grew up much more carefree than you did. Indeed, her lighthearted outlook has long kept her immune to the hardships of the world, though the horrors she has endured have definitely taken their toll.
    SetGlobal("K#ImoenImport","AR1512",1)
    Continue()
END
>>>>>>>>

EXTEND_TOP ~AR1512.BCS~ ~.../AR1512-et.baf~

/////                                                  \\\\\
///// AR2000, OHR_JOIN (Rasaad spawn)                  \\\\\
/////                                                  \\\\\

<<<<<<<< .../AR2000-rbOld.baf
IF
  HasDLC("Rasaad")
  Global("OHR_SPAWN","AR2000",0)
THEN
  RESPONSE #100
    SetGlobal("OHR_SPAWN","AR2000",1)
    CreateCreature("RASAAD8",[1550.1368],S) // Rasaad
    CreateCreature("OHRTREYA",[1600.1435],NNW) // Treya
    CreateCreature("OHRSSM01",[1486.1435],NE) // Sun Soul Monk
END
>>>>>>>>

<<<<<<<< .../AR2000-rbNew.baf
IF
  HasDLC("Rasaad")
  Global("K#RasaadImport","AR2000",0)
  BeenInParty("Rasaad")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Rasaad",STATE_REALLY_DEAD)
THEN
  RESPONSE #100
    ActionOverride("Rasaad",SetDialog("RASAAD"))
    ActionOverride("Rasaad",ChangeAIScript("",CLASS))
    ActionOverride("Rasaad",ChangeAIScript("",RACE))
    ActionOverride("Rasaad",ChangeAIScript("",GENERAL))
    ActionOverride("Rasaad",ChangeAIScript("WTASIGHT",DEFAULT))
    ActionOverride("Rasaad",ChangeAIScript("RASAAD",OVERRIDE))
    MoveGlobal("AR2000","Rasaad",[1550.1368])
    ActionOverride("Rasaad",Face(S))
    ActionOverride("Rasaad",SetGlobal("BD_JOINXP","LOCALS",0))
    ActionOverride("Rasaad",SetGlobal("KickedOut","LOCALS",0))
    ActionOverride("Rasaad",SetNumTimesTalkedTo(0))
    ActionOverride("Rasaad",DestroyAllEquipment())
    ActionOverride("Rasaad",CreateItem("RSBRAC",1,0,0)) // Glimmering Bands
    ActionOverride("Rasaad",CreateItem("RSBOOT",1,0,0)) // Moonlight Walkers
    ActionOverride("Rasaad",FillSlot(SLOT_GAUNTLETS))
    ActionOverride("Rasaad",FillSlot(SLOT_BOOTS))
    ActionOverride("Rasaad",EquipMostDamagingMelee())
    //ReallyForceSpellRES("K#PORRAS","Rasaad")
    SetPlayerSound("Rasaad",-1,INITIAL_MEETING) // No such index
    SetPlayerSound("Rasaad",-1,MORALE) // No such index
    SetPlayerSound("Rasaad",93990,HAPPY) // My heart is filled with joy.
    SetPlayerSound("Rasaad",93991,UNHAPPY_ANNOYED) // I am rising above this.
    SetPlayerSound("Rasaad",93992,UNHAPPY_SERIOUS) // This will not stand.
    SetPlayerSound("Rasaad",93993,UNHAPPY_BREAKING_POINT) // This is intolerable!
    SetPlayerSound("Rasaad",86697,LEADER) // I shall do everything to prove "Rasaad" worthy to lead.
    SetPlayerSound("Rasaad",86701,TIRED) // I am weary. Let us rest for a while, my friend.
    SetPlayerSound("Rasaad",86711,BORED) // I am a patient man, but that patience is being tried.
    SetPlayerSound("Rasaad",86686,BATTLE_CRY1) // Pay for your sins!
    SetPlayerSound("Rasaad",86690,BATTLE_CRY2) // I'll see you in the ground!
    SetPlayerSound("Rasaad",86695,BATTLE_CRY3) // Taste my foot!
    SetPlayerSound("Rasaad",-1,BATTLE_CRY4) // No such index
    SetPlayerSound("Rasaad",-1,BATTLE_CRY5) // No such index
    SetPlayerSound("Rasaad",-1,ATTACK1) // No such index
    SetPlayerSound("Rasaad",-1,ATTACK2) // No such index
    SetPlayerSound("Rasaad",-1,ATTACK3) // No such index
    SetPlayerSound("Rasaad",-1,ATTACK4) // No such index
    SetPlayerSound("Rasaad",86757,DAMAGE) // Uagh!
    SetPlayerSound("Rasaad",86758,DYING) // I fear I am done. Gamaz, my brother, I will see you soon.
    SetPlayerSound("Rasaad",86719,HURT) // Leave me. I will only slow you down.
    SetPlayerSound("Rasaad",86759,AREA_FOREST) // It is so peaceful here. My mind is calm, and my heart is not so heavy.
    SetPlayerSound("Rasaad",86760,AREA_CITY) // This place is so full of motion and noise—it is difficult to focus on what really matters.
    SetPlayerSound("Rasaad",86761,AREA_DUNGEON) // Let us do what needs to be done and be done with this place.
    SetPlayerSound("Rasaad",86762,AREA_DAY) // The sun is just, but merciless.
    SetPlayerSound("Rasaad",86763,AREA_NIGHT) // Once, Selûne's light calmed my heart and cleared my mind. No longer.
    SetPlayerSound("Rasaad",86740,SELECT_COMMON1) // What can I do?
    SetPlayerSound("Rasaad",86766,SELECT_COMMON2) // Let me help you.
    SetPlayerSound("Rasaad",86731,SELECT_COMMON3) // I need something to punch or kick.
    SetPlayerSound("Rasaad",86767,SELECT_COMMON4) // What do you want of me?
    SetPlayerSound("Rasaad",86723,SELECT_COMMON5) // I shall do what is required.
    SetPlayerSound("Rasaad",86714,SELECT_COMMON6) // We will take action soon. Right?
    SetPlayerSound("Rasaad",86743,SELECT_ACTION1) // Very well.
    SetPlayerSound("Rasaad",86751,SELECT_ACTION2) // I could handle that.
    SetPlayerSound("Rasaad",86752,SELECT_ACTION3) // Excellent.
    SetPlayerSound("Rasaad",86747,SELECT_ACTION4) // As you wish.
    SetPlayerSound("Rasaad",86754,SELECT_ACTION5) // It would be my pleasure.
    SetPlayerSound("Rasaad",86755,SELECT_ACTION6) // Certainly.
    SetPlayerSound("Rasaad",86756,SELECT_ACTION7) // That is all?
    SetPlayerSound("Rasaad",-1,INTERACTION1) // No such index
    SetPlayerSound("Rasaad",-1,INTERACTION1) // No such index
    SetPlayerSound("Rasaad",-1,INTERACTION2) // No such index
    SetPlayerSound("Rasaad",-1,INTERACTION3) // No such index
    SetPlayerSound("Rasaad",-1,INTERACTION4) // No such index
    SetPlayerSound("Rasaad",-1,INTERACTION5) // No such index
    SetPlayerSound("Rasaad",-1,INSULT1) // No such index
    SetPlayerSound("Rasaad",-1,INSULT2) // No such index
    SetPlayerSound("Rasaad",-1,INSULT3) // No such index
    SetPlayerSound("Rasaad",-1,COMPLIMENT1) // No such index
    SetPlayerSound("Rasaad",-1,COMPLIMENT2) // No such index
    SetPlayerSound("Rasaad",-1,COMPLIMENT3) // No such index
    SetPlayerSound("Rasaad",-1,SPECIAL1) // No such index
    SetPlayerSound("Rasaad",-1,SPECIAL2) // No such index
    SetPlayerSound("Rasaad",-1,SPECIAL3) // No such index
    SetPlayerSound("Rasaad",86764,REACT_TO_DIE_GENERAL) // Our enemies will pay a terrible price for this!
    SetPlayerSound("Rasaad",-1,REACT_TO_DIE_SPECIFIC) // No such index
    SetPlayerSound("Rasaad",-1,MISCELLANEOUS) // No such index
    SetPlayerSound("Rasaad",-1,RESPONSE_TO_COMPLIMENT2) // No such index
    SetPlayerSound("Rasaad",-1,RESPONSE_TO_COMPLIMENT3) // No such index
    SetPlayerSound("Rasaad",-1,RESPONSE_TO_INSULT1) // No such index
    SetPlayerSound("Rasaad",-1,RESPONSE_TO_INSULT2) // No such index
    SetPlayerSound("Rasaad",-1,RESPONSE_TO_INSULT3) // No such index
    SetPlayerSound("Rasaad",-1,DIALOG_HOSTILE) // No such index
    SetPlayerSound("Rasaad",-1,DIALOG_DEFAULT) // No such index
    SetPlayerSound("Rasaad",86753,SELECT_RARE1) // Simplicity itself for one trained in the techniques of the Sun Soul order.
    SetPlayerSound("Rasaad",86728,SELECT_RARE2) // It is the will of the goddess.
    SetPlayerSound("Rasaad",86768,CRITICAL_HIT) // You cannot defeat me. Surrender now, before it's too late.
    SetPlayerSound("Rasaad",86770,CRITICAL_MISS) // You are a slippery one!
    SetPlayerSound("Rasaad",86771,TARGET_IMMUNE) // Nothing? Then I'll try something different!
    SetPlayerSound("Rasaad",86772,INVENTORY_FULL) // Each new item restricts my movement further. I can carry no more.
    SetPlayerSound("Rasaad",86773,PICKED_POCKET) // Not the honorable way to do things—but certainly an efficient one.
    SetPlayerSound("Rasaad",86774,EXISTANCE1) // As long as we are unseen, we are safe.
    SetPlayerSound("Rasaad",86775,EXISTANCE2) // Tchah! That didn't work.
    SetPlayerSound("Rasaad",86776,EXISTANCE3) // This should make our enemies think twice.
    SetPlayerSound("Rasaad",-1,EXISTANCE4) // No such index
    SetPlayerSound("Rasaad",86676,EXISTANCE5) // A worshipper of the moon goddess Selûne, the taciturn monk Rasaad's life in service to the Sun Soul order ended in tragedy. He speaks of his brother Gamaz in reverent tones, even though Gamaz betrayed the Sun Soul by joining the Dark Moon sect, where he learned to worship Shar at the feet of a man named Alorgoth. Though it was his own hand that slew Gamaz, Rasaad holds Alorgoth responsible for his brother's death. He has committed himself to avenging Gamaz, and it's obvious there is little he won't sacrifice to achieve that goal.
    SetGlobal("K#RasaadImport","AR2000",1)
    Continue()
END

IF
  HasDLC("Rasaad")
  Global("K#RasaadImport","AR2000",0)
  !BeenInParty("Rasaad")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Rasaad",STATE_REALLY_DEAD)
  //XPLT(Player1,250000)
THEN
  RESPONSE #100
    CreateCreature("RASAAD8",[1550.1368],S) // Rasaad
    ActionOverride("Rasaad",MakeGlobalOverride())
    SetGlobal("K#RasaadImport","AR2000",1)
    Continue()
END

/*IF
  HasDLC("Rasaad")
  Global("K#RasaadImport","AR2000",0)
  !BeenInParty("Rasaad")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Rasaad",STATE_REALLY_DEAD)
  XPGT(Player1,249999)
  XPLT(Player1,450000)
THEN
  RESPONSE #100
    CreateCreature("RASAAD9",[1550.1368],S) // Rasaad
    ActionOverride("Rasaad",MakeGlobalOverride())
    SetGlobal("K#RasaadImport","AR2000",1)
    Continue()
END

IF
  HasDLC("Rasaad")
  Global("K#RasaadImport","AR2000",0)
  !BeenInParty("Rasaad")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Rasaad",STATE_REALLY_DEAD)
  XPGT(Player1,449999)
  XPLT(Player1,800000)
THEN
  RESPONSE #100
    CreateCreature("RASAAD10",[1550.1368],S) // Rasaad
    ActionOverride("Rasaad",MakeGlobalOverride())
    SetGlobal("K#RasaadImport","AR2000",1)
    Continue()
END

IF
  HasDLC("Rasaad")
  Global("K#RasaadImport","AR2000",0)
  !BeenInParty("Rasaad")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Rasaad",STATE_REALLY_DEAD)
  XPGT(Player1,799999)
  XPLT(Player1,1200000)
THEN
  RESPONSE #100
    CreateCreature("RASAAD11",[1550.1368],S) // Rasaad
    ActionOverride("Rasaad",MakeGlobalOverride())
    SetGlobal("K#RasaadImport","AR2000",1)
    Continue()
END

IF
  HasDLC("Rasaad")
  Global("K#RasaadImport","AR2000",0)
  !BeenInParty("Rasaad")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Rasaad",STATE_REALLY_DEAD)
  XPGT(Player1,1199999)
THEN
  RESPONSE #100
    CreateCreature("RASAAD12",[1550.1368],S) // Rasaad
    ActionOverride("Rasaad",MakeGlobalOverride())
    SetGlobal("K#RasaadImport","AR2000",1)
    Continue()
END*/

IF
  HasDLC("Rasaad")
  Global("OHR_SPAWN","AR2000",0)
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Rasaad",STATE_REALLY_DEAD)
THEN
  RESPONSE #100
    SetGlobal("OHR_SPAWN","AR2000",1)
    CreateCreature("OHRTREYA",[1600.1435],NNW) // Treya
    CreateCreature("OHRSSM01",[1486.1435],NE) // Sun Soul Monk
END
>>>>>>>>

COPY_EXISTING ~AR2000.BCS~ ~override~
	REPLACE_BCS_BLOCK ~.../AR2000-rbOld.baf~ ~.../AR2000-rbNew.baf~ ON_MISMATCH PATCH_WARN ~WARNING: could not find REPLACE_BCS_BLOCK matching .../AR2000-rbOld.baf in %SOURCE_FILE%~ END
BUT_ONLY

<<<<<<<< .../OHR_JOIN-rbOld.baf
IF
  Global("OHR_PLOT","GLOBAL",0)
  Range(Player1,30)
  XPLT(Player1,250000)
  !InMyArea("RASAAD")
  !InPartyAllowDead("RASAAD")
  !Dead("RASAAD")
THEN
  RESPONSE #100
    CreateCreatureObject("RASAAD8",Player1,0,0,0) // Rasaad
END

IF
  Global("OHR_PLOT","GLOBAL",0)
  Range(Player1,30)
  XPGT(Player1,249999)
  XPLT(Player1,450000)
  !InMyArea("RASAAD")
  !InPartyAllowDead("RASAAD")
  !Dead("RASAAD")
THEN
  RESPONSE #100
    CreateCreatureObject("RASAAD9",Player1,0,0,0) // Rasaad
END

IF
  Global("OHR_PLOT","GLOBAL",0)
  Range(Player1,30)
  XPGT(Player1,449999)
  XPLT(Player1,800000)
  !InMyArea("RASAAD")
  !InPartyAllowDead("RASAAD")
  !Dead("RASAAD")
THEN
  RESPONSE #100
    CreateCreatureObject("RASAAD10",Player1,0,0,0) // Rasaad
END

IF
  Global("OHR_PLOT","GLOBAL",0)
  Range(Player1,30)
  XPGT(Player1,799999)
  XPLT(Player1,1200000)
  !InMyArea("RASAAD")
  !InPartyAllowDead("RASAAD")
  !Dead("RASAAD")
THEN
  RESPONSE #100
    CreateCreatureObject("RASAAD11",Player1,0,0,0) // Rasaad
END

IF
  Global("OHR_PLOT","GLOBAL",0)
  Range(Player1,30)
  XPGT(Player1,1199999)
  !InMyArea("RASAAD")
  !InPartyAllowDead("RASAAD")
  !Dead("RASAAD")
THEN
  RESPONSE #100
    CreateCreatureObject("RASAAD13",Player1,0,0,0) // Rasaad
END
>>>>>>>>

<<<<<<<< .../OHR_JOIN-rbNew.baf
IF
  Global("K#RasaadImport","AR2000",1)
  Global("OHR_PLOT","GLOBAL",0)
  Range(Player1,30)
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Rasaad",STATE_REALLY_DEAD)
  !InMyArea("RASAAD")
  !InPartyAllowDead("RASAAD")
THEN
  RESPONSE #100
    MoveGlobalObject("Rasaad",Player1)
    SetGlobal("K#RasaadImport","AR2000",2)
END
>>>>>>>>

COPY_EXISTING ~OHR_JOIN.BCS~ ~override~
	REPLACE_BCS_BLOCK ~.../OHR_JOIN-rbOld.baf~ ~.../OHR_JOIN-rbNew.baf~ ON_MISMATCH PATCH_WARN ~WARNING: could not find REPLACE_BCS_BLOCK matching .../OHR_JOIN-rbOld.baf in %SOURCE_FILE%.~ END
BUT_ONLY

/////                                                  \\\\\
///// AR2000 (Drizzt "random" encounter)               \\\\\
/////                                                  \\\\\

COPY_EXISTING ~AR2601.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~\(SetEncounterProbability("AR2500","AR1700",0)\)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~\1
    SetEncounterProbability("AR2500","AR3000",0)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

/////                                                  \\\\\
///// AR4000 (ToB starting location - Spirit Heads)    \\\\\
/////                                                  \\\\\

COPY_EXISTING ~AR4000.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~OnCreation()[%newline%]*\(Global("TurnDay","AR4000",0)\)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~\1~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
		SPRINT textToReplace ~IF[%newline%]*InParty(".+")[%newline%]*Global(".+","GLOBAL",0)[%newline%]*THEN[%newline%]*RESPONSE #100[%newline%]*SetGlobal(".+","GLOBAL",2)[%newline%]*END~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches >= 21) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find 21 matches for %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

<<<<<<<< .../AR4000-et.baf
IF
  Global("K#NewGame","AR4000",0)
  InPartyAllowDead(Player2)
  !Name("None",Player2)
THEN
  RESPONSE #100
    ActionOverride(Player2,SetGlobal("K#PartyToB","LOCALS",1))
    Continue()
END

IF
  Global("K#NewGame","AR4000",0)
  InPartyAllowDead(Player3)
  !Name("None",Player3)
THEN
  RESPONSE #100
    ActionOverride(Player3,SetGlobal("K#PartyToB","LOCALS",1))
    Continue()
END

IF
  Global("K#NewGame","AR4000",0)
  InPartyAllowDead(Player4)
  !Name("None",Player4)
THEN
  RESPONSE #100
    ActionOverride(Player4,SetGlobal("K#PartyToB","LOCALS",1))
    Continue()
END

IF
  Global("K#NewGame","AR4000",0)
  InPartyAllowDead(Player5)
  !Name("None",Player5)
THEN
  RESPONSE #100
    ActionOverride(Player5,SetGlobal("K#PartyToB","LOCALS",1))
    Continue()
END

IF
  Global("K#NewGame","AR4000",0)
  InPartyAllowDead(Player6)
  !Name("None",Player6)
THEN
  RESPONSE #100
    ActionOverride(Player6,SetGlobal("K#PartyToB","LOCALS",1))
    Continue()
END

IF
  Global("K#NewGame","AR4000",0)
  Global("ENDOFBG1","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("K#NewGame","AR4000",1)
    SetGlobal("DREAM","GLOBAL",7)
    SetGlobal("XPGiven","GLOBAL",0)
    SetGlobal("INTOB","GLOBAL",1)
    SetGlobal("StartMP","GLOBAL",1)
    SetGlobal("HadEllesimeDream1","GLOBAL",1)
    SetGlobal("HadImoenDream1","GLOBAL",1)
    SetGlobal("HadSlayerDream","GLOBAL",1)
    SetGlobal("HadJonDream1","GLOBAL",1)
    SetGlobal("HadJonDream2","GLOBAL",1)
    SetGlobal("HadEllesimeDream2","GLOBAL",1)
    SetGlobal("ENDOFBG1","GLOBAL",2)
    SetGlobal("SPRITE_IS_DEADYOSHIMO","GLOBAL",1)
    SetGlobal("NEWGAME_TOB","GLOBAL",1)
    StartMovie("INTRO")
    AddWorldmapAreaFlag("AR4000",EXPLORED) //Has been visited
    RemoveWorldmapAreaFlag("AR0020",ENABLED) //Reveal from linked area
    ReallyForceSpellRES("K#REMBHA",Player1)
    //ActionOverride(Player1,ApplySpell(Myself,GIVE_SLAYER_POWER))
    ActionOverride(Player1,AddSpecialAbility("SPIN822"))
    TakeItemListPartyNum("K#PLOT",99)
    GiveItemCreate("BAG19",Player1,1,0,0)
    GiveItemCreate("AMUL27",Player1,1,0,0)
    Continue()
END

IF
  Global("K#NewGame","AR4000",0)
  !Global("ENDOFBG1","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("K#NewGame","AR4000",1)
    SetGlobal("XPGiven","GLOBAL",0)
    SetGlobal("INTOB","GLOBAL",1)
    SetGlobal("StartMP","GLOBAL",1)
    SetGlobal("HadEllesimeDream1","GLOBAL",1)
    SetGlobal("HadImoenDream1","GLOBAL",1)
    SetGlobal("HadSlayerDream","GLOBAL",1)
    SetGlobal("HadJonDream1","GLOBAL",1)
    SetGlobal("HadJonDream2","GLOBAL",1)
    SetGlobal("HadEllesimeDream2","GLOBAL",1)
    SetGlobal("ENDOFBG1","GLOBAL",2)
    SetGlobal("SPRITE_IS_DEADYOSHIMO","GLOBAL",1)
    SetGlobal("SPRITE_IS_DEADSAREVOK","GLOBAL",0)
    ChangeGender("Edwin",MALE)
    ReallyForceSpellRES("K#FAMREM",Player1)
    ReallyForceSpellRES("K#FAMREM",Player2)
    ReallyForceSpellRES("K#FAMREM",Player3)
    ReallyForceSpellRES("K#FAMREM",Player4)
    ReallyForceSpellRES("K#FAMREM",Player5)
    ReallyForceSpellRES("K#FAMREM",Player6)
    GiveItemCreate("AMUL27",Player1,1,0,0)
    Continue()
END
>>>>>>>>

EXTEND_TOP ~AR4000.BCS~ ~.../AR4000-et.baf~

/////                                                  \\\\\
///// AR4500 (Pocket Plane)                            \\\\\
/////                                                  \\\\\

COPY_EXISTING ~AR4500.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~SpawnPlane","GLOBAL",0)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~%textToReplace%
  Global("NEWGAME_TOB","GLOBAL",1)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
		SPRINT textToReplace ~ActionOverride("[^"]+",SetBeenInPartyFlags())~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

<<<<<<<< .../AR4500-eb.baf
IF
  Global("K#DisableSPIN649","GLOBAL",0)
THEN
  RESPONSE #100
    ReallyForceSpellRES("K#PP_ADD",Player1) // No such index
    SetGlobal("K#DisableSPIN649","GLOBAL",1)
    Continue()
END
>>>>>>>>

EXTEND_BOTTOM ~AR4500.BCS~ ~.../AR4500-eb.baf~

/////                                                  \\\\\
///// AERIE                                            \\\\\
/////                                                  \\\\\

COPY_EXISTING ~AERIE.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~SetBeenInPartyFlags()~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

/////                                                  \\\\\
///// BDSODIMP                                         \\\\\
/////                                                  \\\\\

COPY_EXISTING ~BDSODIMP.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~\(PartyHasItem("\)\([^"]+\)\(")[%newline%]*THEN[%newline%]*RESPONSE #100[%newline%]*CutSceneId(Player1)\)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~\1\2\3
    TakePartyItem("\2")
    DestroyItem("\2")~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

/////                                                  \\\\\
///// CUT205B (Sarevok spawn cutscene)                 \\\\\
/////                                                  \\\\\

COPY_EXISTING ~CUT205B.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~CreateCreature("Sarevok",\[1986\.1145\],S)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~CreateCreature("Sarevok",[1986.1145],S)
    SetGlobal("SPRITE_IS_DEADSAREVOK","GLOBAL",0)
    ActionOverride("Sarevok",SetNumTimesTalkedTo(0))~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

/////                                                  \\\\\
///// AR0500, OHNCUT1A, OH6000 (Neera spawn)           \\\\\
/////                                                  \\\\\

COPY_EXISTING ~OHNMCUT1.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~CreateCreature("OHNELLIS",\[3848\.448\],NNW)[%newline%]*END~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~CreateCreature("OHNELLIS",[3848.448],NNW)
    Continue()
END~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

<<<<<<<< .../AR0500-et.baf
IF
  Global("OHN_INTRO_SCENE","AR0500",2)
  Global("K#NeeraImport","AR0500",0)
  BeenInParty("Neera")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Neera",STATE_REALLY_DEAD)
THEN
  RESPONSE #100
    ActionOverride("Neera",SetDialog("NEERA"))
    ActionOverride("Neera",ChangeAIScript("",CLASS))
    ActionOverride("Neera",ChangeAIScript("",RACE))
    ActionOverride("Neera",ChangeAIScript("",GENERAL))
    ActionOverride("Neera",ChangeAIScript("WTARSGT",DEFAULT))
    ActionOverride("Neera",ChangeAIScript("NEERA",OVERRIDE))
    MoveGlobal("AR0500","Neera",[3927.485])
    ActionOverride("Neera",Face(NNW))
    ActionOverride("Neera",SetGlobal("BD_JOINXP","LOCALS",0))
    ActionOverride("Neera",SetGlobal("KickedOut","LOCALS",0))
    ActionOverride("Neera",SetNumTimesTalkedTo(0))
    ActionOverride("Neera",DestroyAllEquipment())
    ActionOverride("Neera",CreateItem("NEBELT01",1,0,0)) // Adoy's Belt
    ActionOverride("Neera",CreateItem("STAFN1",1,0,0)) // Neera's Staff +1
    ActionOverride("Neera",FillSlot(SLOT_BELT))
    ActionOverride("Neera",FillSlot(SLOT_WEAPON))
    ActionOverride("Neera",EquipMostDamagingMelee())
    SetPlayerSound("Neera",-1,INITIAL_MEETING) // No such index
    SetPlayerSound("Neera",-1,MORALE) // No such index
    SetPlayerSound("Neera",84546,HAPPY) // I'm so proud of you, <CHARNAME>.
    SetPlayerSound("Neera",86672,UNHAPPY_ANNOYED) // I don't like where this is headed.
    SetPlayerSound("Neera",86673,UNHAPPY_SERIOUS) // Definitely don't like where this is headed.
    SetPlayerSound("Neera",102930,UNHAPPY_BREAKING_POINT) // I can't take any more of this!
    SetPlayerSound("Neera",88513,LEADER) // You understand that I am volatile and occasionally unreasonable? Okay, great!
    SetPlayerSound("Neera",88514,TIRED) // *yawn* My mind's even foggier than usual. Can we... stop?
    SetPlayerSound("Neera",88516,BORED) // Fidgeting over here... fidget, fidget, fidget!
    SetPlayerSound("Neera",88510,BATTLE_CRY1) // Get down, everyone!
    SetPlayerSound("Neera",88511,BATTLE_CRY2) // I command pure chaos! Kinda.
    SetPlayerSound("Neera",88512,BATTLE_CRY3) // Victory? Unclear. Destruction? Certain!
    SetPlayerSound("Neera",-1,BATTLE_CRY4) // No such index
    SetPlayerSound("Neera",-1,BATTLE_CRY5) // No such index
    SetPlayerSound("Neera",-1,ATTACK1) // No such index
    SetPlayerSound("Neera",-1,ATTACK2) // No such index
    SetPlayerSound("Neera",-1,ATTACK3) // No such index
    SetPlayerSound("Neera",-1,ATTACK4) // No such index
    SetPlayerSound("Neera",88533,DAMAGE) // Ouch. OUCH!
    SetPlayerSound("Neera",88534,DYING) // 
    SetPlayerSound("Neera",88518,HURT) // Please! Someone... anyone?! I'm in... quite a bit of pain here.
    SetPlayerSound("Neera",88535,AREA_FOREST) // Being in the woods always reminds me of the High Forest. I like it.
    SetPlayerSound("Neera",88536,AREA_CITY) // Are you gonna make me cast spells here? There are a lot of people around.
    SetPlayerSound("Neera",88537,AREA_DUNGEON) // I sense great evil... fabled treasure... terrible danger... probably some spiders.
    SetPlayerSound("Neera",88538,AREA_DAY) // It's a fine day for fireballs.
    SetPlayerSound("Neera",88539,AREA_NIGHT) // An evening stroll under the stars! When do we get attacked?
    SetPlayerSound("Neera",88519,SELECT_COMMON1) // Hmm?
    SetPlayerSound("Neera",88520,SELECT_COMMON2) // Ready for anything.
    SetPlayerSound("Neera",88521,SELECT_COMMON3) // Happy to help... uh, to try to help, anyway.
    SetPlayerSound("Neera",88522,SELECT_COMMON4) // I'm ready!
    SetPlayerSound("Neera",88523,SELECT_COMMON5) // Yes?
    SetPlayerSound("Neera",88524,SELECT_COMMON6) // What'll it be?
    SetPlayerSound("Neera",88526,SELECT_ACTION1) // That's it?
    SetPlayerSound("Neera",88527,SELECT_ACTION2) // Fine!
    SetPlayerSound("Neera",88528,SELECT_ACTION3) // Sure.
    SetPlayerSound("Neera",88529,SELECT_ACTION4) // I suppose.
    SetPlayerSound("Neera",88530,SELECT_ACTION5) // I'll do it.
    SetPlayerSound("Neera",88531,SELECT_ACTION6) // Simple and surge-free.
    SetPlayerSound("Neera",88532,SELECT_ACTION7) // So easy you could almost do it yourself.
    SetPlayerSound("Neera",-1,INTERACTION1) // No such index
    SetPlayerSound("Neera",-1,INTERACTION1) // No such index
    SetPlayerSound("Neera",-1,INTERACTION2) // No such index
    SetPlayerSound("Neera",-1,INTERACTION3) // No such index
    SetPlayerSound("Neera",-1,INTERACTION4) // No such index
    SetPlayerSound("Neera",-1,INTERACTION5) // No such index
    SetPlayerSound("Neera",-1,INSULT1) // No such index
    SetPlayerSound("Neera",-1,INSULT2) // No such index
    SetPlayerSound("Neera",-1,INSULT3) // No such index
    SetPlayerSound("Neera",-1,COMPLIMENT1) // No such index
    SetPlayerSound("Neera",-1,COMPLIMENT2) // No such index
    SetPlayerSound("Neera",-1,COMPLIMENT3) // No such index
    SetPlayerSound("Neera",-1,SPECIAL1) // No such index
    SetPlayerSound("Neera",-1,SPECIAL2) // No such index
    SetPlayerSound("Neera",-1,SPECIAL3) // No such index
    SetPlayerSound("Neera",88540,REACT_TO_DIE_GENERAL) // No! We can't let them get away with this!
    SetPlayerSound("Neera",-1,REACT_TO_DIE_SPECIFIC) // No such index
    SetPlayerSound("Neera",-1,MISCELLANEOUS) // No such index
    SetPlayerSound("Neera",-1,RESPONSE_TO_COMPLIMENT2) // No such index
    SetPlayerSound("Neera",-1,RESPONSE_TO_COMPLIMENT3) // No such index
    SetPlayerSound("Neera",-1,RESPONSE_TO_INSULT1) // No such index
    SetPlayerSound("Neera",-1,RESPONSE_TO_INSULT2) // No such index
    SetPlayerSound("Neera",-1,RESPONSE_TO_INSULT3) // No such index
    SetPlayerSound("Neera",-1,DIALOG_HOSTILE) // No such index
    SetPlayerSound("Neera",-1,DIALOG_DEFAULT) // No such index
    SetPlayerSound("Neera",88541,SELECT_RARE1) // Not savin' the day this time.
    SetPlayerSound("Neera",88542,SELECT_RARE2) // I was tryin' to concentrate!
    SetPlayerSound("Neera",88544,CRITICAL_HIT) // Did everyone see that? It was incredible!
    SetPlayerSound("Neera",88546,CRITICAL_MISS) // That wasn't even close, was it?
    SetPlayerSound("Neera",88547,TARGET_IMMUNE) // Blast it! That's not gonna work.
    SetPlayerSound("Neera",88548,INVENTORY_FULL) // Get rid of some of this trash! I can't carry anymore.
    SetPlayerSound("Neera",88549,PICKED_POCKET) // I could get used to this! It was so easy.
    SetPlayerSound("Neera",88550,EXISTANCE1) // I feel so sneaky.
    SetPlayerSound("Neera",88551,EXISTANCE2) // Oh no, I've lost my spell!
    SetPlayerSound("Neera",88552,EXISTANCE3) // Ha! Can't wait to see what happens.
    SetPlayerSound("Neera",-1,EXISTANCE4) // No such index
    SetPlayerSound("Neera",93710,EXISTANCE5) // When asked about her past, NEERA shrugs. She says that, before coming to Athkatla, she wandered the Sword Coast enjoying an adventurer's life while evading the Order of Eight Staves, an organization dedicated to hunting wild mages. She talks less about her distant past, but does not hide the fact she was banished from the High Forest for her wild magic. She is quick to laugh and to chatter, perhaps a little glibly, but lashes out whenever she senses a threat to her autonomy. She is deeply invested in protecting other wild mages and seems willing to risk almost everything to do so.
    SetGlobal("K#NeeraImport","AR0500",1)
    Continue()
END

IF
  Global("OHN_INTRO_SCENE","AR0500",2)
  Global("K#NeeraImport","AR0500",0)
  !BeenInParty("Neera")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Neera",STATE_REALLY_DEAD)
  //XPLT(Player1,250000)
THEN
  RESPONSE #100
    CreateCreature("NEERA8",[3927.485],NNW) // Neera
    ActionOverride("Neera",MakeGlobalOverride())
    SetGlobal("K#NeeraImport","AR0500",1)
    Continue()
END

/*IF
  Global("OHN_INTRO_SCENE","AR0500",2)
  Global("K#NeeraImport","AR0500",0)
  !BeenInParty("Neera")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Neera",STATE_REALLY_DEAD)
  XPGT(Player1,249999)
  XPLT(Player1,400000)
THEN
  RESPONSE #100
    CreateCreature("NEERA10",[3927.485],NNW) // Neera
    ActionOverride("Neera",MakeGlobalOverride())
    SetGlobal("K#NeeraImport","AR0500",1)
    Continue()
END

IF
  Global("OHN_INTRO_SCENE","AR0500",2)
  Global("K#NeeraImport","AR0500",0)
  !BeenInParty("Neera")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Neera",STATE_REALLY_DEAD)
  XPGT(Player1,399999)
  XPLT(Player1,800000)
THEN
  RESPONSE #100
    CreateCreature("NEERA11",[3927.485],NNW) // Neera
    ActionOverride("Neera",MakeGlobalOverride())
    SetGlobal("K#NeeraImport","AR0500",1)
    Continue()
END

IF
  Global("OHN_INTRO_SCENE","AR0500",2)
  Global("K#NeeraImport","AR0500",0)
  !BeenInParty("Neera")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Neera",STATE_REALLY_DEAD)
  XPGT(Player1,799999)
  XPLT(Player1,1200000)
THEN
  RESPONSE #100
    CreateCreature("NEERA12",[3927.485],NNW) // Neera
    ActionOverride("Neera",MakeGlobalOverride())
    SetGlobal("K#NeeraImport","AR0500",1)
    Continue()
END

IF
  Global("OHN_INTRO_SCENE","AR0500",2)
  Global("K#NeeraImport","AR0500",0)
  !BeenInParty("Neera")
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Neera",STATE_REALLY_DEAD)
  XPGT(Player1,1199999)
THEN
  RESPONSE #100
    CreateCreature("NEERA13",[3927.485],NNW) // Neera
    ActionOverride("Neera",MakeGlobalOverride())
    SetGlobal("K#NeeraImport","AR0500",1)
    Continue()
END*/
>>>>>>>>

EXTEND_TOP ~AR0500.BCS~ ~.../AR0500-et.baf~

COPY_EXISTING ~OHNCUT1A.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~CreateCreature("NEERA8",\[3927\.485\],NNW)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

<<<<<<<< .../OH6000-rbOld.baf
IF
  Global("OHN_PLOT","GLOBAL",0)
  XPLT(Player1,250000)
  !InMyArea("NEERA")
  !InPartyAllowDead("NEERA")
  !Dead("NEERA")
THEN
  RESPONSE #100
    SetGlobal("OHN_PLOT","GLOBAL",1)
    CreateCreature("NEERA8",[993.3534],S) // Neera
END

IF
  Global("OHN_PLOT","GLOBAL",0)
  XPGT(Player1,249999)
  XPLT(Player1,400000)
  !InMyArea("NEERA")
  !InPartyAllowDead("NEERA")
  !Dead("NEERA")
THEN
  RESPONSE #100
    SetGlobal("OHN_PLOT","GLOBAL",1)
    CreateCreature("NEERA10",[993.3534],S) // Neera
END

IF
  Global("OHN_PLOT","GLOBAL",0)
  XPGT(Player1,399999)
  XPLT(Player1,800000)
  !InMyArea("NEERA")
  !InPartyAllowDead("NEERA")
  !Dead("NEERA")
THEN
  RESPONSE #100
    SetGlobal("OHN_PLOT","GLOBAL",1)
    CreateCreature("NEERA11",[993.3534],S) // Neera
END

IF
  Global("OHN_PLOT","GLOBAL",0)
  XPGT(Player1,799999)
  XPLT(Player1,1200000)
  !InMyArea("NEERA")
  !InPartyAllowDead("NEERA")
  !Dead("NEERA")
THEN
  RESPONSE #100
    SetGlobal("OHN_PLOT","GLOBAL",1)
    CreateCreature("NEERA12",[993.3534],S) // Neera
END

IF
  Global("OHN_PLOT","GLOBAL",0)
  XPGT(Player1,1199999)
  !InMyArea("NEERA")
  !InPartyAllowDead("NEERA")
  !Dead("NEERA")
THEN
  RESPONSE #100
    SetGlobal("OHN_PLOT","GLOBAL",1)
    CreateCreature("NEERA13",[993.3534],S) // Neera
END
>>>>>>>>

<<<<<<<< .../OH6000-rbNew.baf
IF
  Global("OHN_PLOT","GLOBAL",0)
  GlobalLT("chapter","GLOBAL",20)
  !StateCheck("Neera",STATE_REALLY_DEAD)
THEN
  RESPONSE #100
    MoveGlobal("OH6000","Neera",[993.3534])
    ActionOverride("Neera",Face(S))
    SetGlobal("OHN_PLOT","GLOBAL",1)
END
>>>>>>>>

COPY_EXISTING ~OH6000.BCS~ ~override~
	REPLACE_BCS_BLOCK ~.../OH6000-rbOld.baf~ ~.../OH6000-rbNew.baf~ ON_MISMATCH PATCH_WARN ~WARNING: could not find REPLACE_BCS_BLOCK matching .../OH6000-rbOld.baf in %SOURCE_FILE%.~ END
BUT_ONLY

/////                                                  \\\\\
///// OH8000 (Black Pits 2)                            \\\\\
/////                                                  \\\\\

<<<<<<<< .../OH8000-et.baf
IF
  Global("K#NewGame","OH8000",0)
THEN
  RESPONSE #100
    SetGlobal("K#NewGame","OH8000",1)
    LeaveAreaLUAPanic("OH8000","",[2.2],S)
    ActionOverride(Player1,LeaveAreaLUA("OH8000","",[2.2],S))
    ActionOverride(Player2,LeaveAreaLUA("OH8000","",[2.2],S))
    ActionOverride(Player3,LeaveAreaLUA("OH8000","",[2.2],S))
    ActionOverride(Player4,LeaveAreaLUA("OH8000","",[2.2],S))
    ActionOverride(Player5,LeaveAreaLUA("OH8000","",[2.2],S))
    ActionOverride(Player6,LeaveAreaLUA("OH8000","",[2.2],S))
    MultiPlayerSync()
    SmallWait(2)
    Continue()
END
>>>>>>>>

EXTEND_TOP ~OH8000.BCS~ ~.../OH8000-et.baf~

/////                                                  \\\\\
/////existing in BG2:EE and BG:EE, also used in BG2:EE \\\\\
/////                                                  \\\\\

//scripts imported from BG:EE
//BEAR.BCS
//CBEAR.BCS
//CCRAWLER.BCS

//different but no changes needed?:
//CTCK.BCS
//GTCK.BCS
//ICMYC01.BCS
//SLIFIS01.BCS//just different StrRef
//TROLIC01.BCS
//WTATTWAT.BCS

//AMNISE.BCS
COPY_EXISTING ~AMNISE.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~NumTimesTalkedTo(0)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~!Allegiance(Myself,ENEMY)
  NumTimesTalkedTo(0)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

//ANKHEG.BCS
COPY_EXISTING ~ANKHEG.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~RunAwayFrom(NearestEnemyOf(Myself),45)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),45)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

//BLBEAR.BCS
COPY_EXISTING ~BLBEAR.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~RunAwayFrom(LastAttackerOf(Myself),75)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~RunAwayFromNoLeaveArea(LastAttackerOf(Myself),75)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

//DEMGLASU.BCS
COPY_EXISTING ~DEMGLASU.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~See(\[ANYONE\])~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~See([ANYONE])
  Global("Prep","LOCALS",1)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

//DEMNABSU.BCS
COPY_EXISTING ~DEMNABSU.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~ForceSpell(LastSeenBy(Myself),0)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~ForceSpell(LastSeenBy(Myself),TANARI_DEATH_GAZE)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

//DEMSUC.BCS
COPY_EXISTING ~DEMSUC.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~RunAwayFrom(NearestEnemyOf(Myself),30)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),30)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

//FIGHTER4.BCS
COPY_EXISTING ~FIGHTER4.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~RunAwayFrom(NearestEnemyOf(Myself),45)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),45)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

//GBASILSK.BCS
COPY_EXISTING ~GBASILSK.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~RunAwayFrom(NearestEnemyOf(Myself),45)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),45)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

//GENSHY.BCS
COPY_EXISTING ~GENSHY.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~RunAwayFrom(LastSeenBy(Myself),100)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~RunAwayFromNoLeaveArea(LastSeenBy(Myself),100)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

//GIBBER.BCS
COPY_EXISTING ~GIBBER.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~RunAwayFrom(NearestEnemyOf(Myself),75)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),75)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

//INITDLG.BCS, INITDLG2.BCS, INITMAIN.BCS
<<<<<<<< .../INITx-et.baf
IF
  See([PC])
  AttackedBy([GOODCUTOFF],DEFAULT)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    SmallWait(5)
    Enemy()
END
>>>>>>>>

COPY_EXISTING ~INITDLG.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~See(\[PC\])~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~See([PC])
  !Allegiance(Myself,ENEMY)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

EXTEND_TOP ~INITDLG.BCS~ ~.../INITx-et.baf~

COPY_EXISTING ~INITDLG2.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~See(\[PC\])~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~See([PC])
  !Allegiance(Myself,ENEMY)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

EXTEND_TOP ~INITDLG2.BCS~ ~.../INITx-et.baf~

COPY_EXISTING ~INITMAIN.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~See(Player1)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~See(Player1)
  !Allegiance(Myself,ENEMY)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

EXTEND_TOP ~INITMAIN.BCS~ ~.../INITx-et.baf~

//LBASILSK.BCS
COPY_EXISTING ~LBASILSK.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~RunAwayFrom(NearestEnemyOf(Myself),45)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),45)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

//MAGE1.BCS
COPY_EXISTING ~MAGE1.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~HaveSpell(WIZARD_ARMOR)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~CheckStatGT(Myself,4,ARMORCLASS)
  HaveSpell(WIZARD_ARMOR)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

//MAGE2.BCS
<<<<<<<< .../oMAGE2.baf
IF
  ActionListEmpty()
  See(NearestEnemyOf(Myself))
  HaveSpell(WIZARD_DELETED)
  !HasBounceEffects(LastSeenBy(Myself))
  !HasImmunityEffects(LastSeenBy(Myself))
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_DELETED)
END
>>>>>>>> 

<<<<<<<< .../nMAGE2.baf
>>>>>>>>

COPY_EXISTING ~MAGE2.BCS~ ~override/BG2MAGE2.BCS~ //compatibility with BGT mods, used only by GARRICK.cre in BG2:EE
R_B_B ~.../oMAGE2.baf~ ~.../nMAGE2.baf~ ON_MISMATCH PATCH_WARN ~WARNING: Could not find block matching .../oMAGE2.baf in %SOURCE_FILE%~ END

//MAGE3.BCS
COPY_EXISTING ~MAGE3.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~HaveSpell(WIZARD_GHOST_ARMOR)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~CheckStatGT(Myself,2,ARMORCLASS)
  HaveSpell(WIZARD_GHOST_ARMOR)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

//MAGE4.BCS
COPY_EXISTING ~MAGE4.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~HaveSpell(WIZARD_IMPROVED_INVISIBILITY)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~!StateCheck(Myself,STATE_INVISIBLE)
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
  HaveSpell(WIZARD_IMPROVED_INVISIBILITY)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

//MAGE5.BCS
COPY_EXISTING ~MAGE5.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~HaveSpell(WIZARD_MIRROR_IMAGE)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~!StateCheck(Myself,STATE_MIRRORIMAGE)
  HaveSpell(WIZARD_MIRROR_IMAGE)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

//MAGE6.BCS
COPY_EXISTING ~MAGE6.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~HaveSpell(WIZARD_SHADOW_DOOR)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~!StateCheck(Myself,STATE_INVISIBLE)
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
  HaveSpell(WIZARD_SHADOW_DOOR)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

//MAGE7.BCS
COPY_EXISTING ~MAGE7.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~HaveSpell(WIZARD_MIRROR_IMAGE)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~!StateCheck(Myself,STATE_MIRRORIMAGE)
  HaveSpell(WIZARD_MIRROR_IMAGE)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END

		SPRINT textToReplace ~HaveSpell(WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~!CheckStatGT(Myself,0,MINORGLOBE)
  !CheckStatGT(Myself,0,SHIELDGLOBE)
  HaveSpell(WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

//MAGE8.BCS
COPY_EXISTING ~MAGE8.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~HaveSpell(WIZARD_MIRROR_IMAGE)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~!StateCheck(Myself,STATE_MIRRORIMAGE)
  HaveSpell(WIZARD_MIRROR_IMAGE)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END

		SPRINT textToReplace ~HaveSpell(WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~!CheckStatGT(Myself,0,MINORGLOBE)
  !CheckStatGT(Myself,0,SHIELDGLOBE)
  HaveSpell(WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

//PREY.BCS
COPY_EXISTING ~PREY.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~RunAwayFrom(LastSeenBy(Myself),15)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~RunAwayFromNoLeaveArea(LastSeenBy(Myself),15)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

//PRIEST4.BCS
COPY_EXISTING ~PRIEST4.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~RunAwayFrom(NearestEnemyOf(Myself),15)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),15)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

//QUASIT01.BCS
<<<<<<<< .../QUASIT01-et.baf
IF
  See(NearestEnemyOf(Myself))
  !GlobalTimerNotExpired("Prep","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("Prep","LOCALS",1000)
    ReallyForceSpell(Myself,WIZARD_LUCK)
    ReallyForceSpell(Myself,WIZARD_SHIELD)
END

IF
  See(NearestEnemyOf(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  !GlobalTimerNotExpired("Barrage","LOCALS")
  RandomNum(2,1)
THEN
  RESPONSE #100
    SetGlobalTimer("Barrage","LOCALS",12)
    ForceSpell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
  RESPONSE #100
    SetGlobalTimer("Barrage","LOCALS",12)
    ForceSpell(LastSeenBy(Myself),WIZARD_DEAFNESS)
  RESPONSE #100
    SetGlobalTimer("Barrage","LOCALS",12)
    ForceSpell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
  RESPONSE #100
    SetGlobalTimer("Barrage","LOCALS",12)
    ForceSpell(LastSeenBy(Myself),WIZARD_LARLOCH_MINOR_DRAIN)
  RESPONSE #100
    SetGlobalTimer("Barrage","LOCALS",12)
    ForceSpell(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)
  RESPONSE #100
    SetGlobalTimer("Barrage","LOCALS",12)
    ForceSpell(LastSeenBy(Myself),WIZARD_RAY_OF_ENFEEBLEMENT)
END

IF
  See(NearestEnemyOf(Myself))
  Range(NearestEnemyOf(Myself),10)
THEN
  RESPONSE #100
    AttackOneRound(NearestEnemyOf(Myself))
    RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),30)
  RESPONSE #100
    RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),30)
END

IF
  See(NearestEnemyOf(Myself))
  !Range(NearestEnemyOf(Myself),10)
THEN
  RESPONSE #100
    AttackOneRound(NearestEnemyOf(Myself))
    RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),30)
  RESPONSE #50
    RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),30)
END
>>>>>>>>

EXTEND_TOP ~QUASIT01.BCS~ ~.../QUASIT01-et.baf~

//RUNENEMY.BCS
//needed due to "multiplayer cloning bug": http://forum.baldursgate.com/discussion/10389/bug-random-commoners-appear-final-fight-thief-maze-werewolf-island/p1
//Beamdog simply changed RunAwayFrom action to RunAwayFromNoLeaveArea to "fix" this issue
COPY_EXISTING ~RUNENEMY.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~RunAwayFrom(~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~RunAwayFromNoLeaveArea(~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

//SEEENEMY.BCS
COPY_EXISTING ~SEEENEMY.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		//no need to create more conflicts with BG2 mods when not necessary
		/*SPRINT textToReplace ~!Allegiance(Myself,ENEMY)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~!Allegiance(Myself,EVILCUTOFF)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END*/

		SPRINT textToReplace ~!Class(LastSeenBy(Myself),FLAMING_FIST)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~!Class(LastSeenBy(Myself),FLAMING_FIST)
  !Class(LastSeenBy(Myself),CANDLEKEEP_WATCHER)
  !Class(LastSeenBy(Myself),AMNISH_SOLDIER)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

//SHADFI02.BCS
COPY_EXISTING ~SHADFI02.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~See(NearestEnemyOf(Myself))~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~See(NearestEnemyOf(Myself))
  HPPercentGT(Myself,49)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

//SHOUT.BCS
<<<<<<<< .../SHOUT-et.baf
IF
  OR(2)
    StateCheck(Myself,STATE_STONE_DEATH)
    StateCheck(Myself,STATE_FROZEN_DEATH)
THEN
  RESPONSE #100
    SmallWait(5)
END
>>>>>>>>

EXTEND_TOP ~SHOUT.BCS~ ~.../SHOUT-et.baf~

//SIRSPELL.BCS
COPY_EXISTING ~SIRSPELL.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~HaveSpell(WIZARD_IMPROVED_INVISIBILITY)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~!StateCheck(Myself,STATE_INVISIBLE)
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
  HaveSpell(WIZARD_IMPROVED_INVISIBILITY)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

//WDRUNSGT.BCS
COPY_EXISTING ~WDRUNSGT.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~RunAwayFrom(~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~RunAwayFromNoLeaveArea(~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

//WTASIGHT.BCS
COPY_EXISTING ~WTASIGHT.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~See(NearestEnemyOf(Myself))~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~See(NearestEnemyOf(Myself))
  InWeaponRange(LastSeenBy(Myself))~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END

		SPRINT textToReplace ~AttackedBy(\[ANYONE\],DEFAULT)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~AttackedBy([ANYONE],DEFAULT)
  InWeaponRange(LastSeenBy(Myself))~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

<<<<<<<< .../WTASIGHT-eb.baf
IF
  ActionListEmpty()
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    MoveToObject(LastSeenBy(Myself))
END
>>>>>>>>

EXTEND_BOTTOM ~WTASIGHT.BCS~ ~.../WTASIGHT-eb.baf~

//WTRUNSGT.BCS
COPY_EXISTING ~WTRUNSGT.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~RunAwayFrom(NearestEnemyOf(Myself),150)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),150)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
		SPRINT textToReplace ~RunAwayFrom(LastAttackerOf(Myself),150)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~RunAwayFromNoLeaveArea(LastAttackerOf(Myself),150)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

//WTRUNWAT.BCS
COPY_EXISTING ~WTRUNWAT.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		SPRINT textToReplace ~RunAwayFrom(LastAttackerOf(Myself),150)~
		COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
		PATCH_IF (num_matches > 0) BEGIN
			REPLACE_TEXTUALLY ~%textToReplace%~ ~RunAwayFromNoLeaveArea(LastAttackerOf(Myself),150)~
			PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
		END ELSE BEGIN
			PATCH_WARN ~WARNING: could not find %textToReplace% in %SOURCE_FILESPEC%~
		END
	END
BUT_ONLY

/////                                                  \\\\\
///// STATE_PANIC                                      \\\\\
/////                                                  \\\\\

<<<<<<<< .../STATE_PANIC-et.baf
IF
  StateCheck(Myself,STATE_PANIC)
THEN
  RESPONSE #100
    RandomWalkContinuous()
END
>>>>>>>>

ACTION_FOR_EACH script IN ANKHEG CDRYAD DIREWOLF GBASILSK GIBBER GNOLLF HAMA HOBGOBF KOBOLDF LBASILSK OGRE PRIEST1 PRIEST2 PRIEST3 PRIEST4 PRIEST5 PSPIDER WARDOG WDARSGT WDASIGHT WILDDOG WTARSGT WTASIGHT XVART BEGIN
	EXTEND_TOP ~%script%.BCS~ ~.../STATE_PANIC-et.baf~
END

/////                                                  \\\\\
///// BDDEFAI                                          \\\\\
/////                                                  \\\\\

<<<<<<<< .../BDDEFAI-eb.baf
IF
  Global("ENDOFBG1","GLOBAL",0)
  Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
  ActionListEmpty()
  InParty(Myself)
  HaveSpell(BERSERKER_ENRAGE) // SPCL321.SPL (Enrage)
  !CheckSpellState(Myself,BERSERKER_RAGE)
  !GlobalTimerNotExpired("BD_Cast","LOCALS")
  See([EVILCUTOFF])
  OR(4)
    CheckStatGT(LastSeenBy(Myself),6,LEVEL)
    NumCreatureGT([EVILCUTOFF],3)
    See([EVILCUTOFF.0.UMBERHULK])
    See([EVILCUTOFF.0.MYCONID])
THEN
  RESPONSE #100
    SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
    Spell(Myself,BERSERKER_ENRAGE) // SPCL321.SPL (Enrage)
END

IF
  Global("ENDOFBG1","GLOBAL",0)
  Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
  ActionListEmpty()
  InParty(Myself)
  HaveSpell(BARBARIAN_RAGE) // SPCL152.SPL (Barbarian Rage)
  !CheckSpellState(Myself,BARBARIAN_RAGE)
  !GlobalTimerNotExpired("BD_Cast","LOCALS")
  See([EVILCUTOFF])
  OR(4)
    CheckStatGT(LastSeenBy(Myself),6,LEVEL)
    NumCreatureGT([EVILCUTOFF],3)
    See([EVILCUTOFF.0.UMBERHULK])
    See([EVILCUTOFF.0.MYCONID])
THEN
  RESPONSE #100
    SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
    Spell(Myself,BARBARIAN_RAGE) // SPCL152.SPL (Barbarian Rage)
END

IF
  Global("ENDOFBG1","GLOBAL",0)
  Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
  ActionListEmpty()
  InParty(Myself)
  HaveSpell(KENSAI_KIA) // SPCL144.SPL (Kai)
  !CheckSpellState(Myself,KENSAI_KIA)
  Range(NearestEnemyOf(Myself),6)
  !GlobalTimerNotExpired("BD_Cast","LOCALS")
  See([EVILCUTOFF])
  OR(2)
    CheckStatGT(LastSeenBy(Myself),6,LEVEL)
    NumCreatureGT([EVILCUTOFF],3)
THEN
  RESPONSE #100
    SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
    Spell(Myself,KENSAI_KIA) // SPCL144.SPL (Kai)
END

IF
  Global("ENDOFBG1","GLOBAL",0)
  HaveSpellRES("SPDWD02") // Defensive Stance
  !CheckSpellState(Myself,DEFENSIVE_STANCE)
  Range(NearestEnemyOf(Myself),6)
  OR(2)
    CheckStatGT(LastSeenBy(Myself),6,LEVEL)
    NumCreatureGT([EVILCUTOFF],3)
  !GlobalTimerNotExpired("BD_Cast","LOCALS")
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
    SpellRES("SPDWD02",Myself) // Defensive Stance
    SetInterrupt(TRUE)
END

IF
  Global("ENDOFBG1","GLOBAL",0)
  Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
  ActionListEmpty()
  InParty(Myself)
  HaveSpell(BLADE_OFFENSIVE_SPIN) // SPCL521.SPL (Offensive Spin)
  !CheckSpellState(Myself,OFFENSIVE_SPIN)
  !CheckSpellState(Myself,DEFENSIVE_SPIN)
  Range(NearestEnemyOf(Myself),6)
  !GlobalTimerNotExpired("BD_Cast","LOCALS")
  See([EVILCUTOFF])
  OR(2)
    CheckStatGT(LastSeenBy(Myself),6,LEVEL)
    NumCreatureGT([EVILCUTOFF],3)
THEN
  RESPONSE #100
    SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
    Spell(Myself,BLADE_OFFENSIVE_SPIN) // SPCL521.SPL (Offensive Spin)
END

IF
  Global("ENDOFBG1","GLOBAL",0)
  Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
  !GlobalTimerNotExpired("BD_Cast","LOCALS")
  HaveSpell(ARCHER_CALL_SHOT) // SPCL121.SPL (Called Shot)
  !CheckSpellState(Myself,ARCHER_CALL_SHOT)
  IsWeaponRanged(Myself)
  !Range([EVILCUTOFF],5)
  OR(4)
    CheckStatGT([EVILCUTOFF],6,LEVEL)
    CheckStatGT(SecondNearest([EVILCUTOFF]),6,LEVEL)
    CheckStatGT(ThirdNearest([EVILCUTOFF]),6,LEVEL)
    NumCreatureGT([EVILCUTOFF],4)
THEN
  RESPONSE #100
    SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
    Spell(Myself,ARCHER_CALL_SHOT) // SPCL121.SPL (Called Shot)
END

IF
  Global("ENDOFBG1","GLOBAL",0)
  Global("BDAI_DISABLE_DEFENSIVE","LOCALS",0)
  ActionListEmpty()
  InParty(Myself)
  !GlobalTimerNotExpired("BD_Cast","LOCALS")
  !GlobalTimerNotExpired("BD_Support","LOCALS")
  HaveSpell(CLERIC_ARMOR_OF_FAITH) // SPPR111.SPL (Armor of Faith)
  See([EVILCUTOFF])
  OR(2)
    CheckStatGT(LastSeenBy(Myself),6,LEVEL)
    NumCreatureGT([EVILCUTOFF],3)
  !CheckSpellState(Myself,ARMOR_OF_FAITH)
  CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
    SetGlobalTimer("BD_Support","LOCALS",TWO_ROUNDS)
    Spell(Myself,CLERIC_ARMOR_OF_FAITH) // SPPR111.SPL (Armor of Faith)
END

IF
  Global("ENDOFBG1","GLOBAL",0)
  Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
  ActionListEmpty()
  InParty(Myself)
  !GlobalTimerNotExpired("BD_Cast","LOCALS")
  HaveSpellRES("SPIN103") // Draw Upon Holy Might
  See([EVILCUTOFF])
  OR(2)
    CheckStatGT(LastSeenBy(Myself),6,LEVEL)
    NumCreatureGT([EVILCUTOFF],3)
  !StateCheck(Myself,STATE_DRAWUPONHOLYMIGHT)
  CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
    SpellRES("SPIN103",Myself) // Draw Upon Holy Might
END

IF
  Global("ENDOFBG1","GLOBAL",0)
  Global("BDAI_DISABLE_DEFENSIVE","LOCALS",0)
  ActionListEmpty()
  InParty(Myself)
  !GlobalTimerNotExpired("BD_Cast","LOCALS")
  !GlobalTimerNotExpired("BD_Support","LOCALS")
  HaveSpell(CLERIC_DRAW_UPON_HOLY_MIGHT) // SPPR214.SPL (Draw Upon Holy Might)
  See([EVILCUTOFF])
  OR(2)
    CheckStatGT(LastSeenBy(Myself),6,LEVEL)
    NumCreatureGT([EVILCUTOFF],3)
  !StateCheck(Myself,STATE_DRAWUPONHOLYMIGHT)
  CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
    SetGlobalTimer("BD_Support","LOCALS",TWO_ROUNDS)
    Spell(Myself,CLERIC_DRAW_UPON_HOLY_MIGHT) // SPPR214.SPL (Draw Upon Holy Might)
END

IF
  Global("ENDOFBG1","GLOBAL",0)
  Global("BDAI_DISABLE_OFFENSIVE","LOCALS",0)
  ActionListEmpty()
  InParty(Myself)
  !GlobalTimerNotExpired("BD_Cast","LOCALS")
  HaveSpell(WIZARD_MONSTER_SUMMONING_2) // SPWI407.SPL (Monster Summoning II)
  OR(2)
    NumCreatureGT([EVILCUTOFF],4)
    CheckStatGT([EVILCUTOFF],6,LEVEL)
  CheckStatLT(Myself,50,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
    Spell(Myself,WIZARD_MONSTER_SUMMONING_2) // SPWI407.SPL (Monster Summoning II)
END

IF
  Global("ENDOFBG1","GLOBAL",0)
  Global("BDAI_DISABLE_ITEMS","LOCALS",0)
  ActionListEmpty()
  InParty(Myself)
  !GlobalTimerNotExpired("BD_Cast","LOCALS")
  !GlobalTimerNotExpired("BD_Wand","LOCALS")
  HasItem("WAND10",Myself) // Wand of Monster Summoning
  OR(2)
    NumCreatureGT([EVILCUTOFF],4)
    CheckStatGT([EVILCUTOFF],6,LEVEL)
THEN
  RESPONSE #100
    SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
    SetGlobalTimer("BD_Wand","LOCALS",THREE_ROUNDS)
    UseItem("WAND10",Myself) // Wand of Monster Summoning
    SetSequence(SEQ_CAST)
    DisplayString(Myself,266959) // *uses a wand*
END
>>>>>>>>

EXTEND_BOTTOM ~BDDEFAI.BCS~ ~.../BDDEFAI-eb.baf~
