COPY_LARGE + ~%patch_dir%/are/AR0002.ARE~ ~%patch_dir%/are/BG0002.ARE~
	~%patch_dir%/are/AR0004.ARE~ ~%patch_dir%/are/BG0004.ARE~
	~%patch_dir%/are/AR0005.ARE~ ~%patch_dir%/are/BG0005.ARE~
	~%patch_dir%/are/AR0006.ARE~ ~%patch_dir%/are/BG0006.ARE~
	~%patch_dir%/are/AR0007.ARE~ ~%patch_dir%/are/BG0007.ARE~
	~%patch_dir%/are/AR0008.ARE~ ~%patch_dir%/are/BG0008.ARE~
	~%patch_dir%/are/AR0009.ARE~ ~%patch_dir%/are/BG0009.ARE~
	~%patch_dir%/are/AR0010.ARE~ ~%patch_dir%/are/BG0010.ARE~
	~%patch_dir%/are/AR0011.ARE~ ~%patch_dir%/are/BG0011.ARE~
	~%patch_dir%/are/AR0012.ARE~ ~%patch_dir%/are/BG0012.ARE~
	~%patch_dir%/are/AR0013.ARE~ ~%patch_dir%/are/BG0013.ARE~
	~%patch_dir%/are/AR0014.ARE~ ~%patch_dir%/are/BG0014.ARE~
	~%patch_dir%/are/AR0015.ARE~ ~%patch_dir%/are/BG0015.ARE~
	~%patch_dir%/are/AR0016.ARE~ ~%patch_dir%/are/BG0016.ARE~
	~%patch_dir%/are/AR0017.ARE~ ~%patch_dir%/are/BG0017.ARE~
	~%patch_dir%/are/AR0018.ARE~ ~%patch_dir%/are/BG0018.ARE~
	~%patch_dir%/are/AR0019.ARE~ ~%patch_dir%/are/BG0019.ARE~
	~%patch_dir%/are/AR0020.ARE~ ~%patch_dir%/are/BG0020.ARE~
	~%patch_dir%/are/AR0021.ARE~ ~%patch_dir%/are/BG0021.ARE~
	~%patch_dir%/are/AR0100.ARE~ ~%patch_dir%/are/BG0100.ARE~
	~%patch_dir%/are/AR0101.ARE~ ~%patch_dir%/are/BG0101.ARE~
	~%patch_dir%/are/AR0102.ARE~ ~%patch_dir%/are/BG0102.ARE~
	~%patch_dir%/are/AR0103.ARE~ ~%patch_dir%/are/BG0103.ARE~
	~%patch_dir%/are/AR0104.ARE~ ~%patch_dir%/are/BG0104.ARE~
	~%patch_dir%/are/AR0105.ARE~ ~%patch_dir%/are/BG0105.ARE~
	~%patch_dir%/are/AR0106.ARE~ ~%patch_dir%/are/BG0106.ARE~
	~%patch_dir%/are/AR0107.ARE~ ~%patch_dir%/are/BG0107.ARE~
	~%patch_dir%/are/AR0108.ARE~ ~%patch_dir%/are/BG0108.ARE~
	~%patch_dir%/are/AR0109.ARE~ ~%patch_dir%/are/BG0109.ARE~
	~%patch_dir%/are/AR0110.ARE~ ~%patch_dir%/are/BG0110.ARE~
	~%patch_dir%/are/AR0111.ARE~ ~%patch_dir%/are/BG0111.ARE~
	~%patch_dir%/are/AR0112.ARE~ ~%patch_dir%/are/BG0112.ARE~
	~%patch_dir%/are/AR0114.ARE~ ~%patch_dir%/are/BG0114.ARE~
	~%patch_dir%/are/AR0115.ARE~ ~%patch_dir%/are/BG0115.ARE~
	~%patch_dir%/are/AR0116.ARE~ ~%patch_dir%/are/BG0116.ARE~
	~%patch_dir%/are/AR0117.ARE~ ~%patch_dir%/are/BG0117.ARE~
	~%patch_dir%/are/AR0118.ARE~ ~%patch_dir%/are/BG0118.ARE~
	~%patch_dir%/are/AR0119.ARE~ ~%patch_dir%/are/BG0119.ARE~
	~%patch_dir%/are/AR0120.ARE~ ~%patch_dir%/are/BG0120.ARE~
	~%patch_dir%/are/AR0121.ARE~ ~%patch_dir%/are/BG0121.ARE~
	~%patch_dir%/are/AR0123.ARE~ ~%patch_dir%/are/BG0123.ARE~
	~%patch_dir%/are/AR0125.ARE~ ~%patch_dir%/are/BG0125.ARE~
	~%patch_dir%/are/AR0126.ARE~ ~%patch_dir%/are/BG0126.ARE~
	~%patch_dir%/are/AR0127.ARE~ ~%patch_dir%/are/BG0127.ARE~
	~%patch_dir%/are/AR0128.ARE~ ~%patch_dir%/are/BG0128.ARE~
	~%patch_dir%/are/AR0129.ARE~ ~%patch_dir%/are/BG0129.ARE~
	~%patch_dir%/are/AR0130.ARE~ ~%patch_dir%/are/BG0130.ARE~
	~%patch_dir%/are/AR0131.ARE~ ~%patch_dir%/are/BG0131.ARE~
	~%patch_dir%/are/AR0132.ARE~ ~%patch_dir%/are/BG0132.ARE~
	~%patch_dir%/are/AR0133.ARE~ ~%patch_dir%/are/BG0133.ARE~
	~%patch_dir%/are/AR0134.ARE~ ~%patch_dir%/are/BG0134.ARE~
	~%patch_dir%/are/AR0135.ARE~ ~%patch_dir%/are/BG0135.ARE~
	~%patch_dir%/are/AR0136.ARE~ ~%patch_dir%/are/BG0136.ARE~
	~%patch_dir%/are/AR0137.ARE~ ~%patch_dir%/are/BG0137.ARE~
	~%patch_dir%/are/AR0138.ARE~ ~%patch_dir%/are/BG0138.ARE~
	~%patch_dir%/are/AR0139.ARE~ ~%patch_dir%/are/BG0139.ARE~
	~%patch_dir%/are/AR0140.ARE~ ~%patch_dir%/are/BG0140.ARE~
	~%patch_dir%/are/AR0141.ARE~ ~%patch_dir%/are/BG0141.ARE~
	~%patch_dir%/are/AR0142.ARE~ ~%patch_dir%/are/BG0142.ARE~
	~%patch_dir%/are/AR0143.ARE~ ~%patch_dir%/are/BG0143.ARE~
	~%patch_dir%/are/AR0144.ARE~ ~%patch_dir%/are/BG0144.ARE~
	~%patch_dir%/are/AR0145.ARE~ ~%patch_dir%/are/BG0145.ARE~
	~%patch_dir%/are/AR0146.ARE~ ~%patch_dir%/are/BG0146.ARE~
	~%patch_dir%/are/AR0148.ARE~ ~%patch_dir%/are/BG0148.ARE~
	~%patch_dir%/are/AR0149.ARE~ ~%patch_dir%/are/BG0149.ARE~
	~%patch_dir%/are/AR0150.ARE~ ~%patch_dir%/are/BG0150.ARE~
	~%patch_dir%/are/AR0151.ARE~ ~%patch_dir%/are/BG0151.ARE~
	~%patch_dir%/are/AR0152.ARE~ ~%patch_dir%/are/BG0152.ARE~
	~%patch_dir%/are/AR0153.ARE~ ~%patch_dir%/are/BG0153.ARE~
	~%patch_dir%/are/AR0154.ARE~ ~%patch_dir%/are/BG0154.ARE~
	~%patch_dir%/are/AR0155.ARE~ ~%patch_dir%/are/BG0155.ARE~
	~%patch_dir%/are/AR0156.ARE~ ~%patch_dir%/are/BG0156.ARE~
	~%patch_dir%/are/AR0157.ARE~ ~%patch_dir%/are/BG0157.ARE~
	~%patch_dir%/are/AR0158.ARE~ ~%patch_dir%/are/BG0158.ARE~
	~%patch_dir%/are/AR0159.ARE~ ~%patch_dir%/are/BG0159.ARE~
	~%patch_dir%/are/AR0160.ARE~ ~%patch_dir%/are/BG0160.ARE~
	~%patch_dir%/are/AR0161.ARE~ ~%patch_dir%/are/BG0161.ARE~
	~%patch_dir%/are/AR0162.ARE~ ~%patch_dir%/are/BG0162.ARE~
	~%patch_dir%/are/AR0163.ARE~ ~%patch_dir%/are/BG0163.ARE~
	~%patch_dir%/are/AR0164.ARE~ ~%patch_dir%/are/BG0164.ARE~
	~%patch_dir%/are/AR0165.ARE~ ~%patch_dir%/are/BG0165.ARE~
	~%patch_dir%/are/AR0166.ARE~ ~%patch_dir%/are/BG0166.ARE~
	~%patch_dir%/are/AR0167.ARE~ ~%patch_dir%/are/BG0167.ARE~
	~%patch_dir%/are/AR0168.ARE~ ~%patch_dir%/are/BG0168.ARE~
	~%patch_dir%/are/AR0169.ARE~ ~%patch_dir%/are/BG0169.ARE~
	~%patch_dir%/are/AR0170.ARE~ ~%patch_dir%/are/BG0170.ARE~
	~%patch_dir%/are/AR0171.ARE~ ~%patch_dir%/are/BG0171.ARE~
	~%patch_dir%/are/AR0200.ARE~ ~%patch_dir%/are/BG0200.ARE~
	~%patch_dir%/are/AR0224.ARE~ ~%patch_dir%/are/BG0224.ARE~
	~%patch_dir%/are/AR0225.ARE~ ~%patch_dir%/are/BG0225.ARE~
	~%patch_dir%/are/AR0226.ARE~ ~%patch_dir%/are/BG0226.ARE~
	~%patch_dir%/are/AR0300.ARE~ ~%patch_dir%/are/BG0300.ARE~
	~%patch_dir%/are/AR0302.ARE~ ~%patch_dir%/are/BG0302.ARE~
	~%patch_dir%/are/AR0303.ARE~ ~%patch_dir%/are/BG0303.ARE~
	~%patch_dir%/are/AR0304.ARE~ ~%patch_dir%/are/BG0304.ARE~
	~%patch_dir%/are/AR0305.ARE~ ~%patch_dir%/are/BG0305.ARE~
	~%patch_dir%/are/AR0306.ARE~ ~%patch_dir%/are/BG0306.ARE~
	~%patch_dir%/are/AR0307.ARE~ ~%patch_dir%/are/BG0307.ARE~
	~%patch_dir%/are/AR0308.ARE~ ~%patch_dir%/are/BG0308.ARE~
	~%patch_dir%/are/AR0400.ARE~ ~%patch_dir%/are/BG0400.ARE~
	~%patch_dir%/are/AR0401.ARE~ ~%patch_dir%/are/BG0401.ARE~
	~%patch_dir%/are/AR0500.ARE~ ~%patch_dir%/are/BG0500.ARE~
	~%patch_dir%/are/AR0501.ARE~ ~%patch_dir%/are/BG0501.ARE~
	~%patch_dir%/are/AR0502.ARE~ ~%patch_dir%/are/BG0502.ARE~
	~%patch_dir%/are/AR0503.ARE~ ~%patch_dir%/are/BG0503.ARE~
	~%patch_dir%/are/AR0504.ARE~ ~%patch_dir%/are/BG0504.ARE~
	~%patch_dir%/are/AR0505.ARE~ ~%patch_dir%/are/BG0505.ARE~
	~%patch_dir%/are/AR0506.ARE~ ~%patch_dir%/are/BG0506.ARE~
	~%patch_dir%/are/AR0507.ARE~ ~%patch_dir%/are/BG0507.ARE~
	~%patch_dir%/are/AR0508.ARE~ ~%patch_dir%/are/BG0508.ARE~
	~%patch_dir%/are/AR0509.ARE~ ~%patch_dir%/are/BG0509.ARE~
	~%patch_dir%/are/AR0510.ARE~ ~%patch_dir%/are/BG0510.ARE~
	~%patch_dir%/are/AR0511.ARE~ ~%patch_dir%/are/BG0511.ARE~
	~%patch_dir%/are/AR0512.ARE~ ~%patch_dir%/are/BG0512.ARE~
	~%patch_dir%/are/AR0513.ARE~ ~%patch_dir%/are/BG0513.ARE~
	~%patch_dir%/are/AR0514.ARE~ ~%patch_dir%/are/BG0514.ARE~
	~%patch_dir%/are/AR0515.ARE~ ~%patch_dir%/are/BG0515.ARE~
	~%patch_dir%/are/AR0516.ARE~ ~%patch_dir%/are/BG0516.ARE~
	~%patch_dir%/are/AR0600.ARE~ ~%patch_dir%/are/BG0600.ARE~
	~%patch_dir%/are/AR0601.ARE~ ~%patch_dir%/are/BG0601.ARE~
	~%patch_dir%/are/AR0602.ARE~ ~%patch_dir%/are/BG0602.ARE~
	~%patch_dir%/are/AR0603.ARE~ ~%patch_dir%/are/BG0603.ARE~
	~%patch_dir%/are/AR0606.ARE~ ~%patch_dir%/are/BG0606.ARE~
	~%patch_dir%/are/AR0607.ARE~ ~%patch_dir%/are/BG0607.ARE~
	~%patch_dir%/are/AR0608.ARE~ ~%patch_dir%/are/BG0608.ARE~
	~%patch_dir%/are/AR0609.ARE~ ~%patch_dir%/are/BG0609.ARE~
	~%patch_dir%/are/AR0611.ARE~ ~%patch_dir%/are/BG0611.ARE~
	~%patch_dir%/are/AR0612.ARE~ ~%patch_dir%/are/BG0612.ARE~
	~%patch_dir%/are/AR0613.ARE~ ~%patch_dir%/are/BG0613.ARE~
	~%patch_dir%/are/AR0614.ARE~ ~%patch_dir%/are/BG0614.ARE~
	~%patch_dir%/are/AR0615.ARE~ ~%patch_dir%/are/BG0615.ARE~
	~%patch_dir%/are/AR0616.ARE~ ~%patch_dir%/are/BG0616.ARE~
	~%patch_dir%/are/AR0617.ARE~ ~%patch_dir%/are/BG0617.ARE~
	~%patch_dir%/are/AR0618.ARE~ ~%patch_dir%/are/BG0618.ARE~
	~%patch_dir%/are/AR0619.ARE~ ~%patch_dir%/are/BG0619.ARE~
	~%patch_dir%/are/AR0620.ARE~ ~%patch_dir%/are/BG0620.ARE~
	~%patch_dir%/are/AR0621.ARE~ ~%patch_dir%/are/BG0621.ARE~
	~%patch_dir%/are/AR0700.ARE~ ~%patch_dir%/are/BG0700.ARE~
	~%patch_dir%/are/AR0702.ARE~ ~%patch_dir%/are/BG0702.ARE~
	~%patch_dir%/are/AR0703.ARE~ ~%patch_dir%/are/BG0703.ARE~
	~%patch_dir%/are/AR0704.ARE~ ~%patch_dir%/are/BG0704.ARE~
	~%patch_dir%/are/AR0705.ARE~ ~%patch_dir%/are/BG0705.ARE~
	~%patch_dir%/are/AR0706.ARE~ ~%patch_dir%/are/BG0706.ARE~
	~%patch_dir%/are/AR0707.ARE~ ~%patch_dir%/are/BG0707.ARE~
	~%patch_dir%/are/AR0708.ARE~ ~%patch_dir%/are/BG0708.ARE~
	~%patch_dir%/are/AR0709.ARE~ ~%patch_dir%/are/BG0709.ARE~
	~%patch_dir%/are/AR0710.ARE~ ~%patch_dir%/are/BG0710.ARE~
	~%patch_dir%/are/AR0711.ARE~ ~%patch_dir%/are/BG0711.ARE~
	~%patch_dir%/are/AR0712.ARE~ ~%patch_dir%/are/BG0712.ARE~
	~%patch_dir%/are/AR0713.ARE~ ~%patch_dir%/are/BG0713.ARE~
	~%patch_dir%/are/AR0714.ARE~ ~%patch_dir%/are/BG0714.ARE~
	~%patch_dir%/are/AR0715.ARE~ ~%patch_dir%/are/BG0715.ARE~
	~%patch_dir%/are/AR0716.ARE~ ~%patch_dir%/are/BG0716.ARE~
	~%patch_dir%/are/AR0717.ARE~ ~%patch_dir%/are/BG0717.ARE~
	~%patch_dir%/are/AR0718.ARE~ ~%patch_dir%/are/BG0718.ARE~
	~%patch_dir%/are/AR0719.ARE~ ~%patch_dir%/are/BG0719.ARE~
	~%patch_dir%/are/AR0720.ARE~ ~%patch_dir%/are/BG0720.ARE~
	~%patch_dir%/are/AR0721.ARE~ ~%patch_dir%/are/BG0721.ARE~
	~%patch_dir%/are/AR0722.ARE~ ~%patch_dir%/are/BG0722.ARE~
	~%patch_dir%/are/AR0723.ARE~ ~%patch_dir%/are/BG0723.ARE~
	~%patch_dir%/are/AR0724.ARE~ ~%patch_dir%/are/BG0724.ARE~
	~%patch_dir%/are/AR0725.ARE~ ~%patch_dir%/are/BG0725.ARE~
	~%patch_dir%/are/AR0726.ARE~ ~%patch_dir%/are/BG0726.ARE~
	~%patch_dir%/are/AR0800.ARE~ ~%patch_dir%/are/BG0800.ARE~
	~%patch_dir%/are/AR0801.ARE~ ~%patch_dir%/are/BG0801.ARE~
	~%patch_dir%/are/AR0802.ARE~ ~%patch_dir%/are/BG0802.ARE~
	~%patch_dir%/are/AR0803.ARE~ ~%patch_dir%/are/BG0803.ARE~
	~%patch_dir%/are/AR0804.ARE~ ~%patch_dir%/are/BG0804.ARE~
	~%patch_dir%/are/AR0805.ARE~ ~%patch_dir%/are/BG0805.ARE~
	~%patch_dir%/are/AR0806.ARE~ ~%patch_dir%/are/BG0806.ARE~
	~%patch_dir%/are/AR0807.ARE~ ~%patch_dir%/are/BG0807.ARE~
	~%patch_dir%/are/AR0808.ARE~ ~%patch_dir%/are/BG0808.ARE~
	~%patch_dir%/are/AR0809.ARE~ ~%patch_dir%/are/BG0809.ARE~
	~%patch_dir%/are/AR0810.ARE~ ~%patch_dir%/are/BG0810.ARE~
	~%patch_dir%/are/AR0811.ARE~ ~%patch_dir%/are/BG0811.ARE~
	~%patch_dir%/are/AR0812.ARE~ ~%patch_dir%/are/BG0812.ARE~
	~%patch_dir%/are/AR0813.ARE~ ~%patch_dir%/are/BG0813.ARE~
	~%patch_dir%/are/AR0814.ARE~ ~%patch_dir%/are/BG0814.ARE~
	~%patch_dir%/are/AR0900.ARE~ ~%patch_dir%/are/BG0900.ARE~
	~%patch_dir%/are/AR0901.ARE~ ~%patch_dir%/are/BG0901.ARE~
	~%patch_dir%/are/AR1000.ARE~ ~%patch_dir%/are/BG1000.ARE~
	~%patch_dir%/are/AR1001.ARE~ ~%patch_dir%/are/BG1001.ARE~
	~%patch_dir%/are/AR1002.ARE~ ~%patch_dir%/are/BG1002.ARE~
	~%patch_dir%/are/AR1003.ARE~ ~%patch_dir%/are/BG1003.ARE~
	~%patch_dir%/are/AR1004.ARE~ ~%patch_dir%/are/BG1004.ARE~
	~%patch_dir%/are/AR1005.ARE~ ~%patch_dir%/are/BG1005.ARE~
	~%patch_dir%/are/AR1006.ARE~ ~%patch_dir%/are/BG1006.ARE~
	~%patch_dir%/are/AR1007.ARE~ ~%patch_dir%/are/BG1007.ARE~
	~%patch_dir%/are/AR1008.ARE~ ~%patch_dir%/are/BG1008.ARE~
	~%patch_dir%/are/AR1009.ARE~ ~%patch_dir%/are/BG1009.ARE~
	~%patch_dir%/are/AR1010.ARE~ ~%patch_dir%/are/BG1010.ARE~
	~%patch_dir%/are/AR1100.ARE~ ~%patch_dir%/are/BG1100.ARE~
	~%patch_dir%/are/AR1101.ARE~ ~%patch_dir%/are/BG1101.ARE~
	~%patch_dir%/are/AR1102.ARE~ ~%patch_dir%/are/BG1102.ARE~
	~%patch_dir%/are/AR1103.ARE~ ~%patch_dir%/are/BG1103.ARE~
	~%patch_dir%/are/AR1104.ARE~ ~%patch_dir%/are/BG1104.ARE~
	~%patch_dir%/are/AR1105.ARE~ ~%patch_dir%/are/BG1105.ARE~
	~%patch_dir%/are/AR1106.ARE~ ~%patch_dir%/are/BG1106.ARE~
	~%patch_dir%/are/AR1107.ARE~ ~%patch_dir%/are/BG1107.ARE~
	~%patch_dir%/are/AR1108.ARE~ ~%patch_dir%/are/BG1108.ARE~
	~%patch_dir%/are/AR1109.ARE~ ~%patch_dir%/are/BG1109.ARE~
	~%patch_dir%/are/AR1110.ARE~ ~%patch_dir%/are/BG1110.ARE~
	~%patch_dir%/are/AR1111.ARE~ ~%patch_dir%/are/BG1111.ARE~
	~%patch_dir%/are/AR1112.ARE~ ~%patch_dir%/are/BG1112.ARE~
	~%patch_dir%/are/AR1113.ARE~ ~%patch_dir%/are/BG1113.ARE~
	~%patch_dir%/are/AR1114.ARE~ ~%patch_dir%/are/BG1114.ARE~
	~%patch_dir%/are/AR1115.ARE~ ~%patch_dir%/are/BG1115.ARE~
	~%patch_dir%/are/AR1116.ARE~ ~%patch_dir%/are/BG1116.ARE~
	~%patch_dir%/are/AR1117.ARE~ ~%patch_dir%/are/BG1117.ARE~
	~%patch_dir%/are/AR1200.ARE~ ~%patch_dir%/are/BG1200.ARE~
	~%patch_dir%/are/AR1201.ARE~ ~%patch_dir%/are/BG1201.ARE~
	~%patch_dir%/are/AR1202.ARE~ ~%patch_dir%/are/BG1202.ARE~
	~%patch_dir%/are/AR1203.ARE~ ~%patch_dir%/are/BG1203.ARE~
	~%patch_dir%/are/AR1204.ARE~ ~%patch_dir%/are/BG1204.ARE~
	~%patch_dir%/are/AR1205.ARE~ ~%patch_dir%/are/BG1205.ARE~
	~%patch_dir%/are/AR1206.ARE~ ~%patch_dir%/are/BG1206.ARE~
	~%patch_dir%/are/AR1207.ARE~ ~%patch_dir%/are/BG1207.ARE~
	~%patch_dir%/are/AR1208.ARE~ ~%patch_dir%/are/BG1208.ARE~
	~%patch_dir%/are/AR1209.ARE~ ~%patch_dir%/are/BG1209.ARE~
	~%patch_dir%/are/AR1210.ARE~ ~%patch_dir%/are/BG1210.ARE~
	~%patch_dir%/are/AR1211.ARE~ ~%patch_dir%/are/BG1211.ARE~
	~%patch_dir%/are/AR1212.ARE~ ~%patch_dir%/are/BG1212.ARE~
	~%patch_dir%/are/AR1213.ARE~ ~%patch_dir%/are/BG1213.ARE~
	~%patch_dir%/are/AR1214.ARE~ ~%patch_dir%/are/BG1214.ARE~
	~%patch_dir%/are/AR1215.ARE~ ~%patch_dir%/are/BG1215.ARE~
	~%patch_dir%/are/AR1300.ARE~ ~%patch_dir%/are/BG1300.ARE~
	~%patch_dir%/are/AR1301.ARE~ ~%patch_dir%/are/BG1301.ARE~
	~%patch_dir%/are/AR1302.ARE~ ~%patch_dir%/are/BG1302.ARE~
	~%patch_dir%/are/AR1303.ARE~ ~%patch_dir%/are/BG1303.ARE~
	~%patch_dir%/are/AR1304.ARE~ ~%patch_dir%/are/BG1304.ARE~
	~%patch_dir%/are/AR1305.ARE~ ~%patch_dir%/are/BG1305.ARE~
	~%patch_dir%/are/AR1306.ARE~ ~%patch_dir%/are/BG1306.ARE~
	~%patch_dir%/are/AR1307.ARE~ ~%patch_dir%/are/BG1307.ARE~
	~%patch_dir%/are/AR1308.ARE~ ~%patch_dir%/are/BG1308.ARE~
	~%patch_dir%/are/AR1309.ARE~ ~%patch_dir%/are/BG1309.ARE~
	~%patch_dir%/are/AR1310.ARE~ ~%patch_dir%/are/BG1310.ARE~
	~%patch_dir%/are/AR1311.ARE~ ~%patch_dir%/are/BG1311.ARE~
	~%patch_dir%/are/AR1312.ARE~ ~%patch_dir%/are/BG1312.ARE~
	~%patch_dir%/are/AR1313.ARE~ ~%patch_dir%/are/BG1313.ARE~
	~%patch_dir%/are/AR1314.ARE~ ~%patch_dir%/are/BG1314.ARE~
	~%patch_dir%/are/AR1315.ARE~ ~%patch_dir%/are/BG1315.ARE~
	~%patch_dir%/are/AR1316.ARE~ ~%patch_dir%/are/BG1316.ARE~
	~%patch_dir%/are/AR1317.ARE~ ~%patch_dir%/are/BG1317.ARE~
	~%patch_dir%/are/AR1320.ARE~ ~%patch_dir%/are/BG1320.ARE~
	~%patch_dir%/are/AR1400.ARE~ ~%patch_dir%/are/BG1400.ARE~
	~%patch_dir%/are/AR1401.ARE~ ~%patch_dir%/are/BG1401.ARE~
	~%patch_dir%/are/AR1402.ARE~ ~%patch_dir%/are/BG1402.ARE~
	~%patch_dir%/are/AR1403.ARE~ ~%patch_dir%/are/BG1403.ARE~
	~%patch_dir%/are/AR1404.ARE~ ~%patch_dir%/are/BG1404.ARE~
	~%patch_dir%/are/AR1500.ARE~ ~%patch_dir%/are/BG1500.ARE~
	~%patch_dir%/are/AR1501.ARE~ ~%patch_dir%/are/BG1501.ARE~
	~%patch_dir%/are/AR1502.ARE~ ~%patch_dir%/are/BG1502.ARE~
	~%patch_dir%/are/AR1503.ARE~ ~%patch_dir%/are/BG1503.ARE~
	~%patch_dir%/are/AR1504.ARE~ ~%patch_dir%/are/BG1504.ARE~
	~%patch_dir%/are/AR1505.ARE~ ~%patch_dir%/are/BG1505.ARE~
	~%patch_dir%/are/AR1600.ARE~ ~%patch_dir%/are/BG1600.ARE~
	~%patch_dir%/are/AR1601.ARE~ ~%patch_dir%/are/BG1601.ARE~
	~%patch_dir%/are/AR1602.ARE~ ~%patch_dir%/are/BG1602.ARE~
	~%patch_dir%/are/AR1603.ARE~ ~%patch_dir%/are/BG1603.ARE~
	~%patch_dir%/are/AR1700.ARE~ ~%patch_dir%/are/BG1700.ARE~
	~%patch_dir%/are/AR1800.ARE~ ~%patch_dir%/are/BG1800.ARE~
	~%patch_dir%/are/AR1801.ARE~ ~%patch_dir%/are/BG1801.ARE~
	~%patch_dir%/are/AR1801A.ARE~ ~%patch_dir%/are/BG1801A.ARE~
	~%patch_dir%/are/AR1802.ARE~ ~%patch_dir%/are/BG1802.ARE~
	~%patch_dir%/are/AR1803.ARE~ ~%patch_dir%/are/BG1803.ARE~
	~%patch_dir%/are/AR1804.ARE~ ~%patch_dir%/are/BG1804.ARE~
	~%patch_dir%/are/AR1805.ARE~ ~%patch_dir%/are/BG1805.ARE~
	~%patch_dir%/are/AR1806.ARE~ ~%patch_dir%/are/BG1806.ARE~
	~%patch_dir%/are/AR1807.ARE~ ~%patch_dir%/are/BG1807.ARE~
	~%patch_dir%/are/AR1808.ARE~ ~%patch_dir%/are/BG1808.ARE~
	~%patch_dir%/are/AR1809.ARE~ ~%patch_dir%/are/BG1809.ARE~
	~%patch_dir%/are/AR1900.ARE~ ~%patch_dir%/are/BG1900.ARE~
	~%patch_dir%/are/AR1901.ARE~ ~%patch_dir%/are/BG1901.ARE~
	~%patch_dir%/are/AR1902.ARE~ ~%patch_dir%/are/BG1902.ARE~
	~%patch_dir%/are/AR1903.ARE~ ~%patch_dir%/are/BG1903.ARE~
	~%patch_dir%/are/AR1904.ARE~ ~%patch_dir%/are/BG1904.ARE~
	~%patch_dir%/are/AR1905.ARE~ ~%patch_dir%/are/BG1905.ARE~
	~%patch_dir%/are/AR1906.ARE~ ~%patch_dir%/are/BG1906.ARE~
	~%patch_dir%/are/AR1907.ARE~ ~%patch_dir%/are/BG1907.ARE~
	~%patch_dir%/are/AR2000.ARE~ ~%patch_dir%/are/BG2000.ARE~
	~%patch_dir%/are/AR2001.ARE~ ~%patch_dir%/are/BG2001.ARE~
	~%patch_dir%/are/AR2002.ARE~ ~%patch_dir%/are/BG2002.ARE~
	~%patch_dir%/are/AR2003.ARE~ ~%patch_dir%/are/BG2003.ARE~
	~%patch_dir%/are/AR2004.ARE~ ~%patch_dir%/are/BG2004.ARE~
	~%patch_dir%/are/AR2005.ARE~ ~%patch_dir%/are/BG2005.ARE~
	~%patch_dir%/are/AR2006.ARE~ ~%patch_dir%/are/BG2006.ARE~
	~%patch_dir%/are/AR2007.ARE~ ~%patch_dir%/are/BG2007.ARE~
	~%patch_dir%/are/AR2008.ARE~ ~%patch_dir%/are/BG2008.ARE~
	~%patch_dir%/are/AR2009.ARE~ ~%patch_dir%/are/BG2009.ARE~
	~%patch_dir%/are/AR2010.ARE~ ~%patch_dir%/are/BG2010.ARE~
	~%patch_dir%/are/AR2011.ARE~ ~%patch_dir%/are/BG2011.ARE~
	~%patch_dir%/are/AR2012.ARE~ ~%patch_dir%/are/BG2012.ARE~
	~%patch_dir%/are/AR2100.ARE~ ~%patch_dir%/are/BG2100.ARE~
	~%patch_dir%/are/AR2101.ARE~ ~%patch_dir%/are/BG2101.ARE~
	~%patch_dir%/are/AR2200.ARE~ ~%patch_dir%/are/BG2200.ARE~
	~%patch_dir%/are/AR2215.ARE~ ~%patch_dir%/are/BG2215.ARE~
	~%patch_dir%/are/AR2300.ARE~ ~%patch_dir%/are/BG2300.ARE~
	~%patch_dir%/are/AR2301.ARE~ ~%patch_dir%/are/BG2301.ARE~
	~%patch_dir%/are/AR2302.ARE~ ~%patch_dir%/are/BG2302.ARE~
	~%patch_dir%/are/AR2303.ARE~ ~%patch_dir%/are/BG2303.ARE~
	~%patch_dir%/are/AR2304.ARE~ ~%patch_dir%/are/BG2304.ARE~
	~%patch_dir%/are/AR2305.ARE~ ~%patch_dir%/are/BG2305.ARE~
	~%patch_dir%/are/AR2306.ARE~ ~%patch_dir%/are/BG2306.ARE~
	~%patch_dir%/are/AR2400.ARE~ ~%patch_dir%/are/BG2400.ARE~
	~%patch_dir%/are/AR2600.ARE~ ~%patch_dir%/are/BG2600.ARE~
	~%patch_dir%/are/AR2602.ARE~ ~%patch_dir%/are/BG2602.ARE~
	~%patch_dir%/are/AR2605.ARE~ ~%patch_dir%/are/BG2605.ARE~
	~%patch_dir%/are/AR2606.ARE~ ~%patch_dir%/are/BG2606.ARE~
	~%patch_dir%/are/AR2607.ARE~ ~%patch_dir%/are/BG2607.ARE~
	~%patch_dir%/are/AR2608.ARE~ ~%patch_dir%/are/BG2608.ARE~
	~%patch_dir%/are/AR2609.ARE~ ~%patch_dir%/are/BG2609.ARE~
	~%patch_dir%/are/AR2610.ARE~ ~%patch_dir%/are/BG2610.ARE~
	~%patch_dir%/are/AR2611.ARE~ ~%patch_dir%/are/BG2611.ARE~
	~%patch_dir%/are/AR2612.ARE~ ~%patch_dir%/are/BG2612.ARE~
	~%patch_dir%/are/AR2613.ARE~ ~%patch_dir%/are/BG2613.ARE~
	~%patch_dir%/are/AR2614.ARE~ ~%patch_dir%/are/BG2614.ARE~
	~%patch_dir%/are/AR2615.ARE~ ~%patch_dir%/are/BG2615.ARE~
	~%patch_dir%/are/AR2616.ARE~ ~%patch_dir%/are/BG2616.ARE~
	~%patch_dir%/are/AR2617.ARE~ ~%patch_dir%/are/BG2617.ARE~
	~%patch_dir%/are/AR2618.ARE~ ~%patch_dir%/are/BG2618.ARE~
	~%patch_dir%/are/AR2619.ARE~ ~%patch_dir%/are/BG2619.ARE~
	~%patch_dir%/are/AR2622.ARE~ ~%patch_dir%/are/BG2622.ARE~
	~%patch_dir%/are/AR2623.ARE~ ~%patch_dir%/are/BG2623.ARE~
	~%patch_dir%/are/AR2624.ARE~ ~%patch_dir%/are/BG2624.ARE~
	~%patch_dir%/are/AR2626.ARE~ ~%patch_dir%/are/BG2626.ARE~
	~%patch_dir%/are/AR2627.ARE~ ~%patch_dir%/are/BG2627.ARE~
	~%patch_dir%/are/AR2628.ARE~ ~%patch_dir%/are/BG2628.ARE~
	~%patch_dir%/are/AR2629.ARE~ ~%patch_dir%/are/BG2629.ARE~
	~%patch_dir%/are/AR2630.ARE~ ~%patch_dir%/are/BG2630.ARE~
	~%patch_dir%/are/AR2631.ARE~ ~%patch_dir%/are/BG2631.ARE~
	~%patch_dir%/are/AR2632.ARE~ ~%patch_dir%/are/BG2632.ARE~
	~%patch_dir%/are/AR2633.ARE~ ~%patch_dir%/are/BG2633.ARE~
	~%patch_dir%/are/AR2634.ARE~ ~%patch_dir%/are/BG2634.ARE~
	~%patch_dir%/are/AR2635.ARE~ ~%patch_dir%/are/BG2635.ARE~
	~%patch_dir%/are/AR2636.ARE~ ~%patch_dir%/are/BG2636.ARE~
	~%patch_dir%/are/AR2637.ARE~ ~%patch_dir%/are/BG2637.ARE~
	~%patch_dir%/are/AR2638.ARE~ ~%patch_dir%/are/BG2638.ARE~
	~%patch_dir%/are/AR2639.ARE~ ~%patch_dir%/are/BG2639.ARE~
	~%patch_dir%/are/AR2640.ARE~ ~%patch_dir%/are/BG2640.ARE~
	~%patch_dir%/are/AR2641.ARE~ ~%patch_dir%/are/BG2641.ARE~
	~%patch_dir%/are/AR2642.ARE~ ~%patch_dir%/are/BG2642.ARE~
	~%patch_dir%/are/AR2643.ARE~ ~%patch_dir%/are/BG2643.ARE~
	~%patch_dir%/are/AR2700.ARE~ ~%patch_dir%/are/BG2700.ARE~
	~%patch_dir%/are/AR2800.ARE~ ~%patch_dir%/are/BG2800.ARE~
	~%patch_dir%/are/AR2900.ARE~ ~%patch_dir%/are/BG2900.ARE~
	~%patch_dir%/are/AR3000.ARE~ ~%patch_dir%/are/BG3000.ARE~
	~%patch_dir%/are/AR3100.ARE~ ~%patch_dir%/are/BG3100.ARE~
	~%patch_dir%/are/AR3200.ARE~ ~%patch_dir%/are/BG3200.ARE~
	~%patch_dir%/are/AR3201.ARE~ ~%patch_dir%/are/BG3201.ARE~
	~%patch_dir%/are/AR3202.ARE~ ~%patch_dir%/are/BG3202.ARE~
	~%patch_dir%/are/AR3300.ARE~ ~%patch_dir%/are/BG3300.ARE~
	~%patch_dir%/are/AR3301.ARE~ ~%patch_dir%/are/BG3301.ARE~
	~%patch_dir%/are/AR3302.ARE~ ~%patch_dir%/are/BG3302.ARE~
	~%patch_dir%/are/AR3303.ARE~ ~%patch_dir%/are/BG3303.ARE~
	~%patch_dir%/are/AR3304.ARE~ ~%patch_dir%/are/BG3304.ARE~
	~%patch_dir%/are/AR3305.ARE~ ~%patch_dir%/are/BG3305.ARE~
	~%patch_dir%/are/AR3306.ARE~ ~%patch_dir%/are/BG3306.ARE~
	~%patch_dir%/are/AR3307.ARE~ ~%patch_dir%/are/BG3307.ARE~
	~%patch_dir%/are/AR3308.ARE~ ~%patch_dir%/are/BG3308.ARE~
	~%patch_dir%/are/AR3309.ARE~ ~%patch_dir%/are/BG3309.ARE~
	~%patch_dir%/are/AR3310.ARE~ ~%patch_dir%/are/BG3310.ARE~
	~%patch_dir%/are/AR3311.ARE~ ~%patch_dir%/are/BG3311.ARE~
	~%patch_dir%/are/AR3312.ARE~ ~%patch_dir%/are/BG3312.ARE~
	~%patch_dir%/are/AR3313.ARE~ ~%patch_dir%/are/BG3313.ARE~
	~%patch_dir%/are/AR3314.ARE~ ~%patch_dir%/are/BG3314.ARE~
	~%patch_dir%/are/AR3315.ARE~ ~%patch_dir%/are/BG3315.ARE~
	~%patch_dir%/are/AR3316.ARE~ ~%patch_dir%/are/BG3316.ARE~
	~%patch_dir%/are/AR3317.ARE~ ~%patch_dir%/are/BG3317.ARE~
	~%patch_dir%/are/AR3318.ARE~ ~%patch_dir%/are/BG3318.ARE~
	~%patch_dir%/are/AR3319.ARE~ ~%patch_dir%/are/BG3319.ARE~
	~%patch_dir%/are/AR3320.ARE~ ~%patch_dir%/are/BG3320.ARE~
	~%patch_dir%/are/AR3321.ARE~ ~%patch_dir%/are/BG3321.ARE~
	~%patch_dir%/are/AR3322.ARE~ ~%patch_dir%/are/BG3322.ARE~
	~%patch_dir%/are/AR3323.ARE~ ~%patch_dir%/are/BG3323.ARE~
	~%patch_dir%/are/AR3324.ARE~ ~%patch_dir%/are/BG3324.ARE~
	~%patch_dir%/are/AR3325.ARE~ ~%patch_dir%/are/BG3325.ARE~
	~%patch_dir%/are/AR3326.ARE~ ~%patch_dir%/are/BG3326.ARE~
	~%patch_dir%/are/AR3327.ARE~ ~%patch_dir%/are/BG3327.ARE~
	~%patch_dir%/are/AR3328.ARE~ ~%patch_dir%/are/BG3328.ARE~
	~%patch_dir%/are/AR3329.ARE~ ~%patch_dir%/are/BG3329.ARE~
	~%patch_dir%/are/AR3330.ARE~ ~%patch_dir%/are/BG3330.ARE~
	~%patch_dir%/are/AR3331.ARE~ ~%patch_dir%/are/BG3331.ARE~
	~%patch_dir%/are/AR3332.ARE~ ~%patch_dir%/are/BG3332.ARE~
	~%patch_dir%/are/AR3333.ARE~ ~%patch_dir%/are/BG3333.ARE~
	~%patch_dir%/are/AR3334.ARE~ ~%patch_dir%/are/BG3334.ARE~
	~%patch_dir%/are/AR3335.ARE~ ~%patch_dir%/are/BG3335.ARE~
	~%patch_dir%/are/AR3336.ARE~ ~%patch_dir%/are/BG3336.ARE~
	~%patch_dir%/are/AR3337.ARE~ ~%patch_dir%/are/BG3337.ARE~
	~%patch_dir%/are/AR3338.ARE~ ~%patch_dir%/are/BG3338.ARE~
	~%patch_dir%/are/AR3339.ARE~ ~%patch_dir%/are/BG3339.ARE~
	~%patch_dir%/are/AR3340.ARE~ ~%patch_dir%/are/BG3340.ARE~
	~%patch_dir%/are/AR3341.ARE~ ~%patch_dir%/are/BG3341.ARE~
	~%patch_dir%/are/AR3342.ARE~ ~%patch_dir%/are/BG3342.ARE~
	~%patch_dir%/are/AR3343.ARE~ ~%patch_dir%/are/BG3343.ARE~
	~%patch_dir%/are/AR3344.ARE~ ~%patch_dir%/are/BG3344.ARE~
	~%patch_dir%/are/AR3345.ARE~ ~%patch_dir%/are/BG3345.ARE~
	~%patch_dir%/are/AR3346.ARE~ ~%patch_dir%/are/BG3346.ARE~
	~%patch_dir%/are/AR3347.ARE~ ~%patch_dir%/are/BG3347.ARE~
	~%patch_dir%/are/AR3348.ARE~ ~%patch_dir%/are/BG3348.ARE~
	~%patch_dir%/are/AR3349.ARE~ ~%patch_dir%/are/BG3349.ARE~
	~%patch_dir%/are/AR3350.ARE~ ~%patch_dir%/are/BG3350.ARE~
	~%patch_dir%/are/AR3351.ARE~ ~%patch_dir%/are/BG3351.ARE~
	~%patch_dir%/are/AR3352.ARE~ ~%patch_dir%/are/BG3352.ARE~
	~%patch_dir%/are/AR3353.ARE~ ~%patch_dir%/are/BG3353.ARE~
	~%patch_dir%/are/AR3354.ARE~ ~%patch_dir%/are/BG3354.ARE~
	~%patch_dir%/are/AR3355.ARE~ ~%patch_dir%/are/BG3355.ARE~
	~%patch_dir%/are/AR3356.ARE~ ~%patch_dir%/are/BG3356.ARE~
	~%patch_dir%/are/AR3357.ARE~ ~%patch_dir%/are/BG3357.ARE~
	~%patch_dir%/are/AR3400.ARE~ ~%patch_dir%/are/BG3400.ARE~
	~%patch_dir%/are/AR3401.ARE~ ~%patch_dir%/are/BG3401.ARE~
	~%patch_dir%/are/AR3402.ARE~ ~%patch_dir%/are/BG3402.ARE~
	~%patch_dir%/are/AR3500.ARE~ ~%patch_dir%/are/BG3500.ARE~
	~%patch_dir%/are/AR3600.ARE~ ~%patch_dir%/are/BG3600.ARE~
	~%patch_dir%/are/AR3601.ARE~ ~%patch_dir%/are/BG3601.ARE~
	~%patch_dir%/are/AR3700.ARE~ ~%patch_dir%/are/BG3700.ARE~
	~%patch_dir%/are/AR3800.ARE~ ~%patch_dir%/are/BG3800.ARE~
	~%patch_dir%/are/AR3802.ARE~ ~%patch_dir%/are/BG3802.ARE~
	~%patch_dir%/are/AR3900.ARE~ ~%patch_dir%/are/BG3900.ARE~
	~%patch_dir%/are/AR3901.ARE~ ~%patch_dir%/are/BG3901.ARE~
	~%patch_dir%/are/AR4000.ARE~ ~%patch_dir%/are/BG4000.ARE~
	~%patch_dir%/are/AR4001.ARE~ ~%patch_dir%/are/BG4001.ARE~
	~%patch_dir%/are/AR4002.ARE~ ~%patch_dir%/are/BG4002.ARE~
	~%patch_dir%/are/AR4003.ARE~ ~%patch_dir%/are/BG4003.ARE~
	~%patch_dir%/are/AR4004.ARE~ ~%patch_dir%/are/BG4004.ARE~
	~%patch_dir%/are/AR4005.ARE~ ~%patch_dir%/are/BG4005.ARE~
	~%patch_dir%/are/AR4006.ARE~ ~%patch_dir%/are/BG4006.ARE~
	~%patch_dir%/are/AR4007.ARE~ ~%patch_dir%/are/BG4007.ARE~
	~%patch_dir%/are/AR4008.ARE~ ~%patch_dir%/are/BG4008.ARE~
	~%patch_dir%/are/AR4009.ARE~ ~%patch_dir%/are/BG4009.ARE~
	~%patch_dir%/are/AR4010.ARE~ ~%patch_dir%/are/BG4010.ARE~
	~%patch_dir%/are/AR4011.ARE~ ~%patch_dir%/are/BG4011.ARE~
	~%patch_dir%/are/AR4012.ARE~ ~%patch_dir%/are/BG4012.ARE~
	~%patch_dir%/are/AR4013.ARE~ ~%patch_dir%/are/BG4013.ARE~
	~%patch_dir%/are/AR4014.ARE~ ~%patch_dir%/are/BG4014.ARE~
	~%patch_dir%/are/AR4100.ARE~ ~%patch_dir%/are/BG4100.ARE~
	~%patch_dir%/are/AR4101.ARE~ ~%patch_dir%/are/BG4101.ARE~
	~%patch_dir%/are/AR4200.ARE~ ~%patch_dir%/are/BG4200.ARE~
	~%patch_dir%/are/AR4201.ARE~ ~%patch_dir%/are/BG4201.ARE~
	~%patch_dir%/are/AR4300.ARE~ ~%patch_dir%/are/BG4300.ARE~
	~%patch_dir%/are/AR4400.ARE~ ~%patch_dir%/are/BG4400.ARE~
	~%patch_dir%/are/AR4401.ARE~ ~%patch_dir%/are/BG4401.ARE~
	~%patch_dir%/are/AR4500.ARE~ ~%patch_dir%/are/BG4500.ARE~
	~%patch_dir%/are/AR4501.ARE~ ~%patch_dir%/are/BG4501.ARE~
	~%patch_dir%/are/AR4600.ARE~ ~%patch_dir%/are/BG4600.ARE~
	~%patch_dir%/are/AR4700.ARE~ ~%patch_dir%/are/BG4700.ARE~
	~%patch_dir%/are/AR4701.ARE~ ~%patch_dir%/are/BG4701.ARE~
	~%patch_dir%/are/AR4800.ARE~ ~%patch_dir%/are/BG4800.ARE~
	~%patch_dir%/are/AR4801.ARE~ ~%patch_dir%/are/BG4801.ARE~
	~%patch_dir%/are/AR4802.ARE~ ~%patch_dir%/are/BG4802.ARE~
	~%patch_dir%/are/AR4803.ARE~ ~%patch_dir%/are/BG4803.ARE~
	~%patch_dir%/are/AR4804.ARE~ ~%patch_dir%/are/BG4804.ARE~
	~%patch_dir%/are/AR4805.ARE~ ~%patch_dir%/are/BG4805.ARE~
	~%patch_dir%/are/AR4806.ARE~ ~%patch_dir%/are/BG4806.ARE~
	~%patch_dir%/are/AR4807.ARE~ ~%patch_dir%/are/BG4807.ARE~
	~%patch_dir%/are/AR4808.ARE~ ~%patch_dir%/are/BG4808.ARE~
	~%patch_dir%/are/AR4809.ARE~ ~%patch_dir%/are/BG4809.ARE~
	~%patch_dir%/are/AR4810.ARE~ ~%patch_dir%/are/BG4810.ARE~
	~%patch_dir%/are/AR4900.ARE~ ~%patch_dir%/are/BG4900.ARE~
	~%patch_dir%/are/AR4901.ARE~ ~%patch_dir%/are/BG4901.ARE~
	~%patch_dir%/are/AR4902.ARE~ ~%patch_dir%/are/BG4902.ARE~
	~%patch_dir%/are/AR4903.ARE~ ~%patch_dir%/are/BG4903.ARE~
	~%patch_dir%/are/AR4904.ARE~ ~%patch_dir%/are/BG4904.ARE~
	~%patch_dir%/are/AR4905.ARE~ ~%patch_dir%/are/BG4905.ARE~
	~%patch_dir%/are/AR4906.ARE~ ~%patch_dir%/are/BG4906.ARE~
	~%patch_dir%/are/AR4907.ARE~ ~%patch_dir%/are/BG4907.ARE~
	~%patch_dir%/are/AR4908.ARE~ ~%patch_dir%/are/BG4908.ARE~
	~%patch_dir%/are/AR4909.ARE~ ~%patch_dir%/are/BG4909.ARE~
	~%patch_dir%/are/AR5000.ARE~ ~%patch_dir%/are/BG5000.ARE~
	~%patch_dir%/are/AR5001.ARE~ ~%patch_dir%/are/BG5001.ARE~
	~%patch_dir%/are/AR5100.ARE~ ~%patch_dir%/are/BG5100.ARE~
	~%patch_dir%/are/AR5101.ARE~ ~%patch_dir%/are/BG5101.ARE~
	~%patch_dir%/are/AR5102.ARE~ ~%patch_dir%/are/BG5102.ARE~
	~%patch_dir%/are/AR5103.ARE~ ~%patch_dir%/are/BG5103.ARE~
	~%patch_dir%/are/AR5200.ARE~ ~%patch_dir%/are/BG5200.ARE~
	~%patch_dir%/are/AR5201.ARE~ ~%patch_dir%/are/BG5201.ARE~
	~%patch_dir%/are/AR5202.ARE~ ~%patch_dir%/are/BG5202.ARE~
	~%patch_dir%/are/AR5300.ARE~ ~%patch_dir%/are/BG5300.ARE~
	~%patch_dir%/are/AR5400.ARE~ ~%patch_dir%/are/BG5400.ARE~
	~%patch_dir%/are/AR5401.ARE~ ~%patch_dir%/are/BG5401.ARE~
	~%patch_dir%/are/AR5402.ARE~ ~%patch_dir%/are/BG5402.ARE~
	~%patch_dir%/are/AR5403.ARE~ ~%patch_dir%/are/BG5403.ARE~
	~%patch_dir%/are/AR5404.ARE~ ~%patch_dir%/are/BG5404.ARE~
	~%patch_dir%/are/AR5405.ARE~ ~%patch_dir%/are/BG5405.ARE~
	~%patch_dir%/are/AR5406.ARE~ ~%patch_dir%/are/BG5406.ARE~
	~%patch_dir%/are/AR5500.ARE~ ~%patch_dir%/are/BG5500.ARE~
	~%patch_dir%/are/AR5506.ARE~ ~%patch_dir%/are/BG5506.ARE~
	~%patch_dir%/are/AR5600.ARE~ ~%patch_dir%/are/BG5600.ARE~
	~%patch_dir%/are/AR5601.ARE~ ~%patch_dir%/are/BG5601.ARE~
	~%patch_dir%/are/AR5610.ARE~ ~%patch_dir%/are/BG5610.ARE~
	~%patch_dir%/are/AR5700.ARE~ ~%patch_dir%/are/BG5700.ARE~
	~%patch_dir%/are/AR5701.ARE~ ~%patch_dir%/are/BG5701.ARE~
	~%patch_dir%/are/AR5710.ARE~ ~%patch_dir%/are/BG5710.ARE~
	~%patch_dir%/are/AR5800.ARE~ ~%patch_dir%/are/BG5800.ARE~
	~%patch_dir%/are/AR5801.ARE~ ~%patch_dir%/are/BG5801.ARE~
	~%patch_dir%/are/AR5810.ARE~ ~%patch_dir%/are/BG5810.ARE~
	~%patch_dir%/are/AR5900.ARE~ ~%patch_dir%/are/BG5900.ARE~
	~%patch_dir%/are/AR5901.ARE~ ~%patch_dir%/are/BG5901.ARE~
	~%patch_dir%/are/AR5910.ARE~ ~%patch_dir%/are/BG5910.ARE~
	~%patch_dir%/are/AR6000.ARE~ ~%patch_dir%/are/BG6000.ARE~
	~%patch_dir%/are/AR6001.ARE~ ~%patch_dir%/are/BG6001.ARE~
	~%patch_dir%/are/AR6010.ARE~ ~%patch_dir%/are/BG6010.ARE~
	~%patch_dir%/are/AR6100.ARE~ ~%patch_dir%/are/BG6100.ARE~
	~%patch_dir%/are/AR6110.ARE~ ~%patch_dir%/are/BG6110.ARE~

//renamed
DELETE + ~%patch_dir%/are/AR0002.ARE~
	~%patch_dir%/are/AR0004.ARE~
	~%patch_dir%/are/AR0005.ARE~
	~%patch_dir%/are/AR0006.ARE~
	~%patch_dir%/are/AR0007.ARE~
	~%patch_dir%/are/AR0008.ARE~
	~%patch_dir%/are/AR0009.ARE~
	~%patch_dir%/are/AR0010.ARE~
	~%patch_dir%/are/AR0011.ARE~
	~%patch_dir%/are/AR0012.ARE~
	~%patch_dir%/are/AR0013.ARE~
	~%patch_dir%/are/AR0014.ARE~
	~%patch_dir%/are/AR0015.ARE~
	~%patch_dir%/are/AR0016.ARE~
	~%patch_dir%/are/AR0017.ARE~
	~%patch_dir%/are/AR0018.ARE~
	~%patch_dir%/are/AR0019.ARE~
	~%patch_dir%/are/AR0020.ARE~
	~%patch_dir%/are/AR0021.ARE~
	~%patch_dir%/are/AR0100.ARE~
	~%patch_dir%/are/AR0101.ARE~
	~%patch_dir%/are/AR0102.ARE~
	~%patch_dir%/are/AR0103.ARE~
	~%patch_dir%/are/AR0104.ARE~
	~%patch_dir%/are/AR0105.ARE~
	~%patch_dir%/are/AR0106.ARE~
	~%patch_dir%/are/AR0107.ARE~
	~%patch_dir%/are/AR0108.ARE~
	~%patch_dir%/are/AR0109.ARE~
	~%patch_dir%/are/AR0110.ARE~
	~%patch_dir%/are/AR0111.ARE~
	~%patch_dir%/are/AR0112.ARE~
	~%patch_dir%/are/AR0114.ARE~
	~%patch_dir%/are/AR0115.ARE~
	~%patch_dir%/are/AR0116.ARE~
	~%patch_dir%/are/AR0117.ARE~
	~%patch_dir%/are/AR0118.ARE~
	~%patch_dir%/are/AR0119.ARE~
	~%patch_dir%/are/AR0120.ARE~
	~%patch_dir%/are/AR0121.ARE~
	~%patch_dir%/are/AR0123.ARE~
	~%patch_dir%/are/AR0125.ARE~
	~%patch_dir%/are/AR0126.ARE~
	~%patch_dir%/are/AR0127.ARE~
	~%patch_dir%/are/AR0128.ARE~
	~%patch_dir%/are/AR0129.ARE~
	~%patch_dir%/are/AR0130.ARE~
	~%patch_dir%/are/AR0131.ARE~
	~%patch_dir%/are/AR0132.ARE~
	~%patch_dir%/are/AR0133.ARE~
	~%patch_dir%/are/AR0134.ARE~
	~%patch_dir%/are/AR0135.ARE~
	~%patch_dir%/are/AR0136.ARE~
	~%patch_dir%/are/AR0137.ARE~
	~%patch_dir%/are/AR0138.ARE~
	~%patch_dir%/are/AR0139.ARE~
	~%patch_dir%/are/AR0140.ARE~
	~%patch_dir%/are/AR0141.ARE~
	~%patch_dir%/are/AR0142.ARE~
	~%patch_dir%/are/AR0143.ARE~
	~%patch_dir%/are/AR0144.ARE~
	~%patch_dir%/are/AR0145.ARE~
	~%patch_dir%/are/AR0146.ARE~
	~%patch_dir%/are/AR0148.ARE~
	~%patch_dir%/are/AR0149.ARE~
	~%patch_dir%/are/AR0150.ARE~
	~%patch_dir%/are/AR0151.ARE~
	~%patch_dir%/are/AR0152.ARE~
	~%patch_dir%/are/AR0153.ARE~
	~%patch_dir%/are/AR0154.ARE~
	~%patch_dir%/are/AR0155.ARE~
	~%patch_dir%/are/AR0156.ARE~
	~%patch_dir%/are/AR0157.ARE~
	~%patch_dir%/are/AR0158.ARE~
	~%patch_dir%/are/AR0159.ARE~
	~%patch_dir%/are/AR0160.ARE~
	~%patch_dir%/are/AR0161.ARE~
	~%patch_dir%/are/AR0162.ARE~
	~%patch_dir%/are/AR0163.ARE~
	~%patch_dir%/are/AR0164.ARE~
	~%patch_dir%/are/AR0165.ARE~
	~%patch_dir%/are/AR0166.ARE~
	~%patch_dir%/are/AR0167.ARE~
	~%patch_dir%/are/AR0168.ARE~
	~%patch_dir%/are/AR0169.ARE~
	~%patch_dir%/are/AR0170.ARE~
	~%patch_dir%/are/AR0171.ARE~
	~%patch_dir%/are/AR0200.ARE~
	~%patch_dir%/are/AR0224.ARE~
	~%patch_dir%/are/AR0225.ARE~
	~%patch_dir%/are/AR0226.ARE~
	~%patch_dir%/are/AR0300.ARE~
	~%patch_dir%/are/AR0302.ARE~
	~%patch_dir%/are/AR0303.ARE~
	~%patch_dir%/are/AR0304.ARE~
	~%patch_dir%/are/AR0305.ARE~
	~%patch_dir%/are/AR0306.ARE~
	~%patch_dir%/are/AR0307.ARE~
	~%patch_dir%/are/AR0308.ARE~
	~%patch_dir%/are/AR0400.ARE~
	~%patch_dir%/are/AR0401.ARE~
	~%patch_dir%/are/AR0500.ARE~
	~%patch_dir%/are/AR0501.ARE~
	~%patch_dir%/are/AR0502.ARE~
	~%patch_dir%/are/AR0503.ARE~
	~%patch_dir%/are/AR0504.ARE~
	~%patch_dir%/are/AR0505.ARE~
	~%patch_dir%/are/AR0506.ARE~
	~%patch_dir%/are/AR0507.ARE~
	~%patch_dir%/are/AR0508.ARE~
	~%patch_dir%/are/AR0509.ARE~
	~%patch_dir%/are/AR0510.ARE~
	~%patch_dir%/are/AR0511.ARE~
	~%patch_dir%/are/AR0512.ARE~
	~%patch_dir%/are/AR0513.ARE~
	~%patch_dir%/are/AR0514.ARE~
	~%patch_dir%/are/AR0515.ARE~
	~%patch_dir%/are/AR0516.ARE~
	~%patch_dir%/are/AR0600.ARE~
	~%patch_dir%/are/AR0601.ARE~
	~%patch_dir%/are/AR0602.ARE~
	~%patch_dir%/are/AR0603.ARE~
	~%patch_dir%/are/AR0606.ARE~
	~%patch_dir%/are/AR0607.ARE~
	~%patch_dir%/are/AR0608.ARE~
	~%patch_dir%/are/AR0609.ARE~
	~%patch_dir%/are/AR0611.ARE~
	~%patch_dir%/are/AR0612.ARE~
	~%patch_dir%/are/AR0613.ARE~
	~%patch_dir%/are/AR0614.ARE~
	~%patch_dir%/are/AR0615.ARE~
	~%patch_dir%/are/AR0616.ARE~
	~%patch_dir%/are/AR0617.ARE~
	~%patch_dir%/are/AR0618.ARE~
	~%patch_dir%/are/AR0619.ARE~
	~%patch_dir%/are/AR0620.ARE~
	~%patch_dir%/are/AR0621.ARE~
	~%patch_dir%/are/AR0700.ARE~
	~%patch_dir%/are/AR0702.ARE~
	~%patch_dir%/are/AR0703.ARE~
	~%patch_dir%/are/AR0704.ARE~
	~%patch_dir%/are/AR0705.ARE~
	~%patch_dir%/are/AR0706.ARE~
	~%patch_dir%/are/AR0707.ARE~
	~%patch_dir%/are/AR0708.ARE~
	~%patch_dir%/are/AR0709.ARE~
	~%patch_dir%/are/AR0710.ARE~
	~%patch_dir%/are/AR0711.ARE~
	~%patch_dir%/are/AR0712.ARE~
	~%patch_dir%/are/AR0713.ARE~
	~%patch_dir%/are/AR0714.ARE~
	~%patch_dir%/are/AR0715.ARE~
	~%patch_dir%/are/AR0716.ARE~
	~%patch_dir%/are/AR0717.ARE~
	~%patch_dir%/are/AR0718.ARE~
	~%patch_dir%/are/AR0719.ARE~
	~%patch_dir%/are/AR0720.ARE~
	~%patch_dir%/are/AR0721.ARE~
	~%patch_dir%/are/AR0722.ARE~
	~%patch_dir%/are/AR0723.ARE~
	~%patch_dir%/are/AR0724.ARE~
	~%patch_dir%/are/AR0725.ARE~
	~%patch_dir%/are/AR0726.ARE~
	~%patch_dir%/are/AR0800.ARE~
	~%patch_dir%/are/AR0801.ARE~
	~%patch_dir%/are/AR0802.ARE~
	~%patch_dir%/are/AR0803.ARE~
	~%patch_dir%/are/AR0804.ARE~
	~%patch_dir%/are/AR0805.ARE~
	~%patch_dir%/are/AR0806.ARE~
	~%patch_dir%/are/AR0807.ARE~
	~%patch_dir%/are/AR0808.ARE~
	~%patch_dir%/are/AR0809.ARE~
	~%patch_dir%/are/AR0810.ARE~
	~%patch_dir%/are/AR0811.ARE~
	~%patch_dir%/are/AR0812.ARE~
	~%patch_dir%/are/AR0813.ARE~
	~%patch_dir%/are/AR0814.ARE~
	~%patch_dir%/are/AR0900.ARE~
	~%patch_dir%/are/AR0901.ARE~
	~%patch_dir%/are/AR1000.ARE~
	~%patch_dir%/are/AR1001.ARE~
	~%patch_dir%/are/AR1002.ARE~
	~%patch_dir%/are/AR1003.ARE~
	~%patch_dir%/are/AR1004.ARE~
	~%patch_dir%/are/AR1005.ARE~
	~%patch_dir%/are/AR1006.ARE~
	~%patch_dir%/are/AR1007.ARE~
	~%patch_dir%/are/AR1008.ARE~
	~%patch_dir%/are/AR1009.ARE~
	~%patch_dir%/are/AR1010.ARE~
	~%patch_dir%/are/AR1100.ARE~
	~%patch_dir%/are/AR1101.ARE~
	~%patch_dir%/are/AR1102.ARE~
	~%patch_dir%/are/AR1103.ARE~
	~%patch_dir%/are/AR1104.ARE~
	~%patch_dir%/are/AR1105.ARE~
	~%patch_dir%/are/AR1106.ARE~
	~%patch_dir%/are/AR1107.ARE~
	~%patch_dir%/are/AR1108.ARE~
	~%patch_dir%/are/AR1109.ARE~
	~%patch_dir%/are/AR1110.ARE~
	~%patch_dir%/are/AR1111.ARE~
	~%patch_dir%/are/AR1112.ARE~
	~%patch_dir%/are/AR1113.ARE~
	~%patch_dir%/are/AR1114.ARE~
	~%patch_dir%/are/AR1115.ARE~
	~%patch_dir%/are/AR1116.ARE~
	~%patch_dir%/are/AR1117.ARE~
	~%patch_dir%/are/AR1200.ARE~
	~%patch_dir%/are/AR1201.ARE~
	~%patch_dir%/are/AR1202.ARE~
	~%patch_dir%/are/AR1203.ARE~
	~%patch_dir%/are/AR1204.ARE~
	~%patch_dir%/are/AR1205.ARE~
	~%patch_dir%/are/AR1206.ARE~
	~%patch_dir%/are/AR1207.ARE~
	~%patch_dir%/are/AR1208.ARE~
	~%patch_dir%/are/AR1209.ARE~
	~%patch_dir%/are/AR1210.ARE~
	~%patch_dir%/are/AR1211.ARE~
	~%patch_dir%/are/AR1212.ARE~
	~%patch_dir%/are/AR1213.ARE~
	~%patch_dir%/are/AR1214.ARE~
	~%patch_dir%/are/AR1215.ARE~
	~%patch_dir%/are/AR1300.ARE~
	~%patch_dir%/are/AR1301.ARE~
	~%patch_dir%/are/AR1302.ARE~
	~%patch_dir%/are/AR1303.ARE~
	~%patch_dir%/are/AR1304.ARE~
	~%patch_dir%/are/AR1305.ARE~
	~%patch_dir%/are/AR1306.ARE~
	~%patch_dir%/are/AR1307.ARE~
	~%patch_dir%/are/AR1308.ARE~
	~%patch_dir%/are/AR1309.ARE~
	~%patch_dir%/are/AR1310.ARE~
	~%patch_dir%/are/AR1311.ARE~
	~%patch_dir%/are/AR1312.ARE~
	~%patch_dir%/are/AR1313.ARE~
	~%patch_dir%/are/AR1314.ARE~
	~%patch_dir%/are/AR1315.ARE~
	~%patch_dir%/are/AR1316.ARE~
	~%patch_dir%/are/AR1317.ARE~
	~%patch_dir%/are/AR1320.ARE~
	~%patch_dir%/are/AR1400.ARE~
	~%patch_dir%/are/AR1401.ARE~
	~%patch_dir%/are/AR1402.ARE~
	~%patch_dir%/are/AR1403.ARE~
	~%patch_dir%/are/AR1404.ARE~
	~%patch_dir%/are/AR1500.ARE~
	~%patch_dir%/are/AR1501.ARE~
	~%patch_dir%/are/AR1502.ARE~
	~%patch_dir%/are/AR1503.ARE~
	~%patch_dir%/are/AR1504.ARE~
	~%patch_dir%/are/AR1505.ARE~
	~%patch_dir%/are/AR1600.ARE~
	~%patch_dir%/are/AR1601.ARE~
	~%patch_dir%/are/AR1602.ARE~
	~%patch_dir%/are/AR1603.ARE~
	~%patch_dir%/are/AR1700.ARE~
	~%patch_dir%/are/AR1800.ARE~
	~%patch_dir%/are/AR1801.ARE~
	~%patch_dir%/are/AR1801A.ARE~
	~%patch_dir%/are/AR1802.ARE~
	~%patch_dir%/are/AR1803.ARE~
	~%patch_dir%/are/AR1804.ARE~
	~%patch_dir%/are/AR1805.ARE~
	~%patch_dir%/are/AR1806.ARE~
	~%patch_dir%/are/AR1807.ARE~
	~%patch_dir%/are/AR1808.ARE~
	~%patch_dir%/are/AR1809.ARE~
	~%patch_dir%/are/AR1900.ARE~
	~%patch_dir%/are/AR1901.ARE~
	~%patch_dir%/are/AR1902.ARE~
	~%patch_dir%/are/AR1903.ARE~
	~%patch_dir%/are/AR1904.ARE~
	~%patch_dir%/are/AR1905.ARE~
	~%patch_dir%/are/AR1906.ARE~
	~%patch_dir%/are/AR1907.ARE~
	~%patch_dir%/are/AR2000.ARE~
	~%patch_dir%/are/AR2001.ARE~
	~%patch_dir%/are/AR2002.ARE~
	~%patch_dir%/are/AR2003.ARE~
	~%patch_dir%/are/AR2004.ARE~
	~%patch_dir%/are/AR2005.ARE~
	~%patch_dir%/are/AR2006.ARE~
	~%patch_dir%/are/AR2007.ARE~
	~%patch_dir%/are/AR2008.ARE~
	~%patch_dir%/are/AR2009.ARE~
	~%patch_dir%/are/AR2010.ARE~
	~%patch_dir%/are/AR2011.ARE~
	~%patch_dir%/are/AR2012.ARE~
	~%patch_dir%/are/AR2100.ARE~
	~%patch_dir%/are/AR2101.ARE~
	~%patch_dir%/are/AR2200.ARE~
	~%patch_dir%/are/AR2215.ARE~
	~%patch_dir%/are/AR2300.ARE~
	~%patch_dir%/are/AR2301.ARE~
	~%patch_dir%/are/AR2302.ARE~
	~%patch_dir%/are/AR2303.ARE~
	~%patch_dir%/are/AR2304.ARE~
	~%patch_dir%/are/AR2305.ARE~
	~%patch_dir%/are/AR2306.ARE~
	~%patch_dir%/are/AR2400.ARE~
	~%patch_dir%/are/AR2600.ARE~
	~%patch_dir%/are/AR2602.ARE~
	~%patch_dir%/are/AR2605.ARE~
	~%patch_dir%/are/AR2606.ARE~
	~%patch_dir%/are/AR2607.ARE~
	~%patch_dir%/are/AR2608.ARE~
	~%patch_dir%/are/AR2609.ARE~
	~%patch_dir%/are/AR2610.ARE~
	~%patch_dir%/are/AR2611.ARE~
	~%patch_dir%/are/AR2612.ARE~
	~%patch_dir%/are/AR2613.ARE~
	~%patch_dir%/are/AR2614.ARE~
	~%patch_dir%/are/AR2615.ARE~
	~%patch_dir%/are/AR2616.ARE~
	~%patch_dir%/are/AR2617.ARE~
	~%patch_dir%/are/AR2618.ARE~
	~%patch_dir%/are/AR2619.ARE~
	~%patch_dir%/are/AR2622.ARE~
	~%patch_dir%/are/AR2623.ARE~
	~%patch_dir%/are/AR2624.ARE~
	~%patch_dir%/are/AR2626.ARE~
	~%patch_dir%/are/AR2627.ARE~
	~%patch_dir%/are/AR2628.ARE~
	~%patch_dir%/are/AR2629.ARE~
	~%patch_dir%/are/AR2630.ARE~
	~%patch_dir%/are/AR2631.ARE~
	~%patch_dir%/are/AR2632.ARE~
	~%patch_dir%/are/AR2633.ARE~
	~%patch_dir%/are/AR2634.ARE~
	~%patch_dir%/are/AR2635.ARE~
	~%patch_dir%/are/AR2636.ARE~
	~%patch_dir%/are/AR2637.ARE~
	~%patch_dir%/are/AR2638.ARE~
	~%patch_dir%/are/AR2639.ARE~
	~%patch_dir%/are/AR2640.ARE~
	~%patch_dir%/are/AR2641.ARE~
	~%patch_dir%/are/AR2642.ARE~
	~%patch_dir%/are/AR2643.ARE~
	~%patch_dir%/are/AR2700.ARE~
	~%patch_dir%/are/AR2800.ARE~
	~%patch_dir%/are/AR2900.ARE~
	~%patch_dir%/are/AR3000.ARE~
	~%patch_dir%/are/AR3100.ARE~
	~%patch_dir%/are/AR3200.ARE~
	~%patch_dir%/are/AR3201.ARE~
	~%patch_dir%/are/AR3202.ARE~
	~%patch_dir%/are/AR3300.ARE~
	~%patch_dir%/are/AR3301.ARE~
	~%patch_dir%/are/AR3302.ARE~
	~%patch_dir%/are/AR3303.ARE~
	~%patch_dir%/are/AR3304.ARE~
	~%patch_dir%/are/AR3305.ARE~
	~%patch_dir%/are/AR3306.ARE~
	~%patch_dir%/are/AR3307.ARE~
	~%patch_dir%/are/AR3308.ARE~
	~%patch_dir%/are/AR3309.ARE~
	~%patch_dir%/are/AR3310.ARE~
	~%patch_dir%/are/AR3311.ARE~
	~%patch_dir%/are/AR3312.ARE~
	~%patch_dir%/are/AR3313.ARE~
	~%patch_dir%/are/AR3314.ARE~
	~%patch_dir%/are/AR3315.ARE~
	~%patch_dir%/are/AR3316.ARE~
	~%patch_dir%/are/AR3317.ARE~
	~%patch_dir%/are/AR3318.ARE~
	~%patch_dir%/are/AR3319.ARE~
	~%patch_dir%/are/AR3320.ARE~
	~%patch_dir%/are/AR3321.ARE~
	~%patch_dir%/are/AR3322.ARE~
	~%patch_dir%/are/AR3323.ARE~
	~%patch_dir%/are/AR3324.ARE~
	~%patch_dir%/are/AR3325.ARE~
	~%patch_dir%/are/AR3326.ARE~
	~%patch_dir%/are/AR3327.ARE~
	~%patch_dir%/are/AR3328.ARE~
	~%patch_dir%/are/AR3329.ARE~
	~%patch_dir%/are/AR3330.ARE~
	~%patch_dir%/are/AR3331.ARE~
	~%patch_dir%/are/AR3332.ARE~
	~%patch_dir%/are/AR3333.ARE~
	~%patch_dir%/are/AR3334.ARE~
	~%patch_dir%/are/AR3335.ARE~
	~%patch_dir%/are/AR3336.ARE~
	~%patch_dir%/are/AR3337.ARE~
	~%patch_dir%/are/AR3338.ARE~
	~%patch_dir%/are/AR3339.ARE~
	~%patch_dir%/are/AR3340.ARE~
	~%patch_dir%/are/AR3341.ARE~
	~%patch_dir%/are/AR3342.ARE~
	~%patch_dir%/are/AR3343.ARE~
	~%patch_dir%/are/AR3344.ARE~
	~%patch_dir%/are/AR3345.ARE~
	~%patch_dir%/are/AR3346.ARE~
	~%patch_dir%/are/AR3347.ARE~
	~%patch_dir%/are/AR3348.ARE~
	~%patch_dir%/are/AR3349.ARE~
	~%patch_dir%/are/AR3350.ARE~
	~%patch_dir%/are/AR3351.ARE~
	~%patch_dir%/are/AR3352.ARE~
	~%patch_dir%/are/AR3353.ARE~
	~%patch_dir%/are/AR3354.ARE~
	~%patch_dir%/are/AR3355.ARE~
	~%patch_dir%/are/AR3356.ARE~
	~%patch_dir%/are/AR3357.ARE~
	~%patch_dir%/are/AR3400.ARE~
	~%patch_dir%/are/AR3401.ARE~
	~%patch_dir%/are/AR3402.ARE~
	~%patch_dir%/are/AR3500.ARE~
	~%patch_dir%/are/AR3600.ARE~
	~%patch_dir%/are/AR3601.ARE~
	~%patch_dir%/are/AR3700.ARE~
	~%patch_dir%/are/AR3800.ARE~
	~%patch_dir%/are/AR3802.ARE~
	~%patch_dir%/are/AR3900.ARE~
	~%patch_dir%/are/AR3901.ARE~
	~%patch_dir%/are/AR4000.ARE~
	~%patch_dir%/are/AR4001.ARE~
	~%patch_dir%/are/AR4002.ARE~
	~%patch_dir%/are/AR4003.ARE~
	~%patch_dir%/are/AR4004.ARE~
	~%patch_dir%/are/AR4005.ARE~
	~%patch_dir%/are/AR4006.ARE~
	~%patch_dir%/are/AR4007.ARE~
	~%patch_dir%/are/AR4008.ARE~
	~%patch_dir%/are/AR4009.ARE~
	~%patch_dir%/are/AR4010.ARE~
	~%patch_dir%/are/AR4011.ARE~
	~%patch_dir%/are/AR4012.ARE~
	~%patch_dir%/are/AR4013.ARE~
	~%patch_dir%/are/AR4014.ARE~
	~%patch_dir%/are/AR4100.ARE~
	~%patch_dir%/are/AR4101.ARE~
	~%patch_dir%/are/AR4200.ARE~
	~%patch_dir%/are/AR4201.ARE~
	~%patch_dir%/are/AR4300.ARE~
	~%patch_dir%/are/AR4400.ARE~
	~%patch_dir%/are/AR4401.ARE~
	~%patch_dir%/are/AR4500.ARE~
	~%patch_dir%/are/AR4501.ARE~
	~%patch_dir%/are/AR4600.ARE~
	~%patch_dir%/are/AR4700.ARE~
	~%patch_dir%/are/AR4701.ARE~
	~%patch_dir%/are/AR4800.ARE~
	~%patch_dir%/are/AR4801.ARE~
	~%patch_dir%/are/AR4802.ARE~
	~%patch_dir%/are/AR4803.ARE~
	~%patch_dir%/are/AR4804.ARE~
	~%patch_dir%/are/AR4805.ARE~
	~%patch_dir%/are/AR4806.ARE~
	~%patch_dir%/are/AR4807.ARE~
	~%patch_dir%/are/AR4808.ARE~
	~%patch_dir%/are/AR4809.ARE~
	~%patch_dir%/are/AR4810.ARE~
	~%patch_dir%/are/AR4900.ARE~
	~%patch_dir%/are/AR4901.ARE~
	~%patch_dir%/are/AR4902.ARE~
	~%patch_dir%/are/AR4903.ARE~
	~%patch_dir%/are/AR4904.ARE~
	~%patch_dir%/are/AR4905.ARE~
	~%patch_dir%/are/AR4906.ARE~
	~%patch_dir%/are/AR4907.ARE~
	~%patch_dir%/are/AR4908.ARE~
	~%patch_dir%/are/AR4909.ARE~
	~%patch_dir%/are/AR5000.ARE~
	~%patch_dir%/are/AR5001.ARE~
	~%patch_dir%/are/AR5100.ARE~
	~%patch_dir%/are/AR5101.ARE~
	~%patch_dir%/are/AR5102.ARE~
	~%patch_dir%/are/AR5103.ARE~
	~%patch_dir%/are/AR5200.ARE~
	~%patch_dir%/are/AR5201.ARE~
	~%patch_dir%/are/AR5202.ARE~
	~%patch_dir%/are/AR5300.ARE~
	~%patch_dir%/are/AR5400.ARE~
	~%patch_dir%/are/AR5401.ARE~
	~%patch_dir%/are/AR5402.ARE~
	~%patch_dir%/are/AR5403.ARE~
	~%patch_dir%/are/AR5404.ARE~
	~%patch_dir%/are/AR5405.ARE~
	~%patch_dir%/are/AR5406.ARE~
	~%patch_dir%/are/AR5500.ARE~
	~%patch_dir%/are/AR5506.ARE~
	~%patch_dir%/are/AR5600.ARE~
	~%patch_dir%/are/AR5601.ARE~
	~%patch_dir%/are/AR5610.ARE~
	~%patch_dir%/are/AR5700.ARE~
	~%patch_dir%/are/AR5701.ARE~
	~%patch_dir%/are/AR5710.ARE~
	~%patch_dir%/are/AR5800.ARE~
	~%patch_dir%/are/AR5801.ARE~
	~%patch_dir%/are/AR5810.ARE~
	~%patch_dir%/are/AR5900.ARE~
	~%patch_dir%/are/AR5901.ARE~
	~%patch_dir%/are/AR5910.ARE~
	~%patch_dir%/are/AR6000.ARE~
	~%patch_dir%/are/AR6001.ARE~
	~%patch_dir%/are/AR6010.ARE~
	~%patch_dir%/are/AR6100.ARE~
	~%patch_dir%/are/AR6110.ARE~
//other
	~%patch_dir%/are/AR7100.ARE~
	~%patch_dir%/are/AR9901.ARE~
	~%patch_dir%/are/PH0001.ARE~
