COPY_LARGE + ~%biff_dir%/AR0002HT.BMP~ ~%biff_dir%/eetBG00/BG0002HT.BMP~
	~%biff_dir%/AR0002LM.BMP~ ~%biff_dir%/eetBG00/BG0002LM.BMP~
	~%biff_dir%/AR0002SR.BMP~ ~%biff_dir%/eetBG00/BG0002SR.BMP~
	~%biff_dir%/AR0100HT.BMP~ ~%biff_dir%/eetBG01/BG0100HT.BMP~
	~%biff_dir%/AR0100LM.BMP~ ~%biff_dir%/eetBG01/BG0100LM.BMP~
	~%biff_dir%/AR0100LN.BMP~ ~%biff_dir%/eetBG01/BG0100LN.BMP~
	~%biff_dir%/AR0100SR.BMP~ ~%biff_dir%/eetBG01/BG0100SR.BMP~
	~%biff_dir%/AR0101HT.BMP~ ~%biff_dir%/eetBG01/BG0101HT.BMP~
	~%biff_dir%/AR0101LM.BMP~ ~%biff_dir%/eetBG01/BG0101LM.BMP~
	~%biff_dir%/AR0101SR.BMP~ ~%biff_dir%/eetBG01/BG0101SR.BMP~
	~%biff_dir%/AR0102HT.BMP~ ~%biff_dir%/eetBG01/BG0102HT.BMP~
	~%biff_dir%/AR0102LM.BMP~ ~%biff_dir%/eetBG01/BG0102LM.BMP~
	~%biff_dir%/AR0102SR.BMP~ ~%biff_dir%/eetBG01/BG0102SR.BMP~
	~%biff_dir%/AR0103HT.BMP~ ~%biff_dir%/eetBG01/BG0103HT.BMP~
	~%biff_dir%/AR0103LM.BMP~ ~%biff_dir%/eetBG01/BG0103LM.BMP~
	~%biff_dir%/AR0103SR.BMP~ ~%biff_dir%/eetBG01/BG0103SR.BMP~
	~%biff_dir%/AR0104HT.BMP~ ~%biff_dir%/eetBG01/BG0104HT.BMP~
	~%biff_dir%/AR0104LM.BMP~ ~%biff_dir%/eetBG01/BG0104LM.BMP~
	~%biff_dir%/AR0104SR.BMP~ ~%biff_dir%/eetBG01/BG0104SR.BMP~
	~%biff_dir%/AR0105HT.BMP~ ~%biff_dir%/eetBG01/BG0105HT.BMP~
	~%biff_dir%/AR0105LM.BMP~ ~%biff_dir%/eetBG01/BG0105LM.BMP~
	~%biff_dir%/AR0105SR.BMP~ ~%biff_dir%/eetBG01/BG0105SR.BMP~
	~%biff_dir%/AR0106HT.BMP~ ~%biff_dir%/eetBG01/BG0106HT.BMP~
	~%biff_dir%/AR0106LM.BMP~ ~%biff_dir%/eetBG01/BG0106LM.BMP~
	~%biff_dir%/AR0106SR.BMP~ ~%biff_dir%/eetBG01/BG0106SR.BMP~
	~%biff_dir%/AR0107HT.BMP~ ~%biff_dir%/eetBG01/BG0107HT.BMP~
	~%biff_dir%/AR0107LM.BMP~ ~%biff_dir%/eetBG01/BG0107LM.BMP~
	~%biff_dir%/AR0107SR.BMP~ ~%biff_dir%/eetBG01/BG0107SR.BMP~
	~%biff_dir%/AR0108HT.BMP~ ~%biff_dir%/eetBG01/BG0108HT.BMP~
	~%biff_dir%/AR0108LM.BMP~ ~%biff_dir%/eetBG01/BG0108LM.BMP~
	~%biff_dir%/AR0108SR.BMP~ ~%biff_dir%/eetBG01/BG0108SR.BMP~
	~%biff_dir%/AR0109HT.BMP~ ~%biff_dir%/eetBG01/BG0109HT.BMP~
	~%biff_dir%/AR0109LM.BMP~ ~%biff_dir%/eetBG01/BG0109LM.BMP~
	~%biff_dir%/AR0109SR.BMP~ ~%biff_dir%/eetBG01/BG0109SR.BMP~
	~%biff_dir%/AR0110HT.BMP~ ~%biff_dir%/eetBG01/BG0110HT.BMP~
	~%biff_dir%/AR0110LM.BMP~ ~%biff_dir%/eetBG01/BG0110LM.BMP~
	~%biff_dir%/AR0110SR.BMP~ ~%biff_dir%/eetBG01/BG0110SR.BMP~
	~%biff_dir%/AR0111HT.BMP~ ~%biff_dir%/eetBG01/BG0111HT.BMP~
	~%biff_dir%/AR0111LM.BMP~ ~%biff_dir%/eetBG01/BG0111LM.BMP~
	~%biff_dir%/AR0111SR.BMP~ ~%biff_dir%/eetBG01/BG0111SR.BMP~
	~%biff_dir%/AR0112HT.BMP~ ~%biff_dir%/eetBG01/BG0112HT.BMP~
	~%biff_dir%/AR0112LM.BMP~ ~%biff_dir%/eetBG01/BG0112LM.BMP~
	~%biff_dir%/AR0112SR.BMP~ ~%biff_dir%/eetBG01/BG0112SR.BMP~
	~%biff_dir%/AR0114HT.BMP~ ~%biff_dir%/eetBG01/BG0114HT.BMP~
	~%biff_dir%/AR0114LM.BMP~ ~%biff_dir%/eetBG01/BG0114LM.BMP~
	~%biff_dir%/AR0114SR.BMP~ ~%biff_dir%/eetBG01/BG0114SR.BMP~
	~%biff_dir%/AR0115HT.BMP~ ~%biff_dir%/eetBG01/BG0115HT.BMP~
	~%biff_dir%/AR0115LM.BMP~ ~%biff_dir%/eetBG01/BG0115LM.BMP~
	~%biff_dir%/AR0115SR.BMP~ ~%biff_dir%/eetBG01/BG0115SR.BMP~
	~%biff_dir%/AR0116HT.BMP~ ~%biff_dir%/eetBG01/BG0116HT.BMP~
	~%biff_dir%/AR0116LM.BMP~ ~%biff_dir%/eetBG01/BG0116LM.BMP~
	~%biff_dir%/AR0116SR.BMP~ ~%biff_dir%/eetBG01/BG0116SR.BMP~
	~%biff_dir%/AR0117HT.BMP~ ~%biff_dir%/eetBG01/BG0117HT.BMP~
	~%biff_dir%/AR0117LM.BMP~ ~%biff_dir%/eetBG01/BG0117LM.BMP~
	~%biff_dir%/AR0117SR.BMP~ ~%biff_dir%/eetBG01/BG0117SR.BMP~
	~%biff_dir%/AR0118HT.BMP~ ~%biff_dir%/eetBG01/BG0118HT.BMP~
	~%biff_dir%/AR0118LM.BMP~ ~%biff_dir%/eetBG01/BG0118LM.BMP~
	~%biff_dir%/AR0118SR.BMP~ ~%biff_dir%/eetBG01/BG0118SR.BMP~
	~%biff_dir%/AR0119HT.BMP~ ~%biff_dir%/eetBG01/BG0119HT.BMP~
	~%biff_dir%/AR0119LM.BMP~ ~%biff_dir%/eetBG01/BG0119LM.BMP~
	~%biff_dir%/AR0119SR.BMP~ ~%biff_dir%/eetBG01/BG0119SR.BMP~
	~%biff_dir%/AR0120HT.BMP~ ~%biff_dir%/eetBG01/BG0120HT.BMP~
	~%biff_dir%/AR0120LM.BMP~ ~%biff_dir%/eetBG01/BG0120LM.BMP~
	~%biff_dir%/AR0120SR.BMP~ ~%biff_dir%/eetBG01/BG0120SR.BMP~
	~%biff_dir%/AR0121HT.BMP~ ~%biff_dir%/eetBG01/BG0121HT.BMP~
	~%biff_dir%/AR0121LM.BMP~ ~%biff_dir%/eetBG01/BG0121LM.BMP~
	~%biff_dir%/AR0121SR.BMP~ ~%biff_dir%/eetBG01/BG0121SR.BMP~
	~%biff_dir%/AR0123HT.BMP~ ~%biff_dir%/eetBG01/BG0123HT.BMP~
	~%biff_dir%/AR0123LM.BMP~ ~%biff_dir%/eetBG01/BG0123LM.BMP~
	~%biff_dir%/AR0123SR.BMP~ ~%biff_dir%/eetBG01/BG0123SR.BMP~
	~%biff_dir%/AR0125HT.BMP~ ~%biff_dir%/eetBG01/BG0125HT.BMP~
	~%biff_dir%/AR0125LM.BMP~ ~%biff_dir%/eetBG01/BG0125LM.BMP~
	~%biff_dir%/AR0125SR.BMP~ ~%biff_dir%/eetBG01/BG0125SR.BMP~
	~%biff_dir%/AR0126HT.BMP~ ~%biff_dir%/eetBG01/BG0126HT.BMP~
	~%biff_dir%/AR0126LM.BMP~ ~%biff_dir%/eetBG01/BG0126LM.BMP~
	~%biff_dir%/AR0126SR.BMP~ ~%biff_dir%/eetBG01/BG0126SR.BMP~
	~%biff_dir%/AR0127HT.BMP~ ~%biff_dir%/eetBG01/BG0127HT.BMP~
	~%biff_dir%/AR0127LM.BMP~ ~%biff_dir%/eetBG01/BG0127LM.BMP~
	~%biff_dir%/AR0127SR.BMP~ ~%biff_dir%/eetBG01/BG0127SR.BMP~
	~%biff_dir%/AR0128HT.BMP~ ~%biff_dir%/eetBG01/BG0128HT.BMP~
	~%biff_dir%/AR0128LM.BMP~ ~%biff_dir%/eetBG01/BG0128LM.BMP~
	~%biff_dir%/AR0128SR.BMP~ ~%biff_dir%/eetBG01/BG0128SR.BMP~
	~%biff_dir%/AR0129HT.BMP~ ~%biff_dir%/eetBG01/BG0129HT.BMP~
	~%biff_dir%/AR0129LM.BMP~ ~%biff_dir%/eetBG01/BG0129LM.BMP~
	~%biff_dir%/AR0129SR.BMP~ ~%biff_dir%/eetBG01/BG0129SR.BMP~
	~%biff_dir%/AR0130HT.BMP~ ~%biff_dir%/eetBG01/BG0130HT.BMP~
	~%biff_dir%/AR0130LM.BMP~ ~%biff_dir%/eetBG01/BG0130LM.BMP~
	~%biff_dir%/AR0130SR.BMP~ ~%biff_dir%/eetBG01/BG0130SR.BMP~
	~%biff_dir%/AR0131HT.BMP~ ~%biff_dir%/eetBG01/BG0131HT.BMP~
	~%biff_dir%/AR0131LM.BMP~ ~%biff_dir%/eetBG01/BG0131LM.BMP~
	~%biff_dir%/AR0131SR.BMP~ ~%biff_dir%/eetBG01/BG0131SR.BMP~
	~%biff_dir%/AR0132HT.BMP~ ~%biff_dir%/eetBG01/BG0132HT.BMP~
	~%biff_dir%/AR0132LM.BMP~ ~%biff_dir%/eetBG01/BG0132LM.BMP~
	~%biff_dir%/AR0132SR.BMP~ ~%biff_dir%/eetBG01/BG0132SR.BMP~
	~%biff_dir%/AR0133HT.BMP~ ~%biff_dir%/eetBG01/BG0133HT.BMP~
	~%biff_dir%/AR0133LM.BMP~ ~%biff_dir%/eetBG01/BG0133LM.BMP~
	~%biff_dir%/AR0133SR.BMP~ ~%biff_dir%/eetBG01/BG0133SR.BMP~
	~%biff_dir%/AR0134HT.BMP~ ~%biff_dir%/eetBG01/BG0134HT.BMP~
	~%biff_dir%/AR0134LM.BMP~ ~%biff_dir%/eetBG01/BG0134LM.BMP~
	~%biff_dir%/AR0134SR.BMP~ ~%biff_dir%/eetBG01/BG0134SR.BMP~
	~%biff_dir%/AR0135HT.BMP~ ~%biff_dir%/eetBG01/BG0135HT.BMP~
	~%biff_dir%/AR0135LM.BMP~ ~%biff_dir%/eetBG01/BG0135LM.BMP~
	~%biff_dir%/AR0135SR.BMP~ ~%biff_dir%/eetBG01/BG0135SR.BMP~
	~%biff_dir%/AR0136HT.BMP~ ~%biff_dir%/eetBG01/BG0136HT.BMP~
	~%biff_dir%/AR0136LM.BMP~ ~%biff_dir%/eetBG01/BG0136LM.BMP~
	~%biff_dir%/AR0136SR.BMP~ ~%biff_dir%/eetBG01/BG0136SR.BMP~
	~%biff_dir%/AR0137HT.BMP~ ~%biff_dir%/eetBG01/BG0137HT.BMP~
	~%biff_dir%/AR0137LM.BMP~ ~%biff_dir%/eetBG01/BG0137LM.BMP~
	~%biff_dir%/AR0137SR.BMP~ ~%biff_dir%/eetBG01/BG0137SR.BMP~
	~%biff_dir%/AR0138HT.BMP~ ~%biff_dir%/eetBG01/BG0138HT.BMP~
	~%biff_dir%/AR0138LM.BMP~ ~%biff_dir%/eetBG01/BG0138LM.BMP~
	~%biff_dir%/AR0138SR.BMP~ ~%biff_dir%/eetBG01/BG0138SR.BMP~
	~%biff_dir%/AR0139HT.BMP~ ~%biff_dir%/eetBG01/BG0139HT.BMP~
	~%biff_dir%/AR0139LM.BMP~ ~%biff_dir%/eetBG01/BG0139LM.BMP~
	~%biff_dir%/AR0139SR.BMP~ ~%biff_dir%/eetBG01/BG0139SR.BMP~
	~%biff_dir%/AR0140HT.BMP~ ~%biff_dir%/eetBG01/BG0140HT.BMP~
	~%biff_dir%/AR0140LM.BMP~ ~%biff_dir%/eetBG01/BG0140LM.BMP~
	~%biff_dir%/AR0140SR.BMP~ ~%biff_dir%/eetBG01/BG0140SR.BMP~
	~%biff_dir%/AR0141HT.BMP~ ~%biff_dir%/eetBG01/BG0141HT.BMP~
	~%biff_dir%/AR0141LM.BMP~ ~%biff_dir%/eetBG01/BG0141LM.BMP~
	~%biff_dir%/AR0141SR.BMP~ ~%biff_dir%/eetBG01/BG0141SR.BMP~
	~%biff_dir%/AR0142HT.BMP~ ~%biff_dir%/eetBG01/BG0142HT.BMP~
	~%biff_dir%/AR0142LM.BMP~ ~%biff_dir%/eetBG01/BG0142LM.BMP~
	~%biff_dir%/AR0142SR.BMP~ ~%biff_dir%/eetBG01/BG0142SR.BMP~
	~%biff_dir%/AR0143HT.BMP~ ~%biff_dir%/eetBG01/BG0143HT.BMP~
	~%biff_dir%/AR0143LM.BMP~ ~%biff_dir%/eetBG01/BG0143LM.BMP~
	~%biff_dir%/AR0143SR.BMP~ ~%biff_dir%/eetBG01/BG0143SR.BMP~
	~%biff_dir%/AR0144HT.BMP~ ~%biff_dir%/eetBG01/BG0144HT.BMP~
	~%biff_dir%/AR0144LM.BMP~ ~%biff_dir%/eetBG01/BG0144LM.BMP~
	~%biff_dir%/AR0144SR.BMP~ ~%biff_dir%/eetBG01/BG0144SR.BMP~
	~%biff_dir%/AR0145HT.BMP~ ~%biff_dir%/eetBG01/BG0145HT.BMP~
	~%biff_dir%/AR0145LM.BMP~ ~%biff_dir%/eetBG01/BG0145LM.BMP~
	~%biff_dir%/AR0145SR.BMP~ ~%biff_dir%/eetBG01/BG0145SR.BMP~
	~%biff_dir%/AR0146HT.BMP~ ~%biff_dir%/eetBG01/BG0146HT.BMP~
	~%biff_dir%/AR0146LM.BMP~ ~%biff_dir%/eetBG01/BG0146LM.BMP~
	~%biff_dir%/AR0146SR.BMP~ ~%biff_dir%/eetBG01/BG0146SR.BMP~
	~%biff_dir%/AR0148HT.BMP~ ~%biff_dir%/eetBG01/BG0148HT.BMP~
	~%biff_dir%/AR0148LM.BMP~ ~%biff_dir%/eetBG01/BG0148LM.BMP~
	~%biff_dir%/AR0148SR.BMP~ ~%biff_dir%/eetBG01/BG0148SR.BMP~
	~%biff_dir%/AR0149HT.BMP~ ~%biff_dir%/eetBG01/BG0149HT.BMP~
	~%biff_dir%/AR0149LM.BMP~ ~%biff_dir%/eetBG01/BG0149LM.BMP~
	~%biff_dir%/AR0149SR.BMP~ ~%biff_dir%/eetBG01/BG0149SR.BMP~
	~%biff_dir%/AR0150HT.BMP~ ~%biff_dir%/eetBG01/BG0150HT.BMP~
	~%biff_dir%/AR0150LM.BMP~ ~%biff_dir%/eetBG01/BG0150LM.BMP~
	~%biff_dir%/AR0150SR.BMP~ ~%biff_dir%/eetBG01/BG0150SR.BMP~
	~%biff_dir%/AR0151HT.BMP~ ~%biff_dir%/eetBG01/BG0151HT.BMP~
	~%biff_dir%/AR0151LM.BMP~ ~%biff_dir%/eetBG01/BG0151LM.BMP~
	~%biff_dir%/AR0151SR.BMP~ ~%biff_dir%/eetBG01/BG0151SR.BMP~
	~%biff_dir%/AR0152HT.BMP~ ~%biff_dir%/eetBG01/BG0152HT.BMP~
	~%biff_dir%/AR0152LM.BMP~ ~%biff_dir%/eetBG01/BG0152LM.BMP~
	~%biff_dir%/AR0152SR.BMP~ ~%biff_dir%/eetBG01/BG0152SR.BMP~
	~%biff_dir%/AR0153HT.BMP~ ~%biff_dir%/eetBG01/BG0153HT.BMP~
	~%biff_dir%/AR0153LM.BMP~ ~%biff_dir%/eetBG01/BG0153LM.BMP~
	~%biff_dir%/AR0153SR.BMP~ ~%biff_dir%/eetBG01/BG0153SR.BMP~
	~%biff_dir%/AR0155HT.BMP~ ~%biff_dir%/eetBG01/BG0155HT.BMP~
	~%biff_dir%/AR0155LM.BMP~ ~%biff_dir%/eetBG01/BG0155LM.BMP~
	~%biff_dir%/AR0155SR.BMP~ ~%biff_dir%/eetBG01/BG0155SR.BMP~
	~%biff_dir%/AR0156HT.BMP~ ~%biff_dir%/eetBG01/BG0156HT.BMP~
	~%biff_dir%/AR0156LM.BMP~ ~%biff_dir%/eetBG01/BG0156LM.BMP~
	~%biff_dir%/AR0156SR.BMP~ ~%biff_dir%/eetBG01/BG0156SR.BMP~
	~%biff_dir%/AR0161HT.BMP~ ~%biff_dir%/eetBG01/BG0161HT.BMP~
	~%biff_dir%/AR0161LM.BMP~ ~%biff_dir%/eetBG01/BG0161LM.BMP~
	~%biff_dir%/AR0161SR.BMP~ ~%biff_dir%/eetBG01/BG0161SR.BMP~
	~%biff_dir%/AR0162HT.BMP~ ~%biff_dir%/eetBG01/BG0162HT.BMP~
	~%biff_dir%/AR0162LM.BMP~ ~%biff_dir%/eetBG01/BG0162LM.BMP~
	~%biff_dir%/AR0162SR.BMP~ ~%biff_dir%/eetBG01/BG0162SR.BMP~
	~%biff_dir%/AR0163HT.BMP~ ~%biff_dir%/eetBG01/BG0163HT.BMP~
	~%biff_dir%/AR0163LM.BMP~ ~%biff_dir%/eetBG01/BG0163LM.BMP~
	~%biff_dir%/AR0163SR.BMP~ ~%biff_dir%/eetBG01/BG0163SR.BMP~
	~%biff_dir%/AR0164HT.BMP~ ~%biff_dir%/eetBG01/BG0164HT.BMP~
	~%biff_dir%/AR0164LM.BMP~ ~%biff_dir%/eetBG01/BG0164LM.BMP~
	~%biff_dir%/AR0164SR.BMP~ ~%biff_dir%/eetBG01/BG0164SR.BMP~
	~%biff_dir%/AR0165HT.BMP~ ~%biff_dir%/eetBG01/BG0165HT.BMP~
	~%biff_dir%/AR0165LM.BMP~ ~%biff_dir%/eetBG01/BG0165LM.BMP~
	~%biff_dir%/AR0165SR.BMP~ ~%biff_dir%/eetBG01/BG0165SR.BMP~
	~%biff_dir%/AR0166HT.BMP~ ~%biff_dir%/eetBG01/BG0166HT.BMP~
	~%biff_dir%/AR0166LM.BMP~ ~%biff_dir%/eetBG01/BG0166LM.BMP~
	~%biff_dir%/AR0166SR.BMP~ ~%biff_dir%/eetBG01/BG0166SR.BMP~
	~%biff_dir%/AR0167HT.BMP~ ~%biff_dir%/eetBG01/BG0167HT.BMP~
	~%biff_dir%/AR0167LM.BMP~ ~%biff_dir%/eetBG01/BG0167LM.BMP~
	~%biff_dir%/AR0167SR.BMP~ ~%biff_dir%/eetBG01/BG0167SR.BMP~
	~%biff_dir%/AR0168HT.BMP~ ~%biff_dir%/eetBG01/BG0168HT.BMP~
	~%biff_dir%/AR0168LM.BMP~ ~%biff_dir%/eetBG01/BG0168LM.BMP~
	~%biff_dir%/AR0168SR.BMP~ ~%biff_dir%/eetBG01/BG0168SR.BMP~
	~%biff_dir%/AR0169HT.BMP~ ~%biff_dir%/eetBG01/BG0169HT.BMP~
	~%biff_dir%/AR0169LM.BMP~ ~%biff_dir%/eetBG01/BG0169LM.BMP~
	~%biff_dir%/AR0169SR.BMP~ ~%biff_dir%/eetBG01/BG0169SR.BMP~
	~%biff_dir%/AR0170HT.BMP~ ~%biff_dir%/eetBG01/BG0170HT.BMP~
	~%biff_dir%/AR0170LM.BMP~ ~%biff_dir%/eetBG01/BG0170LM.BMP~
	~%biff_dir%/AR0170SR.BMP~ ~%biff_dir%/eetBG01/BG0170SR.BMP~
	~%biff_dir%/AR0200HT.BMP~ ~%biff_dir%/eetBG02/BG0200HT.BMP~
	~%biff_dir%/AR0200LM.BMP~ ~%biff_dir%/eetBG02/BG0200LM.BMP~
	~%biff_dir%/AR0200LN.BMP~ ~%biff_dir%/eetBG02/BG0200LN.BMP~
	~%biff_dir%/AR0200SR.BMP~ ~%biff_dir%/eetBG02/BG0200SR.BMP~
	~%biff_dir%/AR0224HT.BMP~ ~%biff_dir%/eetBG02/BG0224HT.BMP~
	~%biff_dir%/AR0224LM.BMP~ ~%biff_dir%/eetBG02/BG0224LM.BMP~
	~%biff_dir%/AR0224SR.BMP~ ~%biff_dir%/eetBG02/BG0224SR.BMP~
	~%biff_dir%/AR0225HT.BMP~ ~%biff_dir%/eetBG02/BG0225HT.BMP~
	~%biff_dir%/AR0225LM.BMP~ ~%biff_dir%/eetBG02/BG0225LM.BMP~
	~%biff_dir%/AR0225SR.BMP~ ~%biff_dir%/eetBG02/BG0225SR.BMP~
	~%biff_dir%/AR0226HT.BMP~ ~%biff_dir%/eetBG02/BG0226HT.BMP~
	~%biff_dir%/AR0226LM.BMP~ ~%biff_dir%/eetBG02/BG0226LM.BMP~
	~%biff_dir%/AR0226SR.BMP~ ~%biff_dir%/eetBG02/BG0226SR.BMP~
	~%biff_dir%/AR0300HT.BMP~ ~%biff_dir%/eetBG03/BG0300HT.BMP~
	~%biff_dir%/AR0300LM.BMP~ ~%biff_dir%/eetBG03/BG0300LM.BMP~
	~%biff_dir%/AR0300LN.BMP~ ~%biff_dir%/eetBG03/BG0300LN.BMP~
	~%biff_dir%/AR0300SR.BMP~ ~%biff_dir%/eetBG03/BG0300SR.BMP~
	~%biff_dir%/AR0304HT.BMP~ ~%biff_dir%/eetBG03/BG0304HT.BMP~
	~%biff_dir%/AR0304LM.BMP~ ~%biff_dir%/eetBG03/BG0304LM.BMP~
	~%biff_dir%/AR0304SR.BMP~ ~%biff_dir%/eetBG03/BG0304SR.BMP~
	~%biff_dir%/AR0400HT.BMP~ ~%biff_dir%/eetBG04/BG0400HT.BMP~
	~%biff_dir%/AR0400LM.BMP~ ~%biff_dir%/eetBG04/BG0400LM.BMP~
	~%biff_dir%/AR0400SR.BMP~ ~%biff_dir%/eetBG04/BG0400SR.BMP~
	~%biff_dir%/AR0401HT.BMP~ ~%biff_dir%/eetBG04/BG0401HT.BMP~
	~%biff_dir%/AR0401LM.BMP~ ~%biff_dir%/eetBG04/BG0401LM.BMP~
	~%biff_dir%/AR0401SR.BMP~ ~%biff_dir%/eetBG04/BG0401SR.BMP~
	~%biff_dir%/AR0500HT.BMP~ ~%biff_dir%/eetBG05/BG0500HT.BMP~
	~%biff_dir%/AR0500LM.BMP~ ~%biff_dir%/eetBG05/BG0500LM.BMP~
	~%biff_dir%/AR0500SR.BMP~ ~%biff_dir%/eetBG05/BG0500SR.BMP~
	~%biff_dir%/AR0501HT.BMP~ ~%biff_dir%/eetBG05/BG0501HT.BMP~
	~%biff_dir%/AR0501LM.BMP~ ~%biff_dir%/eetBG05/BG0501LM.BMP~
	~%biff_dir%/AR0501SR.BMP~ ~%biff_dir%/eetBG05/BG0501SR.BMP~
	~%biff_dir%/AR0502HT.BMP~ ~%biff_dir%/eetBG05/BG0502HT.BMP~
	~%biff_dir%/AR0502LM.BMP~ ~%biff_dir%/eetBG05/BG0502LM.BMP~
	~%biff_dir%/AR0502SR.BMP~ ~%biff_dir%/eetBG05/BG0502SR.BMP~
	~%biff_dir%/AR0503HT.BMP~ ~%biff_dir%/eetBG05/BG0503HT.BMP~
	~%biff_dir%/AR0503LM.BMP~ ~%biff_dir%/eetBG05/BG0503LM.BMP~
	~%biff_dir%/AR0503SR.BMP~ ~%biff_dir%/eetBG05/BG0503SR.BMP~
	~%biff_dir%/AR0504HT.BMP~ ~%biff_dir%/eetBG05/BG0504HT.BMP~
	~%biff_dir%/AR0504LM.BMP~ ~%biff_dir%/eetBG05/BG0504LM.BMP~
	~%biff_dir%/AR0504SR.BMP~ ~%biff_dir%/eetBG05/BG0504SR.BMP~
	~%biff_dir%/AR0505HT.BMP~ ~%biff_dir%/eetBG05/BG0505HT.BMP~
	~%biff_dir%/AR0505LM.BMP~ ~%biff_dir%/eetBG05/BG0505LM.BMP~
	~%biff_dir%/AR0505SR.BMP~ ~%biff_dir%/eetBG05/BG0505SR.BMP~
	~%biff_dir%/AR0506HT.BMP~ ~%biff_dir%/eetBG05/BG0506HT.BMP~
	~%biff_dir%/AR0506LM.BMP~ ~%biff_dir%/eetBG05/BG0506LM.BMP~
	~%biff_dir%/AR0506SR.BMP~ ~%biff_dir%/eetBG05/BG0506SR.BMP~
	~%biff_dir%/AR0507HT.BMP~ ~%biff_dir%/eetBG05/BG0507HT.BMP~
	~%biff_dir%/AR0507LM.BMP~ ~%biff_dir%/eetBG05/BG0507LM.BMP~
	~%biff_dir%/AR0507SR.BMP~ ~%biff_dir%/eetBG05/BG0507SR.BMP~
	~%biff_dir%/AR0508HT.BMP~ ~%biff_dir%/eetBG05/BG0508HT.BMP~
	~%biff_dir%/AR0508LM.BMP~ ~%biff_dir%/eetBG05/BG0508LM.BMP~
	~%biff_dir%/AR0508SR.BMP~ ~%biff_dir%/eetBG05/BG0508SR.BMP~
	~%biff_dir%/AR0509HT.BMP~ ~%biff_dir%/eetBG05/BG0509HT.BMP~
	~%biff_dir%/AR0509LM.BMP~ ~%biff_dir%/eetBG05/BG0509LM.BMP~
	~%biff_dir%/AR0509SR.BMP~ ~%biff_dir%/eetBG05/BG0509SR.BMP~
	~%biff_dir%/AR0510HT.BMP~ ~%biff_dir%/eetBG05/BG0510HT.BMP~
	~%biff_dir%/AR0510LM.BMP~ ~%biff_dir%/eetBG05/BG0510LM.BMP~
	~%biff_dir%/AR0510SR.BMP~ ~%biff_dir%/eetBG05/BG0510SR.BMP~
	~%biff_dir%/AR0511HT.BMP~ ~%biff_dir%/eetBG05/BG0511HT.BMP~
	~%biff_dir%/AR0511LM.BMP~ ~%biff_dir%/eetBG05/BG0511LM.BMP~
	~%biff_dir%/AR0511SR.BMP~ ~%biff_dir%/eetBG05/BG0511SR.BMP~
	~%biff_dir%/AR0512HT.BMP~ ~%biff_dir%/eetBG05/BG0512HT.BMP~
	~%biff_dir%/AR0512LM.BMP~ ~%biff_dir%/eetBG05/BG0512LM.BMP~
	~%biff_dir%/AR0512SR.BMP~ ~%biff_dir%/eetBG05/BG0512SR.BMP~
	~%biff_dir%/AR0513HT.BMP~ ~%biff_dir%/eetBG05/BG0513HT.BMP~
	~%biff_dir%/AR0513LM.BMP~ ~%biff_dir%/eetBG05/BG0513LM.BMP~
	~%biff_dir%/AR0513SR.BMP~ ~%biff_dir%/eetBG05/BG0513SR.BMP~
	~%biff_dir%/AR0514HT.BMP~ ~%biff_dir%/eetBG05/BG0514HT.BMP~
	~%biff_dir%/AR0514LM.BMP~ ~%biff_dir%/eetBG05/BG0514LM.BMP~
	~%biff_dir%/AR0514SR.BMP~ ~%biff_dir%/eetBG05/BG0514SR.BMP~
	~%biff_dir%/AR0515HT.BMP~ ~%biff_dir%/eetBG05/BG0515HT.BMP~
	~%biff_dir%/AR0515LM.BMP~ ~%biff_dir%/eetBG05/BG0515LM.BMP~
	~%biff_dir%/AR0515SR.BMP~ ~%biff_dir%/eetBG05/BG0515SR.BMP~
	~%biff_dir%/AR0516HT.BMP~ ~%biff_dir%/eetBG05/BG0516HT.BMP~
	~%biff_dir%/AR0516LM.BMP~ ~%biff_dir%/eetBG05/BG0516LM.BMP~
	~%biff_dir%/AR0516SR.BMP~ ~%biff_dir%/eetBG05/BG0516SR.BMP~
	~%biff_dir%/AR0600HT.BMP~ ~%biff_dir%/eetBG06/BG0600HT.BMP~
	~%biff_dir%/AR0600LM.BMP~ ~%biff_dir%/eetBG06/BG0600LM.BMP~
	~%biff_dir%/AR0600LN.BMP~ ~%biff_dir%/eetBG06/BG0600LN.BMP~
	~%biff_dir%/AR0600SR.BMP~ ~%biff_dir%/eetBG06/BG0600SR.BMP~
	~%biff_dir%/AR0601HT.BMP~ ~%biff_dir%/eetBG06/BG0601HT.BMP~
	~%biff_dir%/AR0601LM.BMP~ ~%biff_dir%/eetBG06/BG0601LM.BMP~
	~%biff_dir%/AR0601SR.BMP~ ~%biff_dir%/eetBG06/BG0601SR.BMP~
	~%biff_dir%/AR0602HT.BMP~ ~%biff_dir%/eetBG06/BG0602HT.BMP~
	~%biff_dir%/AR0602LM.BMP~ ~%biff_dir%/eetBG06/BG0602LM.BMP~
	~%biff_dir%/AR0602SR.BMP~ ~%biff_dir%/eetBG06/BG0602SR.BMP~
	~%biff_dir%/AR0603HT.BMP~ ~%biff_dir%/eetBG06/BG0603HT.BMP~
	~%biff_dir%/AR0603LM.BMP~ ~%biff_dir%/eetBG06/BG0603LM.BMP~
	~%biff_dir%/AR0603SR.BMP~ ~%biff_dir%/eetBG06/BG0603SR.BMP~
	~%biff_dir%/AR0606HT.BMP~ ~%biff_dir%/eetBG06/BG0606HT.BMP~
	~%biff_dir%/AR0606LM.BMP~ ~%biff_dir%/eetBG06/BG0606LM.BMP~
	~%biff_dir%/AR0606SR.BMP~ ~%biff_dir%/eetBG06/BG0606SR.BMP~
	~%biff_dir%/AR0607HT.BMP~ ~%biff_dir%/eetBG06/BG0607HT.BMP~
	~%biff_dir%/AR0607LM.BMP~ ~%biff_dir%/eetBG06/BG0607LM.BMP~
	~%biff_dir%/AR0607SR.BMP~ ~%biff_dir%/eetBG06/BG0607SR.BMP~
	~%biff_dir%/AR0608HT.BMP~ ~%biff_dir%/eetBG06/BG0608HT.BMP~
	~%biff_dir%/AR0608LM.BMP~ ~%biff_dir%/eetBG06/BG0608LM.BMP~
	~%biff_dir%/AR0608SR.BMP~ ~%biff_dir%/eetBG06/BG0608SR.BMP~
	~%biff_dir%/AR0609HT.BMP~ ~%biff_dir%/eetBG06/BG0609HT.BMP~
	~%biff_dir%/AR0609LM.BMP~ ~%biff_dir%/eetBG06/BG0609LM.BMP~
	~%biff_dir%/AR0609SR.BMP~ ~%biff_dir%/eetBG06/BG0609SR.BMP~
	~%biff_dir%/AR0611HT.BMP~ ~%biff_dir%/eetBG06/BG0611HT.BMP~
	~%biff_dir%/AR0611LM.BMP~ ~%biff_dir%/eetBG06/BG0611LM.BMP~
	~%biff_dir%/AR0611SR.BMP~ ~%biff_dir%/eetBG06/BG0611SR.BMP~
	~%biff_dir%/AR0612HT.BMP~ ~%biff_dir%/eetBG06/BG0612HT.BMP~
	~%biff_dir%/AR0612LM.BMP~ ~%biff_dir%/eetBG06/BG0612LM.BMP~
	~%biff_dir%/AR0612SR.BMP~ ~%biff_dir%/eetBG06/BG0612SR.BMP~
	~%biff_dir%/AR0613HT.BMP~ ~%biff_dir%/eetBG06/BG0613HT.BMP~
	~%biff_dir%/AR0613LM.BMP~ ~%biff_dir%/eetBG06/BG0613LM.BMP~
	~%biff_dir%/AR0613SR.BMP~ ~%biff_dir%/eetBG06/BG0613SR.BMP~
	~%biff_dir%/AR0614HT.BMP~ ~%biff_dir%/eetBG06/BG0614HT.BMP~
	~%biff_dir%/AR0614LM.BMP~ ~%biff_dir%/eetBG06/BG0614LM.BMP~
	~%biff_dir%/AR0614SR.BMP~ ~%biff_dir%/eetBG06/BG0614SR.BMP~
	~%biff_dir%/AR0615HT.BMP~ ~%biff_dir%/eetBG06/BG0615HT.BMP~
	~%biff_dir%/AR0615LM.BMP~ ~%biff_dir%/eetBG06/BG0615LM.BMP~
	~%biff_dir%/AR0615SR.BMP~ ~%biff_dir%/eetBG06/BG0615SR.BMP~
	~%biff_dir%/AR0616HT.BMP~ ~%biff_dir%/eetBG06/BG0616HT.BMP~
	~%biff_dir%/AR0616LM.BMP~ ~%biff_dir%/eetBG06/BG0616LM.BMP~
	~%biff_dir%/AR0616SR.BMP~ ~%biff_dir%/eetBG06/BG0616SR.BMP~
	~%biff_dir%/AR0621HT.BMP~ ~%biff_dir%/eetBG06/BG0621HT.BMP~
	~%biff_dir%/AR0621LM.BMP~ ~%biff_dir%/eetBG06/BG0621LM.BMP~
	~%biff_dir%/AR0621LN.BMP~ ~%biff_dir%/eetBG06/BG0621LN.BMP~
	~%biff_dir%/AR0621SR.BMP~ ~%biff_dir%/eetBG06/BG0621SR.BMP~
	~%biff_dir%/AR0700HT.BMP~ ~%biff_dir%/eetBG07/BG0700HT.BMP~
	~%biff_dir%/AR0700LM.BMP~ ~%biff_dir%/eetBG07/BG0700LM.BMP~
	~%biff_dir%/AR0700LN.BMP~ ~%biff_dir%/eetBG07/BG0700LN.BMP~
	~%biff_dir%/AR0700SR.BMP~ ~%biff_dir%/eetBG07/BG0700SR.BMP~
	~%biff_dir%/AR0702HT.BMP~ ~%biff_dir%/eetBG07/BG0702HT.BMP~
	~%biff_dir%/AR0702LM.BMP~ ~%biff_dir%/eetBG07/BG0702LM.BMP~
	~%biff_dir%/AR0702SR.BMP~ ~%biff_dir%/eetBG07/BG0702SR.BMP~
	~%biff_dir%/AR0703HT.BMP~ ~%biff_dir%/eetBG07/BG0703HT.BMP~
	~%biff_dir%/AR0703LM.BMP~ ~%biff_dir%/eetBG07/BG0703LM.BMP~
	~%biff_dir%/AR0703SR.BMP~ ~%biff_dir%/eetBG07/BG0703SR.BMP~
	~%biff_dir%/AR0704HT.BMP~ ~%biff_dir%/eetBG07/BG0704HT.BMP~
	~%biff_dir%/AR0704LM.BMP~ ~%biff_dir%/eetBG07/BG0704LM.BMP~
	~%biff_dir%/AR0704SR.BMP~ ~%biff_dir%/eetBG07/BG0704SR.BMP~
	~%biff_dir%/AR0705HT.BMP~ ~%biff_dir%/eetBG07/BG0705HT.BMP~
	~%biff_dir%/AR0705LM.BMP~ ~%biff_dir%/eetBG07/BG0705LM.BMP~
	~%biff_dir%/AR0705SR.BMP~ ~%biff_dir%/eetBG07/BG0705SR.BMP~
	~%biff_dir%/AR0706HT.BMP~ ~%biff_dir%/eetBG07/BG0706HT.BMP~
	~%biff_dir%/AR0706LM.BMP~ ~%biff_dir%/eetBG07/BG0706LM.BMP~
	~%biff_dir%/AR0706SR.BMP~ ~%biff_dir%/eetBG07/BG0706SR.BMP~
	~%biff_dir%/AR0719HT.BMP~ ~%biff_dir%/eetBG07/BG0719HT.BMP~
	~%biff_dir%/AR0719LM.BMP~ ~%biff_dir%/eetBG07/BG0719LM.BMP~
	~%biff_dir%/AR0719SR.BMP~ ~%biff_dir%/eetBG07/BG0719SR.BMP~
	~%biff_dir%/AR0720HT.BMP~ ~%biff_dir%/eetBG07/BG0720HT.BMP~
	~%biff_dir%/AR0720LM.BMP~ ~%biff_dir%/eetBG07/BG0720LM.BMP~
	~%biff_dir%/AR0720SR.BMP~ ~%biff_dir%/eetBG07/BG0720SR.BMP~
	~%biff_dir%/AR0724HT.BMP~ ~%biff_dir%/eetBG07/BG0724HT.BMP~
	~%biff_dir%/AR0724LM.BMP~ ~%biff_dir%/eetBG07/BG0724LM.BMP~
	~%biff_dir%/AR0724SR.BMP~ ~%biff_dir%/eetBG07/BG0724SR.BMP~
	~%biff_dir%/AR0726HT.BMP~ ~%biff_dir%/eetBG07/BG0726HT.BMP~
	~%biff_dir%/AR0726LM.BMP~ ~%biff_dir%/eetBG07/BG0726LM.BMP~
	~%biff_dir%/AR0726SR.BMP~ ~%biff_dir%/eetBG07/BG0726SR.BMP~
	~%biff_dir%/AR0800HT.BMP~ ~%biff_dir%/eetBG08/BG0800HT.BMP~
	~%biff_dir%/AR0800LM.BMP~ ~%biff_dir%/eetBG08/BG0800LM.BMP~
	~%biff_dir%/AR0800LN.BMP~ ~%biff_dir%/eetBG08/BG0800LN.BMP~
	~%biff_dir%/AR0800SR.BMP~ ~%biff_dir%/eetBG08/BG0800SR.BMP~
	~%biff_dir%/AR0807HT.BMP~ ~%biff_dir%/eetBG08/BG0807HT.BMP~
	~%biff_dir%/AR0807LM.BMP~ ~%biff_dir%/eetBG08/BG0807LM.BMP~
	~%biff_dir%/AR0807SR.BMP~ ~%biff_dir%/eetBG08/BG0807SR.BMP~
	~%biff_dir%/AR0808HT.BMP~ ~%biff_dir%/eetBG08/BG0808HT.BMP~
	~%biff_dir%/AR0808LM.BMP~ ~%biff_dir%/eetBG08/BG0808LM.BMP~
	~%biff_dir%/AR0808SR.BMP~ ~%biff_dir%/eetBG08/BG0808SR.BMP~
	~%biff_dir%/AR0809HT.BMP~ ~%biff_dir%/eetBG08/BG0809HT.BMP~
	~%biff_dir%/AR0809LM.BMP~ ~%biff_dir%/eetBG08/BG0809LM.BMP~
	~%biff_dir%/AR0809SR.BMP~ ~%biff_dir%/eetBG08/BG0809SR.BMP~
	~%biff_dir%/AR0900HT.BMP~ ~%biff_dir%/eetBG09/BG0900HT.BMP~
	~%biff_dir%/AR0900LM.BMP~ ~%biff_dir%/eetBG09/BG0900LM.BMP~
	~%biff_dir%/AR0900LN.BMP~ ~%biff_dir%/eetBG09/BG0900LN.BMP~
	~%biff_dir%/AR0900SR.BMP~ ~%biff_dir%/eetBG09/BG0900SR.BMP~
	~%biff_dir%/AR0901HT.BMP~ ~%biff_dir%/eetBG09/BG0901HT.BMP~
	~%biff_dir%/AR0901LM.BMP~ ~%biff_dir%/eetBG09/BG0901LM.BMP~
	~%biff_dir%/AR0901SR.BMP~ ~%biff_dir%/eetBG09/BG0901SR.BMP~
	~%biff_dir%/AR1000HT.BMP~ ~%biff_dir%/eetBG10/BG1000HT.BMP~
	~%biff_dir%/AR1000LM.BMP~ ~%biff_dir%/eetBG10/BG1000LM.BMP~
	~%biff_dir%/AR1000SR.BMP~ ~%biff_dir%/eetBG10/BG1000SR.BMP~
	~%biff_dir%/AR1001HT.BMP~ ~%biff_dir%/eetBG10/BG1001HT.BMP~
	~%biff_dir%/AR1001LM.BMP~ ~%biff_dir%/eetBG10/BG1001LM.BMP~
	~%biff_dir%/AR1001SR.BMP~ ~%biff_dir%/eetBG10/BG1001SR.BMP~
	~%biff_dir%/AR1002HT.BMP~ ~%biff_dir%/eetBG10/BG1002HT.BMP~
	~%biff_dir%/AR1002LM.BMP~ ~%biff_dir%/eetBG10/BG1002LM.BMP~
	~%biff_dir%/AR1002SR.BMP~ ~%biff_dir%/eetBG10/BG1002SR.BMP~
	~%biff_dir%/AR1003HT.BMP~ ~%biff_dir%/eetBG10/BG1003HT.BMP~
	~%biff_dir%/AR1003LM.BMP~ ~%biff_dir%/eetBG10/BG1003LM.BMP~
	~%biff_dir%/AR1003SR.BMP~ ~%biff_dir%/eetBG10/BG1003SR.BMP~
	~%biff_dir%/AR1004HT.BMP~ ~%biff_dir%/eetBG10/BG1004HT.BMP~
	~%biff_dir%/AR1004LM.BMP~ ~%biff_dir%/eetBG10/BG1004LM.BMP~
	~%biff_dir%/AR1004SR.BMP~ ~%biff_dir%/eetBG10/BG1004SR.BMP~
	~%biff_dir%/AR1005HT.BMP~ ~%biff_dir%/eetBG10/BG1005HT.BMP~
	~%biff_dir%/AR1005LM.BMP~ ~%biff_dir%/eetBG10/BG1005LM.BMP~
	~%biff_dir%/AR1005SR.BMP~ ~%biff_dir%/eetBG10/BG1005SR.BMP~
	~%biff_dir%/AR1008HT.BMP~ ~%biff_dir%/eetBG10/BG1008HT.BMP~
	~%biff_dir%/AR1008LM.BMP~ ~%biff_dir%/eetBG10/BG1008LM.BMP~
	~%biff_dir%/AR1008SR.BMP~ ~%biff_dir%/eetBG10/BG1008SR.BMP~
	~%biff_dir%/AR1009HT.BMP~ ~%biff_dir%/eetBG10/BG1009HT.BMP~
	~%biff_dir%/AR1009LM.BMP~ ~%biff_dir%/eetBG10/BG1009LM.BMP~
	~%biff_dir%/AR1009SR.BMP~ ~%biff_dir%/eetBG10/BG1009SR.BMP~
	~%biff_dir%/AR1010HT.BMP~ ~%biff_dir%/eetBG10/BG1010HT.BMP~
	~%biff_dir%/AR1010LM.BMP~ ~%biff_dir%/eetBG10/BG1010LM.BMP~
	~%biff_dir%/AR1010SR.BMP~ ~%biff_dir%/eetBG10/BG1010SR.BMP~
	~%biff_dir%/AR1100HT.BMP~ ~%biff_dir%/eetBG11/BG1100HT.BMP~
	~%biff_dir%/AR1100LM.BMP~ ~%biff_dir%/eetBG11/BG1100LM.BMP~
	~%biff_dir%/AR1100LN.BMP~ ~%biff_dir%/eetBG11/BG1100LN.BMP~
	~%biff_dir%/AR1100SR.BMP~ ~%biff_dir%/eetBG11/BG1100SR.BMP~
	~%biff_dir%/AR1101HT.BMP~ ~%biff_dir%/eetBG11/BG1101HT.BMP~
	~%biff_dir%/AR1101LM.BMP~ ~%biff_dir%/eetBG11/BG1101LM.BMP~
	~%biff_dir%/AR1101SR.BMP~ ~%biff_dir%/eetBG11/BG1101SR.BMP~
	~%biff_dir%/AR1102HT.BMP~ ~%biff_dir%/eetBG11/BG1102HT.BMP~
	~%biff_dir%/AR1102LM.BMP~ ~%biff_dir%/eetBG11/BG1102LM.BMP~
	~%biff_dir%/AR1102SR.BMP~ ~%biff_dir%/eetBG11/BG1102SR.BMP~
	~%biff_dir%/AR1200HT.BMP~ ~%biff_dir%/eetBG12/BG1200HT.BMP~
	~%biff_dir%/AR1200LM.BMP~ ~%biff_dir%/eetBG12/BG1200LM.BMP~
	~%biff_dir%/AR1200LN.BMP~ ~%biff_dir%/eetBG12/BG1200LN.BMP~
	~%biff_dir%/AR1200SR.BMP~ ~%biff_dir%/eetBG12/BG1200SR.BMP~
	~%biff_dir%/AR1207HT.BMP~ ~%biff_dir%/eetBG12/BG1207HT.BMP~
	~%biff_dir%/AR1207LM.BMP~ ~%biff_dir%/eetBG12/BG1207LM.BMP~
	~%biff_dir%/AR1207SR.BMP~ ~%biff_dir%/eetBG12/BG1207SR.BMP~
	~%biff_dir%/AR1208HT.BMP~ ~%biff_dir%/eetBG12/BG1208HT.BMP~
	~%biff_dir%/AR1208LM.BMP~ ~%biff_dir%/eetBG12/BG1208LM.BMP~
	~%biff_dir%/AR1208SR.BMP~ ~%biff_dir%/eetBG12/BG1208SR.BMP~
	~%biff_dir%/AR1215HT.BMP~ ~%biff_dir%/eetBG12/BG1215HT.BMP~
	~%biff_dir%/AR1215LM.BMP~ ~%biff_dir%/eetBG12/BG1215LM.BMP~
	~%biff_dir%/AR1215SR.BMP~ ~%biff_dir%/eetBG12/BG1215SR.BMP~
	~%biff_dir%/AR1300HT.BMP~ ~%biff_dir%/eetBG13/BG1300HT.BMP~
	~%biff_dir%/AR1300LM.BMP~ ~%biff_dir%/eetBG13/BG1300LM.BMP~
	~%biff_dir%/AR1300LN.BMP~ ~%biff_dir%/eetBG13/BG1300LN.BMP~
	~%biff_dir%/AR1300SR.BMP~ ~%biff_dir%/eetBG13/BG1300SR.BMP~
	~%biff_dir%/AR1302HT.BMP~ ~%biff_dir%/eetBG13/BG1302HT.BMP~
	~%biff_dir%/AR1302LM.BMP~ ~%biff_dir%/eetBG13/BG1302LM.BMP~
	~%biff_dir%/AR1302SR.BMP~ ~%biff_dir%/eetBG13/BG1302SR.BMP~
	~%biff_dir%/AR1320LM.BMP~ ~%biff_dir%/eetBG13/BG1320LM.BMP~
	~%biff_dir%/AR1400HT.BMP~ ~%biff_dir%/eetBG14/BG1400HT.BMP~
	~%biff_dir%/AR1400LM.BMP~ ~%biff_dir%/eetBG14/BG1400LM.BMP~
	~%biff_dir%/AR1400SR.BMP~ ~%biff_dir%/eetBG14/BG1400SR.BMP~
	~%biff_dir%/AR1401HT.BMP~ ~%biff_dir%/eetBG14/BG1401HT.BMP~
	~%biff_dir%/AR1401LM.BMP~ ~%biff_dir%/eetBG14/BG1401LM.BMP~
	~%biff_dir%/AR1401SR.BMP~ ~%biff_dir%/eetBG14/BG1401SR.BMP~
	~%biff_dir%/AR1402HT.BMP~ ~%biff_dir%/eetBG14/BG1402HT.BMP~
	~%biff_dir%/AR1402LM.BMP~ ~%biff_dir%/eetBG14/BG1402LM.BMP~
	~%biff_dir%/AR1402SR.BMP~ ~%biff_dir%/eetBG14/BG1402SR.BMP~
	~%biff_dir%/AR1403HT.BMP~ ~%biff_dir%/eetBG14/BG1403HT.BMP~
	~%biff_dir%/AR1403LM.BMP~ ~%biff_dir%/eetBG14/BG1403LM.BMP~
	~%biff_dir%/AR1403SR.BMP~ ~%biff_dir%/eetBG14/BG1403SR.BMP~
	~%biff_dir%/AR1404HT.BMP~ ~%biff_dir%/eetBG14/BG1404HT.BMP~
	~%biff_dir%/AR1404LM.BMP~ ~%biff_dir%/eetBG14/BG1404LM.BMP~
	~%biff_dir%/AR1404SR.BMP~ ~%biff_dir%/eetBG14/BG1404SR.BMP~
	~%biff_dir%/AR1500HT.BMP~ ~%biff_dir%/eetBG15/BG1500HT.BMP~
	~%biff_dir%/AR1500LM.BMP~ ~%biff_dir%/eetBG15/BG1500LM.BMP~
	~%biff_dir%/AR1500SR.BMP~ ~%biff_dir%/eetBG15/BG1500SR.BMP~
	~%biff_dir%/AR1501HT.BMP~ ~%biff_dir%/eetBG15/BG1501HT.BMP~
	~%biff_dir%/AR1501LM.BMP~ ~%biff_dir%/eetBG15/BG1501LM.BMP~
	~%biff_dir%/AR1501SR.BMP~ ~%biff_dir%/eetBG15/BG1501SR.BMP~
	~%biff_dir%/AR1502HT.BMP~ ~%biff_dir%/eetBG15/BG1502HT.BMP~
	~%biff_dir%/AR1502LM.BMP~ ~%biff_dir%/eetBG15/BG1502LM.BMP~
	~%biff_dir%/AR1502SR.BMP~ ~%biff_dir%/eetBG15/BG1502SR.BMP~
	~%biff_dir%/AR1503HT.BMP~ ~%biff_dir%/eetBG15/BG1503HT.BMP~
	~%biff_dir%/AR1503LM.BMP~ ~%biff_dir%/eetBG15/BG1503LM.BMP~
	~%biff_dir%/AR1503SR.BMP~ ~%biff_dir%/eetBG15/BG1503SR.BMP~
	~%biff_dir%/AR1504HT.BMP~ ~%biff_dir%/eetBG15/BG1504HT.BMP~
	~%biff_dir%/AR1504LM.BMP~ ~%biff_dir%/eetBG15/BG1504LM.BMP~
	~%biff_dir%/AR1504SR.BMP~ ~%biff_dir%/eetBG15/BG1504SR.BMP~
	~%biff_dir%/AR1505HT.BMP~ ~%biff_dir%/eetBG15/BG1505HT.BMP~
	~%biff_dir%/AR1505LM.BMP~ ~%biff_dir%/eetBG15/BG1505LM.BMP~
	~%biff_dir%/AR1505SR.BMP~ ~%biff_dir%/eetBG15/BG1505SR.BMP~
	~%biff_dir%/AR1600HT.BMP~ ~%biff_dir%/eetBG16/BG1600HT.BMP~
	~%biff_dir%/AR1600LM.BMP~ ~%biff_dir%/eetBG16/BG1600LM.BMP~
	~%biff_dir%/AR1600SR.BMP~ ~%biff_dir%/eetBG16/BG1600SR.BMP~
	~%biff_dir%/AR1601HT.BMP~ ~%biff_dir%/eetBG16/BG1601HT.BMP~
	~%biff_dir%/AR1601LM.BMP~ ~%biff_dir%/eetBG16/BG1601LM.BMP~
	~%biff_dir%/AR1601SR.BMP~ ~%biff_dir%/eetBG16/BG1601SR.BMP~
	~%biff_dir%/AR1602HT.BMP~ ~%biff_dir%/eetBG16/BG1602HT.BMP~
	~%biff_dir%/AR1602LM.BMP~ ~%biff_dir%/eetBG16/BG1602LM.BMP~
	~%biff_dir%/AR1602SR.BMP~ ~%biff_dir%/eetBG16/BG1602SR.BMP~
	~%biff_dir%/AR1603HT.BMP~ ~%biff_dir%/eetBG16/BG1603HT.BMP~
	~%biff_dir%/AR1603LM.BMP~ ~%biff_dir%/eetBG16/BG1603LM.BMP~
	~%biff_dir%/AR1603SR.BMP~ ~%biff_dir%/eetBG16/BG1603SR.BMP~
	~%biff_dir%/AR1700HT.BMP~ ~%biff_dir%/eetBG17/BG1700HT.BMP~
	~%biff_dir%/AR1700LM.BMP~ ~%biff_dir%/eetBG17/BG1700LM.BMP~
	~%biff_dir%/AR1700SR.BMP~ ~%biff_dir%/eetBG17/BG1700SR.BMP~
	~%biff_dir%/AR1800HT.BMP~ ~%biff_dir%/eetBG18/BG1800HT.BMP~
	~%biff_dir%/AR1800LM.BMP~ ~%biff_dir%/eetBG18/BG1800LM.BMP~
	~%biff_dir%/AR1800SR.BMP~ ~%biff_dir%/eetBG18/BG1800SR.BMP~
	~%biff_dir%/AR1801HT.BMP~ ~%biff_dir%/eetBG18/BG1801HT.BMP~
	~%biff_dir%/AR1801LM.BMP~ ~%biff_dir%/eetBG18/BG1801LM.BMP~
	~%biff_dir%/AR1801SR.BMP~ ~%biff_dir%/eetBG18/BG1801SR.BMP~
	~%biff_dir%/AR1802HT.BMP~ ~%biff_dir%/eetBG18/BG1802HT.BMP~
	~%biff_dir%/AR1802LM.BMP~ ~%biff_dir%/eetBG18/BG1802LM.BMP~
	~%biff_dir%/AR1802SR.BMP~ ~%biff_dir%/eetBG18/BG1802SR.BMP~
	~%biff_dir%/AR1803HT.BMP~ ~%biff_dir%/eetBG18/BG1803HT.BMP~
	~%biff_dir%/AR1803LM.BMP~ ~%biff_dir%/eetBG18/BG1803LM.BMP~
	~%biff_dir%/AR1803SR.BMP~ ~%biff_dir%/eetBG18/BG1803SR.BMP~
	~%biff_dir%/AR1804HT.BMP~ ~%biff_dir%/eetBG18/BG1804HT.BMP~
	~%biff_dir%/AR1804LM.BMP~ ~%biff_dir%/eetBG18/BG1804LM.BMP~
	~%biff_dir%/AR1804SR.BMP~ ~%biff_dir%/eetBG18/BG1804SR.BMP~
	~%biff_dir%/AR1805HT.BMP~ ~%biff_dir%/eetBG18/BG1805HT.BMP~
	~%biff_dir%/AR1805LM.BMP~ ~%biff_dir%/eetBG18/BG1805LM.BMP~
	~%biff_dir%/AR1805SR.BMP~ ~%biff_dir%/eetBG18/BG1805SR.BMP~
	~%biff_dir%/AR1806HT.BMP~ ~%biff_dir%/eetBG18/BG1806HT.BMP~
	~%biff_dir%/AR1806LM.BMP~ ~%biff_dir%/eetBG18/BG1806LM.BMP~
	~%biff_dir%/AR1806SR.BMP~ ~%biff_dir%/eetBG18/BG1806SR.BMP~
	~%biff_dir%/AR1807HT.BMP~ ~%biff_dir%/eetBG18/BG1807HT.BMP~
	~%biff_dir%/AR1807LM.BMP~ ~%biff_dir%/eetBG18/BG1807LM.BMP~
	~%biff_dir%/AR1807SR.BMP~ ~%biff_dir%/eetBG18/BG1807SR.BMP~
	~%biff_dir%/AR1808HT.BMP~ ~%biff_dir%/eetBG18/BG1808HT.BMP~
	~%biff_dir%/AR1808LM.BMP~ ~%biff_dir%/eetBG18/BG1808LM.BMP~
	~%biff_dir%/AR1808SR.BMP~ ~%biff_dir%/eetBG18/BG1808SR.BMP~
	~%biff_dir%/AR1809HT.BMP~ ~%biff_dir%/eetBG18/BG1809HT.BMP~
	~%biff_dir%/AR1809LM.BMP~ ~%biff_dir%/eetBG18/BG1809LM.BMP~
	~%biff_dir%/AR1809SR.BMP~ ~%biff_dir%/eetBG18/BG1809SR.BMP~
	~%biff_dir%/AR1900HT.BMP~ ~%biff_dir%/eetBG19/BG1900HT.BMP~
	~%biff_dir%/AR1900LM.BMP~ ~%biff_dir%/eetBG19/BG1900LM.BMP~
	~%biff_dir%/AR1900LN.BMP~ ~%biff_dir%/eetBG19/BG1900LN.BMP~
	~%biff_dir%/AR1900SR.BMP~ ~%biff_dir%/eetBG19/BG1900SR.BMP~
	~%biff_dir%/AR1901HT.BMP~ ~%biff_dir%/eetBG19/BG1901HT.BMP~
	~%biff_dir%/AR1901LM.BMP~ ~%biff_dir%/eetBG19/BG1901LM.BMP~
	~%biff_dir%/AR1901SR.BMP~ ~%biff_dir%/eetBG19/BG1901SR.BMP~
	~%biff_dir%/AR1902HT.BMP~ ~%biff_dir%/eetBG19/BG1902HT.BMP~
	~%biff_dir%/AR1902LM.BMP~ ~%biff_dir%/eetBG19/BG1902LM.BMP~
	~%biff_dir%/AR1902SR.BMP~ ~%biff_dir%/eetBG19/BG1902SR.BMP~
	~%biff_dir%/AR1903HT.BMP~ ~%biff_dir%/eetBG19/BG1903HT.BMP~
	~%biff_dir%/AR1903LM.BMP~ ~%biff_dir%/eetBG19/BG1903LM.BMP~
	~%biff_dir%/AR1903SR.BMP~ ~%biff_dir%/eetBG19/BG1903SR.BMP~
	~%biff_dir%/AR2000HT.BMP~ ~%biff_dir%/eetBG20/BG2000HT.BMP~
	~%biff_dir%/AR2000LM.BMP~ ~%biff_dir%/eetBG20/BG2000LM.BMP~
	~%biff_dir%/AR2000SR.BMP~ ~%biff_dir%/eetBG20/BG2000SR.BMP~
	~%biff_dir%/AR2001HT.BMP~ ~%biff_dir%/eetBG20/BG2001HT.BMP~
	~%biff_dir%/AR2001LM.BMP~ ~%biff_dir%/eetBG20/BG2001LM.BMP~
	~%biff_dir%/AR2001SR.BMP~ ~%biff_dir%/eetBG20/BG2001SR.BMP~
	~%biff_dir%/AR2002HT.BMP~ ~%biff_dir%/eetBG20/BG2002HT.BMP~
	~%biff_dir%/AR2002LM.BMP~ ~%biff_dir%/eetBG20/BG2002LM.BMP~
	~%biff_dir%/AR2002SR.BMP~ ~%biff_dir%/eetBG20/BG2002SR.BMP~
	~%biff_dir%/AR2004HT.BMP~ ~%biff_dir%/eetBG20/BG2004HT.BMP~
	~%biff_dir%/AR2004LM.BMP~ ~%biff_dir%/eetBG20/BG2004LM.BMP~
	~%biff_dir%/AR2004SR.BMP~ ~%biff_dir%/eetBG20/BG2004SR.BMP~
	~%biff_dir%/AR2006HT.BMP~ ~%biff_dir%/eetBG20/BG2006HT.BMP~
	~%biff_dir%/AR2006LM.BMP~ ~%biff_dir%/eetBG20/BG2006LM.BMP~
	~%biff_dir%/AR2006SR.BMP~ ~%biff_dir%/eetBG20/BG2006SR.BMP~
	~%biff_dir%/AR2008HT.BMP~ ~%biff_dir%/eetBG20/BG2008HT.BMP~
	~%biff_dir%/AR2008LM.BMP~ ~%biff_dir%/eetBG20/BG2008LM.BMP~
	~%biff_dir%/AR2008SR.BMP~ ~%biff_dir%/eetBG20/BG2008SR.BMP~
	~%biff_dir%/AR2012HT.BMP~ ~%biff_dir%/eetBG20/BG2012HT.BMP~
	~%biff_dir%/AR2012LM.BMP~ ~%biff_dir%/eetBG20/BG2012LM.BMP~
	~%biff_dir%/AR2012SR.BMP~ ~%biff_dir%/eetBG20/BG2012SR.BMP~
	~%biff_dir%/AR2100HT.BMP~ ~%biff_dir%/eetBG21/BG2100HT.BMP~
	~%biff_dir%/AR2100LM.BMP~ ~%biff_dir%/eetBG21/BG2100LM.BMP~
	~%biff_dir%/AR2100SR.BMP~ ~%biff_dir%/eetBG21/BG2100SR.BMP~
	~%biff_dir%/AR2101HT.BMP~ ~%biff_dir%/eetBG21/BG2101HT.BMP~
	~%biff_dir%/AR2101LM.BMP~ ~%biff_dir%/eetBG21/BG2101LM.BMP~
	~%biff_dir%/AR2101SR.BMP~ ~%biff_dir%/eetBG21/BG2101SR.BMP~
	~%biff_dir%/AR2200HT.BMP~ ~%biff_dir%/eetBG22/BG2200HT.BMP~
	~%biff_dir%/AR2200LM.BMP~ ~%biff_dir%/eetBG22/BG2200LM.BMP~
	~%biff_dir%/AR2200SR.BMP~ ~%biff_dir%/eetBG22/BG2200SR.BMP~
	~%biff_dir%/AR2215HT.BMP~ ~%biff_dir%/eetBG22/BG2215HT.BMP~
	~%biff_dir%/AR2215LM.BMP~ ~%biff_dir%/eetBG22/BG2215LM.BMP~
	~%biff_dir%/AR2215SR.BMP~ ~%biff_dir%/eetBG22/BG2215SR.BMP~
	~%biff_dir%/AR2300HT.BMP~ ~%biff_dir%/eetBG23/BG2300HT.BMP~
	~%biff_dir%/AR2300LM.BMP~ ~%biff_dir%/eetBG23/BG2300LM.BMP~
	~%biff_dir%/AR2300LN.BMP~ ~%biff_dir%/eetBG23/BG2300LN.BMP~
	~%biff_dir%/AR2300SR.BMP~ ~%biff_dir%/eetBG23/BG2300SR.BMP~
	~%biff_dir%/AR2301HT.BMP~ ~%biff_dir%/eetBG23/BG2301HT.BMP~
	~%biff_dir%/AR2301LM.BMP~ ~%biff_dir%/eetBG23/BG2301LM.BMP~
	~%biff_dir%/AR2301SR.BMP~ ~%biff_dir%/eetBG23/BG2301SR.BMP~
	~%biff_dir%/AR2302HT.BMP~ ~%biff_dir%/eetBG23/BG2302HT.BMP~
	~%biff_dir%/AR2302LM.BMP~ ~%biff_dir%/eetBG23/BG2302LM.BMP~
	~%biff_dir%/AR2302SR.BMP~ ~%biff_dir%/eetBG23/BG2302SR.BMP~
	~%biff_dir%/AR2303HT.BMP~ ~%biff_dir%/eetBG23/BG2303HT.BMP~
	~%biff_dir%/AR2303LM.BMP~ ~%biff_dir%/eetBG23/BG2303LM.BMP~
	~%biff_dir%/AR2303SR.BMP~ ~%biff_dir%/eetBG23/BG2303SR.BMP~
	~%biff_dir%/AR2304HT.BMP~ ~%biff_dir%/eetBG23/BG2304HT.BMP~
	~%biff_dir%/AR2304LM.BMP~ ~%biff_dir%/eetBG23/BG2304LM.BMP~
	~%biff_dir%/AR2304SR.BMP~ ~%biff_dir%/eetBG23/BG2304SR.BMP~
	~%biff_dir%/AR2305HT.BMP~ ~%biff_dir%/eetBG23/BG2305HT.BMP~
	~%biff_dir%/AR2305LM.BMP~ ~%biff_dir%/eetBG23/BG2305LM.BMP~
	~%biff_dir%/AR2305SR.BMP~ ~%biff_dir%/eetBG23/BG2305SR.BMP~
	~%biff_dir%/AR2306HT.BMP~ ~%biff_dir%/eetBG23/BG2306HT.BMP~
	~%biff_dir%/AR2306LM.BMP~ ~%biff_dir%/eetBG23/BG2306LM.BMP~
	~%biff_dir%/AR2306SR.BMP~ ~%biff_dir%/eetBG23/BG2306SR.BMP~
	~%biff_dir%/AR2400HT.BMP~ ~%biff_dir%/eetBG24/BG2400HT.BMP~
	~%biff_dir%/AR2400LM.BMP~ ~%biff_dir%/eetBG24/BG2400LM.BMP~
	~%biff_dir%/AR2400SR.BMP~ ~%biff_dir%/eetBG24/BG2400SR.BMP~
	~%biff_dir%/AR2600HT.BMP~ ~%biff_dir%/eetBG26/BG2600HT.BMP~
	~%biff_dir%/AR2600LM.BMP~ ~%biff_dir%/eetBG26/BG2600LM.BMP~
	~%biff_dir%/AR2600LN.BMP~ ~%biff_dir%/eetBG26/BG2600LN.BMP~
	~%biff_dir%/AR2600SR.BMP~ ~%biff_dir%/eetBG26/BG2600SR.BMP~
	~%biff_dir%/AR2602HT.BMP~ ~%biff_dir%/eetBG26/BG2602HT.BMP~
	~%biff_dir%/AR2602LM.BMP~ ~%biff_dir%/eetBG26/BG2602LM.BMP~
	~%biff_dir%/AR2602SR.BMP~ ~%biff_dir%/eetBG26/BG2602SR.BMP~
	~%biff_dir%/AR2605HT.BMP~ ~%biff_dir%/eetBG26/BG2605HT.BMP~
	~%biff_dir%/AR2605LM.BMP~ ~%biff_dir%/eetBG26/BG2605LM.BMP~
	~%biff_dir%/AR2605SR.BMP~ ~%biff_dir%/eetBG26/BG2605SR.BMP~
	~%biff_dir%/AR2606HT.BMP~ ~%biff_dir%/eetBG26/BG2606HT.BMP~
	~%biff_dir%/AR2606LM.BMP~ ~%biff_dir%/eetBG26/BG2606LM.BMP~
	~%biff_dir%/AR2606SR.BMP~ ~%biff_dir%/eetBG26/BG2606SR.BMP~
	~%biff_dir%/AR2607HT.BMP~ ~%biff_dir%/eetBG26/BG2607HT.BMP~
	~%biff_dir%/AR2607LM.BMP~ ~%biff_dir%/eetBG26/BG2607LM.BMP~
	~%biff_dir%/AR2607SR.BMP~ ~%biff_dir%/eetBG26/BG2607SR.BMP~
	~%biff_dir%/AR2608HT.BMP~ ~%biff_dir%/eetBG26/BG2608HT.BMP~
	~%biff_dir%/AR2608LM.BMP~ ~%biff_dir%/eetBG26/BG2608LM.BMP~
	~%biff_dir%/AR2608SR.BMP~ ~%biff_dir%/eetBG26/BG2608SR.BMP~
	~%biff_dir%/AR2609HT.BMP~ ~%biff_dir%/eetBG26/BG2609HT.BMP~
	~%biff_dir%/AR2609LM.BMP~ ~%biff_dir%/eetBG26/BG2609LM.BMP~
	~%biff_dir%/AR2609SR.BMP~ ~%biff_dir%/eetBG26/BG2609SR.BMP~
	~%biff_dir%/AR2610HT.BMP~ ~%biff_dir%/eetBG26/BG2610HT.BMP~
	~%biff_dir%/AR2610LM.BMP~ ~%biff_dir%/eetBG26/BG2610LM.BMP~
	~%biff_dir%/AR2610SR.BMP~ ~%biff_dir%/eetBG26/BG2610SR.BMP~
	~%biff_dir%/AR2611HT.BMP~ ~%biff_dir%/eetBG26/BG2611HT.BMP~
	~%biff_dir%/AR2611LM.BMP~ ~%biff_dir%/eetBG26/BG2611LM.BMP~
	~%biff_dir%/AR2611SR.BMP~ ~%biff_dir%/eetBG26/BG2611SR.BMP~
	~%biff_dir%/AR2612HT.BMP~ ~%biff_dir%/eetBG26/BG2612HT.BMP~
	~%biff_dir%/AR2612LM.BMP~ ~%biff_dir%/eetBG26/BG2612LM.BMP~
	~%biff_dir%/AR2612SR.BMP~ ~%biff_dir%/eetBG26/BG2612SR.BMP~
	~%biff_dir%/AR2613HT.BMP~ ~%biff_dir%/eetBG26/BG2613HT.BMP~
	~%biff_dir%/AR2613LM.BMP~ ~%biff_dir%/eetBG26/BG2613LM.BMP~
	~%biff_dir%/AR2613SR.BMP~ ~%biff_dir%/eetBG26/BG2613SR.BMP~
	~%biff_dir%/AR2614HT.BMP~ ~%biff_dir%/eetBG26/BG2614HT.BMP~
	~%biff_dir%/AR2614LM.BMP~ ~%biff_dir%/eetBG26/BG2614LM.BMP~
	~%biff_dir%/AR2614SR.BMP~ ~%biff_dir%/eetBG26/BG2614SR.BMP~
	~%biff_dir%/AR2615HT.BMP~ ~%biff_dir%/eetBG26/BG2615HT.BMP~
	~%biff_dir%/AR2615LM.BMP~ ~%biff_dir%/eetBG26/BG2615LM.BMP~
	~%biff_dir%/AR2615SR.BMP~ ~%biff_dir%/eetBG26/BG2615SR.BMP~
	~%biff_dir%/AR2616HT.BMP~ ~%biff_dir%/eetBG26/BG2616HT.BMP~
	~%biff_dir%/AR2616LM.BMP~ ~%biff_dir%/eetBG26/BG2616LM.BMP~
	~%biff_dir%/AR2616SR.BMP~ ~%biff_dir%/eetBG26/BG2616SR.BMP~
	~%biff_dir%/AR2617HT.BMP~ ~%biff_dir%/eetBG26/BG2617HT.BMP~
	~%biff_dir%/AR2617LM.BMP~ ~%biff_dir%/eetBG26/BG2617LM.BMP~
	~%biff_dir%/AR2617SR.BMP~ ~%biff_dir%/eetBG26/BG2617SR.BMP~
	~%biff_dir%/AR2618HT.BMP~ ~%biff_dir%/eetBG26/BG2618HT.BMP~
	~%biff_dir%/AR2618LM.BMP~ ~%biff_dir%/eetBG26/BG2618LM.BMP~
	~%biff_dir%/AR2618SR.BMP~ ~%biff_dir%/eetBG26/BG2618SR.BMP~
	~%biff_dir%/AR2619HT.BMP~ ~%biff_dir%/eetBG26/BG2619HT.BMP~
	~%biff_dir%/AR2619LM.BMP~ ~%biff_dir%/eetBG26/BG2619LM.BMP~
	~%biff_dir%/AR2619SR.BMP~ ~%biff_dir%/eetBG26/BG2619SR.BMP~
	~%biff_dir%/AR2631HT.BMP~ ~%biff_dir%/eetBG26/BG2631HT.BMP~
	~%biff_dir%/AR2631LM.BMP~ ~%biff_dir%/eetBG26/BG2631LM.BMP~
	~%biff_dir%/AR2631SR.BMP~ ~%biff_dir%/eetBG26/BG2631SR.BMP~
	~%biff_dir%/AR2643HT.BMP~ ~%biff_dir%/eetBG26/BG2643HT.BMP~
	~%biff_dir%/AR2643LM.BMP~ ~%biff_dir%/eetBG26/BG2643LM.BMP~
	~%biff_dir%/AR2643SR.BMP~ ~%biff_dir%/eetBG26/BG2643SR.BMP~
	~%biff_dir%/AR2700HT.BMP~ ~%biff_dir%/eetBG27/BG2700HT.BMP~
	~%biff_dir%/AR2700LM.BMP~ ~%biff_dir%/eetBG27/BG2700LM.BMP~
	~%biff_dir%/AR2700SR.BMP~ ~%biff_dir%/eetBG27/BG2700SR.BMP~
	~%biff_dir%/AR2800HT.BMP~ ~%biff_dir%/eetBG28/BG2800HT.BMP~
	~%biff_dir%/AR2800LM.BMP~ ~%biff_dir%/eetBG28/BG2800LM.BMP~
	~%biff_dir%/AR2800SR.BMP~ ~%biff_dir%/eetBG28/BG2800SR.BMP~
	~%biff_dir%/AR2900HT.BMP~ ~%biff_dir%/eetBG29/BG2900HT.BMP~
	~%biff_dir%/AR2900LM.BMP~ ~%biff_dir%/eetBG29/BG2900LM.BMP~
	~%biff_dir%/AR2900SR.BMP~ ~%biff_dir%/eetBG29/BG2900SR.BMP~
	~%biff_dir%/AR3000HT.BMP~ ~%biff_dir%/eetBG30/BG3000HT.BMP~
	~%biff_dir%/AR3000LM.BMP~ ~%biff_dir%/eetBG30/BG3000LM.BMP~
	~%biff_dir%/AR3000SR.BMP~ ~%biff_dir%/eetBG30/BG3000SR.BMP~
	~%biff_dir%/AR3100HT.BMP~ ~%biff_dir%/eetBG31/BG3100HT.BMP~
	~%biff_dir%/AR3100LM.BMP~ ~%biff_dir%/eetBG31/BG3100LM.BMP~
	~%biff_dir%/AR3100SR.BMP~ ~%biff_dir%/eetBG31/BG3100SR.BMP~
	~%biff_dir%/AR3200HT.BMP~ ~%biff_dir%/eetBG32/BG3200HT.BMP~
	~%biff_dir%/AR3200LM.BMP~ ~%biff_dir%/eetBG32/BG3200LM.BMP~
	~%biff_dir%/AR3200LN.BMP~ ~%biff_dir%/eetBG32/BG3200LN.BMP~
	~%biff_dir%/AR3200SR.BMP~ ~%biff_dir%/eetBG32/BG3200SR.BMP~
	~%biff_dir%/AR3201HT.BMP~ ~%biff_dir%/eetBG32/BG3201HT.BMP~
	~%biff_dir%/AR3201LM.BMP~ ~%biff_dir%/eetBG32/BG3201LM.BMP~
	~%biff_dir%/AR3201SR.BMP~ ~%biff_dir%/eetBG32/BG3201SR.BMP~
	~%biff_dir%/AR3202HT.BMP~ ~%biff_dir%/eetBG32/BG3202HT.BMP~
	~%biff_dir%/AR3202LM.BMP~ ~%biff_dir%/eetBG32/BG3202LM.BMP~
	~%biff_dir%/AR3202SR.BMP~ ~%biff_dir%/eetBG32/BG3202SR.BMP~
	~%biff_dir%/AR3300HT.BMP~ ~%biff_dir%/eetBG33/BG3300HT.BMP~
	~%biff_dir%/AR3300LM.BMP~ ~%biff_dir%/eetBG33/BG3300LM.BMP~
	~%biff_dir%/AR3300SR.BMP~ ~%biff_dir%/eetBG33/BG3300SR.BMP~
	~%biff_dir%/AR3301HT.BMP~ ~%biff_dir%/eetBG33/BG3301HT.BMP~
	~%biff_dir%/AR3301LM.BMP~ ~%biff_dir%/eetBG33/BG3301LM.BMP~
	~%biff_dir%/AR3301SR.BMP~ ~%biff_dir%/eetBG33/BG3301SR.BMP~
	~%biff_dir%/AR3302HT.BMP~ ~%biff_dir%/eetBG33/BG3302HT.BMP~
	~%biff_dir%/AR3302LM.BMP~ ~%biff_dir%/eetBG33/BG3302LM.BMP~
	~%biff_dir%/AR3302SR.BMP~ ~%biff_dir%/eetBG33/BG3302SR.BMP~
	~%biff_dir%/AR3303HT.BMP~ ~%biff_dir%/eetBG33/BG3303HT.BMP~
	~%biff_dir%/AR3303LM.BMP~ ~%biff_dir%/eetBG33/BG3303LM.BMP~
	~%biff_dir%/AR3303SR.BMP~ ~%biff_dir%/eetBG33/BG3303SR.BMP~
	~%biff_dir%/AR3304HT.BMP~ ~%biff_dir%/eetBG33/BG3304HT.BMP~
	~%biff_dir%/AR3304LM.BMP~ ~%biff_dir%/eetBG33/BG3304LM.BMP~
	~%biff_dir%/AR3304SR.BMP~ ~%biff_dir%/eetBG33/BG3304SR.BMP~
	~%biff_dir%/AR3305HT.BMP~ ~%biff_dir%/eetBG33/BG3305HT.BMP~
	~%biff_dir%/AR3305LM.BMP~ ~%biff_dir%/eetBG33/BG3305LM.BMP~
	~%biff_dir%/AR3305SR.BMP~ ~%biff_dir%/eetBG33/BG3305SR.BMP~
	~%biff_dir%/AR3306HT.BMP~ ~%biff_dir%/eetBG33/BG3306HT.BMP~
	~%biff_dir%/AR3306LM.BMP~ ~%biff_dir%/eetBG33/BG3306LM.BMP~
	~%biff_dir%/AR3306SR.BMP~ ~%biff_dir%/eetBG33/BG3306SR.BMP~
	~%biff_dir%/AR3307HT.BMP~ ~%biff_dir%/eetBG33/BG3307HT.BMP~
	~%biff_dir%/AR3307LM.BMP~ ~%biff_dir%/eetBG33/BG3307LM.BMP~
	~%biff_dir%/AR3307SR.BMP~ ~%biff_dir%/eetBG33/BG3307SR.BMP~
	~%biff_dir%/AR3308HT.BMP~ ~%biff_dir%/eetBG33/BG3308HT.BMP~
	~%biff_dir%/AR3308LM.BMP~ ~%biff_dir%/eetBG33/BG3308LM.BMP~
	~%biff_dir%/AR3308SR.BMP~ ~%biff_dir%/eetBG33/BG3308SR.BMP~
	~%biff_dir%/AR3309HT.BMP~ ~%biff_dir%/eetBG33/BG3309HT.BMP~
	~%biff_dir%/AR3309LM.BMP~ ~%biff_dir%/eetBG33/BG3309LM.BMP~
	~%biff_dir%/AR3309SR.BMP~ ~%biff_dir%/eetBG33/BG3309SR.BMP~
	~%biff_dir%/AR3310HT.BMP~ ~%biff_dir%/eetBG33/BG3310HT.BMP~
	~%biff_dir%/AR3310LM.BMP~ ~%biff_dir%/eetBG33/BG3310LM.BMP~
	~%biff_dir%/AR3310SR.BMP~ ~%biff_dir%/eetBG33/BG3310SR.BMP~
	~%biff_dir%/AR3313HT.BMP~ ~%biff_dir%/eetBG33/BG3313HT.BMP~
	~%biff_dir%/AR3313LM.BMP~ ~%biff_dir%/eetBG33/BG3313LM.BMP~
	~%biff_dir%/AR3313SR.BMP~ ~%biff_dir%/eetBG33/BG3313SR.BMP~
	~%biff_dir%/AR3314HT.BMP~ ~%biff_dir%/eetBG33/BG3314HT.BMP~
	~%biff_dir%/AR3314LM.BMP~ ~%biff_dir%/eetBG33/BG3314LM.BMP~
	~%biff_dir%/AR3314SR.BMP~ ~%biff_dir%/eetBG33/BG3314SR.BMP~
	~%biff_dir%/AR3316HT.BMP~ ~%biff_dir%/eetBG33/BG3316HT.BMP~
	~%biff_dir%/AR3316LM.BMP~ ~%biff_dir%/eetBG33/BG3316LM.BMP~
	~%biff_dir%/AR3316SR.BMP~ ~%biff_dir%/eetBG33/BG3316SR.BMP~
	~%biff_dir%/AR3317HT.BMP~ ~%biff_dir%/eetBG33/BG3317HT.BMP~
	~%biff_dir%/AR3317LM.BMP~ ~%biff_dir%/eetBG33/BG3317LM.BMP~
	~%biff_dir%/AR3317SR.BMP~ ~%biff_dir%/eetBG33/BG3317SR.BMP~
	~%biff_dir%/AR3320HT.BMP~ ~%biff_dir%/eetBG33/BG3320HT.BMP~
	~%biff_dir%/AR3320LM.BMP~ ~%biff_dir%/eetBG33/BG3320LM.BMP~
	~%biff_dir%/AR3320SR.BMP~ ~%biff_dir%/eetBG33/BG3320SR.BMP~
	~%biff_dir%/AR3321HT.BMP~ ~%biff_dir%/eetBG33/BG3321HT.BMP~
	~%biff_dir%/AR3321LM.BMP~ ~%biff_dir%/eetBG33/BG3321LM.BMP~
	~%biff_dir%/AR3321SR.BMP~ ~%biff_dir%/eetBG33/BG3321SR.BMP~
	~%biff_dir%/AR3327HT.BMP~ ~%biff_dir%/eetBG33/BG3327HT.BMP~
	~%biff_dir%/AR3327LM.BMP~ ~%biff_dir%/eetBG33/BG3327LM.BMP~
	~%biff_dir%/AR3327SR.BMP~ ~%biff_dir%/eetBG33/BG3327SR.BMP~
	~%biff_dir%/AR3328HT.BMP~ ~%biff_dir%/eetBG33/BG3328HT.BMP~
	~%biff_dir%/AR3328LM.BMP~ ~%biff_dir%/eetBG33/BG3328LM.BMP~
	~%biff_dir%/AR3328SR.BMP~ ~%biff_dir%/eetBG33/BG3328SR.BMP~
	~%biff_dir%/AR3339HT.BMP~ ~%biff_dir%/eetBG33/BG3339HT.BMP~
	~%biff_dir%/AR3339LM.BMP~ ~%biff_dir%/eetBG33/BG3339LM.BMP~
	~%biff_dir%/AR3339SR.BMP~ ~%biff_dir%/eetBG33/BG3339SR.BMP~
	~%biff_dir%/AR3340HT.BMP~ ~%biff_dir%/eetBG33/BG3340HT.BMP~
	~%biff_dir%/AR3340LM.BMP~ ~%biff_dir%/eetBG33/BG3340LM.BMP~
	~%biff_dir%/AR3340SR.BMP~ ~%biff_dir%/eetBG33/BG3340SR.BMP~
	~%biff_dir%/AR3351HT.BMP~ ~%biff_dir%/eetBG33/BG3351HT.BMP~
	~%biff_dir%/AR3351LM.BMP~ ~%biff_dir%/eetBG33/BG3351LM.BMP~
	~%biff_dir%/AR3351SR.BMP~ ~%biff_dir%/eetBG33/BG3351SR.BMP~
	~%biff_dir%/AR3352HT.BMP~ ~%biff_dir%/eetBG33/BG3352HT.BMP~
	~%biff_dir%/AR3352LM.BMP~ ~%biff_dir%/eetBG33/BG3352LM.BMP~
	~%biff_dir%/AR3352SR.BMP~ ~%biff_dir%/eetBG33/BG3352SR.BMP~
	~%biff_dir%/AR3353HT.BMP~ ~%biff_dir%/eetBG33/BG3353HT.BMP~
	~%biff_dir%/AR3353LM.BMP~ ~%biff_dir%/eetBG33/BG3353LM.BMP~
	~%biff_dir%/AR3353SR.BMP~ ~%biff_dir%/eetBG33/BG3353SR.BMP~
	~%biff_dir%/AR3357HT.BMP~ ~%biff_dir%/eetBG33/BG3357HT.BMP~
	~%biff_dir%/AR3357LM.BMP~ ~%biff_dir%/eetBG33/BG3357LM.BMP~
	~%biff_dir%/AR3357SR.BMP~ ~%biff_dir%/eetBG33/BG3357SR.BMP~
	~%biff_dir%/AR3400HT.BMP~ ~%biff_dir%/eetBG34/BG3400HT.BMP~
	~%biff_dir%/AR3400LM.BMP~ ~%biff_dir%/eetBG34/BG3400LM.BMP~
	~%biff_dir%/AR3400LN.BMP~ ~%biff_dir%/eetBG34/BG3400LN.BMP~
	~%biff_dir%/AR3400SR.BMP~ ~%biff_dir%/eetBG34/BG3400SR.BMP~
	~%biff_dir%/AR3401HT.BMP~ ~%biff_dir%/eetBG34/BG3401HT.BMP~
	~%biff_dir%/AR3401LM.BMP~ ~%biff_dir%/eetBG34/BG3401LM.BMP~
	~%biff_dir%/AR3401SR.BMP~ ~%biff_dir%/eetBG34/BG3401SR.BMP~
	~%biff_dir%/AR3402HT.BMP~ ~%biff_dir%/eetBG34/BG3402HT.BMP~
	~%biff_dir%/AR3402LM.BMP~ ~%biff_dir%/eetBG34/BG3402LM.BMP~
	~%biff_dir%/AR3402SR.BMP~ ~%biff_dir%/eetBG34/BG3402SR.BMP~
	~%biff_dir%/AR3500HT.BMP~ ~%biff_dir%/eetBG35/BG3500HT.BMP~
	~%biff_dir%/AR3500LM.BMP~ ~%biff_dir%/eetBG35/BG3500LM.BMP~
	~%biff_dir%/AR3500SR.BMP~ ~%biff_dir%/eetBG35/BG3500SR.BMP~
	~%biff_dir%/AR3600HT.BMP~ ~%biff_dir%/eetBG36/BG3600HT.BMP~
	~%biff_dir%/AR3600LM.BMP~ ~%biff_dir%/eetBG36/BG3600LM.BMP~
	~%biff_dir%/AR3600SR.BMP~ ~%biff_dir%/eetBG36/BG3600SR.BMP~
	~%biff_dir%/AR3601HT.BMP~ ~%biff_dir%/eetBG36/BG3601HT.BMP~
	~%biff_dir%/AR3601LM.BMP~ ~%biff_dir%/eetBG36/BG3601LM.BMP~
	~%biff_dir%/AR3601SR.BMP~ ~%biff_dir%/eetBG36/BG3601SR.BMP~
	~%biff_dir%/AR3700HT.BMP~ ~%biff_dir%/eetBG37/BG3700HT.BMP~
	~%biff_dir%/AR3700LM.BMP~ ~%biff_dir%/eetBG37/BG3700LM.BMP~
	~%biff_dir%/AR3700SR.BMP~ ~%biff_dir%/eetBG37/BG3700SR.BMP~
	~%biff_dir%/AR3800HT.BMP~ ~%biff_dir%/eetBG38/BG3800HT.BMP~
	~%biff_dir%/AR3800LM.BMP~ ~%biff_dir%/eetBG38/BG3800LM.BMP~
	~%biff_dir%/AR3800SR.BMP~ ~%biff_dir%/eetBG38/BG3800SR.BMP~
	~%biff_dir%/AR3802HT.BMP~ ~%biff_dir%/eetBG38/BG3802HT.BMP~
	~%biff_dir%/AR3802LM.BMP~ ~%biff_dir%/eetBG38/BG3802LM.BMP~
	~%biff_dir%/AR3802SR.BMP~ ~%biff_dir%/eetBG38/BG3802SR.BMP~
	~%biff_dir%/AR3900HT.BMP~ ~%biff_dir%/eetBG39/BG3900HT.BMP~
	~%biff_dir%/AR3900LM.BMP~ ~%biff_dir%/eetBG39/BG3900LM.BMP~
	~%biff_dir%/AR3900SR.BMP~ ~%biff_dir%/eetBG39/BG3900SR.BMP~
	~%biff_dir%/AR3901HT.BMP~ ~%biff_dir%/eetBG39/BG3901HT.BMP~
	~%biff_dir%/AR3901LM.BMP~ ~%biff_dir%/eetBG39/BG3901LM.BMP~
	~%biff_dir%/AR3901SR.BMP~ ~%biff_dir%/eetBG39/BG3901SR.BMP~
	~%biff_dir%/AR4000HT.BMP~ ~%biff_dir%/eetBG40/BG4000HT.BMP~
	~%biff_dir%/AR4000LM.BMP~ ~%biff_dir%/eetBG40/BG4000LM.BMP~
	~%biff_dir%/AR4000SR.BMP~ ~%biff_dir%/eetBG40/BG4000SR.BMP~
	~%biff_dir%/AR4001HT.BMP~ ~%biff_dir%/eetBG40/BG4001HT.BMP~
	~%biff_dir%/AR4001LM.BMP~ ~%biff_dir%/eetBG40/BG4001LM.BMP~
	~%biff_dir%/AR4001SR.BMP~ ~%biff_dir%/eetBG40/BG4001SR.BMP~
	~%biff_dir%/AR4002HT.BMP~ ~%biff_dir%/eetBG40/BG4002HT.BMP~
	~%biff_dir%/AR4002LM.BMP~ ~%biff_dir%/eetBG40/BG4002LM.BMP~
	~%biff_dir%/AR4002SR.BMP~ ~%biff_dir%/eetBG40/BG4002SR.BMP~
	~%biff_dir%/AR4003HT.BMP~ ~%biff_dir%/eetBG40/BG4003HT.BMP~
	~%biff_dir%/AR4003LM.BMP~ ~%biff_dir%/eetBG40/BG4003LM.BMP~
	~%biff_dir%/AR4003SR.BMP~ ~%biff_dir%/eetBG40/BG4003SR.BMP~
	~%biff_dir%/AR4004HT.BMP~ ~%biff_dir%/eetBG40/BG4004HT.BMP~
	~%biff_dir%/AR4004LM.BMP~ ~%biff_dir%/eetBG40/BG4004LM.BMP~
	~%biff_dir%/AR4004SR.BMP~ ~%biff_dir%/eetBG40/BG4004SR.BMP~
	~%biff_dir%/AR4006HT.BMP~ ~%biff_dir%/eetBG40/BG4006HT.BMP~
	~%biff_dir%/AR4006LM.BMP~ ~%biff_dir%/eetBG40/BG4006LM.BMP~
	~%biff_dir%/AR4006SR.BMP~ ~%biff_dir%/eetBG40/BG4006SR.BMP~
	~%biff_dir%/AR4100HT.BMP~ ~%biff_dir%/eetBG41/BG4100HT.BMP~
	~%biff_dir%/AR4100LM.BMP~ ~%biff_dir%/eetBG41/BG4100LM.BMP~
	~%biff_dir%/AR4100SR.BMP~ ~%biff_dir%/eetBG41/BG4100SR.BMP~
	~%biff_dir%/AR4101HT.BMP~ ~%biff_dir%/eetBG41/BG4101HT.BMP~
	~%biff_dir%/AR4101LM.BMP~ ~%biff_dir%/eetBG41/BG4101LM.BMP~
	~%biff_dir%/AR4101SR.BMP~ ~%biff_dir%/eetBG41/BG4101SR.BMP~
	~%biff_dir%/AR4200HT.BMP~ ~%biff_dir%/eetBG42/BG4200HT.BMP~
	~%biff_dir%/AR4200LM.BMP~ ~%biff_dir%/eetBG42/BG4200LM.BMP~
	~%biff_dir%/AR4200SR.BMP~ ~%biff_dir%/eetBG42/BG4200SR.BMP~
	~%biff_dir%/AR4201HT.BMP~ ~%biff_dir%/eetBG42/BG4201HT.BMP~
	~%biff_dir%/AR4201LM.BMP~ ~%biff_dir%/eetBG42/BG4201LM.BMP~
	~%biff_dir%/AR4201SR.BMP~ ~%biff_dir%/eetBG42/BG4201SR.BMP~
	~%biff_dir%/AR4300HT.BMP~ ~%biff_dir%/eetBG43/BG4300HT.BMP~
	~%biff_dir%/AR4300LM.BMP~ ~%biff_dir%/eetBG43/BG4300LM.BMP~
	~%biff_dir%/AR4300SR.BMP~ ~%biff_dir%/eetBG43/BG4300SR.BMP~
	~%biff_dir%/AR4400HT.BMP~ ~%biff_dir%/eetBG44/BG4400HT.BMP~
	~%biff_dir%/AR4400LM.BMP~ ~%biff_dir%/eetBG44/BG4400LM.BMP~
	~%biff_dir%/AR4400SR.BMP~ ~%biff_dir%/eetBG44/BG4400SR.BMP~
	~%biff_dir%/AR4401HT.BMP~ ~%biff_dir%/eetBG44/BG4401HT.BMP~
	~%biff_dir%/AR4401LM.BMP~ ~%biff_dir%/eetBG44/BG4401LM.BMP~
	~%biff_dir%/AR4401SR.BMP~ ~%biff_dir%/eetBG44/BG4401SR.BMP~
	~%biff_dir%/AR4500HT.BMP~ ~%biff_dir%/eetBG45/BG4500HT.BMP~
	~%biff_dir%/AR4500LM.BMP~ ~%biff_dir%/eetBG45/BG4500LM.BMP~
	~%biff_dir%/AR4500SR.BMP~ ~%biff_dir%/eetBG45/BG4500SR.BMP~
	~%biff_dir%/AR4501HT.BMP~ ~%biff_dir%/eetBG45/BG4501HT.BMP~
	~%biff_dir%/AR4501LM.BMP~ ~%biff_dir%/eetBG45/BG4501LM.BMP~
	~%biff_dir%/AR4501SR.BMP~ ~%biff_dir%/eetBG45/BG4501SR.BMP~
	~%biff_dir%/AR4600HT.BMP~ ~%biff_dir%/eetBG46/BG4600HT.BMP~
	~%biff_dir%/AR4600LM.BMP~ ~%biff_dir%/eetBG46/BG4600LM.BMP~
	~%biff_dir%/AR4600SR.BMP~ ~%biff_dir%/eetBG46/BG4600SR.BMP~
	~%biff_dir%/AR4700HT.BMP~ ~%biff_dir%/eetBG47/BG4700HT.BMP~
	~%biff_dir%/AR4700LM.BMP~ ~%biff_dir%/eetBG47/BG4700LM.BMP~
	~%biff_dir%/AR4700LN.BMP~ ~%biff_dir%/eetBG47/BG4700LN.BMP~
	~%biff_dir%/AR4700SR.BMP~ ~%biff_dir%/eetBG47/BG4700SR.BMP~
	~%biff_dir%/AR4701HT.BMP~ ~%biff_dir%/eetBG47/BG4701HT.BMP~
	~%biff_dir%/AR4701LM.BMP~ ~%biff_dir%/eetBG47/BG4701LM.BMP~
	~%biff_dir%/AR4701SR.BMP~ ~%biff_dir%/eetBG47/BG4701SR.BMP~
	~%biff_dir%/AR4800HT.BMP~ ~%biff_dir%/eetBG48/BG4800HT.BMP~
	~%biff_dir%/AR4800LM.BMP~ ~%biff_dir%/eetBG48/BG4800LM.BMP~
	~%biff_dir%/AR4800SR.BMP~ ~%biff_dir%/eetBG48/BG4800SR.BMP~
	~%biff_dir%/AR4801HT.BMP~ ~%biff_dir%/eetBG48/BG4801HT.BMP~
	~%biff_dir%/AR4801LM.BMP~ ~%biff_dir%/eetBG48/BG4801LM.BMP~
	~%biff_dir%/AR4801SR.BMP~ ~%biff_dir%/eetBG48/BG4801SR.BMP~
	~%biff_dir%/AR4802HT.BMP~ ~%biff_dir%/eetBG48/BG4802HT.BMP~
	~%biff_dir%/AR4802LM.BMP~ ~%biff_dir%/eetBG48/BG4802LM.BMP~
	~%biff_dir%/AR4802SR.BMP~ ~%biff_dir%/eetBG48/BG4802SR.BMP~
	~%biff_dir%/AR4803HT.BMP~ ~%biff_dir%/eetBG48/BG4803HT.BMP~
	~%biff_dir%/AR4803LM.BMP~ ~%biff_dir%/eetBG48/BG4803LM.BMP~
	~%biff_dir%/AR4803SR.BMP~ ~%biff_dir%/eetBG48/BG4803SR.BMP~
	~%biff_dir%/AR4804HT.BMP~ ~%biff_dir%/eetBG48/BG4804HT.BMP~
	~%biff_dir%/AR4804LM.BMP~ ~%biff_dir%/eetBG48/BG4804LM.BMP~
	~%biff_dir%/AR4804SR.BMP~ ~%biff_dir%/eetBG48/BG4804SR.BMP~
	~%biff_dir%/AR4805HT.BMP~ ~%biff_dir%/eetBG48/BG4805HT.BMP~
	~%biff_dir%/AR4805LM.BMP~ ~%biff_dir%/eetBG48/BG4805LM.BMP~
	~%biff_dir%/AR4805SR.BMP~ ~%biff_dir%/eetBG48/BG4805SR.BMP~
	~%biff_dir%/AR4806HT.BMP~ ~%biff_dir%/eetBG48/BG4806HT.BMP~
	~%biff_dir%/AR4806LM.BMP~ ~%biff_dir%/eetBG48/BG4806LM.BMP~
	~%biff_dir%/AR4806SR.BMP~ ~%biff_dir%/eetBG48/BG4806SR.BMP~
	~%biff_dir%/AR4807HT.BMP~ ~%biff_dir%/eetBG48/BG4807HT.BMP~
	~%biff_dir%/AR4807LM.BMP~ ~%biff_dir%/eetBG48/BG4807LM.BMP~
	~%biff_dir%/AR4807SR.BMP~ ~%biff_dir%/eetBG48/BG4807SR.BMP~
	~%biff_dir%/AR4808HT.BMP~ ~%biff_dir%/eetBG48/BG4808HT.BMP~
	~%biff_dir%/AR4808LM.BMP~ ~%biff_dir%/eetBG48/BG4808LM.BMP~
	~%biff_dir%/AR4808SR.BMP~ ~%biff_dir%/eetBG48/BG4808SR.BMP~
	~%biff_dir%/AR4809HT.BMP~ ~%biff_dir%/eetBG48/BG4809HT.BMP~
	~%biff_dir%/AR4809LM.BMP~ ~%biff_dir%/eetBG48/BG4809LM.BMP~
	~%biff_dir%/AR4809SR.BMP~ ~%biff_dir%/eetBG48/BG4809SR.BMP~
	~%biff_dir%/AR4810HT.BMP~ ~%biff_dir%/eetBG48/BG4810HT.BMP~
	~%biff_dir%/AR4810LM.BMP~ ~%biff_dir%/eetBG48/BG4810LM.BMP~
	~%biff_dir%/AR4810SR.BMP~ ~%biff_dir%/eetBG48/BG4810SR.BMP~
	~%biff_dir%/AR4900HT.BMP~ ~%biff_dir%/eetBG49/BG4900HT.BMP~
	~%biff_dir%/AR4900LM.BMP~ ~%biff_dir%/eetBG49/BG4900LM.BMP~
	~%biff_dir%/AR4900LN.BMP~ ~%biff_dir%/eetBG49/BG4900LN.BMP~
	~%biff_dir%/AR4900SR.BMP~ ~%biff_dir%/eetBG49/BG4900SR.BMP~
	~%biff_dir%/AR4901HT.BMP~ ~%biff_dir%/eetBG49/BG4901HT.BMP~
	~%biff_dir%/AR4901LM.BMP~ ~%biff_dir%/eetBG49/BG4901LM.BMP~
	~%biff_dir%/AR4901SR.BMP~ ~%biff_dir%/eetBG49/BG4901SR.BMP~
	~%biff_dir%/AR4902HT.BMP~ ~%biff_dir%/eetBG49/BG4902HT.BMP~
	~%biff_dir%/AR4902LM.BMP~ ~%biff_dir%/eetBG49/BG4902LM.BMP~
	~%biff_dir%/AR4902SR.BMP~ ~%biff_dir%/eetBG49/BG4902SR.BMP~
	~%biff_dir%/AR4903HT.BMP~ ~%biff_dir%/eetBG49/BG4903HT.BMP~
	~%biff_dir%/AR4903LM.BMP~ ~%biff_dir%/eetBG49/BG4903LM.BMP~
	~%biff_dir%/AR4903SR.BMP~ ~%biff_dir%/eetBG49/BG4903SR.BMP~
	~%biff_dir%/AR4905HT.BMP~ ~%biff_dir%/eetBG49/BG4905HT.BMP~
	~%biff_dir%/AR4905LM.BMP~ ~%biff_dir%/eetBG49/BG4905LM.BMP~
	~%biff_dir%/AR4905SR.BMP~ ~%biff_dir%/eetBG49/BG4905SR.BMP~
	~%biff_dir%/AR4906HT.BMP~ ~%biff_dir%/eetBG49/BG4906HT.BMP~
	~%biff_dir%/AR4906LM.BMP~ ~%biff_dir%/eetBG49/BG4906LM.BMP~
	~%biff_dir%/AR4906SR.BMP~ ~%biff_dir%/eetBG49/BG4906SR.BMP~
	~%biff_dir%/AR5000HT.BMP~ ~%biff_dir%/eetBG50/BG5000HT.BMP~
	~%biff_dir%/AR5000LM.BMP~ ~%biff_dir%/eetBG50/BG5000LM.BMP~
	~%biff_dir%/AR5000SR.BMP~ ~%biff_dir%/eetBG50/BG5000SR.BMP~
	~%biff_dir%/AR5001HT.BMP~ ~%biff_dir%/eetBG50/BG5001HT.BMP~
	~%biff_dir%/AR5001LM.BMP~ ~%biff_dir%/eetBG50/BG5001LM.BMP~
	~%biff_dir%/AR5001SR.BMP~ ~%biff_dir%/eetBG50/BG5001SR.BMP~
	~%biff_dir%/AR5100HT.BMP~ ~%biff_dir%/eetBG51/BG5100HT.BMP~
	~%biff_dir%/AR5100LM.BMP~ ~%biff_dir%/eetBG51/BG5100LM.BMP~
	~%biff_dir%/AR5100SR.BMP~ ~%biff_dir%/eetBG51/BG5100SR.BMP~
	~%biff_dir%/AR5101HT.BMP~ ~%biff_dir%/eetBG51/BG5101HT.BMP~
	~%biff_dir%/AR5101LM.BMP~ ~%biff_dir%/eetBG51/BG5101LM.BMP~
	~%biff_dir%/AR5101SR.BMP~ ~%biff_dir%/eetBG51/BG5101SR.BMP~
	~%biff_dir%/AR5102HT.BMP~ ~%biff_dir%/eetBG51/BG5102HT.BMP~
	~%biff_dir%/AR5102LM.BMP~ ~%biff_dir%/eetBG51/BG5102LM.BMP~
	~%biff_dir%/AR5102SR.BMP~ ~%biff_dir%/eetBG51/BG5102SR.BMP~
	~%biff_dir%/AR5103HT.BMP~ ~%biff_dir%/eetBG51/BG5103HT.BMP~
	~%biff_dir%/AR5103LM.BMP~ ~%biff_dir%/eetBG51/BG5103LM.BMP~
	~%biff_dir%/AR5103SR.BMP~ ~%biff_dir%/eetBG51/BG5103SR.BMP~
	~%biff_dir%/AR5200HT.BMP~ ~%biff_dir%/eetBG52/BG5200HT.BMP~
	~%biff_dir%/AR5200LM.BMP~ ~%biff_dir%/eetBG52/BG5200LM.BMP~
	~%biff_dir%/AR5200SR.BMP~ ~%biff_dir%/eetBG52/BG5200SR.BMP~
	~%biff_dir%/AR5201HT.BMP~ ~%biff_dir%/eetBG52/BG5201HT.BMP~
	~%biff_dir%/AR5201LM.BMP~ ~%biff_dir%/eetBG52/BG5201LM.BMP~
	~%biff_dir%/AR5201SR.BMP~ ~%biff_dir%/eetBG52/BG5201SR.BMP~
	~%biff_dir%/AR5202HT.BMP~ ~%biff_dir%/eetBG52/BG5202HT.BMP~
	~%biff_dir%/AR5202LM.BMP~ ~%biff_dir%/eetBG52/BG5202LM.BMP~
	~%biff_dir%/AR5202SR.BMP~ ~%biff_dir%/eetBG52/BG5202SR.BMP~
	~%biff_dir%/AR5300HT.BMP~ ~%biff_dir%/eetBG53/BG5300HT.BMP~
	~%biff_dir%/AR5300LM.BMP~ ~%biff_dir%/eetBG53/BG5300LM.BMP~
	~%biff_dir%/AR5300SR.BMP~ ~%biff_dir%/eetBG53/BG5300SR.BMP~
	~%biff_dir%/AR5400HT.BMP~ ~%biff_dir%/eetBG54/BG5400HT.BMP~
	~%biff_dir%/AR5400LM.BMP~ ~%biff_dir%/eetBG54/BG5400LM.BMP~
	~%biff_dir%/AR5400SR.BMP~ ~%biff_dir%/eetBG54/BG5400SR.BMP~
	~%biff_dir%/AR5401HT.BMP~ ~%biff_dir%/eetBG54/BG5401HT.BMP~
	~%biff_dir%/AR5401LM.BMP~ ~%biff_dir%/eetBG54/BG5401LM.BMP~
	~%biff_dir%/AR5401SR.BMP~ ~%biff_dir%/eetBG54/BG5401SR.BMP~
	~%biff_dir%/AR5402HT.BMP~ ~%biff_dir%/eetBG54/BG5402HT.BMP~
	~%biff_dir%/AR5402LM.BMP~ ~%biff_dir%/eetBG54/BG5402LM.BMP~
	~%biff_dir%/AR5402SR.BMP~ ~%biff_dir%/eetBG54/BG5402SR.BMP~
	~%biff_dir%/AR5403HT.BMP~ ~%biff_dir%/eetBG54/BG5403HT.BMP~
	~%biff_dir%/AR5403LM.BMP~ ~%biff_dir%/eetBG54/BG5403LM.BMP~
	~%biff_dir%/AR5403SR.BMP~ ~%biff_dir%/eetBG54/BG5403SR.BMP~
	~%biff_dir%/AR5404HT.BMP~ ~%biff_dir%/eetBG54/BG5404HT.BMP~
	~%biff_dir%/AR5404LM.BMP~ ~%biff_dir%/eetBG54/BG5404LM.BMP~
	~%biff_dir%/AR5404SR.BMP~ ~%biff_dir%/eetBG54/BG5404SR.BMP~
	~%biff_dir%/AR5405HT.BMP~ ~%biff_dir%/eetBG54/BG5405HT.BMP~
	~%biff_dir%/AR5405LM.BMP~ ~%biff_dir%/eetBG54/BG5405LM.BMP~
	~%biff_dir%/AR5405SR.BMP~ ~%biff_dir%/eetBG54/BG5405SR.BMP~
	~%biff_dir%/AR5406HT.BMP~ ~%biff_dir%/eetBG54/BG5406HT.BMP~
	~%biff_dir%/AR5406LM.BMP~ ~%biff_dir%/eetBG54/BG5406LM.BMP~
	~%biff_dir%/AR5406SR.BMP~ ~%biff_dir%/eetBG54/BG5406SR.BMP~
	~%biff_dir%/AR5500HT.BMP~ ~%biff_dir%/eetBG55/BG5500HT.BMP~
	~%biff_dir%/AR5500LM.BMP~ ~%biff_dir%/eetBG55/BG5500LM.BMP~
	~%biff_dir%/AR5500SR.BMP~ ~%biff_dir%/eetBG55/BG5500SR.BMP~
	~%biff_dir%/AR5506HT.BMP~ ~%biff_dir%/eetBG55/BG5506HT.BMP~
	~%biff_dir%/AR5506LM.BMP~ ~%biff_dir%/eetBG55/BG5506LM.BMP~
	~%biff_dir%/AR5506SR.BMP~ ~%biff_dir%/eetBG55/BG5506SR.BMP~
	~%biff_dir%/AR5600HT.BMP~ ~%biff_dir%/eetBG56/BG5600HT.BMP~
	~%biff_dir%/AR5600LM.BMP~ ~%biff_dir%/eetBG56/BG5600LM.BMP~
	~%biff_dir%/AR5600SR.BMP~ ~%biff_dir%/eetBG56/BG5600SR.BMP~
	~%biff_dir%/AR5700HT.BMP~ ~%biff_dir%/eetBG57/BG5700HT.BMP~
	~%biff_dir%/AR5700LM.BMP~ ~%biff_dir%/eetBG57/BG5700LM.BMP~
	~%biff_dir%/AR5700SR.BMP~ ~%biff_dir%/eetBG57/BG5700SR.BMP~
	~%biff_dir%/AR5800HT.BMP~ ~%biff_dir%/eetBG58/BG5800HT.BMP~
	~%biff_dir%/AR5800LM.BMP~ ~%biff_dir%/eetBG58/BG5800LM.BMP~
	~%biff_dir%/AR5800SR.BMP~ ~%biff_dir%/eetBG58/BG5800SR.BMP~
	~%biff_dir%/AR5900HT.BMP~ ~%biff_dir%/eetBG59/BG5900HT.BMP~
	~%biff_dir%/AR5900LM.BMP~ ~%biff_dir%/eetBG59/BG5900LM.BMP~
	~%biff_dir%/AR5900SR.BMP~ ~%biff_dir%/eetBG59/BG5900SR.BMP~
	~%biff_dir%/AR6000HT.BMP~ ~%biff_dir%/eetBG60/BG6000HT.BMP~
	~%biff_dir%/AR6000LM.BMP~ ~%biff_dir%/eetBG60/BG6000LM.BMP~
	~%biff_dir%/AR6000SR.BMP~ ~%biff_dir%/eetBG60/BG6000SR.BMP~
	~%biff_dir%/AR6100HT.BMP~ ~%biff_dir%/eetBG61/BG6100HT.BMP~
	~%biff_dir%/AR6100LM.BMP~ ~%biff_dir%/eetBG61/BG6100LM.BMP~
	~%biff_dir%/AR6100SR.BMP~ ~%biff_dir%/eetBG61/BG6100SR.BMP~
	~%biff_dir%/OH2000HT.BMP~ ~%biff_dir%/eetOH2~
	~%biff_dir%/OH2000LM.BMP~ ~%biff_dir%/eetOH2~
	~%biff_dir%/OH2000LN.BMP~ ~%biff_dir%/eetOH2~
	~%biff_dir%/OH2000SR.BMP~ ~%biff_dir%/eetOH2~
	~%biff_dir%/OH2010HT.BMP~ ~%biff_dir%/eetOH2~
	~%biff_dir%/OH2010LM.BMP~ ~%biff_dir%/eetOH2~
	~%biff_dir%/OH2010SR.BMP~ ~%biff_dir%/eetOH2~
	~%biff_dir%/OH3000HT.BMP~ ~%biff_dir%/eetOH3~
	~%biff_dir%/OH3000LM.BMP~ ~%biff_dir%/eetOH3~
	~%biff_dir%/OH3000LN.BMP~ ~%biff_dir%/eetOH3~
	~%biff_dir%/OH3000N.BMP~ ~%biff_dir%/eetOH3~
	~%biff_dir%/OH3000SR.BMP~ ~%biff_dir%/eetOH3~
	~%biff_dir%/OH3010HT.BMP~ ~%biff_dir%/eetOH3~
	~%biff_dir%/OH3010LM.BMP~ ~%biff_dir%/eetOH3~
	~%biff_dir%/OH3010SR.BMP~ ~%biff_dir%/eetOH3~
	~%biff_dir%/OH3020HT.BMP~ ~%biff_dir%/eetOH3~
	~%biff_dir%/OH3020LM.BMP~ ~%biff_dir%/eetOH3~
	~%biff_dir%/OH3020SR.BMP~ ~%biff_dir%/eetOH3~
	~%biff_dir%/OH3100HT.BMP~ ~%biff_dir%/eetOH3~
	~%biff_dir%/OH3100LM.BMP~ ~%biff_dir%/eetOH3~
	~%biff_dir%/OH3100LN.BMP~ ~%biff_dir%/eetOH3~
	~%biff_dir%/OH3100SR.BMP~ ~%biff_dir%/eetOH3~
	~%biff_dir%/OH9310HT.BMP~ ~%biff_dir%/eetOH9~
	~%biff_dir%/OH9310LM.BMP~ ~%biff_dir%/eetOH9~
	~%biff_dir%/OH9310SR.BMP~ ~%biff_dir%/eetOH9~
	~%biff_dir%/OH9350HT.BMP~ ~%biff_dir%/eetOH9~
	~%biff_dir%/OH9350LM.BMP~ ~%biff_dir%/eetOH9~
	~%biff_dir%/OH9350SR.BMP~ ~%biff_dir%/eetOH9~
	~%biff_dir%/OH9360HT.BMP~ ~%biff_dir%/eetOH9~
	~%biff_dir%/OH9360LM.BMP~ ~%biff_dir%/eetOH9~
	~%biff_dir%/OH9360SR.BMP~ ~%biff_dir%/eetOH9~
	~%biff_dir%/OH9400LM.BMP~ ~%biff_dir%/eetOH9~
	~%biff_dir%/TU0015HT.BMP~ ~%biff_dir%/eetTU00~
	~%biff_dir%/TU0015LM.BMP~ ~%biff_dir%/eetTU00~
	~%biff_dir%/TU0015SR.BMP~ ~%biff_dir%/eetTU00~
	~%biff_dir%/TU0016.BMP~ ~%biff_dir%/eetTU00~
	~%biff_dir%/TU0016HT.BMP~ ~%biff_dir%/eetTU00~
	~%biff_dir%/TU0016LM.BMP~ ~%biff_dir%/eetTU00~
	~%biff_dir%/TU0016SR.BMP~ ~%biff_dir%/eetTU00~
	~%biff_dir%/TU0017HT.BMP~ ~%biff_dir%/eetTU00~
	~%biff_dir%/TU0017LM.BMP~ ~%biff_dir%/eetTU00~
	~%biff_dir%/TU0017SR.BMP~ ~%biff_dir%/eetTU00~
	~%biff_dir%/TU0018HT.BMP~ ~%biff_dir%/eetTU00~
	~%biff_dir%/TU0018LM.BMP~ ~%biff_dir%/eetTU00~
	~%biff_dir%/TU0018SR.BMP~ ~%biff_dir%/eetTU00~
//SoD
	~%biff_dir%/BD0010HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0010LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0010LN.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0010SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0020HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0020LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0020LN.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0020SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0021HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0021LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0021LN.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0021SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0030HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0030LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0030LN.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0030SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0035HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0035LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0035SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0040HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0040LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0040LN.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0040SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0050HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0050LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0050LN.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0050SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0060HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0060LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0060LN.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0060SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0061HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0061LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0061SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0062HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0062LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0062SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0063HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0063LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0063LN.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0063SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0064HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0064LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0064LN.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0064SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0065HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0065LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0065LN.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0065SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0066HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0066LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0066LN.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0066SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0067HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0067LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0067SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0071HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0071LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0071LN.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0071SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0072HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0072LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0072SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0100HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0100LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0100SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0101HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0101LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0101SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0102HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0102LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0102SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0103HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0103LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0103SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0104HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0104LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0104SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0105HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0105LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0105SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0106HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0106LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0106SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0107HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0107LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0107SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0108HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0108LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0108SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0109HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0109LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0109SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0110HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0110LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0110SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0111HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0111LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0111SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0112HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0112LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0112SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0113HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0113LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0113SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0114HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0114LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0114SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0115HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0115LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0115SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0116HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0116LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0116SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0117HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0117LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0117SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0120HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0120LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0120SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0121HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0121LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0121SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0122HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0122LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0122SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0130HT.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0130LM.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD0130SR.BMP~ ~%biff_dir%/eetBD0~
	~%biff_dir%/BD1000HT.BMP~ ~%biff_dir%/eetBD1~
	~%biff_dir%/BD1000LM.BMP~ ~%biff_dir%/eetBD1~
	~%biff_dir%/BD1000LN.BMP~ ~%biff_dir%/eetBD1~
	~%biff_dir%/BD1000SR.BMP~ ~%biff_dir%/eetBD1~
	~%biff_dir%/BD1010HT.BMP~ ~%biff_dir%/eetBD1~
	~%biff_dir%/BD1010LM.BMP~ ~%biff_dir%/eetBD1~
	~%biff_dir%/BD1010SR.BMP~ ~%biff_dir%/eetBD1~
	~%biff_dir%/BD1100HT.BMP~ ~%biff_dir%/eetBD1~
	~%biff_dir%/BD1100LM.BMP~ ~%biff_dir%/eetBD1~
	~%biff_dir%/BD1100SR.BMP~ ~%biff_dir%/eetBD1~
	~%biff_dir%/BD1200HT.BMP~ ~%biff_dir%/eetBD1~
	~%biff_dir%/BD1200LM.BMP~ ~%biff_dir%/eetBD1~
	~%biff_dir%/BD1200LN.BMP~ ~%biff_dir%/eetBD1~
	~%biff_dir%/BD1200SR.BMP~ ~%biff_dir%/eetBD1~
	~%biff_dir%/BD2000HT.BMP~ ~%biff_dir%/eetBD2~
	~%biff_dir%/BD2000LM.BMP~ ~%biff_dir%/eetBD2~
	~%biff_dir%/BD2000LN.BMP~ ~%biff_dir%/eetBD2~
	~%biff_dir%/BD2000SR.BMP~ ~%biff_dir%/eetBD2~
	~%biff_dir%/BD2010HT.BMP~ ~%biff_dir%/eetBD2~
	~%biff_dir%/BD2010LM.BMP~ ~%biff_dir%/eetBD2~
	~%biff_dir%/BD2010SR.BMP~ ~%biff_dir%/eetBD2~
	~%biff_dir%/BD2100HT.BMP~ ~%biff_dir%/eetBD2~
	~%biff_dir%/BD2100LM.BMP~ ~%biff_dir%/eetBD2~
	~%biff_dir%/BD2100SR.BMP~ ~%biff_dir%/eetBD2~
	~%biff_dir%/BD3000HT.BMP~ ~%biff_dir%/eetBD3~
	~%biff_dir%/BD3000LM.BMP~ ~%biff_dir%/eetBD3~
	~%biff_dir%/BD3000LN.BMP~ ~%biff_dir%/eetBD3~
	~%biff_dir%/BD3000SR.BMP~ ~%biff_dir%/eetBD3~
	~%biff_dir%/BD4000HT.BMP~ ~%biff_dir%/eetBD4~
	~%biff_dir%/BD4000LM.BMP~ ~%biff_dir%/eetBD4~
	~%biff_dir%/BD4000LN.BMP~ ~%biff_dir%/eetBD4~
	~%biff_dir%/BD4000SR.BMP~ ~%biff_dir%/eetBD4~
	~%biff_dir%/BD4100HT.BMP~ ~%biff_dir%/eetBD4~
	~%biff_dir%/BD4100LM.BMP~ ~%biff_dir%/eetBD4~
	~%biff_dir%/BD4100SR.BMP~ ~%biff_dir%/eetBD4~
	~%biff_dir%/BD4300HT.BMP~ ~%biff_dir%/eetBD4~
	~%biff_dir%/BD4300LM.BMP~ ~%biff_dir%/eetBD4~
	~%biff_dir%/BD4300SR.BMP~ ~%biff_dir%/eetBD4~
	~%biff_dir%/BD4400HT.BMP~ ~%biff_dir%/eetBD4~
	~%biff_dir%/BD4400LM.BMP~ ~%biff_dir%/eetBD4~
	~%biff_dir%/BD4400SR.BMP~ ~%biff_dir%/eetBD4~
	~%biff_dir%/BD4500HT.BMP~ ~%biff_dir%/eetBD4~
	~%biff_dir%/BD4500LM.BMP~ ~%biff_dir%/eetBD4~
	~%biff_dir%/BD4500SR.BMP~ ~%biff_dir%/eetBD4~
	~%biff_dir%/BD4600HT.BMP~ ~%biff_dir%/eetBD4~
	~%biff_dir%/BD4600LM.BMP~ ~%biff_dir%/eetBD4~
	~%biff_dir%/BD4600SR.BMP~ ~%biff_dir%/eetBD4~
	~%biff_dir%/BD4601HT.BMP~ ~%biff_dir%/eetBD4~
	~%biff_dir%/BD4601LM.BMP~ ~%biff_dir%/eetBD4~
	~%biff_dir%/BD4601SR.BMP~ ~%biff_dir%/eetBD4~
	~%biff_dir%/BD4700HT.BMP~ ~%biff_dir%/eetBD4~
	~%biff_dir%/BD4700LM.BMP~ ~%biff_dir%/eetBD4~
	~%biff_dir%/BD4700SR.BMP~ ~%biff_dir%/eetBD4~
	~%biff_dir%/BD5000HT.BMP~ ~%biff_dir%/eetBD5~
	~%biff_dir%/BD5000LM.BMP~ ~%biff_dir%/eetBD5~
	~%biff_dir%/BD5000LN.BMP~ ~%biff_dir%/eetBD5~
	~%biff_dir%/BD5000SR.BMP~ ~%biff_dir%/eetBD5~
	~%biff_dir%/BD5100HT.BMP~ ~%biff_dir%/eetBD5~
	~%biff_dir%/BD5100LM.BMP~ ~%biff_dir%/eetBD5~
	~%biff_dir%/BD5100SR.BMP~ ~%biff_dir%/eetBD5~
	~%biff_dir%/BD5110HT.BMP~ ~%biff_dir%/eetBD5~
	~%biff_dir%/BD5110LM.BMP~ ~%biff_dir%/eetBD5~
	~%biff_dir%/BD5110SR.BMP~ ~%biff_dir%/eetBD5~
	~%biff_dir%/BD5200HT.BMP~ ~%biff_dir%/eetBD5~
	~%biff_dir%/BD5200LM.BMP~ ~%biff_dir%/eetBD5~
	~%biff_dir%/BD5200SR.BMP~ ~%biff_dir%/eetBD5~
	~%biff_dir%/BD5300HT.BMP~ ~%biff_dir%/eetBD5~
	~%biff_dir%/BD5300LM.BMP~ ~%biff_dir%/eetBD5~
	~%biff_dir%/BD5300SR.BMP~ ~%biff_dir%/eetBD5~
	~%biff_dir%/BD6000HT.BMP~ ~%biff_dir%/eetBD6~
	~%biff_dir%/BD6000LM.BMP~ ~%biff_dir%/eetBD6~
	~%biff_dir%/BD6000SR.BMP~ ~%biff_dir%/eetBD6~
	~%biff_dir%/BD6100HT.BMP~ ~%biff_dir%/eetBD6~
	~%biff_dir%/BD6100LM.BMP~ ~%biff_dir%/eetBD6~
	~%biff_dir%/BD6100SR.BMP~ ~%biff_dir%/eetBD6~
	~%biff_dir%/BD6200HT.BMP~ ~%biff_dir%/eetBD6~
	~%biff_dir%/BD6200LM.BMP~ ~%biff_dir%/eetBD6~
	~%biff_dir%/BD6200SR.BMP~ ~%biff_dir%/eetBD6~
	~%biff_dir%/BD7000HT.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7000LM.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7000LN.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7000SR.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7100HT.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7100LM.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7100LN.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7100SR.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7110HT.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7110LM.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7110SR.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7200HT.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7200LM.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7200LN.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7200SR.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7210HT.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7210LM.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7210LN.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7210SR.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7220HT.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7220LM.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7220SR.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7230HT.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7230LM.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7230SR.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7300HT.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7300LM.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7300LN.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7300SR.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7310HT.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7310LM.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7310SR.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7400HT.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7400LM.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7400LN.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7400SR.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7410HT.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7410LM.BMP~ ~%biff_dir%/eetBD7~
	~%biff_dir%/BD7410SR.BMP~ ~%biff_dir%/eetBD7~

//moved
DELETE + ~%biff_dir%/AR0002HT.BMP~
	~%biff_dir%/AR0002LM.BMP~
	~%biff_dir%/AR0002SR.BMP~
	~%biff_dir%/AR0100HT.BMP~
	~%biff_dir%/AR0100LM.BMP~
	~%biff_dir%/AR0100LN.BMP~
	~%biff_dir%/AR0100SR.BMP~
	~%biff_dir%/AR0101HT.BMP~
	~%biff_dir%/AR0101LM.BMP~
	~%biff_dir%/AR0101SR.BMP~
	~%biff_dir%/AR0102HT.BMP~
	~%biff_dir%/AR0102LM.BMP~
	~%biff_dir%/AR0102SR.BMP~
	~%biff_dir%/AR0103HT.BMP~
	~%biff_dir%/AR0103LM.BMP~
	~%biff_dir%/AR0103SR.BMP~
	~%biff_dir%/AR0104HT.BMP~
	~%biff_dir%/AR0104LM.BMP~
	~%biff_dir%/AR0104SR.BMP~
	~%biff_dir%/AR0105HT.BMP~
	~%biff_dir%/AR0105LM.BMP~
	~%biff_dir%/AR0105SR.BMP~
	~%biff_dir%/AR0106HT.BMP~
	~%biff_dir%/AR0106LM.BMP~
	~%biff_dir%/AR0106SR.BMP~
	~%biff_dir%/AR0107HT.BMP~
	~%biff_dir%/AR0107LM.BMP~
	~%biff_dir%/AR0107SR.BMP~
	~%biff_dir%/AR0108HT.BMP~
	~%biff_dir%/AR0108LM.BMP~
	~%biff_dir%/AR0108SR.BMP~
	~%biff_dir%/AR0109HT.BMP~
	~%biff_dir%/AR0109LM.BMP~
	~%biff_dir%/AR0109SR.BMP~
	~%biff_dir%/AR0110HT.BMP~
	~%biff_dir%/AR0110LM.BMP~
	~%biff_dir%/AR0110SR.BMP~
	~%biff_dir%/AR0111HT.BMP~
	~%biff_dir%/AR0111LM.BMP~
	~%biff_dir%/AR0111SR.BMP~
	~%biff_dir%/AR0112HT.BMP~
	~%biff_dir%/AR0112LM.BMP~
	~%biff_dir%/AR0112SR.BMP~
	~%biff_dir%/AR0114HT.BMP~
	~%biff_dir%/AR0114LM.BMP~
	~%biff_dir%/AR0114SR.BMP~
	~%biff_dir%/AR0115HT.BMP~
	~%biff_dir%/AR0115LM.BMP~
	~%biff_dir%/AR0115SR.BMP~
	~%biff_dir%/AR0116HT.BMP~
	~%biff_dir%/AR0116LM.BMP~
	~%biff_dir%/AR0116SR.BMP~
	~%biff_dir%/AR0117HT.BMP~
	~%biff_dir%/AR0117LM.BMP~
	~%biff_dir%/AR0117SR.BMP~
	~%biff_dir%/AR0118HT.BMP~
	~%biff_dir%/AR0118LM.BMP~
	~%biff_dir%/AR0118SR.BMP~
	~%biff_dir%/AR0119HT.BMP~
	~%biff_dir%/AR0119LM.BMP~
	~%biff_dir%/AR0119SR.BMP~
	~%biff_dir%/AR0120HT.BMP~
	~%biff_dir%/AR0120LM.BMP~
	~%biff_dir%/AR0120SR.BMP~
	~%biff_dir%/AR0121HT.BMP~
	~%biff_dir%/AR0121LM.BMP~
	~%biff_dir%/AR0121SR.BMP~
	~%biff_dir%/AR0123HT.BMP~
	~%biff_dir%/AR0123LM.BMP~
	~%biff_dir%/AR0123SR.BMP~
	~%biff_dir%/AR0125HT.BMP~
	~%biff_dir%/AR0125LM.BMP~
	~%biff_dir%/AR0125SR.BMP~
	~%biff_dir%/AR0126HT.BMP~
	~%biff_dir%/AR0126LM.BMP~
	~%biff_dir%/AR0126SR.BMP~
	~%biff_dir%/AR0127HT.BMP~
	~%biff_dir%/AR0127LM.BMP~
	~%biff_dir%/AR0127SR.BMP~
	~%biff_dir%/AR0128HT.BMP~
	~%biff_dir%/AR0128LM.BMP~
	~%biff_dir%/AR0128SR.BMP~
	~%biff_dir%/AR0129HT.BMP~
	~%biff_dir%/AR0129LM.BMP~
	~%biff_dir%/AR0129SR.BMP~
	~%biff_dir%/AR0130HT.BMP~
	~%biff_dir%/AR0130LM.BMP~
	~%biff_dir%/AR0130SR.BMP~
	~%biff_dir%/AR0131HT.BMP~
	~%biff_dir%/AR0131LM.BMP~
	~%biff_dir%/AR0131SR.BMP~
	~%biff_dir%/AR0132HT.BMP~
	~%biff_dir%/AR0132LM.BMP~
	~%biff_dir%/AR0132SR.BMP~
	~%biff_dir%/AR0133HT.BMP~
	~%biff_dir%/AR0133LM.BMP~
	~%biff_dir%/AR0133SR.BMP~
	~%biff_dir%/AR0134HT.BMP~
	~%biff_dir%/AR0134LM.BMP~
	~%biff_dir%/AR0134SR.BMP~
	~%biff_dir%/AR0135HT.BMP~
	~%biff_dir%/AR0135LM.BMP~
	~%biff_dir%/AR0135SR.BMP~
	~%biff_dir%/AR0136HT.BMP~
	~%biff_dir%/AR0136LM.BMP~
	~%biff_dir%/AR0136SR.BMP~
	~%biff_dir%/AR0137HT.BMP~
	~%biff_dir%/AR0137LM.BMP~
	~%biff_dir%/AR0137SR.BMP~
	~%biff_dir%/AR0138HT.BMP~
	~%biff_dir%/AR0138LM.BMP~
	~%biff_dir%/AR0138SR.BMP~
	~%biff_dir%/AR0139HT.BMP~
	~%biff_dir%/AR0139LM.BMP~
	~%biff_dir%/AR0139SR.BMP~
	~%biff_dir%/AR0140HT.BMP~
	~%biff_dir%/AR0140LM.BMP~
	~%biff_dir%/AR0140SR.BMP~
	~%biff_dir%/AR0141HT.BMP~
	~%biff_dir%/AR0141LM.BMP~
	~%biff_dir%/AR0141SR.BMP~
	~%biff_dir%/AR0142HT.BMP~
	~%biff_dir%/AR0142LM.BMP~
	~%biff_dir%/AR0142SR.BMP~
	~%biff_dir%/AR0143HT.BMP~
	~%biff_dir%/AR0143LM.BMP~
	~%biff_dir%/AR0143SR.BMP~
	~%biff_dir%/AR0144HT.BMP~
	~%biff_dir%/AR0144LM.BMP~
	~%biff_dir%/AR0144SR.BMP~
	~%biff_dir%/AR0145HT.BMP~
	~%biff_dir%/AR0145LM.BMP~
	~%biff_dir%/AR0145SR.BMP~
	~%biff_dir%/AR0146HT.BMP~
	~%biff_dir%/AR0146LM.BMP~
	~%biff_dir%/AR0146SR.BMP~
	~%biff_dir%/AR0148HT.BMP~
	~%biff_dir%/AR0148LM.BMP~
	~%biff_dir%/AR0148SR.BMP~
	~%biff_dir%/AR0149HT.BMP~
	~%biff_dir%/AR0149LM.BMP~
	~%biff_dir%/AR0149SR.BMP~
	~%biff_dir%/AR0150HT.BMP~
	~%biff_dir%/AR0150LM.BMP~
	~%biff_dir%/AR0150SR.BMP~
	~%biff_dir%/AR0151HT.BMP~
	~%biff_dir%/AR0151LM.BMP~
	~%biff_dir%/AR0151SR.BMP~
	~%biff_dir%/AR0152HT.BMP~
	~%biff_dir%/AR0152LM.BMP~
	~%biff_dir%/AR0152SR.BMP~
	~%biff_dir%/AR0153HT.BMP~
	~%biff_dir%/AR0153LM.BMP~
	~%biff_dir%/AR0153SR.BMP~
	~%biff_dir%/AR0155HT.BMP~
	~%biff_dir%/AR0155LM.BMP~
	~%biff_dir%/AR0155SR.BMP~
	~%biff_dir%/AR0156HT.BMP~
	~%biff_dir%/AR0156LM.BMP~
	~%biff_dir%/AR0156SR.BMP~
	~%biff_dir%/AR0161HT.BMP~
	~%biff_dir%/AR0161LM.BMP~
	~%biff_dir%/AR0161SR.BMP~
	~%biff_dir%/AR0162HT.BMP~
	~%biff_dir%/AR0162LM.BMP~
	~%biff_dir%/AR0162SR.BMP~
	~%biff_dir%/AR0163HT.BMP~
	~%biff_dir%/AR0163LM.BMP~
	~%biff_dir%/AR0163SR.BMP~
	~%biff_dir%/AR0164HT.BMP~
	~%biff_dir%/AR0164LM.BMP~
	~%biff_dir%/AR0164SR.BMP~
	~%biff_dir%/AR0165HT.BMP~
	~%biff_dir%/AR0165LM.BMP~
	~%biff_dir%/AR0165SR.BMP~
	~%biff_dir%/AR0166HT.BMP~
	~%biff_dir%/AR0166LM.BMP~
	~%biff_dir%/AR0166SR.BMP~
	~%biff_dir%/AR0167HT.BMP~
	~%biff_dir%/AR0167LM.BMP~
	~%biff_dir%/AR0167SR.BMP~
	~%biff_dir%/AR0168HT.BMP~
	~%biff_dir%/AR0168LM.BMP~
	~%biff_dir%/AR0168SR.BMP~
	~%biff_dir%/AR0169HT.BMP~
	~%biff_dir%/AR0169LM.BMP~
	~%biff_dir%/AR0169SR.BMP~
	~%biff_dir%/AR0170HT.BMP~
	~%biff_dir%/AR0170LM.BMP~
	~%biff_dir%/AR0170SR.BMP~
	~%biff_dir%/AR0200HT.BMP~
	~%biff_dir%/AR0200LM.BMP~
	~%biff_dir%/AR0200LN.BMP~
	~%biff_dir%/AR0200SR.BMP~
	~%biff_dir%/AR0224HT.BMP~
	~%biff_dir%/AR0224LM.BMP~
	~%biff_dir%/AR0224SR.BMP~
	~%biff_dir%/AR0225HT.BMP~
	~%biff_dir%/AR0225LM.BMP~
	~%biff_dir%/AR0225SR.BMP~
	~%biff_dir%/AR0226HT.BMP~
	~%biff_dir%/AR0226LM.BMP~
	~%biff_dir%/AR0226SR.BMP~
	~%biff_dir%/AR0300HT.BMP~
	~%biff_dir%/AR0300LM.BMP~
	~%biff_dir%/AR0300LN.BMP~
	~%biff_dir%/AR0300SR.BMP~
	~%biff_dir%/AR0304HT.BMP~
	~%biff_dir%/AR0304LM.BMP~
	~%biff_dir%/AR0304SR.BMP~
	~%biff_dir%/AR0400HT.BMP~
	~%biff_dir%/AR0400LM.BMP~
	~%biff_dir%/AR0400SR.BMP~
	~%biff_dir%/AR0401HT.BMP~
	~%biff_dir%/AR0401LM.BMP~
	~%biff_dir%/AR0401SR.BMP~
	~%biff_dir%/AR0500HT.BMP~
	~%biff_dir%/AR0500LM.BMP~
	~%biff_dir%/AR0500SR.BMP~
	~%biff_dir%/AR0501HT.BMP~
	~%biff_dir%/AR0501LM.BMP~
	~%biff_dir%/AR0501SR.BMP~
	~%biff_dir%/AR0502HT.BMP~
	~%biff_dir%/AR0502LM.BMP~
	~%biff_dir%/AR0502SR.BMP~
	~%biff_dir%/AR0503HT.BMP~
	~%biff_dir%/AR0503LM.BMP~
	~%biff_dir%/AR0503SR.BMP~
	~%biff_dir%/AR0504HT.BMP~
	~%biff_dir%/AR0504LM.BMP~
	~%biff_dir%/AR0504SR.BMP~
	~%biff_dir%/AR0505HT.BMP~
	~%biff_dir%/AR0505LM.BMP~
	~%biff_dir%/AR0505SR.BMP~
	~%biff_dir%/AR0506HT.BMP~
	~%biff_dir%/AR0506LM.BMP~
	~%biff_dir%/AR0506SR.BMP~
	~%biff_dir%/AR0507HT.BMP~
	~%biff_dir%/AR0507LM.BMP~
	~%biff_dir%/AR0507SR.BMP~
	~%biff_dir%/AR0508HT.BMP~
	~%biff_dir%/AR0508LM.BMP~
	~%biff_dir%/AR0508SR.BMP~
	~%biff_dir%/AR0509HT.BMP~
	~%biff_dir%/AR0509LM.BMP~
	~%biff_dir%/AR0509SR.BMP~
	~%biff_dir%/AR0510HT.BMP~
	~%biff_dir%/AR0510LM.BMP~
	~%biff_dir%/AR0510SR.BMP~
	~%biff_dir%/AR0511HT.BMP~
	~%biff_dir%/AR0511LM.BMP~
	~%biff_dir%/AR0511SR.BMP~
	~%biff_dir%/AR0512HT.BMP~
	~%biff_dir%/AR0512LM.BMP~
	~%biff_dir%/AR0512SR.BMP~
	~%biff_dir%/AR0513HT.BMP~
	~%biff_dir%/AR0513LM.BMP~
	~%biff_dir%/AR0513SR.BMP~
	~%biff_dir%/AR0514HT.BMP~
	~%biff_dir%/AR0514LM.BMP~
	~%biff_dir%/AR0514SR.BMP~
	~%biff_dir%/AR0515HT.BMP~
	~%biff_dir%/AR0515LM.BMP~
	~%biff_dir%/AR0515SR.BMP~
	~%biff_dir%/AR0516HT.BMP~
	~%biff_dir%/AR0516LM.BMP~
	~%biff_dir%/AR0516SR.BMP~
	~%biff_dir%/AR0600HT.BMP~
	~%biff_dir%/AR0600LM.BMP~
	~%biff_dir%/AR0600LN.BMP~
	~%biff_dir%/AR0600SR.BMP~
	~%biff_dir%/AR0601HT.BMP~
	~%biff_dir%/AR0601LM.BMP~
	~%biff_dir%/AR0601SR.BMP~
	~%biff_dir%/AR0602HT.BMP~
	~%biff_dir%/AR0602LM.BMP~
	~%biff_dir%/AR0602SR.BMP~
	~%biff_dir%/AR0603HT.BMP~
	~%biff_dir%/AR0603LM.BMP~
	~%biff_dir%/AR0603SR.BMP~
	~%biff_dir%/AR0606HT.BMP~
	~%biff_dir%/AR0606LM.BMP~
	~%biff_dir%/AR0606SR.BMP~
	~%biff_dir%/AR0607HT.BMP~
	~%biff_dir%/AR0607LM.BMP~
	~%biff_dir%/AR0607SR.BMP~
	~%biff_dir%/AR0608HT.BMP~
	~%biff_dir%/AR0608LM.BMP~
	~%biff_dir%/AR0608SR.BMP~
	~%biff_dir%/AR0609HT.BMP~
	~%biff_dir%/AR0609LM.BMP~
	~%biff_dir%/AR0609SR.BMP~
	~%biff_dir%/AR0611HT.BMP~
	~%biff_dir%/AR0611LM.BMP~
	~%biff_dir%/AR0611SR.BMP~
	~%biff_dir%/AR0612HT.BMP~
	~%biff_dir%/AR0612LM.BMP~
	~%biff_dir%/AR0612SR.BMP~
	~%biff_dir%/AR0613HT.BMP~
	~%biff_dir%/AR0613LM.BMP~
	~%biff_dir%/AR0613SR.BMP~
	~%biff_dir%/AR0614HT.BMP~
	~%biff_dir%/AR0614LM.BMP~
	~%biff_dir%/AR0614SR.BMP~
	~%biff_dir%/AR0615HT.BMP~
	~%biff_dir%/AR0615LM.BMP~
	~%biff_dir%/AR0615SR.BMP~
	~%biff_dir%/AR0616HT.BMP~
	~%biff_dir%/AR0616LM.BMP~
	~%biff_dir%/AR0616SR.BMP~
	~%biff_dir%/AR0621HT.BMP~
	~%biff_dir%/AR0621LM.BMP~
	~%biff_dir%/AR0621LN.BMP~
	~%biff_dir%/AR0621SR.BMP~
	~%biff_dir%/AR0700HT.BMP~
	~%biff_dir%/AR0700LM.BMP~
	~%biff_dir%/AR0700LN.BMP~
	~%biff_dir%/AR0700SR.BMP~
	~%biff_dir%/AR0702HT.BMP~
	~%biff_dir%/AR0702LM.BMP~
	~%biff_dir%/AR0702SR.BMP~
	~%biff_dir%/AR0703HT.BMP~
	~%biff_dir%/AR0703LM.BMP~
	~%biff_dir%/AR0703SR.BMP~
	~%biff_dir%/AR0704HT.BMP~
	~%biff_dir%/AR0704LM.BMP~
	~%biff_dir%/AR0704SR.BMP~
	~%biff_dir%/AR0705HT.BMP~
	~%biff_dir%/AR0705LM.BMP~
	~%biff_dir%/AR0705SR.BMP~
	~%biff_dir%/AR0706HT.BMP~
	~%biff_dir%/AR0706LM.BMP~
	~%biff_dir%/AR0706SR.BMP~
	~%biff_dir%/AR0719HT.BMP~
	~%biff_dir%/AR0719LM.BMP~
	~%biff_dir%/AR0719SR.BMP~
	~%biff_dir%/AR0720HT.BMP~
	~%biff_dir%/AR0720LM.BMP~
	~%biff_dir%/AR0720SR.BMP~
	~%biff_dir%/AR0724HT.BMP~
	~%biff_dir%/AR0724LM.BMP~
	~%biff_dir%/AR0724SR.BMP~
	~%biff_dir%/AR0726HT.BMP~
	~%biff_dir%/AR0726LM.BMP~
	~%biff_dir%/AR0726SR.BMP~
	~%biff_dir%/AR0800HT.BMP~
	~%biff_dir%/AR0800LM.BMP~
	~%biff_dir%/AR0800LN.BMP~
	~%biff_dir%/AR0800SR.BMP~
	~%biff_dir%/AR0807HT.BMP~
	~%biff_dir%/AR0807LM.BMP~
	~%biff_dir%/AR0807SR.BMP~
	~%biff_dir%/AR0808HT.BMP~
	~%biff_dir%/AR0808LM.BMP~
	~%biff_dir%/AR0808SR.BMP~
	~%biff_dir%/AR0809HT.BMP~
	~%biff_dir%/AR0809LM.BMP~
	~%biff_dir%/AR0809SR.BMP~
	~%biff_dir%/AR0900HT.BMP~
	~%biff_dir%/AR0900LM.BMP~
	~%biff_dir%/AR0900LN.BMP~
	~%biff_dir%/AR0900SR.BMP~
	~%biff_dir%/AR0901HT.BMP~
	~%biff_dir%/AR0901LM.BMP~
	~%biff_dir%/AR0901SR.BMP~
	~%biff_dir%/AR1000HT.BMP~
	~%biff_dir%/AR1000LM.BMP~
	~%biff_dir%/AR1000SR.BMP~
	~%biff_dir%/AR1001HT.BMP~
	~%biff_dir%/AR1001LM.BMP~
	~%biff_dir%/AR1001SR.BMP~
	~%biff_dir%/AR1002HT.BMP~
	~%biff_dir%/AR1002LM.BMP~
	~%biff_dir%/AR1002SR.BMP~
	~%biff_dir%/AR1003HT.BMP~
	~%biff_dir%/AR1003LM.BMP~
	~%biff_dir%/AR1003SR.BMP~
	~%biff_dir%/AR1004HT.BMP~
	~%biff_dir%/AR1004LM.BMP~
	~%biff_dir%/AR1004SR.BMP~
	~%biff_dir%/AR1005HT.BMP~
	~%biff_dir%/AR1005LM.BMP~
	~%biff_dir%/AR1005SR.BMP~
	~%biff_dir%/AR1008HT.BMP~
	~%biff_dir%/AR1008LM.BMP~
	~%biff_dir%/AR1008SR.BMP~
	~%biff_dir%/AR1009HT.BMP~
	~%biff_dir%/AR1009LM.BMP~
	~%biff_dir%/AR1009SR.BMP~
	~%biff_dir%/AR1010HT.BMP~
	~%biff_dir%/AR1010LM.BMP~
	~%biff_dir%/AR1010SR.BMP~
	~%biff_dir%/AR1100HT.BMP~
	~%biff_dir%/AR1100LM.BMP~
	~%biff_dir%/AR1100LN.BMP~
	~%biff_dir%/AR1100SR.BMP~
	~%biff_dir%/AR1101HT.BMP~
	~%biff_dir%/AR1101LM.BMP~
	~%biff_dir%/AR1101SR.BMP~
	~%biff_dir%/AR1102HT.BMP~
	~%biff_dir%/AR1102LM.BMP~
	~%biff_dir%/AR1102SR.BMP~
	~%biff_dir%/AR1200HT.BMP~
	~%biff_dir%/AR1200LM.BMP~
	~%biff_dir%/AR1200LN.BMP~
	~%biff_dir%/AR1200SR.BMP~
	~%biff_dir%/AR1207HT.BMP~
	~%biff_dir%/AR1207LM.BMP~
	~%biff_dir%/AR1207SR.BMP~
	~%biff_dir%/AR1208HT.BMP~
	~%biff_dir%/AR1208LM.BMP~
	~%biff_dir%/AR1208SR.BMP~
	~%biff_dir%/AR1215HT.BMP~
	~%biff_dir%/AR1215LM.BMP~
	~%biff_dir%/AR1215SR.BMP~
	~%biff_dir%/AR1300HT.BMP~
	~%biff_dir%/AR1300LM.BMP~
	~%biff_dir%/AR1300LN.BMP~
	~%biff_dir%/AR1300SR.BMP~
	~%biff_dir%/AR1302HT.BMP~
	~%biff_dir%/AR1302LM.BMP~
	~%biff_dir%/AR1302SR.BMP~
	~%biff_dir%/AR1320LM.BMP~
	~%biff_dir%/AR1400HT.BMP~
	~%biff_dir%/AR1400LM.BMP~
	~%biff_dir%/AR1400SR.BMP~
	~%biff_dir%/AR1401HT.BMP~
	~%biff_dir%/AR1401LM.BMP~
	~%biff_dir%/AR1401SR.BMP~
	~%biff_dir%/AR1402HT.BMP~
	~%biff_dir%/AR1402LM.BMP~
	~%biff_dir%/AR1402SR.BMP~
	~%biff_dir%/AR1403HT.BMP~
	~%biff_dir%/AR1403LM.BMP~
	~%biff_dir%/AR1403SR.BMP~
	~%biff_dir%/AR1404HT.BMP~
	~%biff_dir%/AR1404LM.BMP~
	~%biff_dir%/AR1404SR.BMP~
	~%biff_dir%/AR1500HT.BMP~
	~%biff_dir%/AR1500LM.BMP~
	~%biff_dir%/AR1500SR.BMP~
	~%biff_dir%/AR1501HT.BMP~
	~%biff_dir%/AR1501LM.BMP~
	~%biff_dir%/AR1501SR.BMP~
	~%biff_dir%/AR1502HT.BMP~
	~%biff_dir%/AR1502LM.BMP~
	~%biff_dir%/AR1502SR.BMP~
	~%biff_dir%/AR1503HT.BMP~
	~%biff_dir%/AR1503LM.BMP~
	~%biff_dir%/AR1503SR.BMP~
	~%biff_dir%/AR1504HT.BMP~
	~%biff_dir%/AR1504LM.BMP~
	~%biff_dir%/AR1504SR.BMP~
	~%biff_dir%/AR1505HT.BMP~
	~%biff_dir%/AR1505LM.BMP~
	~%biff_dir%/AR1505SR.BMP~
	~%biff_dir%/AR1600HT.BMP~
	~%biff_dir%/AR1600LM.BMP~
	~%biff_dir%/AR1600SR.BMP~
	~%biff_dir%/AR1601HT.BMP~
	~%biff_dir%/AR1601LM.BMP~
	~%biff_dir%/AR1601SR.BMP~
	~%biff_dir%/AR1602HT.BMP~
	~%biff_dir%/AR1602LM.BMP~
	~%biff_dir%/AR1602SR.BMP~
	~%biff_dir%/AR1603HT.BMP~
	~%biff_dir%/AR1603LM.BMP~
	~%biff_dir%/AR1603SR.BMP~
	~%biff_dir%/AR1700HT.BMP~
	~%biff_dir%/AR1700LM.BMP~
	~%biff_dir%/AR1700SR.BMP~
	~%biff_dir%/AR1800HT.BMP~
	~%biff_dir%/AR1800LM.BMP~
	~%biff_dir%/AR1800SR.BMP~
	~%biff_dir%/AR1801HT.BMP~
	~%biff_dir%/AR1801LM.BMP~
	~%biff_dir%/AR1801SR.BMP~
	~%biff_dir%/AR1802HT.BMP~
	~%biff_dir%/AR1802LM.BMP~
	~%biff_dir%/AR1802SR.BMP~
	~%biff_dir%/AR1803HT.BMP~
	~%biff_dir%/AR1803LM.BMP~
	~%biff_dir%/AR1803SR.BMP~
	~%biff_dir%/AR1804HT.BMP~
	~%biff_dir%/AR1804LM.BMP~
	~%biff_dir%/AR1804SR.BMP~
	~%biff_dir%/AR1805HT.BMP~
	~%biff_dir%/AR1805LM.BMP~
	~%biff_dir%/AR1805SR.BMP~
	~%biff_dir%/AR1806HT.BMP~
	~%biff_dir%/AR1806LM.BMP~
	~%biff_dir%/AR1806SR.BMP~
	~%biff_dir%/AR1807HT.BMP~
	~%biff_dir%/AR1807LM.BMP~
	~%biff_dir%/AR1807SR.BMP~
	~%biff_dir%/AR1808HT.BMP~
	~%biff_dir%/AR1808LM.BMP~
	~%biff_dir%/AR1808SR.BMP~
	~%biff_dir%/AR1809HT.BMP~
	~%biff_dir%/AR1809LM.BMP~
	~%biff_dir%/AR1809SR.BMP~
	~%biff_dir%/AR1900HT.BMP~
	~%biff_dir%/AR1900LM.BMP~
	~%biff_dir%/AR1900LN.BMP~
	~%biff_dir%/AR1900SR.BMP~
	~%biff_dir%/AR1901HT.BMP~
	~%biff_dir%/AR1901LM.BMP~
	~%biff_dir%/AR1901SR.BMP~
	~%biff_dir%/AR1902HT.BMP~
	~%biff_dir%/AR1902LM.BMP~
	~%biff_dir%/AR1902SR.BMP~
	~%biff_dir%/AR1903HT.BMP~
	~%biff_dir%/AR1903LM.BMP~
	~%biff_dir%/AR1903SR.BMP~
	~%biff_dir%/AR2000HT.BMP~
	~%biff_dir%/AR2000LM.BMP~
	~%biff_dir%/AR2000SR.BMP~
	~%biff_dir%/AR2001HT.BMP~
	~%biff_dir%/AR2001LM.BMP~
	~%biff_dir%/AR2001SR.BMP~
	~%biff_dir%/AR2002HT.BMP~
	~%biff_dir%/AR2002LM.BMP~
	~%biff_dir%/AR2002SR.BMP~
	~%biff_dir%/AR2004HT.BMP~
	~%biff_dir%/AR2004LM.BMP~
	~%biff_dir%/AR2004SR.BMP~
	~%biff_dir%/AR2006HT.BMP~
	~%biff_dir%/AR2006LM.BMP~
	~%biff_dir%/AR2006SR.BMP~
	~%biff_dir%/AR2008HT.BMP~
	~%biff_dir%/AR2008LM.BMP~
	~%biff_dir%/AR2008SR.BMP~
	~%biff_dir%/AR2012HT.BMP~
	~%biff_dir%/AR2012LM.BMP~
	~%biff_dir%/AR2012SR.BMP~
	~%biff_dir%/AR2100HT.BMP~
	~%biff_dir%/AR2100LM.BMP~
	~%biff_dir%/AR2100SR.BMP~
	~%biff_dir%/AR2101HT.BMP~
	~%biff_dir%/AR2101LM.BMP~
	~%biff_dir%/AR2101SR.BMP~
	~%biff_dir%/AR2200HT.BMP~
	~%biff_dir%/AR2200LM.BMP~
	~%biff_dir%/AR2200SR.BMP~
	~%biff_dir%/AR2215HT.BMP~
	~%biff_dir%/AR2215LM.BMP~
	~%biff_dir%/AR2215SR.BMP~
	~%biff_dir%/AR2300HT.BMP~
	~%biff_dir%/AR2300LM.BMP~
	~%biff_dir%/AR2300LN.BMP~
	~%biff_dir%/AR2300SR.BMP~
	~%biff_dir%/AR2301HT.BMP~
	~%biff_dir%/AR2301LM.BMP~
	~%biff_dir%/AR2301SR.BMP~
	~%biff_dir%/AR2302HT.BMP~
	~%biff_dir%/AR2302LM.BMP~
	~%biff_dir%/AR2302SR.BMP~
	~%biff_dir%/AR2303HT.BMP~
	~%biff_dir%/AR2303LM.BMP~
	~%biff_dir%/AR2303SR.BMP~
	~%biff_dir%/AR2304HT.BMP~
	~%biff_dir%/AR2304LM.BMP~
	~%biff_dir%/AR2304SR.BMP~
	~%biff_dir%/AR2305HT.BMP~
	~%biff_dir%/AR2305LM.BMP~
	~%biff_dir%/AR2305SR.BMP~
	~%biff_dir%/AR2306HT.BMP~
	~%biff_dir%/AR2306LM.BMP~
	~%biff_dir%/AR2306SR.BMP~
	~%biff_dir%/AR2400HT.BMP~
	~%biff_dir%/AR2400LM.BMP~
	~%biff_dir%/AR2400SR.BMP~
	~%biff_dir%/AR2600HT.BMP~
	~%biff_dir%/AR2600LM.BMP~
	~%biff_dir%/AR2600LN.BMP~
	~%biff_dir%/AR2600SR.BMP~
	~%biff_dir%/AR2602HT.BMP~
	~%biff_dir%/AR2602LM.BMP~
	~%biff_dir%/AR2602SR.BMP~
	~%biff_dir%/AR2605HT.BMP~
	~%biff_dir%/AR2605LM.BMP~
	~%biff_dir%/AR2605SR.BMP~
	~%biff_dir%/AR2606HT.BMP~
	~%biff_dir%/AR2606LM.BMP~
	~%biff_dir%/AR2606SR.BMP~
	~%biff_dir%/AR2607HT.BMP~
	~%biff_dir%/AR2607LM.BMP~
	~%biff_dir%/AR2607SR.BMP~
	~%biff_dir%/AR2608HT.BMP~
	~%biff_dir%/AR2608LM.BMP~
	~%biff_dir%/AR2608SR.BMP~
	~%biff_dir%/AR2609HT.BMP~
	~%biff_dir%/AR2609LM.BMP~
	~%biff_dir%/AR2609SR.BMP~
	~%biff_dir%/AR2610HT.BMP~
	~%biff_dir%/AR2610LM.BMP~
	~%biff_dir%/AR2610SR.BMP~
	~%biff_dir%/AR2611HT.BMP~
	~%biff_dir%/AR2611LM.BMP~
	~%biff_dir%/AR2611SR.BMP~
	~%biff_dir%/AR2612HT.BMP~
	~%biff_dir%/AR2612LM.BMP~
	~%biff_dir%/AR2612SR.BMP~
	~%biff_dir%/AR2613HT.BMP~
	~%biff_dir%/AR2613LM.BMP~
	~%biff_dir%/AR2613SR.BMP~
	~%biff_dir%/AR2614HT.BMP~
	~%biff_dir%/AR2614LM.BMP~
	~%biff_dir%/AR2614SR.BMP~
	~%biff_dir%/AR2615HT.BMP~
	~%biff_dir%/AR2615LM.BMP~
	~%biff_dir%/AR2615SR.BMP~
	~%biff_dir%/AR2616HT.BMP~
	~%biff_dir%/AR2616LM.BMP~
	~%biff_dir%/AR2616SR.BMP~
	~%biff_dir%/AR2617HT.BMP~
	~%biff_dir%/AR2617LM.BMP~
	~%biff_dir%/AR2617SR.BMP~
	~%biff_dir%/AR2618HT.BMP~
	~%biff_dir%/AR2618LM.BMP~
	~%biff_dir%/AR2618SR.BMP~
	~%biff_dir%/AR2619HT.BMP~
	~%biff_dir%/AR2619LM.BMP~
	~%biff_dir%/AR2619SR.BMP~
	~%biff_dir%/AR2631HT.BMP~
	~%biff_dir%/AR2631LM.BMP~
	~%biff_dir%/AR2631SR.BMP~
	~%biff_dir%/AR2643HT.BMP~
	~%biff_dir%/AR2643LM.BMP~
	~%biff_dir%/AR2643SR.BMP~
	~%biff_dir%/AR2700HT.BMP~
	~%biff_dir%/AR2700LM.BMP~
	~%biff_dir%/AR2700SR.BMP~
	~%biff_dir%/AR2800HT.BMP~
	~%biff_dir%/AR2800LM.BMP~
	~%biff_dir%/AR2800SR.BMP~
	~%biff_dir%/AR2900HT.BMP~
	~%biff_dir%/AR2900LM.BMP~
	~%biff_dir%/AR2900SR.BMP~
	~%biff_dir%/AR3000HT.BMP~
	~%biff_dir%/AR3000LM.BMP~
	~%biff_dir%/AR3000SR.BMP~
	~%biff_dir%/AR3100HT.BMP~
	~%biff_dir%/AR3100LM.BMP~
	~%biff_dir%/AR3100SR.BMP~
	~%biff_dir%/AR3200HT.BMP~
	~%biff_dir%/AR3200LM.BMP~
	~%biff_dir%/AR3200LN.BMP~
	~%biff_dir%/AR3200SR.BMP~
	~%biff_dir%/AR3201HT.BMP~
	~%biff_dir%/AR3201LM.BMP~
	~%biff_dir%/AR3201SR.BMP~
	~%biff_dir%/AR3202HT.BMP~
	~%biff_dir%/AR3202LM.BMP~
	~%biff_dir%/AR3202SR.BMP~
	~%biff_dir%/AR3300HT.BMP~
	~%biff_dir%/AR3300LM.BMP~
	~%biff_dir%/AR3300SR.BMP~
	~%biff_dir%/AR3301HT.BMP~
	~%biff_dir%/AR3301LM.BMP~
	~%biff_dir%/AR3301SR.BMP~
	~%biff_dir%/AR3302HT.BMP~
	~%biff_dir%/AR3302LM.BMP~
	~%biff_dir%/AR3302SR.BMP~
	~%biff_dir%/AR3303HT.BMP~
	~%biff_dir%/AR3303LM.BMP~
	~%biff_dir%/AR3303SR.BMP~
	~%biff_dir%/AR3304HT.BMP~
	~%biff_dir%/AR3304LM.BMP~
	~%biff_dir%/AR3304SR.BMP~
	~%biff_dir%/AR3305HT.BMP~
	~%biff_dir%/AR3305LM.BMP~
	~%biff_dir%/AR3305SR.BMP~
	~%biff_dir%/AR3306HT.BMP~
	~%biff_dir%/AR3306LM.BMP~
	~%biff_dir%/AR3306SR.BMP~
	~%biff_dir%/AR3307HT.BMP~
	~%biff_dir%/AR3307LM.BMP~
	~%biff_dir%/AR3307SR.BMP~
	~%biff_dir%/AR3308HT.BMP~
	~%biff_dir%/AR3308LM.BMP~
	~%biff_dir%/AR3308SR.BMP~
	~%biff_dir%/AR3309HT.BMP~
	~%biff_dir%/AR3309LM.BMP~
	~%biff_dir%/AR3309SR.BMP~
	~%biff_dir%/AR3310HT.BMP~
	~%biff_dir%/AR3310LM.BMP~
	~%biff_dir%/AR3310SR.BMP~
	~%biff_dir%/AR3313HT.BMP~
	~%biff_dir%/AR3313LM.BMP~
	~%biff_dir%/AR3313SR.BMP~
	~%biff_dir%/AR3314HT.BMP~
	~%biff_dir%/AR3314LM.BMP~
	~%biff_dir%/AR3314SR.BMP~
	~%biff_dir%/AR3316HT.BMP~
	~%biff_dir%/AR3316LM.BMP~
	~%biff_dir%/AR3316SR.BMP~
	~%biff_dir%/AR3317HT.BMP~
	~%biff_dir%/AR3317LM.BMP~
	~%biff_dir%/AR3317SR.BMP~
	~%biff_dir%/AR3320HT.BMP~
	~%biff_dir%/AR3320LM.BMP~
	~%biff_dir%/AR3320SR.BMP~
	~%biff_dir%/AR3321HT.BMP~
	~%biff_dir%/AR3321LM.BMP~
	~%biff_dir%/AR3321SR.BMP~
	~%biff_dir%/AR3327HT.BMP~
	~%biff_dir%/AR3327LM.BMP~
	~%biff_dir%/AR3327SR.BMP~
	~%biff_dir%/AR3328HT.BMP~
	~%biff_dir%/AR3328LM.BMP~
	~%biff_dir%/AR3328SR.BMP~
	~%biff_dir%/AR3339HT.BMP~
	~%biff_dir%/AR3339LM.BMP~
	~%biff_dir%/AR3339SR.BMP~
	~%biff_dir%/AR3340HT.BMP~
	~%biff_dir%/AR3340LM.BMP~
	~%biff_dir%/AR3340SR.BMP~
	~%biff_dir%/AR3351HT.BMP~
	~%biff_dir%/AR3351LM.BMP~
	~%biff_dir%/AR3351SR.BMP~
	~%biff_dir%/AR3352HT.BMP~
	~%biff_dir%/AR3352LM.BMP~
	~%biff_dir%/AR3352SR.BMP~
	~%biff_dir%/AR3353HT.BMP~
	~%biff_dir%/AR3353LM.BMP~
	~%biff_dir%/AR3353SR.BMP~
	~%biff_dir%/AR3357HT.BMP~
	~%biff_dir%/AR3357LM.BMP~
	~%biff_dir%/AR3357SR.BMP~
	~%biff_dir%/AR3400HT.BMP~
	~%biff_dir%/AR3400LM.BMP~
	~%biff_dir%/AR3400LN.BMP~
	~%biff_dir%/AR3400SR.BMP~
	~%biff_dir%/AR3401HT.BMP~
	~%biff_dir%/AR3401LM.BMP~
	~%biff_dir%/AR3401SR.BMP~
	~%biff_dir%/AR3402HT.BMP~
	~%biff_dir%/AR3402LM.BMP~
	~%biff_dir%/AR3402SR.BMP~
	~%biff_dir%/AR3500HT.BMP~
	~%biff_dir%/AR3500LM.BMP~
	~%biff_dir%/AR3500SR.BMP~
	~%biff_dir%/AR3600HT.BMP~
	~%biff_dir%/AR3600LM.BMP~
	~%biff_dir%/AR3600SR.BMP~
	~%biff_dir%/AR3601HT.BMP~
	~%biff_dir%/AR3601LM.BMP~
	~%biff_dir%/AR3601SR.BMP~
	~%biff_dir%/AR3700HT.BMP~
	~%biff_dir%/AR3700LM.BMP~
	~%biff_dir%/AR3700SR.BMP~
	~%biff_dir%/AR3800HT.BMP~
	~%biff_dir%/AR3800LM.BMP~
	~%biff_dir%/AR3800SR.BMP~
	~%biff_dir%/AR3802HT.BMP~
	~%biff_dir%/AR3802LM.BMP~
	~%biff_dir%/AR3802SR.BMP~
	~%biff_dir%/AR3900HT.BMP~
	~%biff_dir%/AR3900LM.BMP~
	~%biff_dir%/AR3900SR.BMP~
	~%biff_dir%/AR3901HT.BMP~
	~%biff_dir%/AR3901LM.BMP~
	~%biff_dir%/AR3901SR.BMP~
	~%biff_dir%/AR4000HT.BMP~
	~%biff_dir%/AR4000LM.BMP~
	~%biff_dir%/AR4000SR.BMP~
	~%biff_dir%/AR4001HT.BMP~
	~%biff_dir%/AR4001LM.BMP~
	~%biff_dir%/AR4001SR.BMP~
	~%biff_dir%/AR4002HT.BMP~
	~%biff_dir%/AR4002LM.BMP~
	~%biff_dir%/AR4002SR.BMP~
	~%biff_dir%/AR4003HT.BMP~
	~%biff_dir%/AR4003LM.BMP~
	~%biff_dir%/AR4003SR.BMP~
	~%biff_dir%/AR4004HT.BMP~
	~%biff_dir%/AR4004LM.BMP~
	~%biff_dir%/AR4004SR.BMP~
	~%biff_dir%/AR4006HT.BMP~
	~%biff_dir%/AR4006LM.BMP~
	~%biff_dir%/AR4006SR.BMP~
	~%biff_dir%/AR4100HT.BMP~
	~%biff_dir%/AR4100LM.BMP~
	~%biff_dir%/AR4100SR.BMP~
	~%biff_dir%/AR4101HT.BMP~
	~%biff_dir%/AR4101LM.BMP~
	~%biff_dir%/AR4101SR.BMP~
	~%biff_dir%/AR4200HT.BMP~
	~%biff_dir%/AR4200LM.BMP~
	~%biff_dir%/AR4200SR.BMP~
	~%biff_dir%/AR4201HT.BMP~
	~%biff_dir%/AR4201LM.BMP~
	~%biff_dir%/AR4201SR.BMP~
	~%biff_dir%/AR4300HT.BMP~
	~%biff_dir%/AR4300LM.BMP~
	~%biff_dir%/AR4300SR.BMP~
	~%biff_dir%/AR4400HT.BMP~
	~%biff_dir%/AR4400LM.BMP~
	~%biff_dir%/AR4400SR.BMP~
	~%biff_dir%/AR4401HT.BMP~
	~%biff_dir%/AR4401LM.BMP~
	~%biff_dir%/AR4401SR.BMP~
	~%biff_dir%/AR4500HT.BMP~
	~%biff_dir%/AR4500LM.BMP~
	~%biff_dir%/AR4500SR.BMP~
	~%biff_dir%/AR4501HT.BMP~
	~%biff_dir%/AR4501LM.BMP~
	~%biff_dir%/AR4501SR.BMP~
	~%biff_dir%/AR4600HT.BMP~
	~%biff_dir%/AR4600LM.BMP~
	~%biff_dir%/AR4600SR.BMP~
	~%biff_dir%/AR4700HT.BMP~
	~%biff_dir%/AR4700LM.BMP~
	~%biff_dir%/AR4700LN.BMP~
	~%biff_dir%/AR4700SR.BMP~
	~%biff_dir%/AR4701HT.BMP~
	~%biff_dir%/AR4701LM.BMP~
	~%biff_dir%/AR4701SR.BMP~
	~%biff_dir%/AR4800HT.BMP~
	~%biff_dir%/AR4800LM.BMP~
	~%biff_dir%/AR4800SR.BMP~
	~%biff_dir%/AR4801HT.BMP~
	~%biff_dir%/AR4801LM.BMP~
	~%biff_dir%/AR4801SR.BMP~
	~%biff_dir%/AR4802HT.BMP~
	~%biff_dir%/AR4802LM.BMP~
	~%biff_dir%/AR4802SR.BMP~
	~%biff_dir%/AR4803HT.BMP~
	~%biff_dir%/AR4803LM.BMP~
	~%biff_dir%/AR4803SR.BMP~
	~%biff_dir%/AR4804HT.BMP~
	~%biff_dir%/AR4804LM.BMP~
	~%biff_dir%/AR4804SR.BMP~
	~%biff_dir%/AR4805HT.BMP~
	~%biff_dir%/AR4805LM.BMP~
	~%biff_dir%/AR4805SR.BMP~
	~%biff_dir%/AR4806HT.BMP~
	~%biff_dir%/AR4806LM.BMP~
	~%biff_dir%/AR4806SR.BMP~
	~%biff_dir%/AR4807HT.BMP~
	~%biff_dir%/AR4807LM.BMP~
	~%biff_dir%/AR4807SR.BMP~
	~%biff_dir%/AR4808HT.BMP~
	~%biff_dir%/AR4808LM.BMP~
	~%biff_dir%/AR4808SR.BMP~
	~%biff_dir%/AR4809HT.BMP~
	~%biff_dir%/AR4809LM.BMP~
	~%biff_dir%/AR4809SR.BMP~
	~%biff_dir%/AR4810HT.BMP~
	~%biff_dir%/AR4810LM.BMP~
	~%biff_dir%/AR4810SR.BMP~
	~%biff_dir%/AR4900HT.BMP~
	~%biff_dir%/AR4900LM.BMP~
	~%biff_dir%/AR4900LN.BMP~
	~%biff_dir%/AR4900SR.BMP~
	~%biff_dir%/AR4901HT.BMP~
	~%biff_dir%/AR4901LM.BMP~
	~%biff_dir%/AR4901SR.BMP~
	~%biff_dir%/AR4902HT.BMP~
	~%biff_dir%/AR4902LM.BMP~
	~%biff_dir%/AR4902SR.BMP~
	~%biff_dir%/AR4903HT.BMP~
	~%biff_dir%/AR4903LM.BMP~
	~%biff_dir%/AR4903SR.BMP~
	~%biff_dir%/AR4905HT.BMP~
	~%biff_dir%/AR4905LM.BMP~
	~%biff_dir%/AR4905SR.BMP~
	~%biff_dir%/AR4906HT.BMP~
	~%biff_dir%/AR4906LM.BMP~
	~%biff_dir%/AR4906SR.BMP~
	~%biff_dir%/AR5000HT.BMP~
	~%biff_dir%/AR5000LM.BMP~
	~%biff_dir%/AR5000SR.BMP~
	~%biff_dir%/AR5001HT.BMP~
	~%biff_dir%/AR5001LM.BMP~
	~%biff_dir%/AR5001SR.BMP~
	~%biff_dir%/AR5100HT.BMP~
	~%biff_dir%/AR5100LM.BMP~
	~%biff_dir%/AR5100SR.BMP~
	~%biff_dir%/AR5101HT.BMP~
	~%biff_dir%/AR5101LM.BMP~
	~%biff_dir%/AR5101SR.BMP~
	~%biff_dir%/AR5102HT.BMP~
	~%biff_dir%/AR5102LM.BMP~
	~%biff_dir%/AR5102SR.BMP~
	~%biff_dir%/AR5103HT.BMP~
	~%biff_dir%/AR5103LM.BMP~
	~%biff_dir%/AR5103SR.BMP~
	~%biff_dir%/AR5200HT.BMP~
	~%biff_dir%/AR5200LM.BMP~
	~%biff_dir%/AR5200SR.BMP~
	~%biff_dir%/AR5201HT.BMP~
	~%biff_dir%/AR5201LM.BMP~
	~%biff_dir%/AR5201SR.BMP~
	~%biff_dir%/AR5202HT.BMP~
	~%biff_dir%/AR5202LM.BMP~
	~%biff_dir%/AR5202SR.BMP~
	~%biff_dir%/AR5300HT.BMP~
	~%biff_dir%/AR5300LM.BMP~
	~%biff_dir%/AR5300SR.BMP~
	~%biff_dir%/AR5400HT.BMP~
	~%biff_dir%/AR5400LM.BMP~
	~%biff_dir%/AR5400SR.BMP~
	~%biff_dir%/AR5401HT.BMP~
	~%biff_dir%/AR5401LM.BMP~
	~%biff_dir%/AR5401SR.BMP~
	~%biff_dir%/AR5402HT.BMP~
	~%biff_dir%/AR5402LM.BMP~
	~%biff_dir%/AR5402SR.BMP~
	~%biff_dir%/AR5403HT.BMP~
	~%biff_dir%/AR5403LM.BMP~
	~%biff_dir%/AR5403SR.BMP~
	~%biff_dir%/AR5404HT.BMP~
	~%biff_dir%/AR5404LM.BMP~
	~%biff_dir%/AR5404SR.BMP~
	~%biff_dir%/AR5405HT.BMP~
	~%biff_dir%/AR5405LM.BMP~
	~%biff_dir%/AR5405SR.BMP~
	~%biff_dir%/AR5406HT.BMP~
	~%biff_dir%/AR5406LM.BMP~
	~%biff_dir%/AR5406SR.BMP~
	~%biff_dir%/AR5500HT.BMP~
	~%biff_dir%/AR5500LM.BMP~
	~%biff_dir%/AR5500SR.BMP~
	~%biff_dir%/AR5506HT.BMP~
	~%biff_dir%/AR5506LM.BMP~
	~%biff_dir%/AR5506SR.BMP~
	~%biff_dir%/AR5600HT.BMP~
	~%biff_dir%/AR5600LM.BMP~
	~%biff_dir%/AR5600SR.BMP~
	~%biff_dir%/AR5700HT.BMP~
	~%biff_dir%/AR5700LM.BMP~
	~%biff_dir%/AR5700SR.BMP~
	~%biff_dir%/AR5800HT.BMP~
	~%biff_dir%/AR5800LM.BMP~
	~%biff_dir%/AR5800SR.BMP~
	~%biff_dir%/AR5900HT.BMP~
	~%biff_dir%/AR5900LM.BMP~
	~%biff_dir%/AR5900SR.BMP~
	~%biff_dir%/AR6000HT.BMP~
	~%biff_dir%/AR6000LM.BMP~
	~%biff_dir%/AR6000SR.BMP~
	~%biff_dir%/AR6100HT.BMP~
	~%biff_dir%/AR6100LM.BMP~
	~%biff_dir%/AR6100SR.BMP~
	~%biff_dir%/OH2000HT.BMP~
	~%biff_dir%/OH2000LM.BMP~
	~%biff_dir%/OH2000LN.BMP~
	~%biff_dir%/OH2000SR.BMP~
	~%biff_dir%/OH2010HT.BMP~
	~%biff_dir%/OH2010LM.BMP~
	~%biff_dir%/OH2010SR.BMP~
	~%biff_dir%/OH3000HT.BMP~
	~%biff_dir%/OH3000LM.BMP~
	~%biff_dir%/OH3000LN.BMP~
	~%biff_dir%/OH3000N.BMP~
	~%biff_dir%/OH3000SR.BMP~
	~%biff_dir%/OH3010HT.BMP~
	~%biff_dir%/OH3010LM.BMP~
	~%biff_dir%/OH3010SR.BMP~
	~%biff_dir%/OH3020HT.BMP~
	~%biff_dir%/OH3020LM.BMP~
	~%biff_dir%/OH3020SR.BMP~
	~%biff_dir%/OH3100HT.BMP~
	~%biff_dir%/OH3100LM.BMP~
	~%biff_dir%/OH3100LN.BMP~
	~%biff_dir%/OH3100SR.BMP~
	~%biff_dir%/OH9310HT.BMP~
	~%biff_dir%/OH9310LM.BMP~
	~%biff_dir%/OH9310SR.BMP~
	~%biff_dir%/OH9350HT.BMP~
	~%biff_dir%/OH9350LM.BMP~
	~%biff_dir%/OH9350SR.BMP~
	~%biff_dir%/OH9360HT.BMP~
	~%biff_dir%/OH9360LM.BMP~
	~%biff_dir%/OH9360SR.BMP~
	~%biff_dir%/OH9400LM.BMP~
	~%biff_dir%/TU0015HT.BMP~
	~%biff_dir%/TU0015LM.BMP~
	~%biff_dir%/TU0015SR.BMP~
	~%biff_dir%/TU0016.BMP~
	~%biff_dir%/TU0016HT.BMP~
	~%biff_dir%/TU0016LM.BMP~
	~%biff_dir%/TU0016SR.BMP~
	~%biff_dir%/TU0017HT.BMP~
	~%biff_dir%/TU0017LM.BMP~
	~%biff_dir%/TU0017SR.BMP~
	~%biff_dir%/TU0018HT.BMP~
	~%biff_dir%/TU0018LM.BMP~
	~%biff_dir%/TU0018SR.BMP~
	~%biff_dir%/BD0010HT.BMP~
	~%biff_dir%/BD0010LM.BMP~
	~%biff_dir%/BD0010LN.BMP~
	~%biff_dir%/BD0010SR.BMP~
	~%biff_dir%/BD0020HT.BMP~
	~%biff_dir%/BD0020LM.BMP~
	~%biff_dir%/BD0020LN.BMP~
	~%biff_dir%/BD0020SR.BMP~
	~%biff_dir%/BD0021HT.BMP~
	~%biff_dir%/BD0021LM.BMP~
	~%biff_dir%/BD0021LN.BMP~
	~%biff_dir%/BD0021SR.BMP~
	~%biff_dir%/BD0030HT.BMP~
	~%biff_dir%/BD0030LM.BMP~
	~%biff_dir%/BD0030LN.BMP~
	~%biff_dir%/BD0030SR.BMP~
	~%biff_dir%/BD0035HT.BMP~
	~%biff_dir%/BD0035LM.BMP~
	~%biff_dir%/BD0035SR.BMP~
	~%biff_dir%/BD0040HT.BMP~
	~%biff_dir%/BD0040LM.BMP~
	~%biff_dir%/BD0040LN.BMP~
	~%biff_dir%/BD0040SR.BMP~
	~%biff_dir%/BD0050HT.BMP~
	~%biff_dir%/BD0050LM.BMP~
	~%biff_dir%/BD0050LN.BMP~
	~%biff_dir%/BD0050SR.BMP~
	~%biff_dir%/BD0060HT.BMP~
	~%biff_dir%/BD0060LM.BMP~
	~%biff_dir%/BD0060LN.BMP~
	~%biff_dir%/BD0060SR.BMP~
	~%biff_dir%/BD0061HT.BMP~
	~%biff_dir%/BD0061LM.BMP~
	~%biff_dir%/BD0061SR.BMP~
	~%biff_dir%/BD0062HT.BMP~
	~%biff_dir%/BD0062LM.BMP~
	~%biff_dir%/BD0062SR.BMP~
	~%biff_dir%/BD0063HT.BMP~
	~%biff_dir%/BD0063LM.BMP~
	~%biff_dir%/BD0063LN.BMP~
	~%biff_dir%/BD0063SR.BMP~
	~%biff_dir%/BD0064HT.BMP~
	~%biff_dir%/BD0064LM.BMP~
	~%biff_dir%/BD0064LN.BMP~
	~%biff_dir%/BD0064SR.BMP~
	~%biff_dir%/BD0065HT.BMP~
	~%biff_dir%/BD0065LM.BMP~
	~%biff_dir%/BD0065LN.BMP~
	~%biff_dir%/BD0065SR.BMP~
	~%biff_dir%/BD0066HT.BMP~
	~%biff_dir%/BD0066LM.BMP~
	~%biff_dir%/BD0066LN.BMP~
	~%biff_dir%/BD0066SR.BMP~
	~%biff_dir%/BD0067HT.BMP~
	~%biff_dir%/BD0067LM.BMP~
	~%biff_dir%/BD0067SR.BMP~
	~%biff_dir%/BD0071HT.BMP~
	~%biff_dir%/BD0071LM.BMP~
	~%biff_dir%/BD0071LN.BMP~
	~%biff_dir%/BD0071SR.BMP~
	~%biff_dir%/BD0072HT.BMP~
	~%biff_dir%/BD0072LM.BMP~
	~%biff_dir%/BD0072SR.BMP~
	~%biff_dir%/BD0100HT.BMP~
	~%biff_dir%/BD0100LM.BMP~
	~%biff_dir%/BD0100SR.BMP~
	~%biff_dir%/BD0101HT.BMP~
	~%biff_dir%/BD0101LM.BMP~
	~%biff_dir%/BD0101SR.BMP~
	~%biff_dir%/BD0102HT.BMP~
	~%biff_dir%/BD0102LM.BMP~
	~%biff_dir%/BD0102SR.BMP~
	~%biff_dir%/BD0103HT.BMP~
	~%biff_dir%/BD0103LM.BMP~
	~%biff_dir%/BD0103SR.BMP~
	~%biff_dir%/BD0104HT.BMP~
	~%biff_dir%/BD0104LM.BMP~
	~%biff_dir%/BD0104SR.BMP~
	~%biff_dir%/BD0105HT.BMP~
	~%biff_dir%/BD0105LM.BMP~
	~%biff_dir%/BD0105SR.BMP~
	~%biff_dir%/BD0106HT.BMP~
	~%biff_dir%/BD0106LM.BMP~
	~%biff_dir%/BD0106SR.BMP~
	~%biff_dir%/BD0107HT.BMP~
	~%biff_dir%/BD0107LM.BMP~
	~%biff_dir%/BD0107SR.BMP~
	~%biff_dir%/BD0108HT.BMP~
	~%biff_dir%/BD0108LM.BMP~
	~%biff_dir%/BD0108SR.BMP~
	~%biff_dir%/BD0109HT.BMP~
	~%biff_dir%/BD0109LM.BMP~
	~%biff_dir%/BD0109SR.BMP~
	~%biff_dir%/BD0110HT.BMP~
	~%biff_dir%/BD0110LM.BMP~
	~%biff_dir%/BD0110SR.BMP~
	~%biff_dir%/BD0111HT.BMP~
	~%biff_dir%/BD0111LM.BMP~
	~%biff_dir%/BD0111SR.BMP~
	~%biff_dir%/BD0112HT.BMP~
	~%biff_dir%/BD0112LM.BMP~
	~%biff_dir%/BD0112SR.BMP~
	~%biff_dir%/BD0113HT.BMP~
	~%biff_dir%/BD0113LM.BMP~
	~%biff_dir%/BD0113SR.BMP~
	~%biff_dir%/BD0114HT.BMP~
	~%biff_dir%/BD0114LM.BMP~
	~%biff_dir%/BD0114SR.BMP~
	~%biff_dir%/BD0115HT.BMP~
	~%biff_dir%/BD0115LM.BMP~
	~%biff_dir%/BD0115SR.BMP~
	~%biff_dir%/BD0116HT.BMP~
	~%biff_dir%/BD0116LM.BMP~
	~%biff_dir%/BD0116SR.BMP~
	~%biff_dir%/BD0117HT.BMP~
	~%biff_dir%/BD0117LM.BMP~
	~%biff_dir%/BD0117SR.BMP~
	~%biff_dir%/BD0120HT.BMP~
	~%biff_dir%/BD0120LM.BMP~
	~%biff_dir%/BD0120SR.BMP~
	~%biff_dir%/BD0121HT.BMP~
	~%biff_dir%/BD0121LM.BMP~
	~%biff_dir%/BD0121SR.BMP~
	~%biff_dir%/BD0122HT.BMP~
	~%biff_dir%/BD0122LM.BMP~
	~%biff_dir%/BD0122SR.BMP~
	~%biff_dir%/BD0130HT.BMP~
	~%biff_dir%/BD0130LM.BMP~
	~%biff_dir%/BD0130SR.BMP~
	~%biff_dir%/BD1000HT.BMP~
	~%biff_dir%/BD1000LM.BMP~
	~%biff_dir%/BD1000LN.BMP~
	~%biff_dir%/BD1000SR.BMP~
	~%biff_dir%/BD1010HT.BMP~
	~%biff_dir%/BD1010LM.BMP~
	~%biff_dir%/BD1010SR.BMP~
	~%biff_dir%/BD1100HT.BMP~
	~%biff_dir%/BD1100LM.BMP~
	~%biff_dir%/BD1100SR.BMP~
	~%biff_dir%/BD1200HT.BMP~
	~%biff_dir%/BD1200LM.BMP~
	~%biff_dir%/BD1200LN.BMP~
	~%biff_dir%/BD1200SR.BMP~
	~%biff_dir%/BD2000HT.BMP~
	~%biff_dir%/BD2000LM.BMP~
	~%biff_dir%/BD2000LN.BMP~
	~%biff_dir%/BD2000SR.BMP~
	~%biff_dir%/BD2010HT.BMP~
	~%biff_dir%/BD2010LM.BMP~
	~%biff_dir%/BD2010SR.BMP~
	~%biff_dir%/BD2100HT.BMP~
	~%biff_dir%/BD2100LM.BMP~
	~%biff_dir%/BD2100SR.BMP~
	~%biff_dir%/BD3000HT.BMP~
	~%biff_dir%/BD3000LM.BMP~
	~%biff_dir%/BD3000LN.BMP~
	~%biff_dir%/BD3000SR.BMP~
	~%biff_dir%/BD4000HT.BMP~
	~%biff_dir%/BD4000LM.BMP~
	~%biff_dir%/BD4000LN.BMP~
	~%biff_dir%/BD4000SR.BMP~
	~%biff_dir%/BD4100HT.BMP~
	~%biff_dir%/BD4100LM.BMP~
	~%biff_dir%/BD4100SR.BMP~
	~%biff_dir%/BD4300HT.BMP~
	~%biff_dir%/BD4300LM.BMP~
	~%biff_dir%/BD4300SR.BMP~
	~%biff_dir%/BD4400HT.BMP~
	~%biff_dir%/BD4400LM.BMP~
	~%biff_dir%/BD4400SR.BMP~
	~%biff_dir%/BD4500HT.BMP~
	~%biff_dir%/BD4500LM.BMP~
	~%biff_dir%/BD4500SR.BMP~
	~%biff_dir%/BD4600HT.BMP~
	~%biff_dir%/BD4600LM.BMP~
	~%biff_dir%/BD4600SR.BMP~
	~%biff_dir%/BD4601HT.BMP~
	~%biff_dir%/BD4601LM.BMP~
	~%biff_dir%/BD4601SR.BMP~
	~%biff_dir%/BD4700HT.BMP~
	~%biff_dir%/BD4700LM.BMP~
	~%biff_dir%/BD4700SR.BMP~
	~%biff_dir%/BD5000HT.BMP~
	~%biff_dir%/BD5000LM.BMP~
	~%biff_dir%/BD5000LN.BMP~
	~%biff_dir%/BD5000SR.BMP~
	~%biff_dir%/BD5100HT.BMP~
	~%biff_dir%/BD5100LM.BMP~
	~%biff_dir%/BD5100SR.BMP~
	~%biff_dir%/BD5110HT.BMP~
	~%biff_dir%/BD5110LM.BMP~
	~%biff_dir%/BD5110SR.BMP~
	~%biff_dir%/BD5200HT.BMP~
	~%biff_dir%/BD5200LM.BMP~
	~%biff_dir%/BD5200SR.BMP~
	~%biff_dir%/BD5300HT.BMP~
	~%biff_dir%/BD5300LM.BMP~
	~%biff_dir%/BD5300SR.BMP~
	~%biff_dir%/BD6000HT.BMP~
	~%biff_dir%/BD6000LM.BMP~
	~%biff_dir%/BD6000SR.BMP~
	~%biff_dir%/BD6100HT.BMP~
	~%biff_dir%/BD6100LM.BMP~
	~%biff_dir%/BD6100SR.BMP~
	~%biff_dir%/BD6200HT.BMP~
	~%biff_dir%/BD6200LM.BMP~
	~%biff_dir%/BD6200SR.BMP~
	~%biff_dir%/BD7000HT.BMP~
	~%biff_dir%/BD7000LM.BMP~
	~%biff_dir%/BD7000LN.BMP~
	~%biff_dir%/BD7000SR.BMP~
	~%biff_dir%/BD7100HT.BMP~
	~%biff_dir%/BD7100LM.BMP~
	~%biff_dir%/BD7100LN.BMP~
	~%biff_dir%/BD7100SR.BMP~
	~%biff_dir%/BD7110HT.BMP~
	~%biff_dir%/BD7110LM.BMP~
	~%biff_dir%/BD7110SR.BMP~
	~%biff_dir%/BD7200HT.BMP~
	~%biff_dir%/BD7200LM.BMP~
	~%biff_dir%/BD7200LN.BMP~
	~%biff_dir%/BD7200SR.BMP~
	~%biff_dir%/BD7210HT.BMP~
	~%biff_dir%/BD7210LM.BMP~
	~%biff_dir%/BD7210LN.BMP~
	~%biff_dir%/BD7210SR.BMP~
	~%biff_dir%/BD7220HT.BMP~
	~%biff_dir%/BD7220LM.BMP~
	~%biff_dir%/BD7220SR.BMP~
	~%biff_dir%/BD7230HT.BMP~
	~%biff_dir%/BD7230LM.BMP~
	~%biff_dir%/BD7230SR.BMP~
	~%biff_dir%/BD7300HT.BMP~
	~%biff_dir%/BD7300LM.BMP~
	~%biff_dir%/BD7300LN.BMP~
	~%biff_dir%/BD7300SR.BMP~
	~%biff_dir%/BD7310HT.BMP~
	~%biff_dir%/BD7310LM.BMP~
	~%biff_dir%/BD7310SR.BMP~
	~%biff_dir%/BD7400HT.BMP~
	~%biff_dir%/BD7400LM.BMP~
	~%biff_dir%/BD7400LN.BMP~
	~%biff_dir%/BD7400SR.BMP~
	~%biff_dir%/BD7410HT.BMP~
	~%biff_dir%/BD7410LM.BMP~
	~%biff_dir%/BD7410SR.BMP~
//other
	~%biff_dir%/1CSTAFM.BMP~
	~%biff_dir%/AJANTISL.BMP~
	~%biff_dir%/AJANTISM.BMP~
	~%biff_dir%/AJANTISS.BMP~
	~%biff_dir%/ALORAL.BMP~
	~%biff_dir%/ALORAM.BMP~
	~%biff_dir%/ALORAS.BMP~
	~%biff_dir%/BAELOTHS.BMP~
	~%biff_dir%/BALDUR.BMP~
	~%biff_dir%/BDORCF1L.BMP~
	~%biff_dir%/BDORCF1M.BMP~
	~%biff_dir%/BDORCM1L.BMP~
	~%biff_dir%/BDORCM1M.BMP~
	~%biff_dir%/BDSHAF1L.BMP~
	~%biff_dir%/BDSHAF1M.BMP~
	~%biff_dir%/BDSHAM1L.BMP~
	~%biff_dir%/BDSHAM1M.BMP~
	~%biff_dir%/BRANWEL.BMP~
	~%biff_dir%/BRANWEM.BMP~
	~%biff_dir%/BRANWES.BMP~
	~%biff_dir%/C6LANTHO.BMP~
	~%biff_dir%/CFAMCAT.BMP~
	~%biff_dir%/CFAMFER.BMP~
	~%biff_dir%/CFAMIMP.BMP~
	~%biff_dir%/CFAMPSD.BMP~
	~%biff_dir%/CFAMRAB.BMP~
	~%biff_dir%/CFLAM01.BMP~
	~%biff_dir%/CGBER01.BMP~
	~%biff_dir%/CMISC7P.BMP~
	~%biff_dir%/COADBAR_.BMP~
	~%biff_dir%/COADCNTR.BMP~
	~%biff_dir%/COHBCOM5.BMP~
	~%biff_dir%/CORANL.BMP~
	~%biff_dir%/CORANM.BMP~
	~%biff_dir%/CORANS.BMP~
	~%biff_dir%/CPEN.BMP~
	~%biff_dir%/CREDI_01.BMP~
	~%biff_dir%/CREDI_02.BMP~
	~%biff_dir%/CREDI_03.BMP~
	~%biff_dir%/CREDI_04.BMP~
	~%biff_dir%/CREDI_05.BMP~
	~%biff_dir%/CREDI_06.BMP~
	~%biff_dir%/CREDI_07.BMP~
	~%biff_dir%/CREDI_08.BMP~
	~%biff_dir%/CREDI_09.BMP~
	~%biff_dir%/CREDI_10.BMP~
	~%biff_dir%/CREDI_11.BMP~
	~%biff_dir%/CREDI_12.BMP~
	~%biff_dir%/DLCDN.BMP~
	~%biff_dir%/DLCNE.BMP~
	~%biff_dir%/DLCP1.BMP~
	~%biff_dir%/DLCV1.BMP~
	~%biff_dir%/DORNL.BMP~
	~%biff_dir%/DORNM.BMP~
	~%biff_dir%/DORNS.BMP~
	~%biff_dir%/DYNAHEIL.BMP~
	~%biff_dir%/DYNAHEIM.BMP~
	~%biff_dir%/DYNAHEIS.BMP~
	~%biff_dir%/EDWINL.BMP~
	~%biff_dir%/EDWINM.BMP~
	~%biff_dir%/EDWINS.BMP~
	~%biff_dir%/ELDOTHL.BMP~
	~%biff_dir%/ELDOTHM.BMP~
	~%biff_dir%/ELDOTHS.BMP~
	~%biff_dir%/FALDORNL.BMP~
	~%biff_dir%/FALDORNM.BMP~
	~%biff_dir%/FALDORNS.BMP~
	~%biff_dir%/FEINEN.BMP~
	~%biff_dir%/FLOATTXT.BMP~
	~%biff_dir%/GARRICKL.BMP~
	~%biff_dir%/GARRICKM.BMP~
	~%biff_dir%/GARRICKS.BMP~
	~%biff_dir%/GENDWRFL.BMP~
	~%biff_dir%/GENDWRFM.BMP~
	~%biff_dir%/GENDWRFS.BMP~
	~%biff_dir%/GENMELFL.BMP~
	~%biff_dir%/GENMELFM.BMP~
	~%biff_dir%/GENMELFS.BMP~
	~%biff_dir%/GENMHLFL.BMP~
	~%biff_dir%/GENMHLFM.BMP~
	~%biff_dir%/GENMHLFS.BMP~
	~%biff_dir%/HELML.BMP~
	~%biff_dir%/HELMM.BMP~
	~%biff_dir%/HELMS.BMP~
	~%biff_dir%/HVLNL.BMP~
	~%biff_dir%/HVLNM.BMP~
	~%biff_dir%/HVLNS.BMP~
	~%biff_dir%/IMOENL.BMP~
	~%biff_dir%/IMOENM.BMP~
	~%biff_dir%/IMOENS.BMP~
	~%biff_dir%/JAHEIRAL.BMP~
	~%biff_dir%/JAHEIRAM.BMP~
	~%biff_dir%/JAHEIRAS.BMP~
	~%biff_dir%/KAGAINL.BMP~
	~%biff_dir%/KAGAINM.BMP~
	~%biff_dir%/KAGAINS.BMP~
	~%biff_dir%/KHALIDL.BMP~
	~%biff_dir%/KHALIDM.BMP~
	~%biff_dir%/KHALIDS.BMP~
	~%biff_dir%/KIVANL.BMP~
	~%biff_dir%/KIVANM.BMP~
	~%biff_dir%/KIVANS.BMP~
	~%biff_dir%/MABR_BL.BMP~
	~%biff_dir%/MAN1L.BMP~
	~%biff_dir%/MAN1M.BMP~
	~%biff_dir%/MAN1S.BMP~
	~%biff_dir%/MAN2L.BMP~
	~%biff_dir%/MAN2M.BMP~
	~%biff_dir%/MAN2S.BMP~
	~%biff_dir%/MANLEY0L.BMP~
	~%biff_dir%/MANLEY0M.BMP~
	~%biff_dir%/MANLEY0S.BMP~
	~%biff_dir%/MANLEY1L.BMP~
	~%biff_dir%/MANLEY1M.BMP~
	~%biff_dir%/MANLEY1S.BMP~
	~%biff_dir%/MANLEY2L.BMP~
	~%biff_dir%/MANLEY2M.BMP~
	~%biff_dir%/MANLEY2S.BMP~
	~%biff_dir%/MANLEY3L.BMP~
	~%biff_dir%/MANLEY3M.BMP~
	~%biff_dir%/MANLEY3S.BMP~
	~%biff_dir%/MANLEY4L.BMP~
	~%biff_dir%/MANLEY4M.BMP~
	~%biff_dir%/MANLEY4S.BMP~
	~%biff_dir%/MANLEY5L.BMP~
	~%biff_dir%/MANLEY5M.BMP~
	~%biff_dir%/MANLEY5S.BMP~
	~%biff_dir%/MANLEY6L.BMP~
	~%biff_dir%/MANLEY6M.BMP~
	~%biff_dir%/MANLEY6S.BMP~
	~%biff_dir%/MANLEY7L.BMP~
	~%biff_dir%/MANLEY7M.BMP~
	~%biff_dir%/MANLEY7S.BMP~
	~%biff_dir%/MANLEY8L.BMP~
	~%biff_dir%/MANLEY8M.BMP~
	~%biff_dir%/MANLEY8S.BMP~
	~%biff_dir%/MANLEY9L.BMP~
	~%biff_dir%/MANLEY9M.BMP~
	~%biff_dir%/MANLEY9S.BMP~
	~%biff_dir%/MANLEYXL.BMP~
	~%biff_dir%/MANLEYXM.BMP~
	~%biff_dir%/MANLEYXS.BMP~
	~%biff_dir%/MBAS_GR.BMP~
	~%biff_dir%/MBE2_HE.BMP~
	~%biff_dir%/MBER_BL.BMP~
	~%biff_dir%/MBER_CA.BMP~
	~%biff_dir%/MBER_PO.BMP~
	~%biff_dir%/MBOA_BR.BMP~
	~%biff_dir%/MBU2_SH.BMP~
	~%biff_dir%/MDH2_GR.BMP~
	~%biff_dir%/MDJL_E1.BMP~
	~%biff_dir%/MDJL_E2.BMP~
	~%biff_dir%/MDOG_GR.BMP~
	~%biff_dir%/MDOG_MO.BMP~
	~%biff_dir%/MDOG_WA.BMP~
	~%biff_dir%/MDOG_WI.BMP~
	~%biff_dir%/MDOP_GR.BMP~
	~%biff_dir%/MDR1_AQ1.BMP~
	~%biff_dir%/MDR1_AQ2.BMP~
	~%biff_dir%/MDR1_AQ3.BMP~
	~%biff_dir%/MDR1_AQ4.BMP~
	~%biff_dir%/MDR1_AQ5.BMP~
	~%biff_dir%/MDR1_BL1.BMP~
	~%biff_dir%/MDR1_BL2.BMP~
	~%biff_dir%/MDR1_BL3.BMP~
	~%biff_dir%/MDR1_BL4.BMP~
	~%biff_dir%/MDR1_BL5.BMP~
	~%biff_dir%/MDR1_BR1.BMP~
	~%biff_dir%/MDR1_BR2.BMP~
	~%biff_dir%/MDR1_BR3.BMP~
	~%biff_dir%/MDR1_BR4.BMP~
	~%biff_dir%/MDR1_BR5.BMP~
	~%biff_dir%/MDR1_GR1.BMP~
	~%biff_dir%/MDR1_GR2.BMP~
	~%biff_dir%/MDR1_GR3.BMP~
	~%biff_dir%/MDR1_GR4.BMP~
	~%biff_dir%/MDR1_GR5.BMP~
	~%biff_dir%/MDR1_MC1.BMP~
	~%biff_dir%/MDR1_MC2.BMP~
	~%biff_dir%/MDR1_MC3.BMP~
	~%biff_dir%/MDR1_MC4.BMP~
	~%biff_dir%/MDR1_MC5.BMP~
	~%biff_dir%/MDR1_PU1.BMP~
	~%biff_dir%/MDR1_PU2.BMP~
	~%biff_dir%/MDR1_PU3.BMP~
	~%biff_dir%/MDR1_PU4.BMP~
	~%biff_dir%/MDR1_PU5.BMP~
	~%biff_dir%/MDRD_RE.BMP~
	~%biff_dir%/MDRJ_GR.BMP~
	~%biff_dir%/MEAE_SH.BMP~
	~%biff_dir%/MEAEPAL.BMP~
	~%biff_dir%/METN_GH.BMP~
	~%biff_dir%/MFIEG1B.BMP~
	~%biff_dir%/MFIEG2B.BMP~
	~%biff_dir%/MFIEG3B.BMP~
	~%biff_dir%/MFIEG31.BMP~
	~%biff_dir%/MFIGG1B.BMP~
	~%biff_dir%/MFISG1B.BMP~
	~%biff_dir%/MFISG2B.BMP~
	~%biff_dir%/MGHL_GA.BMP~
	~%biff_dir%/MGHL_MA.BMP~
	~%biff_dir%/MGHL_RE.BMP~
	~%biff_dir%/MGIB_BR.BMP~
	~%biff_dir%/MGW2_DK.BMP~
	~%biff_dir%/MGWO_DK.BMP~
	~%biff_dir%/MHAG_GR.BMP~
	~%biff_dir%/MHAG_SE.BMP~
	~%biff_dir%/MINSCL.BMP~
	~%biff_dir%/MINSCM.BMP~
	~%biff_dir%/MINSCS.BMP~
	~%biff_dir%/MMST_HA.BMP~
	~%biff_dir%/MMST_NI.BMP~
	~%biff_dir%/MONTARL.BMP~
	~%biff_dir%/MONTARM.BMP~
	~%biff_dir%/MONTARS.BMP~
	~%biff_dir%/MOTY_Y1.BMP~
	~%biff_dir%/MOTY_Y2.BMP~
	~%biff_dir%/MPAL256.BMP~
	~%biff_dir%/MPALETTE.BMP~
	~%biff_dir%/MSLI_BL.BMP~
	~%biff_dir%/MSLI_GR.BMP~
	~%biff_dir%/MSLI_MU.BMP~
	~%biff_dir%/MSLI_OC.BMP~
	~%biff_dir%/MSLI_OL.BMP~
	~%biff_dir%/MSNK_W1.BMP~
	~%biff_dir%/MSNK_W2.BMP~
	~%biff_dir%/MSPI_GI.BMP~
	~%biff_dir%/MSPI_HU.BMP~
	~%biff_dir%/MSPI_MY.BMP~
	~%biff_dir%/MSPI_PH.BMP~
	~%biff_dir%/MSPI_SW.BMP~
	~%biff_dir%/MSPI_WA.BMP~
	~%biff_dir%/MSPI_WR.BMP~
	~%biff_dir%/MTAN_BL.BMP~
	~%biff_dir%/MTAN_GR.BMP~
	~%biff_dir%/MTAN_RD.BMP~
	~%biff_dir%/MTRO_DK.BMP~
	~%biff_dir%/MWD2_GR.BMP~
	~%biff_dir%/MWD2_SI.BMP~
	~%biff_dir%/MWDR_GR.BMP~
	~%biff_dir%/MWLF_DI.BMP~
	~%biff_dir%/MWLF_DR.BMP~
	~%biff_dir%/MWLF_VA.BMP~
	~%biff_dir%/MWLF_WI.BMP~
	~%biff_dir%/MWLF_WO.BMP~
	~%biff_dir%/MWYV_AL.BMP~
	~%biff_dir%/MWYV_WH.BMP~
	~%biff_dir%/MWYV_WS.BMP~
	~%biff_dir%/NAERIEL.BMP~
	~%biff_dir%/NAERIEM.BMP~
	~%biff_dir%/NAERIES.BMP~
	~%biff_dir%/NANOMENL.BMP~
	~%biff_dir%/NANOMENM.BMP~
	~%biff_dir%/NANOMENS.BMP~
	~%biff_dir%/NBODHIS.BMP~
	~%biff_dir%/NCERNDL.BMP~
	~%biff_dir%/NCERNDM.BMP~
	~%biff_dir%/NCERNDS.BMP~
	~%biff_dir%/NEDWINL.BMP~
	~%biff_dir%/NEDWINM.BMP~
	~%biff_dir%/NEDWINS.BMP~
	~%biff_dir%/NEERAL.BMP~
	~%biff_dir%/NEERAM.BMP~
	~%biff_dir%/NEERAS.BMP~
	~%biff_dir%/NELLES.BMP~
	~%biff_dir%/NHAERL.BMP~
	~%biff_dir%/NHAERM.BMP~
	~%biff_dir%/NHAERS.BMP~
	~%biff_dir%/NHORCL.BMP~
	~%biff_dir%/NHORCM.BMP~
	~%biff_dir%/NHORCS.BMP~
	~%biff_dir%/NIMOENL.BMP~
	~%biff_dir%/NIMOENM.BMP~
	~%biff_dir%/NIMOENS.BMP~
	~%biff_dir%/NIRO_RD.BMP~
	~%biff_dir%/NJAHEIRL.BMP~
	~%biff_dir%/NJAHEIRM.BMP~
	~%biff_dir%/NJAHEIRS.BMP~
	~%biff_dir%/NJANL.BMP~
	~%biff_dir%/NJANM.BMP~
	~%biff_dir%/NJANS.BMP~
	~%biff_dir%/NJONL.BMP~
	~%biff_dir%/NJONM.BMP~
	~%biff_dir%/NJONS.BMP~
	~%biff_dir%/NKELDORL.BMP~
	~%biff_dir%/NKELDORM.BMP~
	~%biff_dir%/NKELDORS.BMP~
	~%biff_dir%/NKORGANL.BMP~
	~%biff_dir%/NKORGANM.BMP~
	~%biff_dir%/NKORGANS.BMP~
	~%biff_dir%/NMAZZYL.BMP~
	~%biff_dir%/NMAZZYM.BMP~
	~%biff_dir%/NMAZZYS.BMP~
	~%biff_dir%/NMINSCL.BMP~
	~%biff_dir%/NMINSCM.BMP~
	~%biff_dir%/NMINSCS.BMP~
	~%biff_dir%/NNALIAL.BMP~
	~%biff_dir%/NNALIAM.BMP~
	~%biff_dir%/NNALIAS.BMP~
	~%biff_dir%/NOCTRL.BMP~
	~%biff_dir%/NOPORTLL.BMP~
	~%biff_dir%/NOPORTLM.BMP~
	~%biff_dir%/NOPORTLS.BMP~
	~%biff_dir%/NOPORTMD.BMP~
	~%biff_dir%/NOPORTSM.BMP~
	~%biff_dir%/NORMAL.BMP~
	~%biff_dir%/NSAI_D1.BMP~
	~%biff_dir%/NSAI_D2.BMP~
	~%biff_dir%/NSAI_G1.BMP~
	~%biff_dir%/NSAI_G2.BMP~
	~%biff_dir%/NSAI_R1.BMP~
	~%biff_dir%/NSAI_R2.BMP~
	~%biff_dir%/NSOL_C1.BMP~
	~%biff_dir%/NSOL_C2.BMP~
	~%biff_dir%/NVALYGAL.BMP~
	~%biff_dir%/NVALYGAM.BMP~
	~%biff_dir%/NVALYGAS.BMP~
	~%biff_dir%/NVICONL.BMP~
	~%biff_dir%/NVICONM.BMP~
	~%biff_dir%/NVICONS.BMP~
	~%biff_dir%/NYOSHIML.BMP~
	~%biff_dir%/NYOSHIMM.BMP~
	~%biff_dir%/NYOSHIMS.BMP~
	~%biff_dir%/PBAG05.BMP~
	~%biff_dir%/PBAG06.BMP~
	~%biff_dir%/PBOOT12.BMP~
	~%biff_dir%/PLT_AQUA.BMP~
	~%biff_dir%/PLT_BLUE.BMP~
	~%biff_dir%/PLT_BRTG.BMP~
	~%biff_dir%/PLT_FIRE.BMP~
	~%biff_dir%/PLT_MAGE.BMP~
	~%biff_dir%/PLT_PURP.BMP~
	~%biff_dir%/PLT_RED.BMP~
	~%biff_dir%/PLT_SEAG.BMP~
	~%biff_dir%/PLT_SUNS.BMP~
	~%biff_dir%/POO.BMP~
	~%biff_dir%/PORTRT0.BMP~
	~%biff_dir%/PORTRT1.BMP~
	~%biff_dir%/PORTRT2.BMP~
	~%biff_dir%/PORTRT3.BMP~
	~%biff_dir%/PORTRT4.BMP~
	~%biff_dir%/PORTRT5.BMP~
	~%biff_dir%/POSTANT0.BMP~
	~%biff_dir%/PPDOLLBO.BMP~
	~%biff_dir%/PPDOLLHE.BMP~
	~%biff_dir%/PPDOLLSH.BMP~
	~%biff_dir%/PPDOLLWE.BMP~
	~%biff_dir%/QUAYLEL.BMP~
	~%biff_dir%/QUAYLEM.BMP~
	~%biff_dir%/QUAYLES.BMP~
	~%biff_dir%/RANGES12.BMP~
	~%biff_dir%/RASAADG.BMP~
	~%biff_dir%/RASAADL.BMP~
	~%biff_dir%/RASAADM.BMP~
	~%biff_dir%/RASAADS.BMP~
	~%biff_dir%/RBF18_1.BMP~
	~%biff_dir%/RBF18_2.BMP~
	~%biff_dir%/RBF18_3.BMP~
	~%biff_dir%/RBF18_4.BMP~
	~%biff_dir%/RBF18_5.BMP~
	~%biff_dir%/RBF22_1.BMP~
	~%biff_dir%/RBF22_2.BMP~
	~%biff_dir%/RBFR10_1.BMP~
	~%biff_dir%/RBFR10_2.BMP~
	~%biff_dir%/RBFR10_3.BMP~
	~%biff_dir%/RBFR10_4.BMP~
	~%biff_dir%/RBFR10_5.BMP~
	~%biff_dir%/RBFR13_1.BMP~
	~%biff_dir%/RBFR13_2.BMP~
	~%biff_dir%/RBFR13_3.BMP~
	~%biff_dir%/RBFR13_4.BMP~
	~%biff_dir%/RBFR13_5.BMP~
	~%biff_dir%/RBZOMB1.BMP~
	~%biff_dir%/RBZOMB2.BMP~
	~%biff_dir%/REALMS.BMP~
	~%biff_dir%/RNDBASE1.BMP~
	~%biff_dir%/RNDBASE2.BMP~
	~%biff_dir%/RNDBASE3.BMP~
	~%biff_dir%/RNDBASE4.BMP~
	~%biff_dir%/RNDBASE5.BMP~
	~%biff_dir%/RNDSLNG1.BMP~
	~%biff_dir%/SAFANAL.BMP~
	~%biff_dir%/SAFANAM.BMP~
	~%biff_dir%/SAFANAS.BMP~
	~%biff_dir%/SCREEN01.BMP~
	~%biff_dir%/SCREEN02.BMP~
	~%biff_dir%/SCREEN03.BMP~
	~%biff_dir%/SCREEN04.BMP~
	~%biff_dir%/SHAIR1.BMP~
	~%biff_dir%/SHAIR2.BMP~
	~%biff_dir%/SHAIR3.BMP~
	~%biff_dir%/SHAIR4.BMP~
	~%biff_dir%/SHAIR5.BMP~
	~%biff_dir%/SHAIR6.BMP~
	~%biff_dir%/SHAIR7.BMP~
	~%biff_dir%/SHAREA1.BMP~
	~%biff_dir%/SHAREA2.BMP~
	~%biff_dir%/SHAREA3.BMP~
	~%biff_dir%/SHAREA4.BMP~
	~%biff_dir%/SHAREA5.BMP~
	~%biff_dir%/SHAREA6.BMP~
	~%biff_dir%/SHAREA7.BMP~
	~%biff_dir%/SHARTELL.BMP~
	~%biff_dir%/SHARTELM.BMP~
	~%biff_dir%/SHARTELS.BMP~
	~%biff_dir%/SHEARTH1.BMP~
	~%biff_dir%/SHEARTH2.BMP~
	~%biff_dir%/SHEARTH3.BMP~
	~%biff_dir%/SHEARTH4.BMP~
	~%biff_dir%/SHEARTH5.BMP~
	~%biff_dir%/SHEARTH6.BMP~
	~%biff_dir%/SHEARTH7.BMP~
	~%biff_dir%/SHWATER1.BMP~
	~%biff_dir%/SHWATER2.BMP~
	~%biff_dir%/SHWATER3.BMP~
	~%biff_dir%/SHWATER4.BMP~
	~%biff_dir%/SHWATER5.BMP~
	~%biff_dir%/SHWATER6.BMP~
	~%biff_dir%/SHWATER7.BMP~
	~%biff_dir%/SKANL.BMP~
	~%biff_dir%/SKANM.BMP~
	~%biff_dir%/SKANS.BMP~
	~%biff_dir%/SKIEL.BMP~
	~%biff_dir%/SKIEM.BMP~
	~%biff_dir%/SKIES.BMP~
	~%biff_dir%/SPFIREPB.BMP~
	~%biff_dir%/SPFLAMEB.BMP~
	~%biff_dir%/SPGDRABU.BMP~
	~%biff_dir%/SPGDRAIM.BMP~
	~%biff_dir%/SPGDRASI.BMP~
	~%biff_dir%/STATES2.BMP~
	~%biff_dir%/STONEBIG.BMP~
	~%biff_dir%/STONESML.BMP~
	~%biff_dir%/STTRAVL1.BMP~
	~%biff_dir%/STTRAVL2.BMP~
	~%biff_dir%/STTRAVL3.BMP~
	~%biff_dir%/STTRAVL4.BMP~
	~%biff_dir%/STTRAVL5.BMP~
	~%biff_dir%/STTRAVL6.BMP~
	~%biff_dir%/STTRAVL7.BMP~
	~%biff_dir%/STTRAVL8.BMP~
	~%biff_dir%/SUBTITLE.BMP~
	~%biff_dir%/TEST.BMP~
	~%biff_dir%/TESTPOR.BMP~
	~%biff_dir%/TIAXL.BMP~
	~%biff_dir%/TIAXM.BMP~
	~%biff_dir%/TIAXS.BMP~
	~%biff_dir%/TOBTEMP.BMP~
	~%biff_dir%/TOOLFONT.BMP~
	~%biff_dir%/TOOLTIP.BMP~
	~%biff_dir%/VICONIAL.BMP~
	~%biff_dir%/VICONIAM.BMP~
	~%biff_dir%/VICONIAS.BMP~
	~%biff_dir%/WOMAN1L.BMP~
	~%biff_dir%/WOMAN1M.BMP~
	~%biff_dir%/WOMAN1S.BMP~
	~%biff_dir%/WOMAN2L.BMP~
	~%biff_dir%/WOMAN2M.BMP~
	~%biff_dir%/WOMAN2S.BMP~
	~%biff_dir%/XANL.BMP~
	~%biff_dir%/XANM.BMP~
	~%biff_dir%/XANS.BMP~
	~%biff_dir%/XZARL.BMP~
	~%biff_dir%/XZARM.BMP~
	~%biff_dir%/XZARS.BMP~
	~%biff_dir%/YESLICKL.BMP~
	~%biff_dir%/YESLICKM.BMP~
	~%biff_dir%/YESLICKS.BMP~
