MOVE + ~EET/temp/mos/AR0002.MOS~ ~%areas_dir%/bgAR00xx/FH0002.MOS~
	~EET/temp/mos/AR0100.MOS~ ~%areas_dir%/bgAR01xx/FH0100.MOS~
	~EET/temp/mos/AR0100N.MOS~ ~%areas_dir%/bgAR01xx/FH0100N.MOS~
	~EET/temp/mos/AR0101.MOS~ ~%areas_dir%/bgAR01xx/FH0101.MOS~
	~EET/temp/mos/AR0102.MOS~ ~%areas_dir%/bgAR01xx/FH0102.MOS~
	~EET/temp/mos/AR0103.MOS~ ~%areas_dir%/bgAR01xx/FH0103.MOS~
	~EET/temp/mos/AR0104.MOS~ ~%areas_dir%/bgAR01xx/FH0104.MOS~
	~EET/temp/mos/AR0105.MOS~ ~%areas_dir%/bgAR01xx/FH0105.MOS~
	~EET/temp/mos/AR0106.MOS~ ~%areas_dir%/bgAR01xx/FH0106.MOS~
	~EET/temp/mos/AR0107.MOS~ ~%areas_dir%/bgAR01xx/FH0107.MOS~
	~EET/temp/mos/AR0108.MOS~ ~%areas_dir%/bgAR01xx/FH0108.MOS~
	~EET/temp/mos/AR0109.MOS~ ~%areas_dir%/bgAR01xx/FH0109.MOS~
	~EET/temp/mos/AR0110.MOS~ ~%areas_dir%/bgAR01xx/FH0110.MOS~
	~EET/temp/mos/AR0111.MOS~ ~%areas_dir%/bgAR01xx/FH0111.MOS~
	~EET/temp/mos/AR0112.MOS~ ~%areas_dir%/bgAR01xx/FH0112.MOS~
	~EET/temp/mos/AR0114.MOS~ ~%areas_dir%/bgAR01xx/FH0114.MOS~
	~EET/temp/mos/AR0115.MOS~ ~%areas_dir%/bgAR01xx/FH0115.MOS~
	~EET/temp/mos/AR0116.MOS~ ~%areas_dir%/bgAR01xx/FH0116.MOS~
	~EET/temp/mos/AR0117.MOS~ ~%areas_dir%/bgAR01xx/FH0117.MOS~
	~EET/temp/mos/AR0118.MOS~ ~%areas_dir%/bgAR01xx/FH0118.MOS~
	~EET/temp/mos/AR0119.MOS~ ~%areas_dir%/bgAR01xx/FH0119.MOS~
	~EET/temp/mos/AR0120.MOS~ ~%areas_dir%/bgAR01xx/FH0120.MOS~
	~EET/temp/mos/AR0121.MOS~ ~%areas_dir%/bgAR01xx/FH0121.MOS~
	~EET/temp/mos/AR0123.MOS~ ~%areas_dir%/bgAR01xx/FH0123.MOS~
	~EET/temp/mos/AR0125.MOS~ ~%areas_dir%/bgAR01xx/FH0125.MOS~
	~EET/temp/mos/AR0126.MOS~ ~%areas_dir%/bgAR01xx/FH0126.MOS~
	~EET/temp/mos/AR0127.MOS~ ~%areas_dir%/bgAR01xx/FH0127.MOS~
	~EET/temp/mos/AR0128.MOS~ ~%areas_dir%/bgAR01xx/FH0128.MOS~
	~EET/temp/mos/AR0129.MOS~ ~%areas_dir%/bgAR01xx/FH0129.MOS~
	~EET/temp/mos/AR0130.MOS~ ~%areas_dir%/bgAR01xx/FH0130.MOS~
	~EET/temp/mos/AR0131.MOS~ ~%areas_dir%/bgAR01xx/FH0131.MOS~
	~EET/temp/mos/AR0132.MOS~ ~%areas_dir%/bgAR01xx/FH0132.MOS~
	~EET/temp/mos/AR0133.MOS~ ~%areas_dir%/bgAR01xx/FH0133.MOS~
	~EET/temp/mos/AR0134.MOS~ ~%areas_dir%/bgAR01xx/FH0134.MOS~
	~EET/temp/mos/AR0135.MOS~ ~%areas_dir%/bgAR01xx/FH0135.MOS~
	~EET/temp/mos/AR0136.MOS~ ~%areas_dir%/bgAR01xx/FH0136.MOS~
	~EET/temp/mos/AR0137.MOS~ ~%areas_dir%/bgAR01xx/FH0137.MOS~
	~EET/temp/mos/AR0138.MOS~ ~%areas_dir%/bgAR01xx/FH0138.MOS~
	~EET/temp/mos/AR0139.MOS~ ~%areas_dir%/bgAR01xx/FH0139.MOS~
	~EET/temp/mos/AR0140.MOS~ ~%areas_dir%/bgAR01xx/FH0140.MOS~
	~EET/temp/mos/AR0141.MOS~ ~%areas_dir%/bgAR01xx/FH0141.MOS~
	~EET/temp/mos/AR0142.MOS~ ~%areas_dir%/bgAR01xx/FH0142.MOS~
	~EET/temp/mos/AR0143.MOS~ ~%areas_dir%/bgAR01xx/FH0143.MOS~
	~EET/temp/mos/AR0144.MOS~ ~%areas_dir%/bgAR01xx/FH0144.MOS~
	~EET/temp/mos/AR0145.MOS~ ~%areas_dir%/bgAR01xx/FH0145.MOS~
	~EET/temp/mos/AR0146.MOS~ ~%areas_dir%/bgAR01xx/FH0146.MOS~
	~EET/temp/mos/AR0148.MOS~ ~%areas_dir%/bgAR01xx/FH0148.MOS~
	~EET/temp/mos/AR0149.MOS~ ~%areas_dir%/bgAR01xx/FH0149.MOS~
	~EET/temp/mos/AR0150.MOS~ ~%areas_dir%/bgAR01xx/FH0150.MOS~
	~EET/temp/mos/AR0151.MOS~ ~%areas_dir%/bgAR01xx/FH0151.MOS~
	~EET/temp/mos/AR0152.MOS~ ~%areas_dir%/bgAR01xx/FH0152.MOS~
	~EET/temp/mos/AR0153.MOS~ ~%areas_dir%/bgAR01xx/FH0153.MOS~
	~EET/temp/mos/AR0155.MOS~ ~%areas_dir%/bgAR01xx/FH0155.MOS~
	~EET/temp/mos/AR0156.MOS~ ~%areas_dir%/bgAR01xx/FH0156.MOS~
	~EET/temp/mos/AR0161.MOS~ ~%areas_dir%/bgAR01xx/FH0161.MOS~
	~EET/temp/mos/AR0162.MOS~ ~%areas_dir%/bgAR01xx/FH0162.MOS~
	~EET/temp/mos/AR0163.MOS~ ~%areas_dir%/bgAR01xx/FH0163.MOS~
	~EET/temp/mos/AR0164.MOS~ ~%areas_dir%/bgAR01xx/FH0164.MOS~
	~EET/temp/mos/AR0165.MOS~ ~%areas_dir%/bgAR01xx/FH0165.MOS~
	~EET/temp/mos/AR0166.MOS~ ~%areas_dir%/bgAR01xx/FH0166.MOS~
	~EET/temp/mos/AR0167.MOS~ ~%areas_dir%/bgAR01xx/FH0167.MOS~
	~EET/temp/mos/AR0168.MOS~ ~%areas_dir%/bgAR01xx/FH0168.MOS~
	~EET/temp/mos/AR0169.MOS~ ~%areas_dir%/bgAR01xx/FH0169.MOS~
	~EET/temp/mos/AR0170.MOS~ ~%areas_dir%/bgAR01xx/FH0170.MOS~
	~EET/temp/mos/AR0200.MOS~ ~%areas_dir%/bgAR02xx/FH0200.MOS~
	~EET/temp/mos/AR0200N.MOS~ ~%areas_dir%/bgAR02xx/FH0200N.MOS~
	~EET/temp/mos/AR0224.MOS~ ~%areas_dir%/bgAR02xx/FH0224.MOS~
	~EET/temp/mos/AR0225.MOS~ ~%areas_dir%/bgAR02xx/FH0225.MOS~
	~EET/temp/mos/AR0226.MOS~ ~%areas_dir%/bgAR02xx/FH0226.MOS~
	~EET/temp/mos/AR0300.MOS~ ~%areas_dir%/bgAR03xx/FH0300.MOS~
	~EET/temp/mos/AR0300N.MOS~ ~%areas_dir%/bgAR03xx/FH0300N.MOS~
	~EET/temp/mos/AR0304.MOS~ ~%areas_dir%/bgAR03xx/FH0304.MOS~
	~EET/temp/mos/AR0400.MOS~ ~%areas_dir%/bgAR04xx/FH0400.MOS~
	~EET/temp/mos/AR0401.MOS~ ~%areas_dir%/bgAR04xx/FH0401.MOS~
	~EET/temp/mos/AR0500.MOS~ ~%areas_dir%/bgAR05xx/FH0500.MOS~
	~EET/temp/mos/AR0501.MOS~ ~%areas_dir%/bgAR05xx/FH0501.MOS~
	~EET/temp/mos/AR0502.MOS~ ~%areas_dir%/bgAR05xx/FH0502.MOS~
	~EET/temp/mos/AR0503.MOS~ ~%areas_dir%/bgAR05xx/FH0503.MOS~
	~EET/temp/mos/AR0504.MOS~ ~%areas_dir%/bgAR05xx/FH0504.MOS~
	~EET/temp/mos/AR0505.MOS~ ~%areas_dir%/bgAR05xx/FH0505.MOS~
	~EET/temp/mos/AR0506.MOS~ ~%areas_dir%/bgAR05xx/FH0506.MOS~
	~EET/temp/mos/AR0507.MOS~ ~%areas_dir%/bgAR05xx/FH0507.MOS~
	~EET/temp/mos/AR0508.MOS~ ~%areas_dir%/bgAR05xx/FH0508.MOS~
	~EET/temp/mos/AR0509.MOS~ ~%areas_dir%/bgAR05xx/FH0509.MOS~
	~EET/temp/mos/AR0510.MOS~ ~%areas_dir%/bgAR05xx/FH0510.MOS~
	~EET/temp/mos/AR0511.MOS~ ~%areas_dir%/bgAR05xx/FH0511.MOS~
	~EET/temp/mos/AR0512.MOS~ ~%areas_dir%/bgAR05xx/FH0512.MOS~
	~EET/temp/mos/AR0513.MOS~ ~%areas_dir%/bgAR05xx/FH0513.MOS~
	~EET/temp/mos/AR0514.MOS~ ~%areas_dir%/bgAR05xx/FH0514.MOS~
	~EET/temp/mos/AR0515.MOS~ ~%areas_dir%/bgAR05xx/FH0515.MOS~
	~EET/temp/mos/AR0516.MOS~ ~%areas_dir%/bgAR05xx/FH0516.MOS~
	~EET/temp/mos/AR0600.MOS~ ~%areas_dir%/bgAR06xx/FH0600.MOS~
	~EET/temp/mos/AR0600N.MOS~ ~%areas_dir%/bgAR06xx/FH0600N.MOS~
	~EET/temp/mos/AR0601.MOS~ ~%areas_dir%/bgAR06xx/FH0601.MOS~
	~EET/temp/mos/AR0602.MOS~ ~%areas_dir%/bgAR06xx/FH0602.MOS~
	~EET/temp/mos/AR0603.MOS~ ~%areas_dir%/bgAR06xx/FH0603.MOS~
	~EET/temp/mos/AR0606.MOS~ ~%areas_dir%/bgAR06xx/FH0606.MOS~
	~EET/temp/mos/AR0607.MOS~ ~%areas_dir%/bgAR06xx/FH0607.MOS~
	~EET/temp/mos/AR0608.MOS~ ~%areas_dir%/bgAR06xx/FH0608.MOS~
	~EET/temp/mos/AR0609.MOS~ ~%areas_dir%/bgAR06xx/FH0609.MOS~
	~EET/temp/mos/AR0611.MOS~ ~%areas_dir%/bgAR06xx/FH0611.MOS~
	~EET/temp/mos/AR0612.MOS~ ~%areas_dir%/bgAR06xx/FH0612.MOS~
	~EET/temp/mos/AR0613.MOS~ ~%areas_dir%/bgAR06xx/FH0613.MOS~
	~EET/temp/mos/AR0614.MOS~ ~%areas_dir%/bgAR06xx/FH0614.MOS~
	~EET/temp/mos/AR0615.MOS~ ~%areas_dir%/bgAR06xx/FH0615.MOS~
	~EET/temp/mos/AR0616.MOS~ ~%areas_dir%/bgAR06xx/FH0616.MOS~
	~EET/temp/mos/AR0621.MOS~ ~%areas_dir%/bgAR06xx/FH0621.MOS~
	~EET/temp/mos/AR0621N.MOS~ ~%areas_dir%/bgAR06xx/FH0621N.MOS~
	~EET/temp/mos/AR0700.MOS~ ~%areas_dir%/bgAR07xx/FH0700.MOS~
	~EET/temp/mos/AR0700N.MOS~ ~%areas_dir%/bgAR07xx/FH0700N.MOS~
	~EET/temp/mos/AR0702.MOS~ ~%areas_dir%/bgAR07xx/FH0702.MOS~
	~EET/temp/mos/AR0703.MOS~ ~%areas_dir%/bgAR07xx/FH0703.MOS~
	~EET/temp/mos/AR0704.MOS~ ~%areas_dir%/bgAR07xx/FH0704.MOS~
	~EET/temp/mos/AR0705.MOS~ ~%areas_dir%/bgAR07xx/FH0705.MOS~
	~EET/temp/mos/AR0706.MOS~ ~%areas_dir%/bgAR07xx/FH0706.MOS~
	~EET/temp/mos/AR0719.MOS~ ~%areas_dir%/bgAR07xx/FH0719.MOS~
	~EET/temp/mos/AR0720.MOS~ ~%areas_dir%/bgAR07xx/FH0720.MOS~
	~EET/temp/mos/AR0724.MOS~ ~%areas_dir%/bgAR07xx/FH0724.MOS~
	~EET/temp/mos/AR0726.MOS~ ~%areas_dir%/bgAR07xx/FH0726.MOS~
	~EET/temp/mos/AR0800.MOS~ ~%areas_dir%/bgAR08xx/FH0800.MOS~
	~EET/temp/mos/AR0800N.MOS~ ~%areas_dir%/bgAR08xx/FH0800N.MOS~
	~EET/temp/mos/AR0807.MOS~ ~%areas_dir%/bgAR08xx/FH0807.MOS~
	~EET/temp/mos/AR0808.MOS~ ~%areas_dir%/bgAR08xx/FH0808.MOS~
	~EET/temp/mos/AR0809.MOS~ ~%areas_dir%/bgAR08xx/FH0809.MOS~
	~EET/temp/mos/AR0900.MOS~ ~%areas_dir%/bgAR09xx/FH0900.MOS~
	~EET/temp/mos/AR0900N.MOS~ ~%areas_dir%/bgAR09xx/FH0900N.MOS~
	~EET/temp/mos/AR0901.MOS~ ~%areas_dir%/bgAR09xx/FH0901.MOS~
	~EET/temp/mos/AR1000.MOS~ ~%areas_dir%/bgAR10xx/FH1000.MOS~
	~EET/temp/mos/AR1001.MOS~ ~%areas_dir%/bgAR10xx/FH1001.MOS~
	~EET/temp/mos/AR1002.MOS~ ~%areas_dir%/bgAR10xx/FH1002.MOS~
	~EET/temp/mos/AR1003.MOS~ ~%areas_dir%/bgAR10xx/FH1003.MOS~
	~EET/temp/mos/AR1004.MOS~ ~%areas_dir%/bgAR10xx/FH1004.MOS~
	~EET/temp/mos/AR1005.MOS~ ~%areas_dir%/bgAR10xx/FH1005.MOS~
	~EET/temp/mos/AR1006.MOS~ ~%areas_dir%/bgAR10xx/FH1006.MOS~
	~EET/temp/mos/AR1007.MOS~ ~%areas_dir%/bgAR10xx/FH1007.MOS~
	~EET/temp/mos/AR1008.MOS~ ~%areas_dir%/bgAR10xx/FH1008.MOS~
	~EET/temp/mos/AR1009.MOS~ ~%areas_dir%/bgAR10xx/FH1009.MOS~
	~EET/temp/mos/AR1010.MOS~ ~%areas_dir%/bgAR10xx/FH1010.MOS~
	~EET/temp/mos/AR1100.MOS~ ~%areas_dir%/bgAR11xx/FH1100.MOS~
	~EET/temp/mos/AR1100N.MOS~ ~%areas_dir%/bgAR11xx/FH1100N.MOS~
	~EET/temp/mos/AR1101.MOS~ ~%areas_dir%/bgAR11xx/FH1101.MOS~
	~EET/temp/mos/AR1102.MOS~ ~%areas_dir%/bgAR11xx/FH1102.MOS~
	~EET/temp/mos/AR1200.MOS~ ~%areas_dir%/bgAR12xx/FH1200.MOS~
	~EET/temp/mos/AR1200N.MOS~ ~%areas_dir%/bgAR12xx/FH1200N.MOS~
	~EET/temp/mos/AR1207.MOS~ ~%areas_dir%/bgAR12xx/FH1207.MOS~
	~EET/temp/mos/AR1208.MOS~ ~%areas_dir%/bgAR12xx/FH1208.MOS~
	~EET/temp/mos/AR1215.MOS~ ~%areas_dir%/bgAR12xx/FH1215.MOS~
	~EET/temp/mos/AR1300.MOS~ ~%areas_dir%/bgAR13xx/FH1300.MOS~
	~EET/temp/mos/AR1300N.MOS~ ~%areas_dir%/bgAR13xx/FH1300N.MOS~
	~EET/temp/mos/AR1302.MOS~ ~%areas_dir%/bgAR13xx/FH1302.MOS~
	~EET/temp/mos/AR1400.MOS~ ~%areas_dir%/bgAR14xx/FH1400.MOS~
	~EET/temp/mos/AR1401.MOS~ ~%areas_dir%/bgAR14xx/FH1401.MOS~
	~EET/temp/mos/AR1402.MOS~ ~%areas_dir%/bgAR14xx/FH1402.MOS~
	~EET/temp/mos/AR1403.MOS~ ~%areas_dir%/bgAR14xx/FH1403.MOS~
	~EET/temp/mos/AR1404.MOS~ ~%areas_dir%/bgAR14xx/FH1404.MOS~
	~EET/temp/mos/AR1500.MOS~ ~%areas_dir%/bgAR15xx/FH1500.MOS~
	~EET/temp/mos/AR1501.MOS~ ~%areas_dir%/bgAR15xx/FH1501.MOS~
	~EET/temp/mos/AR1502.MOS~ ~%areas_dir%/bgAR15xx/FH1502.MOS~
	~EET/temp/mos/AR1503.MOS~ ~%areas_dir%/bgAR15xx/FH1503.MOS~
	~EET/temp/mos/AR1504.MOS~ ~%areas_dir%/bgAR15xx/FH1504.MOS~
	~EET/temp/mos/AR1505.MOS~ ~%areas_dir%/bgAR15xx/FH1505.MOS~
	~EET/temp/mos/AR1600.MOS~ ~%areas_dir%/bgAR16xx/FH1600.MOS~
	~EET/temp/mos/AR1601.MOS~ ~%areas_dir%/bgAR16xx/FH1601.MOS~
	~EET/temp/mos/AR1602.MOS~ ~%areas_dir%/bgAR16xx/FH1602.MOS~
	~EET/temp/mos/AR1603.MOS~ ~%areas_dir%/bgAR16xx/FH1603.MOS~
	~EET/temp/mos/AR1700.MOS~ ~%areas_dir%/bgAR17xx/FH1700.MOS~
	~EET/temp/mos/AR1800.MOS~ ~%areas_dir%/bgAR18xx/FH1800.MOS~
	~EET/temp/mos/AR1801.MOS~ ~%areas_dir%/bgAR18xx/FH1801.MOS~
	~EET/temp/mos/AR1802.MOS~ ~%areas_dir%/bgAR18xx/FH1802.MOS~
	~EET/temp/mos/AR1803.MOS~ ~%areas_dir%/bgAR18xx/FH1803.MOS~
	~EET/temp/mos/AR1804.MOS~ ~%areas_dir%/bgAR18xx/FH1804.MOS~
	~EET/temp/mos/AR1805.MOS~ ~%areas_dir%/bgAR18xx/FH1805.MOS~
	~EET/temp/mos/AR1806.MOS~ ~%areas_dir%/bgAR18xx/FH1806.MOS~
	~EET/temp/mos/AR1807.MOS~ ~%areas_dir%/bgAR18xx/FH1807.MOS~
	~EET/temp/mos/AR1808.MOS~ ~%areas_dir%/bgAR18xx/FH1808.MOS~
	~EET/temp/mos/AR1809.MOS~ ~%areas_dir%/bgAR18xx/FH1809.MOS~
	~EET/temp/mos/AR1900.MOS~ ~%areas_dir%/bgAR19xx/FH1900.MOS~
	~EET/temp/mos/AR1900N.MOS~ ~%areas_dir%/bgAR19xx/FH1900N.MOS~
	~EET/temp/mos/AR1901.MOS~ ~%areas_dir%/bgAR19xx/FH1901.MOS~
	~EET/temp/mos/AR1902.MOS~ ~%areas_dir%/bgAR19xx/FH1902.MOS~
	~EET/temp/mos/AR1903.MOS~ ~%areas_dir%/bgAR19xx/FH1903.MOS~
	~EET/temp/mos/AR2000.MOS~ ~%areas_dir%/bgAR20xx/FH2000.MOS~
	~EET/temp/mos/AR2001.MOS~ ~%areas_dir%/bgAR20xx/FH2001.MOS~
	~EET/temp/mos/AR2002.MOS~ ~%areas_dir%/bgAR20xx/FH2002.MOS~
	~EET/temp/mos/AR2003.MOS~ ~%areas_dir%/bgAR20xx/FH2003.MOS~
	~EET/temp/mos/AR2004.MOS~ ~%areas_dir%/bgAR20xx/FH2004.MOS~
	~EET/temp/mos/AR2005.MOS~ ~%areas_dir%/bgAR20xx/FH2005.MOS~
	~EET/temp/mos/AR2006.MOS~ ~%areas_dir%/bgAR20xx/FH2006.MOS~
	~EET/temp/mos/AR2007.MOS~ ~%areas_dir%/bgAR20xx/FH2007.MOS~
	~EET/temp/mos/AR2008.MOS~ ~%areas_dir%/bgAR20xx/FH2008.MOS~
	~EET/temp/mos/AR2009.MOS~ ~%areas_dir%/bgAR20xx/FH2009.MOS~
	~EET/temp/mos/AR2010.MOS~ ~%areas_dir%/bgAR20xx/FH2010.MOS~
	~EET/temp/mos/AR2011.MOS~ ~%areas_dir%/bgAR20xx/FH2011.MOS~
	~EET/temp/mos/AR2012.MOS~ ~%areas_dir%/bgAR20xx/FH2012.MOS~
	~EET/temp/mos/AR2100.MOS~ ~%areas_dir%/bgAR21xx/FH2100.MOS~
	~EET/temp/mos/AR2101.MOS~ ~%areas_dir%/bgAR21xx/FH2101.MOS~
	~EET/temp/mos/AR2200.MOS~ ~%areas_dir%/bgAR22xx/FH2200.MOS~
	~EET/temp/mos/AR2215.MOS~ ~%areas_dir%/bgAR22xx/FH2215.MOS~
	~EET/temp/mos/AR2300.MOS~ ~%areas_dir%/bgAR23xx/FH2300.MOS~
	~EET/temp/mos/AR2300N.MOS~ ~%areas_dir%/bgAR23xx/FH2300N.MOS~
	~EET/temp/mos/AR2301.MOS~ ~%areas_dir%/bgAR23xx/FH2301.MOS~
	~EET/temp/mos/AR2302.MOS~ ~%areas_dir%/bgAR23xx/FH2302.MOS~
	~EET/temp/mos/AR2303.MOS~ ~%areas_dir%/bgAR23xx/FH2303.MOS~
	~EET/temp/mos/AR2304.MOS~ ~%areas_dir%/bgAR23xx/FH2304.MOS~
	~EET/temp/mos/AR2305.MOS~ ~%areas_dir%/bgAR23xx/FH2305.MOS~
	~EET/temp/mos/AR2306.MOS~ ~%areas_dir%/bgAR23xx/FH2306.MOS~
	~EET/temp/mos/AR2400.MOS~ ~%areas_dir%/bgAR24xx/FH2400.MOS~
	~EET/temp/mos/AR2600.MOS~ ~%areas_dir%/bgAR26xx/FH2600.MOS~
	~EET/temp/mos/AR2602.MOS~ ~%areas_dir%/bgAR26xx/FH2602.MOS~
	~EET/temp/mos/AR2605.MOS~ ~%areas_dir%/bgAR26xx/FH2605.MOS~
	~EET/temp/mos/AR2606.MOS~ ~%areas_dir%/bgAR26xx/FH2606.MOS~
	~EET/temp/mos/AR2607.MOS~ ~%areas_dir%/bgAR26xx/FH2607.MOS~
	~EET/temp/mos/AR2608.MOS~ ~%areas_dir%/bgAR26xx/FH2608.MOS~
	~EET/temp/mos/AR2609.MOS~ ~%areas_dir%/bgAR26xx/FH2609.MOS~
	~EET/temp/mos/AR2610.MOS~ ~%areas_dir%/bgAR26xx/FH2610.MOS~
	~EET/temp/mos/AR2611.MOS~ ~%areas_dir%/bgAR26xx/FH2611.MOS~
	~EET/temp/mos/AR2612.MOS~ ~%areas_dir%/bgAR26xx/FH2612.MOS~
	~EET/temp/mos/AR2613.MOS~ ~%areas_dir%/bgAR26xx/FH2613.MOS~
	~EET/temp/mos/AR2614.MOS~ ~%areas_dir%/bgAR26xx/FH2614.MOS~
	~EET/temp/mos/AR2615.MOS~ ~%areas_dir%/bgAR26xx/FH2615.MOS~
	~EET/temp/mos/AR2616.MOS~ ~%areas_dir%/bgAR26xx/FH2616.MOS~
	~EET/temp/mos/AR2617.MOS~ ~%areas_dir%/bgAR26xx/FH2617.MOS~
	~EET/temp/mos/AR2618.MOS~ ~%areas_dir%/bgAR26xx/FH2618.MOS~
	~EET/temp/mos/AR2619.MOS~ ~%areas_dir%/bgAR26xx/FH2619.MOS~
	~EET/temp/mos/AR2631.MOS~ ~%areas_dir%/bgAR26xx/FH2631.MOS~
	~EET/temp/mos/AR2643.MOS~ ~%areas_dir%/bgAR26xx/FH2643.MOS~
	~EET/temp/mos/AR2700.MOS~ ~%areas_dir%/bgAR27xx/FH2700.MOS~
	~EET/temp/mos/AR2800.MOS~ ~%areas_dir%/bgAR28xx/FH2800.MOS~
	~EET/temp/mos/AR2900.MOS~ ~%areas_dir%/bgAR29xx/FH2900.MOS~
	~EET/temp/mos/AR3000.MOS~ ~%areas_dir%/bgAR30xx/FH3000.MOS~
	~EET/temp/mos/AR3100.MOS~ ~%areas_dir%/bgAR31xx/FH3100.MOS~
	~EET/temp/mos/AR3200.MOS~ ~%areas_dir%/bgAR32xx/FH3200.MOS~
	~EET/temp/mos/AR3200N.MOS~ ~%areas_dir%/bgAR32xx/FH3200N.MOS~
	~EET/temp/mos/AR3201.MOS~ ~%areas_dir%/bgAR32xx/FH3201.MOS~
	~EET/temp/mos/AR3202.MOS~ ~%areas_dir%/bgAR32xx/FH3202.MOS~
	~EET/temp/mos/AR3300.MOS~ ~%areas_dir%/bgAR33xx/FH3300.MOS~
	~EET/temp/mos/AR3301.MOS~ ~%areas_dir%/bgAR33xx/FH3301.MOS~
	~EET/temp/mos/AR3302.MOS~ ~%areas_dir%/bgAR33xx/FH3302.MOS~
	~EET/temp/mos/AR3303.MOS~ ~%areas_dir%/bgAR33xx/FH3303.MOS~
	~EET/temp/mos/AR3304.MOS~ ~%areas_dir%/bgAR33xx/FH3304.MOS~
	~EET/temp/mos/AR3305.MOS~ ~%areas_dir%/bgAR33xx/FH3305.MOS~
	~EET/temp/mos/AR3306.MOS~ ~%areas_dir%/bgAR33xx/FH3306.MOS~
	~EET/temp/mos/AR3307.MOS~ ~%areas_dir%/bgAR33xx/FH3307.MOS~
	~EET/temp/mos/AR3308.MOS~ ~%areas_dir%/bgAR33xx/FH3308.MOS~
	~EET/temp/mos/AR3309.MOS~ ~%areas_dir%/bgAR33xx/FH3309.MOS~
	~EET/temp/mos/AR3310.MOS~ ~%areas_dir%/bgAR33xx/FH3310.MOS~
	~EET/temp/mos/AR3313.MOS~ ~%areas_dir%/bgAR33xx/FH3313.MOS~
	~EET/temp/mos/AR3314.MOS~ ~%areas_dir%/bgAR33xx/FH3314.MOS~
	~EET/temp/mos/AR3316.MOS~ ~%areas_dir%/bgAR33xx/FH3316.MOS~
	~EET/temp/mos/AR3317.MOS~ ~%areas_dir%/bgAR33xx/FH3317.MOS~
	~EET/temp/mos/AR3320.MOS~ ~%areas_dir%/bgAR33xx/FH3320.MOS~
	~EET/temp/mos/AR3321.MOS~ ~%areas_dir%/bgAR33xx/FH3321.MOS~
	~EET/temp/mos/AR3327.MOS~ ~%areas_dir%/bgAR33xx/FH3327.MOS~
	~EET/temp/mos/AR3328.MOS~ ~%areas_dir%/bgAR33xx/FH3328.MOS~
	~EET/temp/mos/AR3339.MOS~ ~%areas_dir%/bgAR33xx/FH3339.MOS~
	~EET/temp/mos/AR3340.MOS~ ~%areas_dir%/bgAR33xx/FH3340.MOS~
	~EET/temp/mos/AR3351.MOS~ ~%areas_dir%/bgAR33xx/FH3351.MOS~
	~EET/temp/mos/AR3352.MOS~ ~%areas_dir%/bgAR33xx/FH3352.MOS~
	~EET/temp/mos/AR3353.MOS~ ~%areas_dir%/bgAR33xx/FH3353.MOS~
	~EET/temp/mos/AR3357.MOS~ ~%areas_dir%/bgAR33xx/FH3357.MOS~
	~EET/temp/mos/AR3400.MOS~ ~%areas_dir%/bgAR34xx/FH3400.MOS~
	~EET/temp/mos/AR3400N.MOS~ ~%areas_dir%/bgAR34xx/FH3400N.MOS~
	~EET/temp/mos/AR3401.MOS~ ~%areas_dir%/bgAR34xx/FH3401.MOS~
	~EET/temp/mos/AR3402.MOS~ ~%areas_dir%/bgAR34xx/FH3402.MOS~
	~EET/temp/mos/AR3500.MOS~ ~%areas_dir%/bgAR35xx/FH3500.MOS~
	~EET/temp/mos/AR3600.MOS~ ~%areas_dir%/bgAR36xx/FH3600.MOS~
	~EET/temp/mos/AR3601.MOS~ ~%areas_dir%/bgAR36xx/FH3601.MOS~
	~EET/temp/mos/AR3700.MOS~ ~%areas_dir%/bgAR37xx/FH3700.MOS~
	~EET/temp/mos/AR3800.MOS~ ~%areas_dir%/bgAR38xx/FH3800.MOS~
	~EET/temp/mos/AR3802.MOS~ ~%areas_dir%/bgAR38xx/FH3802.MOS~
	~EET/temp/mos/AR3900.MOS~ ~%areas_dir%/bgAR39xx/FH3900.MOS~
	~EET/temp/mos/AR3901.MOS~ ~%areas_dir%/bgAR39xx/FH3901.MOS~
	~EET/temp/mos/AR4000.MOS~ ~%areas_dir%/bgAR40xx/FH4000.MOS~
	~EET/temp/mos/AR4001.MOS~ ~%areas_dir%/bgAR40xx/FH4001.MOS~
	~EET/temp/mos/AR4002.MOS~ ~%areas_dir%/bgAR40xx/FH4002.MOS~
	~EET/temp/mos/AR4003.MOS~ ~%areas_dir%/bgAR40xx/FH4003.MOS~
	~EET/temp/mos/AR4004.MOS~ ~%areas_dir%/bgAR40xx/FH4004.MOS~
	~EET/temp/mos/AR4006.MOS~ ~%areas_dir%/bgAR40xx/FH4006.MOS~
	~EET/temp/mos/AR4100.MOS~ ~%areas_dir%/bgAR41xx/FH4100.MOS~
	~EET/temp/mos/AR4101.MOS~ ~%areas_dir%/bgAR41xx/FH4101.MOS~
	~EET/temp/mos/AR4200.MOS~ ~%areas_dir%/bgAR42xx/FH4200.MOS~
	~EET/temp/mos/AR4201.MOS~ ~%areas_dir%/bgAR42xx/FH4201.MOS~
	~EET/temp/mos/AR4300.MOS~ ~%areas_dir%/bgAR43xx/FH4300.MOS~
	~EET/temp/mos/AR4400.MOS~ ~%areas_dir%/bgAR44xx/FH4400.MOS~
	~EET/temp/mos/AR4401.MOS~ ~%areas_dir%/bgAR44xx/FH4401.MOS~
	~EET/temp/mos/AR4500.MOS~ ~%areas_dir%/bgAR45xx/FH4500.MOS~
	~EET/temp/mos/AR4501.MOS~ ~%areas_dir%/bgAR45xx/FH4501.MOS~
	~EET/temp/mos/AR4600.MOS~ ~%areas_dir%/bgAR46xx/FH4600.MOS~
	~EET/temp/mos/AR4700.MOS~ ~%areas_dir%/bgAR47xx/FH4700.MOS~
	~EET/temp/mos/AR4700N.MOS~ ~%areas_dir%/bgAR47xx/FH4700N.MOS~
	~EET/temp/mos/AR4701.MOS~ ~%areas_dir%/bgAR47xx/FH4701.MOS~
	~EET/temp/mos/AR4800.MOS~ ~%areas_dir%/bgAR48xx/FH4800.MOS~
	~EET/temp/mos/AR4801.MOS~ ~%areas_dir%/bgAR48xx/FH4801.MOS~
	~EET/temp/mos/AR4802.MOS~ ~%areas_dir%/bgAR48xx/FH4802.MOS~
	~EET/temp/mos/AR4803.MOS~ ~%areas_dir%/bgAR48xx/FH4803.MOS~
	~EET/temp/mos/AR4804.MOS~ ~%areas_dir%/bgAR48xx/FH4804.MOS~
	~EET/temp/mos/AR4805.MOS~ ~%areas_dir%/bgAR48xx/FH4805.MOS~
	~EET/temp/mos/AR4806.MOS~ ~%areas_dir%/bgAR48xx/FH4806.MOS~
	~EET/temp/mos/AR4807.MOS~ ~%areas_dir%/bgAR48xx/FH4807.MOS~
	~EET/temp/mos/AR4808.MOS~ ~%areas_dir%/bgAR48xx/FH4808.MOS~
	~EET/temp/mos/AR4809.MOS~ ~%areas_dir%/bgAR48xx/FH4809.MOS~
	~EET/temp/mos/AR4810.MOS~ ~%areas_dir%/bgAR48xx/FH4810.MOS~
	~EET/temp/mos/AR4900.MOS~ ~%areas_dir%/bgAR49xx/FH4900.MOS~
	~EET/temp/mos/AR4900N.MOS~ ~%areas_dir%/bgAR49xx/FH4900N.MOS~
	~EET/temp/mos/AR4901.MOS~ ~%areas_dir%/bgAR49xx/FH4901.MOS~
	~EET/temp/mos/AR4902.MOS~ ~%areas_dir%/bgAR49xx/FH4902.MOS~
	~EET/temp/mos/AR4903.MOS~ ~%areas_dir%/bgAR49xx/FH4903.MOS~
	~EET/temp/mos/AR4905.MOS~ ~%areas_dir%/bgAR49xx/FH4905.MOS~
	~EET/temp/mos/AR4906.MOS~ ~%areas_dir%/bgAR49xx/FH4906.MOS~
	~EET/temp/mos/AR5000.MOS~ ~%areas_dir%/bgAR50xx/FH5000.MOS~
	~EET/temp/mos/AR5001.MOS~ ~%areas_dir%/bgAR50xx/FH5001.MOS~
	~EET/temp/mos/AR5100.MOS~ ~%areas_dir%/bgAR51xx/FH5100.MOS~
	~EET/temp/mos/AR5101.MOS~ ~%areas_dir%/bgAR51xx/FH5101.MOS~
	~EET/temp/mos/AR5102.MOS~ ~%areas_dir%/bgAR51xx/FH5102.MOS~
	~EET/temp/mos/AR5103.MOS~ ~%areas_dir%/bgAR51xx/FH5103.MOS~
	~EET/temp/mos/AR5200.MOS~ ~%areas_dir%/bgAR52xx/FH5200.MOS~
	~EET/temp/mos/AR5201.MOS~ ~%areas_dir%/bgAR52xx/FH5201.MOS~
	~EET/temp/mos/AR5202.MOS~ ~%areas_dir%/bgAR52xx/FH5202.MOS~
	~EET/temp/mos/AR5300.MOS~ ~%areas_dir%/bgAR53xx/FH5300.MOS~
	~EET/temp/mos/AR5400.MOS~ ~%areas_dir%/bgAR54xx/FH5400.MOS~
	~EET/temp/mos/AR5401.MOS~ ~%areas_dir%/bgAR54xx/FH5401.MOS~
	~EET/temp/mos/AR5402.MOS~ ~%areas_dir%/bgAR54xx/FH5402.MOS~
	~EET/temp/mos/AR5403.MOS~ ~%areas_dir%/bgAR54xx/FH5403.MOS~
	~EET/temp/mos/AR5404.MOS~ ~%areas_dir%/bgAR54xx/FH5404.MOS~
	~EET/temp/mos/AR5405.MOS~ ~%areas_dir%/bgAR54xx/FH5405.MOS~
	~EET/temp/mos/AR5406.MOS~ ~%areas_dir%/bgAR54xx/FH5406.MOS~
	~EET/temp/mos/AR5500.MOS~ ~%areas_dir%/bgAR55xx/FH5500.MOS~
	~EET/temp/mos/AR5506.MOS~ ~%areas_dir%/bgAR55xx/FH5506.MOS~
	~EET/temp/mos/AR5600.MOS~ ~%areas_dir%/bgAR56xx/FH5600.MOS~
	~EET/temp/mos/AR5700.MOS~ ~%areas_dir%/bgAR57xx/FH5700.MOS~
	~EET/temp/mos/AR5800.MOS~ ~%areas_dir%/bgAR58xx/FH5800.MOS~
	~EET/temp/mos/AR5900.MOS~ ~%areas_dir%/bgAR59xx/FH5900.MOS~
	~EET/temp/mos/AR6000.MOS~ ~%areas_dir%/bgAR60xx/FH6000.MOS~
	~EET/temp/mos/AR6100.MOS~ ~%areas_dir%/bgAR61xx/FH6100.MOS~
	~EET/temp/mos/OH2000.MOS~ ~%areas_dir%/bgOH2xxx~
	~EET/temp/mos/OH2000N.MOS~ ~%areas_dir%/bgOH2xxx~
	~EET/temp/mos/OH2010.MOS~ ~%areas_dir%/bgOH2xxx~
	~EET/temp/mos/OH3000.MOS~ ~%areas_dir%/bgOH3xxx~
	~EET/temp/mos/OH3000N.MOS~ ~%areas_dir%/bgOH3xxx~
	~EET/temp/mos/OH3010.MOS~ ~%areas_dir%/bgOH3xxx~
	~EET/temp/mos/OH3020.MOS~ ~%areas_dir%/bgOH3xxx~
	~EET/temp/mos/OH3100.MOS~ ~%areas_dir%/bgOH3xxx~
	~EET/temp/mos/OH3100N.MOS~ ~%areas_dir%/bgOH3xxx~
	~EET/temp/mos/OH9310.MOS~ ~%areas_dir%/bgOH9xxx~
	~EET/temp/mos/OH9350.MOS~ ~%areas_dir%/bgOH9xxx~
	~EET/temp/mos/OH9360.MOS~ ~%areas_dir%/bgOH9xxx~
	~EET/temp/mos/TU0015.MOS~ ~%areas_dir%/bgTU00xx~
	~EET/temp/mos/TU0016.MOS~ ~%areas_dir%/bgTU00xx~
	~EET/temp/mos/TU0017.MOS~ ~%areas_dir%/bgTU00xx~
	~EET/temp/mos/TU0018.MOS~ ~%areas_dir%/bgTU00xx~

DELETE + ~EET/temp/mos/ARRIVE.MOS~
	~EET/temp/mos/BAR-FINL.MOS~
	~EET/temp/mos/BAR-STEP.MOS~
	~EET/temp/mos/BGDECBAR.MOS~
	~EET/temp/mos/BGPADB.MOS~
	~EET/temp/mos/BGPADL.MOS~
	~EET/temp/mos/BGPADR.MOS~
	~EET/temp/mos/BPEND.MOS~
	~EET/temp/mos/COLOR.MOS~
	~EET/temp/mos/COLORI.MOS~
	~EET/temp/mos/COLORR.MOS~
	~EET/temp/mos/GKEYMAP.MOS~
	~EET/temp/mos/GMPCARBB.MOS~
	~EET/temp/mos/GMPCARBD.MOS~
	~EET/temp/mos/GMPNCGE1.MOS~
	~EET/temp/mos/GMPNCGE2.MOS~
	~EET/temp/mos/GMPNCGE3.MOS~
	~EET/temp/mos/GMPNJGME.MOS~
	~EET/temp/mos/GMPNTCPE.MOS~
	~EET/temp/mos/GMPPARBE.MOS~
	~EET/temp/mos/GMPPOPTB.MOS~
	~EET/temp/mos/GMPWMSG0.MOS~
	~EET/temp/mos/GMWMSGA0.MOS~
	~EET/temp/mos/GMWMSGA9.MOS~
	~EET/temp/mos/GMWMSGB0.MOS~
	~EET/temp/mos/GOPGAMB.MOS~
	~EET/temp/mos/GOPSNDSB.MOS~
	~EET/temp/mos/GTRBPBAR.MOS~
	~EET/temp/mos/GTRBPCAP.MOS~
	~EET/temp/mos/GTRSPBAR.MOS~
	~EET/temp/mos/GTRSPBG.MOS~
	~EET/temp/mos/GTRSPCAP.MOS~
	~EET/temp/mos/GU10BKLS.MOS~
	~EET/temp/mos/GU10BKMD.MOS~
	~EET/temp/mos/GU10BKRS.MOS~
	~EET/temp/mos/GU20BKLS.MOS~
	~EET/temp/mos/GU20BKMD.MOS~
	~EET/temp/mos/GU20BKRS.MOS~
	~EET/temp/mos/GU3MPB.MOS~
	~EET/temp/mos/GUDEATH0.MOS~
	~EET/temp/mos/GUI_NAME.MOS~
	~EET/temp/mos/GUIAPB.MOS~
	~EET/temp/mos/GUIAPBR.MOS~
	~EET/temp/mos/GUIBTTXT.MOS~
	~EET/temp/mos/GUICGB.MOS~
	~EET/temp/mos/GUICGPR.MOS~
	~EET/temp/mos/GUICHISD.MOS~
	~EET/temp/mos/GUICHISE.MOS~
	~EET/temp/mos/GUICHP0B.MOS~
	~EET/temp/mos/GUICHP1B.MOS~
	~EET/temp/mos/GUICHP2B.MOS~
	~EET/temp/mos/GUICHP3B.MOS~
	~EET/temp/mos/GUICHP4B.MOS~
	~EET/temp/mos/GUICHP5B.MOS~
	~EET/temp/mos/GUICHP6B.MOS~
	~EET/temp/mos/GUICHP7B.MOS~
	~EET/temp/mos/GUICHP8B.MOS~
	~EET/temp/mos/GUICONN1.MOS~
	~EET/temp/mos/GUICONNB.MOS~
	~EET/temp/mos/GUICONTB.MOS~
	~EET/temp/mos/GUICP.MOS~
	~EET/temp/mos/GUICPORB.MOS~
	~EET/temp/mos/GUICREDT.MOS~
	~EET/temp/mos/GUICUSTB.MOS~
	~EET/temp/mos/GUICUSTP.MOS~
	~EET/temp/mos/GUICUSTX.MOS~
	~EET/temp/mos/GUIDCB.MOS~
	~EET/temp/mos/GUIDCX.MOS~
	~EET/temp/mos/GUIDLC.MOS~
	~EET/temp/mos/GUIDRM2.MOS~
	~EET/temp/mos/GUIDRM2B.MOS~
	~EET/temp/mos/GUIDRM3.MOS~
	~EET/temp/mos/GUIDRM3B.MOS~
	~EET/temp/mos/GUIDRM4.MOS~
	~EET/temp/mos/GUIDRM4B.MOS~
	~EET/temp/mos/GUIDRM5.MOS~
	~EET/temp/mos/GUIDRM5B.MOS~
	~EET/temp/mos/GUIDRM6.MOS~
	~EET/temp/mos/GUIDRM6B.MOS~
	~EET/temp/mos/GUIDRM7.MOS~
	~EET/temp/mos/GUIDRM7B.MOS~
	~EET/temp/mos/GUIEDUS.MOS~
	~EET/temp/mos/GUIERR.MOS~
	~EET/temp/mos/GUIERR09.MOS~
	~EET/temp/mos/GUIERR10.MOS~
	~EET/temp/mos/GUIERR2.MOS~
	~EET/temp/mos/GUIERR21.MOS~
	~EET/temp/mos/GUIERR6.MOS~
	~EET/temp/mos/GUIERR8.MOS~
	~EET/temp/mos/GUIEXPE.MOS~
	~EET/temp/mos/GUIGDB.MOS~
	~EET/temp/mos/GUIHELP.MOS~
	~EET/temp/mos/GUIHSB.MOS~
	~EET/temp/mos/GUIHSBS.MOS~
	~EET/temp/mos/GUIINVHB.MOS~
	~EET/temp/mos/GUIINVHI.MOS~
	~EET/temp/mos/GUIINVRE.MOS~
	~EET/temp/mos/GUIJRNL.MOS~
	~EET/temp/mos/GUILUPB.MOS~
	~EET/temp/mos/GUIMAPAB.MOS~
	~EET/temp/mos/GUIMAPWB.MOS~
	~EET/temp/mos/GUIMGB.MOS~
	~EET/temp/mos/GUIMGCP.MOS~
	~EET/temp/mos/GUIMGX.MOS~
	~EET/temp/mos/GUIMOVB.MOS~
	~EET/temp/mos/GUIMPB.MOS~
	~EET/temp/mos/GUINME.MOS~
	~EET/temp/mos/GUIOLSP0.MOS~
	~EET/temp/mos/GUIOSTUM.MOS~
	~EET/temp/mos/GUIPBRC.MOS~
	~EET/temp/mos/GUIPNLC.MOS~
	~EET/temp/mos/GUIPRB.MOS~
	~EET/temp/mos/GUIRECBG.MOS~
	~EET/temp/mos/GUISLDR.MOS~
	~EET/temp/mos/GUISMBM.MOS~
	~EET/temp/mos/GUISMDA.MOS~
	~EET/temp/mos/GUISMDB.MOS~
	~EET/temp/mos/GUISMF.MOS~
	~EET/temp/mos/GUISMF2.MOS~
	~EET/temp/mos/GUISMS.MOS~
	~EET/temp/mos/GUISPLHB.MOS~
	~EET/temp/mos/GUISPMB.MOS~
	~EET/temp/mos/GUISRRQB.MOS~
	~EET/temp/mos/GUISRSVB.MOS~
	~EET/temp/mos/GUISRSVE.MOS~
	~EET/temp/mos/GUISTATS.MOS~
	~EET/temp/mos/GUISTBBB.MOS~
	~EET/temp/mos/GUISTBBM.MOS~
	~EET/temp/mos/GUISTBSC.MOS~
	~EET/temp/mos/GUISTDOB.MOS~
	~EET/temp/mos/GUISTDOE.MOS~
	~EET/temp/mos/GUISTIDB.MOS~
	~EET/temp/mos/GUISTMPE.MOS~
	~EET/temp/mos/GUISTROB.MOS~
	~EET/temp/mos/GUITPP8.MOS~
	~EET/temp/mos/GUIVERB.MOS~
	~EET/temp/mos/GUIW12_1.MOS~
	~EET/temp/mos/GUIW12_2.MOS~
	~EET/temp/mos/GUIW12_3.MOS~
	~EET/temp/mos/GUIW12_4.MOS~
	~EET/temp/mos/GUIW12_5.MOS~
	~EET/temp/mos/GUIW12_6.MOS~
	~EET/temp/mos/GUIW12_7.MOS~
	~EET/temp/mos/GUIW12_8.MOS~
	~EET/temp/mos/GUIWBTP1.MOS~
	~EET/temp/mos/GUIWBTP2.MOS~
	~EET/temp/mos/GUIWBTP3.MOS~
	~EET/temp/mos/GUIWCHT0.MOS~
	~EET/temp/mos/GUIWCHTE.MOS~
	~EET/temp/mos/GUIWDMB.MOS~
	~EET/temp/mos/GUIWDMB0.MOS~
	~EET/temp/mos/GUIWDMB9.MOS~
	~EET/temp/mos/GUIWDMBM.MOS~
	~EET/temp/mos/GUIWDSL0.MOS~
	~EET/temp/mos/GUIWDSL1.MOS~
	~EET/temp/mos/GUIWDSL9.MOS~
	~EET/temp/mos/GUIWLLP.MOS~
	~EET/temp/mos/GUIWLLP8.MOS~
	~EET/temp/mos/GUIWLS20.MOS~
	~EET/temp/mos/GUIWLSP.MOS~
	~EET/temp/mos/GUIWLSP0.MOS~
	~EET/temp/mos/GUIWPPE.MOS~
	~EET/temp/mos/GUIWRLP.MOS~
	~EET/temp/mos/GUIWRLP0.MOS~
	~EET/temp/mos/GUIWRLP8.MOS~
	~EET/temp/mos/GUIWRS20.MOS~
	~EET/temp/mos/GUIWRSP.MOS~
	~EET/temp/mos/GUIWTPP.MOS~
	~EET/temp/mos/GUIWTPP0.MOS~
	~EET/temp/mos/GUIWTPP8.MOS~
	~EET/temp/mos/GUMPB.MOS~
	~EET/temp/mos/GUWBTP10.MOS~
	~EET/temp/mos/GUWBTP20.MOS~
	~EET/temp/mos/GUWBTP29.MOS~
	~EET/temp/mos/GUWBTP30.MOS~
	~EET/temp/mos/GUWBTP39.MOS~
	~EET/temp/mos/GUWBTP3M.MOS~
	~EET/temp/mos/GUWBTP9M.MOS~
	~EET/temp/mos/GUWDMBM9.MOS~
	~EET/temp/mos/GUWDSL9.MOS~
	~EET/temp/mos/GUWPKPC0.MOS~
	~EET/temp/mos/GWCONTB0.MOS~
	~EET/temp/mos/IMEUI.MOS~
	~EET/temp/mos/INVENTOR.MOS~
	~EET/temp/mos/LEAVE.MOS~
	~EET/temp/mos/NPCCHAP.MOS~
	~EET/temp/mos/SIDEBLOK.MOS~
	~EET/temp/mos/START.MOS~
	~EET/temp/mos/STARTEE.MOS~
	~EET/temp/mos/STARTM.MOS~
	~EET/temp/mos/STARTOLD.MOS~
	~EET/temp/mos/STON09B.MOS~
	~EET/temp/mos/STON09L.MOS~
	~EET/temp/mos/STON09R.MOS~
	~EET/temp/mos/STON09T.MOS~
	~EET/temp/mos/STON12B.MOS~
	~EET/temp/mos/STON12L.MOS~
	~EET/temp/mos/STON12R.MOS~
	~EET/temp/mos/STON12T.MOS~
	~EET/temp/mos/STON13B.MOS~
	~EET/temp/mos/STON13L.MOS~
	~EET/temp/mos/STON13R.MOS~
	~EET/temp/mos/STON13T.MOS~
	~EET/temp/mos/STONEOPT.MOS~
	~EET/temp/mos/TEXT.MOS~
	~EET/temp/mos/TEXT_IN.MOS~
	~EET/temp/mos/TOSCEND.MOS~
	~EET/temp/mos/ULGOTHST.MOS~
	~EET/temp/mos/WORLDMAP.MOS~
