MOVE + ~EET/temp/mos/AR0002.MOS~ ~%areas_dir%/bgAR00xx/BG0002.MOS~
	~EET/temp/mos/AR0100.MOS~ ~%areas_dir%/bgAR01xx/BG0100.MOS~
	~EET/temp/mos/AR0100N.MOS~ ~%areas_dir%/bgAR01xx/BG0100N.MOS~
	~EET/temp/mos/AR0101.MOS~ ~%areas_dir%/bgAR01xx/BG0101.MOS~
	~EET/temp/mos/AR0102.MOS~ ~%areas_dir%/bgAR01xx/BG0102.MOS~
	~EET/temp/mos/AR0103.MOS~ ~%areas_dir%/bgAR01xx/BG0103.MOS~
	~EET/temp/mos/AR0104.MOS~ ~%areas_dir%/bgAR01xx/BG0104.MOS~
	~EET/temp/mos/AR0105.MOS~ ~%areas_dir%/bgAR01xx/BG0105.MOS~
	~EET/temp/mos/AR0106.MOS~ ~%areas_dir%/bgAR01xx/BG0106.MOS~
	~EET/temp/mos/AR0107.MOS~ ~%areas_dir%/bgAR01xx/BG0107.MOS~
	~EET/temp/mos/AR0108.MOS~ ~%areas_dir%/bgAR01xx/BG0108.MOS~
	~EET/temp/mos/AR0109.MOS~ ~%areas_dir%/bgAR01xx/BG0109.MOS~
	~EET/temp/mos/AR0110.MOS~ ~%areas_dir%/bgAR01xx/BG0110.MOS~
	~EET/temp/mos/AR0111.MOS~ ~%areas_dir%/bgAR01xx/BG0111.MOS~
	~EET/temp/mos/AR0112.MOS~ ~%areas_dir%/bgAR01xx/BG0112.MOS~
	~EET/temp/mos/AR0114.MOS~ ~%areas_dir%/bgAR01xx/BG0114.MOS~
	~EET/temp/mos/AR0115.MOS~ ~%areas_dir%/bgAR01xx/BG0115.MOS~
	~EET/temp/mos/AR0116.MOS~ ~%areas_dir%/bgAR01xx/BG0116.MOS~
	~EET/temp/mos/AR0117.MOS~ ~%areas_dir%/bgAR01xx/BG0117.MOS~
	~EET/temp/mos/AR0118.MOS~ ~%areas_dir%/bgAR01xx/BG0118.MOS~
	~EET/temp/mos/AR0119.MOS~ ~%areas_dir%/bgAR01xx/BG0119.MOS~
	~EET/temp/mos/AR0120.MOS~ ~%areas_dir%/bgAR01xx/BG0120.MOS~
	~EET/temp/mos/AR0121.MOS~ ~%areas_dir%/bgAR01xx/BG0121.MOS~
	~EET/temp/mos/AR0123.MOS~ ~%areas_dir%/bgAR01xx/BG0123.MOS~
	~EET/temp/mos/AR0125.MOS~ ~%areas_dir%/bgAR01xx/BG0125.MOS~
	~EET/temp/mos/AR0126.MOS~ ~%areas_dir%/bgAR01xx/BG0126.MOS~
	~EET/temp/mos/AR0127.MOS~ ~%areas_dir%/bgAR01xx/BG0127.MOS~
	~EET/temp/mos/AR0128.MOS~ ~%areas_dir%/bgAR01xx/BG0128.MOS~
	~EET/temp/mos/AR0129.MOS~ ~%areas_dir%/bgAR01xx/BG0129.MOS~
	~EET/temp/mos/AR0130.MOS~ ~%areas_dir%/bgAR01xx/BG0130.MOS~
	~EET/temp/mos/AR0131.MOS~ ~%areas_dir%/bgAR01xx/BG0131.MOS~
	~EET/temp/mos/AR0132.MOS~ ~%areas_dir%/bgAR01xx/BG0132.MOS~
	~EET/temp/mos/AR0133.MOS~ ~%areas_dir%/bgAR01xx/BG0133.MOS~
	~EET/temp/mos/AR0134.MOS~ ~%areas_dir%/bgAR01xx/BG0134.MOS~
	~EET/temp/mos/AR0135.MOS~ ~%areas_dir%/bgAR01xx/BG0135.MOS~
	~EET/temp/mos/AR0136.MOS~ ~%areas_dir%/bgAR01xx/BG0136.MOS~
	~EET/temp/mos/AR0137.MOS~ ~%areas_dir%/bgAR01xx/BG0137.MOS~
	~EET/temp/mos/AR0138.MOS~ ~%areas_dir%/bgAR01xx/BG0138.MOS~
	~EET/temp/mos/AR0139.MOS~ ~%areas_dir%/bgAR01xx/BG0139.MOS~
	~EET/temp/mos/AR0140.MOS~ ~%areas_dir%/bgAR01xx/BG0140.MOS~
	~EET/temp/mos/AR0141.MOS~ ~%areas_dir%/bgAR01xx/BG0141.MOS~
	~EET/temp/mos/AR0142.MOS~ ~%areas_dir%/bgAR01xx/BG0142.MOS~
	~EET/temp/mos/AR0143.MOS~ ~%areas_dir%/bgAR01xx/BG0143.MOS~
	~EET/temp/mos/AR0144.MOS~ ~%areas_dir%/bgAR01xx/BG0144.MOS~
	~EET/temp/mos/AR0145.MOS~ ~%areas_dir%/bgAR01xx/BG0145.MOS~
	~EET/temp/mos/AR0146.MOS~ ~%areas_dir%/bgAR01xx/BG0146.MOS~
	~EET/temp/mos/AR0148.MOS~ ~%areas_dir%/bgAR01xx/BG0148.MOS~
	~EET/temp/mos/AR0149.MOS~ ~%areas_dir%/bgAR01xx/BG0149.MOS~
	~EET/temp/mos/AR0150.MOS~ ~%areas_dir%/bgAR01xx/BG0150.MOS~
	~EET/temp/mos/AR0151.MOS~ ~%areas_dir%/bgAR01xx/BG0151.MOS~
	~EET/temp/mos/AR0152.MOS~ ~%areas_dir%/bgAR01xx/BG0152.MOS~
	~EET/temp/mos/AR0153.MOS~ ~%areas_dir%/bgAR01xx/BG0153.MOS~
	~EET/temp/mos/AR0155.MOS~ ~%areas_dir%/bgAR01xx/BG0155.MOS~
	~EET/temp/mos/AR0156.MOS~ ~%areas_dir%/bgAR01xx/BG0156.MOS~
	~EET/temp/mos/AR0161.MOS~ ~%areas_dir%/bgAR01xx/BG0161.MOS~
	~EET/temp/mos/AR0162.MOS~ ~%areas_dir%/bgAR01xx/BG0162.MOS~
	~EET/temp/mos/AR0163.MOS~ ~%areas_dir%/bgAR01xx/BG0163.MOS~
	~EET/temp/mos/AR0164.MOS~ ~%areas_dir%/bgAR01xx/BG0164.MOS~
	~EET/temp/mos/AR0165.MOS~ ~%areas_dir%/bgAR01xx/BG0165.MOS~
	~EET/temp/mos/AR0166.MOS~ ~%areas_dir%/bgAR01xx/BG0166.MOS~
	~EET/temp/mos/AR0167.MOS~ ~%areas_dir%/bgAR01xx/BG0167.MOS~
	~EET/temp/mos/AR0168.MOS~ ~%areas_dir%/bgAR01xx/BG0168.MOS~
	~EET/temp/mos/AR0169.MOS~ ~%areas_dir%/bgAR01xx/BG0169.MOS~
	~EET/temp/mos/AR0170.MOS~ ~%areas_dir%/bgAR01xx/BG0170.MOS~
	~EET/temp/mos/AR0200.MOS~ ~%areas_dir%/bgAR02xx/BG0200.MOS~
	~EET/temp/mos/AR0200N.MOS~ ~%areas_dir%/bgAR02xx/BG0200N.MOS~
	~EET/temp/mos/AR0224.MOS~ ~%areas_dir%/bgAR02xx/BG0224.MOS~
	~EET/temp/mos/AR0225.MOS~ ~%areas_dir%/bgAR02xx/BG0225.MOS~
	~EET/temp/mos/AR0226.MOS~ ~%areas_dir%/bgAR02xx/BG0226.MOS~
	~EET/temp/mos/AR0300.MOS~ ~%areas_dir%/bgAR03xx/BG0300.MOS~
	~EET/temp/mos/AR0300N.MOS~ ~%areas_dir%/bgAR03xx/BG0300N.MOS~
	~EET/temp/mos/AR0304.MOS~ ~%areas_dir%/bgAR03xx/BG0304.MOS~
	~EET/temp/mos/AR0400.MOS~ ~%areas_dir%/bgAR04xx/BG0400.MOS~
	~EET/temp/mos/AR0401.MOS~ ~%areas_dir%/bgAR04xx/BG0401.MOS~
	~EET/temp/mos/AR0500.MOS~ ~%areas_dir%/bgAR05xx/BG0500.MOS~
	~EET/temp/mos/AR0501.MOS~ ~%areas_dir%/bgAR05xx/BG0501.MOS~
	~EET/temp/mos/AR0502.MOS~ ~%areas_dir%/bgAR05xx/BG0502.MOS~
	~EET/temp/mos/AR0503.MOS~ ~%areas_dir%/bgAR05xx/BG0503.MOS~
	~EET/temp/mos/AR0504.MOS~ ~%areas_dir%/bgAR05xx/BG0504.MOS~
	~EET/temp/mos/AR0505.MOS~ ~%areas_dir%/bgAR05xx/BG0505.MOS~
	~EET/temp/mos/AR0506.MOS~ ~%areas_dir%/bgAR05xx/BG0506.MOS~
	~EET/temp/mos/AR0507.MOS~ ~%areas_dir%/bgAR05xx/BG0507.MOS~
	~EET/temp/mos/AR0508.MOS~ ~%areas_dir%/bgAR05xx/BG0508.MOS~
	~EET/temp/mos/AR0509.MOS~ ~%areas_dir%/bgAR05xx/BG0509.MOS~
	~EET/temp/mos/AR0510.MOS~ ~%areas_dir%/bgAR05xx/BG0510.MOS~
	~EET/temp/mos/AR0511.MOS~ ~%areas_dir%/bgAR05xx/BG0511.MOS~
	~EET/temp/mos/AR0512.MOS~ ~%areas_dir%/bgAR05xx/BG0512.MOS~
	~EET/temp/mos/AR0513.MOS~ ~%areas_dir%/bgAR05xx/BG0513.MOS~
	~EET/temp/mos/AR0514.MOS~ ~%areas_dir%/bgAR05xx/BG0514.MOS~
	~EET/temp/mos/AR0515.MOS~ ~%areas_dir%/bgAR05xx/BG0515.MOS~
	~EET/temp/mos/AR0516.MOS~ ~%areas_dir%/bgAR05xx/BG0516.MOS~
	~EET/temp/mos/AR0600.MOS~ ~%areas_dir%/bgAR06xx/BG0600.MOS~
	~EET/temp/mos/AR0600N.MOS~ ~%areas_dir%/bgAR06xx/BG0600N.MOS~
	~EET/temp/mos/AR0601.MOS~ ~%areas_dir%/bgAR06xx/BG0601.MOS~
	~EET/temp/mos/AR0602.MOS~ ~%areas_dir%/bgAR06xx/BG0602.MOS~
	~EET/temp/mos/AR0603.MOS~ ~%areas_dir%/bgAR06xx/BG0603.MOS~
	~EET/temp/mos/AR0606.MOS~ ~%areas_dir%/bgAR06xx/BG0606.MOS~
	~EET/temp/mos/AR0607.MOS~ ~%areas_dir%/bgAR06xx/BG0607.MOS~
	~EET/temp/mos/AR0608.MOS~ ~%areas_dir%/bgAR06xx/BG0608.MOS~
	~EET/temp/mos/AR0609.MOS~ ~%areas_dir%/bgAR06xx/BG0609.MOS~
	~EET/temp/mos/AR0611.MOS~ ~%areas_dir%/bgAR06xx/BG0611.MOS~
	~EET/temp/mos/AR0612.MOS~ ~%areas_dir%/bgAR06xx/BG0612.MOS~
	~EET/temp/mos/AR0613.MOS~ ~%areas_dir%/bgAR06xx/BG0613.MOS~
	~EET/temp/mos/AR0614.MOS~ ~%areas_dir%/bgAR06xx/BG0614.MOS~
	~EET/temp/mos/AR0615.MOS~ ~%areas_dir%/bgAR06xx/BG0615.MOS~
	~EET/temp/mos/AR0616.MOS~ ~%areas_dir%/bgAR06xx/BG0616.MOS~
	~EET/temp/mos/AR0621.MOS~ ~%areas_dir%/bgAR06xx/BG0621.MOS~
	~EET/temp/mos/AR0621N.MOS~ ~%areas_dir%/bgAR06xx/BG0621N.MOS~
	~EET/temp/mos/AR0700.MOS~ ~%areas_dir%/bgAR07xx/BG0700.MOS~
	~EET/temp/mos/AR0700N.MOS~ ~%areas_dir%/bgAR07xx/BG0700N.MOS~
	~EET/temp/mos/AR0702.MOS~ ~%areas_dir%/bgAR07xx/BG0702.MOS~
	~EET/temp/mos/AR0703.MOS~ ~%areas_dir%/bgAR07xx/BG0703.MOS~
	~EET/temp/mos/AR0704.MOS~ ~%areas_dir%/bgAR07xx/BG0704.MOS~
	~EET/temp/mos/AR0705.MOS~ ~%areas_dir%/bgAR07xx/BG0705.MOS~
	~EET/temp/mos/AR0706.MOS~ ~%areas_dir%/bgAR07xx/BG0706.MOS~
	~EET/temp/mos/AR0719.MOS~ ~%areas_dir%/bgAR07xx/BG0719.MOS~
	~EET/temp/mos/AR0720.MOS~ ~%areas_dir%/bgAR07xx/BG0720.MOS~
	~EET/temp/mos/AR0724.MOS~ ~%areas_dir%/bgAR07xx/BG0724.MOS~
	~EET/temp/mos/AR0726.MOS~ ~%areas_dir%/bgAR07xx/BG0726.MOS~
	~EET/temp/mos/AR0800.MOS~ ~%areas_dir%/bgAR08xx/BG0800.MOS~
	~EET/temp/mos/AR0800N.MOS~ ~%areas_dir%/bgAR08xx/BG0800N.MOS~
	~EET/temp/mos/AR0807.MOS~ ~%areas_dir%/bgAR08xx/BG0807.MOS~
	~EET/temp/mos/AR0808.MOS~ ~%areas_dir%/bgAR08xx/BG0808.MOS~
	~EET/temp/mos/AR0809.MOS~ ~%areas_dir%/bgAR08xx/BG0809.MOS~
	~EET/temp/mos/AR0900.MOS~ ~%areas_dir%/bgAR09xx/BG0900.MOS~
	~EET/temp/mos/AR0900N.MOS~ ~%areas_dir%/bgAR09xx/BG0900N.MOS~
	~EET/temp/mos/AR0901.MOS~ ~%areas_dir%/bgAR09xx/BG0901.MOS~
	~EET/temp/mos/AR1000.MOS~ ~%areas_dir%/bgAR10xx/BG1000.MOS~
	~EET/temp/mos/AR1001.MOS~ ~%areas_dir%/bgAR10xx/BG1001.MOS~
	~EET/temp/mos/AR1002.MOS~ ~%areas_dir%/bgAR10xx/BG1002.MOS~
	~EET/temp/mos/AR1003.MOS~ ~%areas_dir%/bgAR10xx/BG1003.MOS~
	~EET/temp/mos/AR1004.MOS~ ~%areas_dir%/bgAR10xx/BG1004.MOS~
	~EET/temp/mos/AR1005.MOS~ ~%areas_dir%/bgAR10xx/BG1005.MOS~
	~EET/temp/mos/AR1006.MOS~ ~%areas_dir%/bgAR10xx/BG1006.MOS~
	~EET/temp/mos/AR1007.MOS~ ~%areas_dir%/bgAR10xx/BG1007.MOS~
	~EET/temp/mos/AR1008.MOS~ ~%areas_dir%/bgAR10xx/BG1008.MOS~
	~EET/temp/mos/AR1009.MOS~ ~%areas_dir%/bgAR10xx/BG1009.MOS~
	~EET/temp/mos/AR1010.MOS~ ~%areas_dir%/bgAR10xx/BG1010.MOS~
	~EET/temp/mos/AR1100.MOS~ ~%areas_dir%/bgAR11xx/BG1100.MOS~
	~EET/temp/mos/AR1100N.MOS~ ~%areas_dir%/bgAR11xx/BG1100N.MOS~
	~EET/temp/mos/AR1101.MOS~ ~%areas_dir%/bgAR11xx/BG1101.MOS~
	~EET/temp/mos/AR1102.MOS~ ~%areas_dir%/bgAR11xx/BG1102.MOS~
	~EET/temp/mos/AR1200.MOS~ ~%areas_dir%/bgAR12xx/BG1200.MOS~
	~EET/temp/mos/AR1200N.MOS~ ~%areas_dir%/bgAR12xx/BG1200N.MOS~
	~EET/temp/mos/AR1207.MOS~ ~%areas_dir%/bgAR12xx/BG1207.MOS~
	~EET/temp/mos/AR1208.MOS~ ~%areas_dir%/bgAR12xx/BG1208.MOS~
	~EET/temp/mos/AR1215.MOS~ ~%areas_dir%/bgAR12xx/BG1215.MOS~
	~EET/temp/mos/AR1300.MOS~ ~%areas_dir%/bgAR13xx/BG1300.MOS~
	~EET/temp/mos/AR1300N.MOS~ ~%areas_dir%/bgAR13xx/BG1300N.MOS~
	~EET/temp/mos/AR1302.MOS~ ~%areas_dir%/bgAR13xx/BG1302.MOS~
	~EET/temp/mos/AR1400.MOS~ ~%areas_dir%/bgAR14xx/BG1400.MOS~
	~EET/temp/mos/AR1401.MOS~ ~%areas_dir%/bgAR14xx/BG1401.MOS~
	~EET/temp/mos/AR1402.MOS~ ~%areas_dir%/bgAR14xx/BG1402.MOS~
	~EET/temp/mos/AR1403.MOS~ ~%areas_dir%/bgAR14xx/BG1403.MOS~
	~EET/temp/mos/AR1404.MOS~ ~%areas_dir%/bgAR14xx/BG1404.MOS~
	~EET/temp/mos/AR1500.MOS~ ~%areas_dir%/bgAR15xx/BG1500.MOS~
	~EET/temp/mos/AR1501.MOS~ ~%areas_dir%/bgAR15xx/BG1501.MOS~
	~EET/temp/mos/AR1502.MOS~ ~%areas_dir%/bgAR15xx/BG1502.MOS~
	~EET/temp/mos/AR1503.MOS~ ~%areas_dir%/bgAR15xx/BG1503.MOS~
	~EET/temp/mos/AR1504.MOS~ ~%areas_dir%/bgAR15xx/BG1504.MOS~
	~EET/temp/mos/AR1505.MOS~ ~%areas_dir%/bgAR15xx/BG1505.MOS~
	~EET/temp/mos/AR1600.MOS~ ~%areas_dir%/bgAR16xx/BG1600.MOS~
	~EET/temp/mos/AR1601.MOS~ ~%areas_dir%/bgAR16xx/BG1601.MOS~
	~EET/temp/mos/AR1602.MOS~ ~%areas_dir%/bgAR16xx/BG1602.MOS~
	~EET/temp/mos/AR1603.MOS~ ~%areas_dir%/bgAR16xx/BG1603.MOS~
	~EET/temp/mos/AR1700.MOS~ ~%areas_dir%/bgAR17xx/BG1700.MOS~
	~EET/temp/mos/AR1800.MOS~ ~%areas_dir%/bgAR18xx/BG1800.MOS~
	~EET/temp/mos/AR1801.MOS~ ~%areas_dir%/bgAR18xx/BG1801.MOS~
	~EET/temp/mos/AR1802.MOS~ ~%areas_dir%/bgAR18xx/BG1802.MOS~
	~EET/temp/mos/AR1803.MOS~ ~%areas_dir%/bgAR18xx/BG1803.MOS~
	~EET/temp/mos/AR1804.MOS~ ~%areas_dir%/bgAR18xx/BG1804.MOS~
	~EET/temp/mos/AR1805.MOS~ ~%areas_dir%/bgAR18xx/BG1805.MOS~
	~EET/temp/mos/AR1806.MOS~ ~%areas_dir%/bgAR18xx/BG1806.MOS~
	~EET/temp/mos/AR1807.MOS~ ~%areas_dir%/bgAR18xx/BG1807.MOS~
	~EET/temp/mos/AR1808.MOS~ ~%areas_dir%/bgAR18xx/BG1808.MOS~
	~EET/temp/mos/AR1809.MOS~ ~%areas_dir%/bgAR18xx/BG1809.MOS~
	~EET/temp/mos/AR1900.MOS~ ~%areas_dir%/bgAR19xx/BG1900.MOS~
	~EET/temp/mos/AR1900N.MOS~ ~%areas_dir%/bgAR19xx/BG1900N.MOS~
	~EET/temp/mos/AR1901.MOS~ ~%areas_dir%/bgAR19xx/BG1901.MOS~
	~EET/temp/mos/AR1902.MOS~ ~%areas_dir%/bgAR19xx/BG1902.MOS~
	~EET/temp/mos/AR1903.MOS~ ~%areas_dir%/bgAR19xx/BG1903.MOS~
	~EET/temp/mos/AR2000.MOS~ ~%areas_dir%/bgAR20xx/BG2000.MOS~
	~EET/temp/mos/AR2001.MOS~ ~%areas_dir%/bgAR20xx/BG2001.MOS~
	~EET/temp/mos/AR2002.MOS~ ~%areas_dir%/bgAR20xx/BG2002.MOS~
	~EET/temp/mos/AR2003.MOS~ ~%areas_dir%/bgAR20xx/BG2003.MOS~
	~EET/temp/mos/AR2004.MOS~ ~%areas_dir%/bgAR20xx/BG2004.MOS~
	~EET/temp/mos/AR2005.MOS~ ~%areas_dir%/bgAR20xx/BG2005.MOS~
	~EET/temp/mos/AR2006.MOS~ ~%areas_dir%/bgAR20xx/BG2006.MOS~
	~EET/temp/mos/AR2007.MOS~ ~%areas_dir%/bgAR20xx/BG2007.MOS~
	~EET/temp/mos/AR2008.MOS~ ~%areas_dir%/bgAR20xx/BG2008.MOS~
	~EET/temp/mos/AR2009.MOS~ ~%areas_dir%/bgAR20xx/BG2009.MOS~
	~EET/temp/mos/AR2010.MOS~ ~%areas_dir%/bgAR20xx/BG2010.MOS~
	~EET/temp/mos/AR2011.MOS~ ~%areas_dir%/bgAR20xx/BG2011.MOS~
	~EET/temp/mos/AR2012.MOS~ ~%areas_dir%/bgAR20xx/BG2012.MOS~
	~EET/temp/mos/AR2100.MOS~ ~%areas_dir%/bgAR21xx/BG2100.MOS~
	~EET/temp/mos/AR2101.MOS~ ~%areas_dir%/bgAR21xx/BG2101.MOS~
	~EET/temp/mos/AR2200.MOS~ ~%areas_dir%/bgAR22xx/BG2200.MOS~
	~EET/temp/mos/AR2215.MOS~ ~%areas_dir%/bgAR22xx/BG2215.MOS~
	~EET/temp/mos/AR2300.MOS~ ~%areas_dir%/bgAR23xx/BG2300.MOS~
	~EET/temp/mos/AR2300N.MOS~ ~%areas_dir%/bgAR23xx/BG2300N.MOS~
	~EET/temp/mos/AR2301.MOS~ ~%areas_dir%/bgAR23xx/BG2301.MOS~
	~EET/temp/mos/AR2302.MOS~ ~%areas_dir%/bgAR23xx/BG2302.MOS~
	~EET/temp/mos/AR2303.MOS~ ~%areas_dir%/bgAR23xx/BG2303.MOS~
	~EET/temp/mos/AR2304.MOS~ ~%areas_dir%/bgAR23xx/BG2304.MOS~
	~EET/temp/mos/AR2305.MOS~ ~%areas_dir%/bgAR23xx/BG2305.MOS~
	~EET/temp/mos/AR2306.MOS~ ~%areas_dir%/bgAR23xx/BG2306.MOS~
	~EET/temp/mos/AR2400.MOS~ ~%areas_dir%/bgAR24xx/BG2400.MOS~
	~EET/temp/mos/AR2600.MOS~ ~%areas_dir%/bgAR26xx/BG2600.MOS~
	~EET/temp/mos/AR2602.MOS~ ~%areas_dir%/bgAR26xx/BG2602.MOS~
	~EET/temp/mos/AR2605.MOS~ ~%areas_dir%/bgAR26xx/BG2605.MOS~
	~EET/temp/mos/AR2606.MOS~ ~%areas_dir%/bgAR26xx/BG2606.MOS~
	~EET/temp/mos/AR2607.MOS~ ~%areas_dir%/bgAR26xx/BG2607.MOS~
	~EET/temp/mos/AR2608.MOS~ ~%areas_dir%/bgAR26xx/BG2608.MOS~
	~EET/temp/mos/AR2609.MOS~ ~%areas_dir%/bgAR26xx/BG2609.MOS~
	~EET/temp/mos/AR2610.MOS~ ~%areas_dir%/bgAR26xx/BG2610.MOS~
	~EET/temp/mos/AR2611.MOS~ ~%areas_dir%/bgAR26xx/BG2611.MOS~
	~EET/temp/mos/AR2612.MOS~ ~%areas_dir%/bgAR26xx/BG2612.MOS~
	~EET/temp/mos/AR2613.MOS~ ~%areas_dir%/bgAR26xx/BG2613.MOS~
	~EET/temp/mos/AR2614.MOS~ ~%areas_dir%/bgAR26xx/BG2614.MOS~
	~EET/temp/mos/AR2615.MOS~ ~%areas_dir%/bgAR26xx/BG2615.MOS~
	~EET/temp/mos/AR2616.MOS~ ~%areas_dir%/bgAR26xx/BG2616.MOS~
	~EET/temp/mos/AR2617.MOS~ ~%areas_dir%/bgAR26xx/BG2617.MOS~
	~EET/temp/mos/AR2618.MOS~ ~%areas_dir%/bgAR26xx/BG2618.MOS~
	~EET/temp/mos/AR2619.MOS~ ~%areas_dir%/bgAR26xx/BG2619.MOS~
	~EET/temp/mos/AR2631.MOS~ ~%areas_dir%/bgAR26xx/BG2631.MOS~
	~EET/temp/mos/AR2643.MOS~ ~%areas_dir%/bgAR26xx/BG2643.MOS~
	~EET/temp/mos/AR2700.MOS~ ~%areas_dir%/bgAR27xx/BG2700.MOS~
	~EET/temp/mos/AR2800.MOS~ ~%areas_dir%/bgAR28xx/BG2800.MOS~
	~EET/temp/mos/AR2900.MOS~ ~%areas_dir%/bgAR29xx/BG2900.MOS~
	~EET/temp/mos/AR3000.MOS~ ~%areas_dir%/bgAR30xx/BG3000.MOS~
	~EET/temp/mos/AR3100.MOS~ ~%areas_dir%/bgAR31xx/BG3100.MOS~
	~EET/temp/mos/AR3200.MOS~ ~%areas_dir%/bgAR32xx/BG3200.MOS~
	~EET/temp/mos/AR3200N.MOS~ ~%areas_dir%/bgAR32xx/BG3200N.MOS~
	~EET/temp/mos/AR3201.MOS~ ~%areas_dir%/bgAR32xx/BG3201.MOS~
	~EET/temp/mos/AR3202.MOS~ ~%areas_dir%/bgAR32xx/BG3202.MOS~
	~EET/temp/mos/AR3300.MOS~ ~%areas_dir%/bgAR33xx/BG3300.MOS~
	~EET/temp/mos/AR3301.MOS~ ~%areas_dir%/bgAR33xx/BG3301.MOS~
	~EET/temp/mos/AR3302.MOS~ ~%areas_dir%/bgAR33xx/BG3302.MOS~
	~EET/temp/mos/AR3303.MOS~ ~%areas_dir%/bgAR33xx/BG3303.MOS~
	~EET/temp/mos/AR3304.MOS~ ~%areas_dir%/bgAR33xx/BG3304.MOS~
	~EET/temp/mos/AR3305.MOS~ ~%areas_dir%/bgAR33xx/BG3305.MOS~
	~EET/temp/mos/AR3306.MOS~ ~%areas_dir%/bgAR33xx/BG3306.MOS~
	~EET/temp/mos/AR3307.MOS~ ~%areas_dir%/bgAR33xx/BG3307.MOS~
	~EET/temp/mos/AR3308.MOS~ ~%areas_dir%/bgAR33xx/BG3308.MOS~
	~EET/temp/mos/AR3309.MOS~ ~%areas_dir%/bgAR33xx/BG3309.MOS~
	~EET/temp/mos/AR3310.MOS~ ~%areas_dir%/bgAR33xx/BG3310.MOS~
	~EET/temp/mos/AR3313.MOS~ ~%areas_dir%/bgAR33xx/BG3313.MOS~
	~EET/temp/mos/AR3314.MOS~ ~%areas_dir%/bgAR33xx/BG3314.MOS~
	~EET/temp/mos/AR3316.MOS~ ~%areas_dir%/bgAR33xx/BG3316.MOS~
	~EET/temp/mos/AR3317.MOS~ ~%areas_dir%/bgAR33xx/BG3317.MOS~
	~EET/temp/mos/AR3320.MOS~ ~%areas_dir%/bgAR33xx/BG3320.MOS~
	~EET/temp/mos/AR3321.MOS~ ~%areas_dir%/bgAR33xx/BG3321.MOS~
	~EET/temp/mos/AR3327.MOS~ ~%areas_dir%/bgAR33xx/BG3327.MOS~
	~EET/temp/mos/AR3328.MOS~ ~%areas_dir%/bgAR33xx/BG3328.MOS~
	~EET/temp/mos/AR3339.MOS~ ~%areas_dir%/bgAR33xx/BG3339.MOS~
	~EET/temp/mos/AR3340.MOS~ ~%areas_dir%/bgAR33xx/BG3340.MOS~
	~EET/temp/mos/AR3351.MOS~ ~%areas_dir%/bgAR33xx/BG3351.MOS~
	~EET/temp/mos/AR3352.MOS~ ~%areas_dir%/bgAR33xx/BG3352.MOS~
	~EET/temp/mos/AR3353.MOS~ ~%areas_dir%/bgAR33xx/BG3353.MOS~
	~EET/temp/mos/AR3357.MOS~ ~%areas_dir%/bgAR33xx/BG3357.MOS~
	~EET/temp/mos/AR3400.MOS~ ~%areas_dir%/bgAR34xx/BG3400.MOS~
	~EET/temp/mos/AR3400N.MOS~ ~%areas_dir%/bgAR34xx/BG3400N.MOS~
	~EET/temp/mos/AR3401.MOS~ ~%areas_dir%/bgAR34xx/BG3401.MOS~
	~EET/temp/mos/AR3402.MOS~ ~%areas_dir%/bgAR34xx/BG3402.MOS~
	~EET/temp/mos/AR3500.MOS~ ~%areas_dir%/bgAR35xx/BG3500.MOS~
	~EET/temp/mos/AR3600.MOS~ ~%areas_dir%/bgAR36xx/BG3600.MOS~
	~EET/temp/mos/AR3601.MOS~ ~%areas_dir%/bgAR36xx/BG3601.MOS~
	~EET/temp/mos/AR3700.MOS~ ~%areas_dir%/bgAR37xx/BG3700.MOS~
	~EET/temp/mos/AR3800.MOS~ ~%areas_dir%/bgAR38xx/BG3800.MOS~
	~EET/temp/mos/AR3802.MOS~ ~%areas_dir%/bgAR38xx/BG3802.MOS~
	~EET/temp/mos/AR3900.MOS~ ~%areas_dir%/bgAR39xx/BG3900.MOS~
	~EET/temp/mos/AR3901.MOS~ ~%areas_dir%/bgAR39xx/BG3901.MOS~
	~EET/temp/mos/AR4000.MOS~ ~%areas_dir%/bgAR40xx/BG4000.MOS~
	~EET/temp/mos/AR4001.MOS~ ~%areas_dir%/bgAR40xx/BG4001.MOS~
	~EET/temp/mos/AR4002.MOS~ ~%areas_dir%/bgAR40xx/BG4002.MOS~
	~EET/temp/mos/AR4003.MOS~ ~%areas_dir%/bgAR40xx/BG4003.MOS~
	~EET/temp/mos/AR4004.MOS~ ~%areas_dir%/bgAR40xx/BG4004.MOS~
	~EET/temp/mos/AR4006.MOS~ ~%areas_dir%/bgAR40xx/BG4006.MOS~
	~EET/temp/mos/AR4100.MOS~ ~%areas_dir%/bgAR41xx/BG4100.MOS~
	~EET/temp/mos/AR4101.MOS~ ~%areas_dir%/bgAR41xx/BG4101.MOS~
	~EET/temp/mos/AR4200.MOS~ ~%areas_dir%/bgAR42xx/BG4200.MOS~
	~EET/temp/mos/AR4201.MOS~ ~%areas_dir%/bgAR42xx/BG4201.MOS~
	~EET/temp/mos/AR4300.MOS~ ~%areas_dir%/bgAR43xx/BG4300.MOS~
	~EET/temp/mos/AR4400.MOS~ ~%areas_dir%/bgAR44xx/BG4400.MOS~
	~EET/temp/mos/AR4401.MOS~ ~%areas_dir%/bgAR44xx/BG4401.MOS~
	~EET/temp/mos/AR4500.MOS~ ~%areas_dir%/bgAR45xx/BG4500.MOS~
	~EET/temp/mos/AR4501.MOS~ ~%areas_dir%/bgAR45xx/BG4501.MOS~
	~EET/temp/mos/AR4600.MOS~ ~%areas_dir%/bgAR46xx/BG4600.MOS~
	~EET/temp/mos/AR4700.MOS~ ~%areas_dir%/bgAR47xx/BG4700.MOS~
	~EET/temp/mos/AR4700N.MOS~ ~%areas_dir%/bgAR47xx/BG4700N.MOS~
	~EET/temp/mos/AR4701.MOS~ ~%areas_dir%/bgAR47xx/BG4701.MOS~
	~EET/temp/mos/AR4800.MOS~ ~%areas_dir%/bgAR48xx/BG4800.MOS~
	~EET/temp/mos/AR4801.MOS~ ~%areas_dir%/bgAR48xx/BG4801.MOS~
	~EET/temp/mos/AR4802.MOS~ ~%areas_dir%/bgAR48xx/BG4802.MOS~
	~EET/temp/mos/AR4803.MOS~ ~%areas_dir%/bgAR48xx/BG4803.MOS~
	~EET/temp/mos/AR4804.MOS~ ~%areas_dir%/bgAR48xx/BG4804.MOS~
	~EET/temp/mos/AR4805.MOS~ ~%areas_dir%/bgAR48xx/BG4805.MOS~
	~EET/temp/mos/AR4806.MOS~ ~%areas_dir%/bgAR48xx/BG4806.MOS~
	~EET/temp/mos/AR4807.MOS~ ~%areas_dir%/bgAR48xx/BG4807.MOS~
	~EET/temp/mos/AR4808.MOS~ ~%areas_dir%/bgAR48xx/BG4808.MOS~
	~EET/temp/mos/AR4809.MOS~ ~%areas_dir%/bgAR48xx/BG4809.MOS~
	~EET/temp/mos/AR4810.MOS~ ~%areas_dir%/bgAR48xx/BG4810.MOS~
	~EET/temp/mos/AR4900.MOS~ ~%areas_dir%/bgAR49xx/BG4900.MOS~
	~EET/temp/mos/AR4900N.MOS~ ~%areas_dir%/bgAR49xx/BG4900N.MOS~
	~EET/temp/mos/AR4901.MOS~ ~%areas_dir%/bgAR49xx/BG4901.MOS~
	~EET/temp/mos/AR4902.MOS~ ~%areas_dir%/bgAR49xx/BG4902.MOS~
	~EET/temp/mos/AR4903.MOS~ ~%areas_dir%/bgAR49xx/BG4903.MOS~
	~EET/temp/mos/AR4905.MOS~ ~%areas_dir%/bgAR49xx/BG4905.MOS~
	~EET/temp/mos/AR4906.MOS~ ~%areas_dir%/bgAR49xx/BG4906.MOS~
	~EET/temp/mos/AR5000.MOS~ ~%areas_dir%/bgAR50xx/BG5000.MOS~
	~EET/temp/mos/AR5001.MOS~ ~%areas_dir%/bgAR50xx/BG5001.MOS~
	~EET/temp/mos/AR5100.MOS~ ~%areas_dir%/bgAR51xx/BG5100.MOS~
	~EET/temp/mos/AR5101.MOS~ ~%areas_dir%/bgAR51xx/BG5101.MOS~
	~EET/temp/mos/AR5102.MOS~ ~%areas_dir%/bgAR51xx/BG5102.MOS~
	~EET/temp/mos/AR5103.MOS~ ~%areas_dir%/bgAR51xx/BG5103.MOS~
	~EET/temp/mos/AR5200.MOS~ ~%areas_dir%/bgAR52xx/BG5200.MOS~
	~EET/temp/mos/AR5201.MOS~ ~%areas_dir%/bgAR52xx/BG5201.MOS~
	~EET/temp/mos/AR5202.MOS~ ~%areas_dir%/bgAR52xx/BG5202.MOS~
	~EET/temp/mos/AR5300.MOS~ ~%areas_dir%/bgAR53xx/BG5300.MOS~
	~EET/temp/mos/AR5400.MOS~ ~%areas_dir%/bgAR54xx/BG5400.MOS~
	~EET/temp/mos/AR5401.MOS~ ~%areas_dir%/bgAR54xx/BG5401.MOS~
	~EET/temp/mos/AR5402.MOS~ ~%areas_dir%/bgAR54xx/BG5402.MOS~
	~EET/temp/mos/AR5403.MOS~ ~%areas_dir%/bgAR54xx/BG5403.MOS~
	~EET/temp/mos/AR5404.MOS~ ~%areas_dir%/bgAR54xx/BG5404.MOS~
	~EET/temp/mos/AR5405.MOS~ ~%areas_dir%/bgAR54xx/BG5405.MOS~
	~EET/temp/mos/AR5406.MOS~ ~%areas_dir%/bgAR54xx/BG5406.MOS~
	~EET/temp/mos/AR5500.MOS~ ~%areas_dir%/bgAR55xx/BG5500.MOS~
	~EET/temp/mos/AR5506.MOS~ ~%areas_dir%/bgAR55xx/BG5506.MOS~
	~EET/temp/mos/AR5600.MOS~ ~%areas_dir%/bgAR56xx/BG5600.MOS~
	~EET/temp/mos/AR5700.MOS~ ~%areas_dir%/bgAR57xx/BG5700.MOS~
	~EET/temp/mos/AR5800.MOS~ ~%areas_dir%/bgAR58xx/BG5800.MOS~
	~EET/temp/mos/AR5900.MOS~ ~%areas_dir%/bgAR59xx/BG5900.MOS~
	~EET/temp/mos/AR6000.MOS~ ~%areas_dir%/bgAR60xx/BG6000.MOS~
	~EET/temp/mos/AR6100.MOS~ ~%areas_dir%/bgAR61xx/BG6100.MOS~
	~EET/temp/mos/OH2000.MOS~ ~%areas_dir%/bgOH2xxx~
	~EET/temp/mos/OH2000N.MOS~ ~%areas_dir%/bgOH2xxx~
	~EET/temp/mos/OH2010.MOS~ ~%areas_dir%/bgOH2xxx~
	~EET/temp/mos/OH3000.MOS~ ~%areas_dir%/bgOH3xxx~
	~EET/temp/mos/OH3000N.MOS~ ~%areas_dir%/bgOH3xxx~
	~EET/temp/mos/OH3010.MOS~ ~%areas_dir%/bgOH3xxx~
	~EET/temp/mos/OH3020.MOS~ ~%areas_dir%/bgOH3xxx~
	~EET/temp/mos/OH3100.MOS~ ~%areas_dir%/bgOH3xxx~
	~EET/temp/mos/OH3100N.MOS~ ~%areas_dir%/bgOH3xxx~
	~EET/temp/mos/OH9310.MOS~ ~%areas_dir%/bgOH9xxx~
	~EET/temp/mos/OH9350.MOS~ ~%areas_dir%/bgOH9xxx~
	~EET/temp/mos/OH9360.MOS~ ~%areas_dir%/bgOH9xxx~
	~EET/temp/mos/TU0015.MOS~ ~%areas_dir%/bgTU00xx~
	~EET/temp/mos/TU0016.MOS~ ~%areas_dir%/bgTU00xx~
	~EET/temp/mos/TU0017.MOS~ ~%areas_dir%/bgTU00xx~
	~EET/temp/mos/TU0018.MOS~ ~%areas_dir%/bgTU00xx~

DELETE + ~EET/temp/mos/ARRIVE.MOS~
	~EET/temp/mos/BAR-FINL.MOS~
	~EET/temp/mos/BAR-STEP.MOS~
	~EET/temp/mos/BGDECBAR.MOS~
	~EET/temp/mos/BGPADB.MOS~
	~EET/temp/mos/BGPADL.MOS~
	~EET/temp/mos/BGPADR.MOS~
	~EET/temp/mos/BPEND.MOS~
	~EET/temp/mos/COLOR.MOS~
	~EET/temp/mos/COLORI.MOS~
	~EET/temp/mos/COLORR.MOS~
	~EET/temp/mos/GKEYMAP.MOS~
	~EET/temp/mos/GMPCARBB.MOS~
	~EET/temp/mos/GMPCARBD.MOS~
	~EET/temp/mos/GMPNCGE1.MOS~
	~EET/temp/mos/GMPNCGE2.MOS~
	~EET/temp/mos/GMPNCGE3.MOS~
	~EET/temp/mos/GMPNJGME.MOS~
	~EET/temp/mos/GMPNTCPE.MOS~
	~EET/temp/mos/GMPPARBE.MOS~
	~EET/temp/mos/GMPPOPTB.MOS~
	~EET/temp/mos/GMPWMSG0.MOS~
	~EET/temp/mos/GMWMSGA0.MOS~
	~EET/temp/mos/GMWMSGA9.MOS~
	~EET/temp/mos/GMWMSGB0.MOS~
	~EET/temp/mos/GOPGAMB.MOS~
	~EET/temp/mos/GOPSNDSB.MOS~
	~EET/temp/mos/GTRBPBAR.MOS~
	~EET/temp/mos/GTRBPCAP.MOS~
	~EET/temp/mos/GTRSPBAR.MOS~
	~EET/temp/mos/GTRSPBG.MOS~
	~EET/temp/mos/GTRSPCAP.MOS~
	~EET/temp/mos/GU10BKLS.MOS~
	~EET/temp/mos/GU10BKMD.MOS~
	~EET/temp/mos/GU10BKRS.MOS~
	~EET/temp/mos/GU20BKLS.MOS~
	~EET/temp/mos/GU20BKMD.MOS~
	~EET/temp/mos/GU20BKRS.MOS~
	~EET/temp/mos/GU3MPB.MOS~
	~EET/temp/mos/GUDEATH0.MOS~
	~EET/temp/mos/GUI_NAME.MOS~
	~EET/temp/mos/GUIAPB.MOS~
	~EET/temp/mos/GUIAPBR.MOS~
	~EET/temp/mos/GUIBTTXT.MOS~
	~EET/temp/mos/GUICGB.MOS~
	~EET/temp/mos/GUICGPR.MOS~
	~EET/temp/mos/GUICHISD.MOS~
	~EET/temp/mos/GUICHISE.MOS~
	~EET/temp/mos/GUICHP0B.MOS~
	~EET/temp/mos/GUICHP1B.MOS~
	~EET/temp/mos/GUICHP2B.MOS~
	~EET/temp/mos/GUICHP3B.MOS~
	~EET/temp/mos/GUICHP4B.MOS~
	~EET/temp/mos/GUICHP5B.MOS~
	~EET/temp/mos/GUICHP6B.MOS~
	~EET/temp/mos/GUICHP7B.MOS~
	~EET/temp/mos/GUICHP8B.MOS~
	~EET/temp/mos/GUICONN1.MOS~
	~EET/temp/mos/GUICONNB.MOS~
	~EET/temp/mos/GUICONTB.MOS~
	~EET/temp/mos/GUICP.MOS~
	~EET/temp/mos/GUICPORB.MOS~
	~EET/temp/mos/GUICREDT.MOS~
	~EET/temp/mos/GUICUSTB.MOS~
	~EET/temp/mos/GUICUSTP.MOS~
	~EET/temp/mos/GUICUSTX.MOS~
	~EET/temp/mos/GUIDCB.MOS~
	~EET/temp/mos/GUIDCX.MOS~
	~EET/temp/mos/GUIDLC.MOS~
	~EET/temp/mos/GUIDRM2.MOS~
	~EET/temp/mos/GUIDRM2B.MOS~
	~EET/temp/mos/GUIDRM3.MOS~
	~EET/temp/mos/GUIDRM3B.MOS~
	~EET/temp/mos/GUIDRM4.MOS~
	~EET/temp/mos/GUIDRM4B.MOS~
	~EET/temp/mos/GUIDRM5.MOS~
	~EET/temp/mos/GUIDRM5B.MOS~
	~EET/temp/mos/GUIDRM6.MOS~
	~EET/temp/mos/GUIDRM6B.MOS~
	~EET/temp/mos/GUIDRM7.MOS~
	~EET/temp/mos/GUIDRM7B.MOS~
	~EET/temp/mos/GUIEDUS.MOS~
	~EET/temp/mos/GUIERR.MOS~
	~EET/temp/mos/GUIERR09.MOS~
	~EET/temp/mos/GUIERR10.MOS~
	~EET/temp/mos/GUIERR2.MOS~
	~EET/temp/mos/GUIERR21.MOS~
	~EET/temp/mos/GUIERR6.MOS~
	~EET/temp/mos/GUIERR8.MOS~
	~EET/temp/mos/GUIEXPE.MOS~
	~EET/temp/mos/GUIGDB.MOS~
	~EET/temp/mos/GUIHELP.MOS~
	~EET/temp/mos/GUIHSB.MOS~
	~EET/temp/mos/GUIHSBS.MOS~
	~EET/temp/mos/GUIINVHB.MOS~
	~EET/temp/mos/GUIINVHI.MOS~
	~EET/temp/mos/GUIINVRE.MOS~
	~EET/temp/mos/GUIJRNL.MOS~
	~EET/temp/mos/GUILUPB.MOS~
	~EET/temp/mos/GUIMAPAB.MOS~
	~EET/temp/mos/GUIMAPWB.MOS~
	~EET/temp/mos/GUIMGB.MOS~
	~EET/temp/mos/GUIMGCP.MOS~
	~EET/temp/mos/GUIMGX.MOS~
	~EET/temp/mos/GUIMOVB.MOS~
	~EET/temp/mos/GUIMPB.MOS~
	~EET/temp/mos/GUINME.MOS~
	~EET/temp/mos/GUIOLSP0.MOS~
	~EET/temp/mos/GUIOSTUM.MOS~
	~EET/temp/mos/GUIPBRC.MOS~
	~EET/temp/mos/GUIPNLC.MOS~
	~EET/temp/mos/GUIPRB.MOS~
	~EET/temp/mos/GUIRECBG.MOS~
	~EET/temp/mos/GUISLDR.MOS~
	~EET/temp/mos/GUISMBM.MOS~
	~EET/temp/mos/GUISMDA.MOS~
	~EET/temp/mos/GUISMDB.MOS~
	~EET/temp/mos/GUISMF.MOS~
	~EET/temp/mos/GUISMF2.MOS~
	~EET/temp/mos/GUISMS.MOS~
	~EET/temp/mos/GUISPLHB.MOS~
	~EET/temp/mos/GUISPMB.MOS~
	~EET/temp/mos/GUISRRQB.MOS~
	~EET/temp/mos/GUISRSVB.MOS~
	~EET/temp/mos/GUISRSVE.MOS~
	~EET/temp/mos/GUISTATS.MOS~
	~EET/temp/mos/GUISTBBB.MOS~
	~EET/temp/mos/GUISTBBM.MOS~
	~EET/temp/mos/GUISTBSC.MOS~
	~EET/temp/mos/GUISTDOB.MOS~
	~EET/temp/mos/GUISTDOE.MOS~
	~EET/temp/mos/GUISTIDB.MOS~
	~EET/temp/mos/GUISTMPE.MOS~
	~EET/temp/mos/GUISTROB.MOS~
	~EET/temp/mos/GUITPP8.MOS~
	~EET/temp/mos/GUIVERB.MOS~
	~EET/temp/mos/GUIW12_1.MOS~
	~EET/temp/mos/GUIW12_2.MOS~
	~EET/temp/mos/GUIW12_3.MOS~
	~EET/temp/mos/GUIW12_4.MOS~
	~EET/temp/mos/GUIW12_5.MOS~
	~EET/temp/mos/GUIW12_6.MOS~
	~EET/temp/mos/GUIW12_7.MOS~
	~EET/temp/mos/GUIW12_8.MOS~
	~EET/temp/mos/GUIWBTP1.MOS~
	~EET/temp/mos/GUIWBTP2.MOS~
	~EET/temp/mos/GUIWBTP3.MOS~
	~EET/temp/mos/GUIWCHT0.MOS~
	~EET/temp/mos/GUIWCHTE.MOS~
	~EET/temp/mos/GUIWDMB.MOS~
	~EET/temp/mos/GUIWDMB0.MOS~
	~EET/temp/mos/GUIWDMB9.MOS~
	~EET/temp/mos/GUIWDMBM.MOS~
	~EET/temp/mos/GUIWDSL0.MOS~
	~EET/temp/mos/GUIWDSL1.MOS~
	~EET/temp/mos/GUIWDSL9.MOS~
	~EET/temp/mos/GUIWLLP.MOS~
	~EET/temp/mos/GUIWLLP8.MOS~
	~EET/temp/mos/GUIWLS20.MOS~
	~EET/temp/mos/GUIWLSP.MOS~
	~EET/temp/mos/GUIWLSP0.MOS~
	~EET/temp/mos/GUIWPPE.MOS~
	~EET/temp/mos/GUIWRLP.MOS~
	~EET/temp/mos/GUIWRLP0.MOS~
	~EET/temp/mos/GUIWRLP8.MOS~
	~EET/temp/mos/GUIWRS20.MOS~
	~EET/temp/mos/GUIWRSP.MOS~
	~EET/temp/mos/GUIWTPP.MOS~
	~EET/temp/mos/GUIWTPP0.MOS~
	~EET/temp/mos/GUIWTPP8.MOS~
	~EET/temp/mos/GUMPB.MOS~
	~EET/temp/mos/GUWBTP10.MOS~
	~EET/temp/mos/GUWBTP20.MOS~
	~EET/temp/mos/GUWBTP29.MOS~
	~EET/temp/mos/GUWBTP30.MOS~
	~EET/temp/mos/GUWBTP39.MOS~
	~EET/temp/mos/GUWBTP3M.MOS~
	~EET/temp/mos/GUWBTP9M.MOS~
	~EET/temp/mos/GUWDMBM9.MOS~
	~EET/temp/mos/GUWDSL9.MOS~
	~EET/temp/mos/GUWPKPC0.MOS~
	~EET/temp/mos/GWCONTB0.MOS~
	~EET/temp/mos/IMEUI.MOS~
	~EET/temp/mos/INVENTOR.MOS~
	~EET/temp/mos/LEAVE.MOS~
	~EET/temp/mos/NPCCHAP.MOS~
	~EET/temp/mos/SIDEBLOK.MOS~
	~EET/temp/mos/START.MOS~
	~EET/temp/mos/STARTEE.MOS~
	~EET/temp/mos/STARTM.MOS~
	~EET/temp/mos/STARTOLD.MOS~
	~EET/temp/mos/STON09B.MOS~
	~EET/temp/mos/STON09L.MOS~
	~EET/temp/mos/STON09R.MOS~
	~EET/temp/mos/STON09T.MOS~
	~EET/temp/mos/STON12B.MOS~
	~EET/temp/mos/STON12L.MOS~
	~EET/temp/mos/STON12R.MOS~
	~EET/temp/mos/STON12T.MOS~
	~EET/temp/mos/STON13B.MOS~
	~EET/temp/mos/STON13L.MOS~
	~EET/temp/mos/STON13R.MOS~
	~EET/temp/mos/STON13T.MOS~
	~EET/temp/mos/STONEOPT.MOS~
	~EET/temp/mos/TEXT.MOS~
	~EET/temp/mos/TEXT_IN.MOS~
	~EET/temp/mos/TOSCEND.MOS~
	~EET/temp/mos/ULGOTHST.MOS~
	~EET/temp/mos/WORLDMAP.MOS~
