DELETE + ~%MOD_FOLDER%/temp/wbm/TUT01.WBM~
	~%MOD_FOLDER%/temp/wbm/TUT03.WBM~
	~%MOD_FOLDER%/temp/wbm/TUT04.WBM~
	~%MOD_FOLDER%/temp/wbm/TUT05.WBM~
	~%MOD_FOLDER%/temp/wbm/TUT06.WBM~
	~%MOD_FOLDER%/temp/wbm/TUT07.WBM~
	~%MOD_FOLDER%/temp/wbm/TUT08.WBM~
	~%MOD_FOLDER%/temp/wbm/TUT09.WBM~
	~%MOD_FOLDER%/temp/wbm/TUT10.WBM~
	~%MOD_FOLDER%/temp/wbm/TUT11.WBM~
	~%MOD_FOLDER%/temp/wbm/TUT12.WBM~
	~%MOD_FOLDER%/temp/wbm/TUT13.WBM~
	~%MOD_FOLDER%/temp/wbm/TUT14.WBM~
