DELETE + ~EET/temp/ttf/DIALOG.TTF~
	~EET/temp/ttf/FEINEN.TTF~
	~EET/temp/ttf/FLOATTXT.TTF~
	~EET/temp/ttf/MODESTOM.TTF~
	~EET/temp/ttf/NANUM.TTF~
	~EET/temp/ttf/NORMAL.TTF~
	~EET/temp/ttf/PERMIAN.TTF~
	~EET/temp/ttf/PTSERIF.TTF~
	~EET/temp/ttf/REALMS.TTF~
	~EET/temp/ttf/SHERWOOD.TTF~
	~EET/temp/ttf/SIMSUN.TTF~
	~EET/temp/ttf/STATES2.TTF~
	~EET/temp/ttf/STONEBIG.TTF~
	~EET/temp/ttf/STONESML.TTF~
	~EET/temp/ttf/SUBTITLE.TTF~
	~EET/temp/ttf/TOOLFONT.TTF~
	~EET/temp/ttf/TOOLTIP.TTF~
