/*not needed, since the tp2 skipped this part for EE
COPY + ~%patch_dir%/cre/ORC06.cre~ ~override~
	~%patch_dir%/cre/HLOLAF.cre~ ~override~
	~%patch_dir%/cre/CHAK.cre~ ~override~
	~%patch_dir%/cre/AR18FIG.cre~ ~override~
	WRITE_LONG 0x28 0xE710 //changed animation back to IC_OROG2 (OROG_BLUE)*/

COPY + ~%patch_dir%/cre/F_GIANTF.cre~ ~%patch_dir%/cre~
	WRITE_LONG 0x28 0xE24F //changed animation to use existing IWD:EE / Expanded Animations entry - GIANT_FROST

//delete files existing in BG2:EE
DELETE + ~%MOD_FOLDER%/temp/bam/mcora1.bam~
	~%MOD_FOLDER%/temp/bam/mcora1e.bam~
	~%MOD_FOLDER%/temp/bam/mcora2.bam~
	~%MOD_FOLDER%/temp/bam/mcora2e.bam~
	~%MOD_FOLDER%/temp/bam/mcorca.bam~
	~%MOD_FOLDER%/temp/bam/mcorcae.bam~
	~%MOD_FOLDER%/temp/bam/mcorde.bam~
	~%MOD_FOLDER%/temp/bam/mcordee.bam~
	~%MOD_FOLDER%/temp/bam/mcorgh.bam~
	~%MOD_FOLDER%/temp/bam/mcorghe.bam~
	~%MOD_FOLDER%/temp/bam/mcorgu.bam~
	~%MOD_FOLDER%/temp/bam/mcorgue.bam~
	~%MOD_FOLDER%/temp/bam/mcorsc.bam~
	~%MOD_FOLDER%/temp/bam/mcorsce.bam~
	~%MOD_FOLDER%/temp/bam/mcorsd.bam~
	~%MOD_FOLDER%/temp/bam/mcorsde.bam~
	~%MOD_FOLDER%/temp/bam/mcorsl.bam~
	~%MOD_FOLDER%/temp/bam/mcorsle.bam~
	~%MOD_FOLDER%/temp/bam/mcorsp.bam~
	~%MOD_FOLDER%/temp/bam/mcorspe.bam~
	~%MOD_FOLDER%/temp/bam/mcortw.bam~
	~%MOD_FOLDER%/temp/bam/mcortwe.bam~
	~%MOD_FOLDER%/temp/bam/mcorwk.bam~
	~%MOD_FOLDER%/temp/bam/mcorwke.bam~
	~%MOD_FOLDER%/temp/bam/mtana1.bam~
	~%MOD_FOLDER%/temp/bam/mtana1e.bam~
	~%MOD_FOLDER%/temp/bam/mtana2.bam~
	~%MOD_FOLDER%/temp/bam/mtana2e.bam~
	~%MOD_FOLDER%/temp/bam/mtana3.bam~
	~%MOD_FOLDER%/temp/bam/mtana3e.bam~
	~%MOD_FOLDER%/temp/bam/mtanca.bam~
	~%MOD_FOLDER%/temp/bam/mtancae.bam~
	~%MOD_FOLDER%/temp/bam/mtande.bam~
	~%MOD_FOLDER%/temp/bam/mtandee.bam~
	~%MOD_FOLDER%/temp/bam/mtangh.bam~
	~%MOD_FOLDER%/temp/bam/mtanghe.bam~
	~%MOD_FOLDER%/temp/bam/mtangu.bam~
	~%MOD_FOLDER%/temp/bam/mtangue.bam~
	~%MOD_FOLDER%/temp/bam/mtansc.bam~
	~%MOD_FOLDER%/temp/bam/mtansce.bam~
	~%MOD_FOLDER%/temp/bam/mtansd.bam~
	~%MOD_FOLDER%/temp/bam/mtansde.bam~
	~%MOD_FOLDER%/temp/bam/mtansl.bam~
	~%MOD_FOLDER%/temp/bam/mtansle.bam~
	~%MOD_FOLDER%/temp/bam/mtansp.bam~
	~%MOD_FOLDER%/temp/bam/mtanspe.bam~
	~%MOD_FOLDER%/temp/bam/mtantw.bam~
	~%MOD_FOLDER%/temp/bam/mtantwe.bam~
	~%MOD_FOLDER%/temp/bam/mtanwk.bam~
	~%MOD_FOLDER%/temp/bam/mtanwke.bam~

//mod supports BP-BGT Worldmap. This patch allows it to support EET worldmap natively too

APPEND_OUTER ~%MOD_FOLDER%/tbl/map_eet_areas.tbl~ ~
//Drizzt Saga New Areas Table
SHORT_NAME CONTENT    LONG_NAME  FLAGS      BAM_ANIM   X_POS      Y_POS      NAME       TOOLTIP    LOAD_IM

F_7777     F_7777     F_7777     4          65         780        212        @F_7777    @F_7777    N        //Bruenor's Cabin
F_9898     F_9898     F_9898     4          73         1060       50         @F_9898    @F_9898    N        //Mountain of the Dead
F_0111     F_0111     F_0111     4          54         580        163        @F_0111    @F_0111    N        //Bear Tribe Village
F_0222     F_0222     F_0222     4          68         990        120        @F_0222    @F_0222    N        //Storm March Mountains~ KEEP_CRLF
