IF
  Global("ImoenSpawned","GLOBAL",0)//ImoenSpawned variable name kept for BGT compatibility reasons
  LevelLT(Protagonist,13)
  XPLT("Imoen2",400000)
THEN
  RESPONSE #100
    ChangeStat("Imoen2",XP,400000,SET)
    SetGlobal("ImoenSpawned","GLOBAL",1)
    Continue()
END

IF
  Global("ImoenSpawned","GLOBAL",0)
  LevelGT(Protagonist,13)
  XPLT("Imoen2",1200000)
THEN
  RESPONSE #100
    ChangeStat("Imoen2",XP,1200000,SET)
    SetGlobal("ImoenSpawned","GLOBAL",1)
    Continue()
END
