IF
  AttackedBy([GOODCUTOFF],DEFAULT)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Shout(99)
    Enemy()
END

IF
  HitBy([GOODCUTOFF],CRUSHING)
THEN
  RESPONSE #100
    Shout(99)
    Continue()
END

IF
  Heard([ANYONE],99)
  Allegiance(Myself,NEUTRAL)
  !Class(Myself,INNOCENT)
THEN
  RESPONSE #100
    Shout(57)
    Enemy()
    MoveToObject(LastHeardBy(Myself))
END

IF
  Heard([ANYONE],99)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END