COPY + ~%patch_dir%/itm/CMBRQ04.ITM~ ~%patch_dir%/itm~
	WRITE_ASCII 0x3a ~IBRAC24#~ #8

COPY ~EET/compat/DarkHorizonsBGee/Ibrac24.bam~ ~%biff_dir%/Ibrac24#.bam~

//these items has wrong Ability Effect index numbering, which may lead to out of bound reading (100% in CMSTQ04.ITM case)
ACTION_BASH_FOR ~EET/compat/DarkHorizonsBGee~ ~.*.itm~ BEGIN
	COPY ~EET/compat/DarkHorizonsBGee/%BASH_FOR_FILE%~ ~override~
		PATCH_FOR_EACH offset IN 0x8 0xc 0x50 0x54 BEGIN //Name - Unidentified, Name - Identified, Description - Unidentified, Description - Identified
			INNER_ACTION BEGIN
				COPY - ~%patch_dir%/itm/%BASH_FOR_FILE%~ ~%patch_dir%/itm~
					READ_LONG offset "strref"
			END
			LPF ~EET_strref~ INT_VAR str = strref RET str END
			WRITE_LONG offset "%str%"
		END
	DELETE + ~%patch_dir%/itm/%BASH_FOR_FILE%~
END

//delete files existing in BG2:EE
DELETE + ~EET/temp/wav/BREGAX02.WAV~
	~EET/temp/wav/BREGAX03.WAV~
	~EET/temp/wav/BREGAX04.WAV~
	~EET/temp/wav/BREGAX05.WAV~
	~EET/temp/wav/BREGAX17.WAV~
	~EET/temp/bam/FIRE_1.bam~
	~EET/temp/bam/FIRE_4.bam~
	~EET/temp/bam/FIRE_4G2.bam~
